bndtools/bnd

- biz.aQute.bnd/src/aQute/bnd/main/ResolveCommand.java
- biz.aQute.bndlib.tests/test/test/component/DSAnnotationTest.java
- biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java
- biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
- biz.aQute.bndlib/src/aQute/bnd/component/ReferenceDef.java
> DS change + command change for resolver

- biz.aQute.bndlib.tests/test/test/MavenVersionTest.java
- biz.aQute.bndlib/src/aQute/bnd/version/MavenVersion.java
- maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
Clean up regexs and avoid using an exception for flow control. Also
better handle tokens which look like integers but are too big for int.
> maven version: Additional fixes/improvements

- biz.aQute.bnd.maven/bnd.bnd
- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/BndrunContainer.java
- biz.aQute.bndlib.tests/test/test/model/EETest.java
- biz.aQute.bndlib/src/aQute/bnd/build/model/EE.java
- maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/pom.xml
- maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/resolve-from-defaults/pom.xml
- maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/resolve-from-defaults/test.bndrun
- maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/verify.groovy
> [maven] make it possible to omit the -runee and infer it from maven-compiler-plugin/configuration/target

- docs/_chapters/330-jpms.md
The menu doesn't look nice with such a long title.
> [jpms] change title

- .travis.yml
- aQute.libg/src/aQute/lib/xpath/XPathParser.java
- biz.aQute.bnd.test/src/aQute/bnd/test/XmlTester.java
- biz.aQute.bndlib.tests/test/test/component/ComponentTest.java
- biz.aQute.bndlib/src/aQute/bnd/cdi/CDIAnnotations.java
- biz.aQute.bndlib/src/aQute/bnd/maven/MavenDependencyGraph.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/eclipse/EclipseClasspath.java
- biz.aQute.repository/src/aQute/p2/provider/TargetImpl.java
- biz.aQute.repository/src/aQute/p2/provider/XML.java
- maven/build.gradle
Some fixes and build changes to start testing parallel building
> Parallel builds

- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceImpl.java
If hashCode/equals was called on a ResourceImpl before the capabilities
were set, the empty location information would be cached.
> resource: Recompute ResourceImpl.hashCode/equals after capabilities set

- biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiRepository.java
- biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java
> [osgirepository] No hard refresh on the repo 'refresh()' call

- biz.aQute.bnd/src/aQute/bnd/main/bnd.java
- biz.aQute.bndlib/src/aQute/bnd/make/MakeBnd.java
- biz.aQute.resolve/src/biz/aQute/resolve/RunResolution.java
- bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionSuccessPanel.java
> NPE in "bnd resolve resolve" #3197

- biz.aQute.bndlib/src/aQute/bnd/remoteworkspace/server/RemoteWorkspaceServer.java
Merge of component header was wrong
> [remotews] ouch

- maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
> do not quote unstructured bundle headers

- biz.aQute.junit/src/aQute/junit/Activator.java
> [tester] findHost() to handle unresolved bundles

- biz.aQute.bndlib/src/aQute/bnd/build/Project.java
- bndtools.core/src/bndtools/launch/OSGiRunLaunchDelegate.java
Update last call site of ProjectLauncher.update since it will refresh
the project.
> launcher: ProjectLauncher.update calls Project.refresh

- .travis.yml
- azure-pipelines.yml
- biz.aQute.bndall.tests/keep.bndrun
- biz.aQute.bndall.tests/keep_notrace.bndrun
- biz.aQute.bndall.tests/startlevels.bndrun
- biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java
- biz.aQute.bndall.tests/test/biz/aQute/launcher/LauncherTest.java
- biz.aQute.bndlib.tests/test/test/WorkspaceBundleVersionedDependencyTest.java
- biz.aQute.bndlib.tests/test/test/WorkspaceTest.java
- demo/old-launcher.bndrun
Parallel gradle builds seem to be very stable. So this moves us to the next level by running all CI gradle builds in parallel mode. This will now include a parallel build on Windows.
> ci: Run all gradle jobs --parallel

- biz.aQute.launcher/src/aQute/launcher/Launcher.java
> [launch] Copy fw properties also to System properties

- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/generator/ReportGeneratorBuilder.java
- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/entries/bndproject/CommonInfoProjectPlugin.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/bndproject/CommonInfoProjectPluginTest.java
- docs/_instructions/reportconfig.md
See #3291
This PR contains implementation, tests, and docs.
Closes #3291
> [reporter] Add commonInfo plugin for projects

- biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
> Add uses directive to generated DS osgi.service capabilities

- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/exporter/ReportExporter.java
- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/JtwigTransformerPlugin.java
- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/templates/blocks.twig
- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/templates/printer.twig
- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/templates/readme.twig
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/exporter/ReportExporterTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/transformer/JtwigPrinterTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/transformer/JtwigReadmeTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/transformer/JtwigTransformerPluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/transformer/TwigChecker.java
Closes #3161 
This based on the work of @stbischof in PR #3152. In complement I have added a set of updated templates (visit https://github.com/cdelg/bnd-doc-demo to see how they look) and some fixes on top of the initial implementation.
As I have reused code of @stbischof maybe we should wait before merging?  
Signed-off-by: Clement Delgrange <cl.delgrange@protonmail.com>
> [reporter] Add default readme templates

- biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
- biz.aQute.bndlib/src/aQute/bnd/help/Syntax.java
- docs/_instructions/nouses.md
Fixes https://github.com/bndtools/bnd/issues/3319
> ds: Respect -nouses when generating osgi.service capabilities

- aQute.libg/src/aQute/lib/io/IO.java
- aQute.libg/src/aQute/libg/remote/source/SourceFS.java
- biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java
- biz.aQute.bndlib/src/aQute/bnd/metatype/ADDef.java
- biz.aQute.bndlib/src/aQute/bnd/metatype/OCDReader.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java
- biz.aQute.bndlib/src/aQute/bnd/service/url/TaggedData.java
- biz.aQute.repository/src/aQute/maven/provider/POM.java
- bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
We don't need to pass start to find. Not passing start avoids reseting
the matcher.
> matcher: Minor simplification to matcher append loop

- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java
- biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
Modify test which intermittently fails to try and get more info.
> Mvn repo test

- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
- maven/build.gradle
Fix several timing issues which made the build unstable.
> Timing issues

- biz.aQute.bndall.tests/build.gradle
- biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
- biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java
Also fixed testNoPolling to actually expose a failure.
> osgi repo test: Update tests to allow more wait time for polling

- biz.aQute.launchpad/test/aQute/launchpad/LaunchpadTest.java
The builder was used in the thread part 
and the builder is not thread safe.
Replaced the stream with the original simple
loops that is much more readable. Moved the
builder out of the loop.
> [launchpad] Fixed test

- biz.aQute.launchpad/test/aQute/launchpad/LaunchpadTest.java
> [launchpad] Added timeout of 1 minute

- biz.aQute.launchpad/src/aQute/launchpad/BundleBuilder.java
- biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java
- biz.aQute.launchpad/test/aQute/launchpad/BundleBuilderTest.java
> [launchpad] Make Launchpad name the default bsn

- biz.aQute.launchpad/test/aQute/launchpad/BundleBuilderTest.java
- cnf/ext/for-launchpad-test.bnd
> Fixes #3316

- bndtools.m2e/src/bndtools/m2e/IndexConfigurator.java
Replaces PR #3343. This may help with issue #2940
> Avoid doing a full maven build when we only wish to refresh the indexes

- maven/bnd-reporter-maven-plugin/pom.xml
Closes #3370.
Add a SLF4j implementation with a test scope (using the managed slf4j-simple dep). 
> [repoter maven] Fix SLF4j binding warning when unit testing

- aQute.libg/src/aQute/lib/watcher/FileWatcher.java
- aQute.libg/src/aQute/lib/watcher/package-info.java
- aQute.libg/test/aQute/lib/watcher/FileWatcherTest.java
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy
- biz.aQute.bnd/src/aQute/bnd/main/bnd.java
- biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java
- maven/bnd-run-maven-plugin/src/main/java/aQute/bnd/maven/run/plugin/RunMojo.java
We move it to a member class of ProjectLauncher: LiveCoding. This class
uses the new FileWatcher class to watch the necessary files from the
ProjectLauncher.
The LiveCoding class now tracks any files included in the bndrun and recomputes the watch list if the bndrun or any included file changes.
We also add live coding support to the gradle plugin for the Bndrun task type.
> livecoding: Refactor live coding support from bnd-run-maven-plugin

- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy
- biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBndPlugin.groovy
- biz.aQute.bnd.gradle/testresources/runtask1/build.gradle
- biz.aQute.bnd.gradle/testresources/workspaceplugin7/test.simple/bnd.bnd
- biz.aQute.bnd.gradle/testresources/workspaceplugin7/test.simple/build.gradle
- biz.aQute.bndlib.tests/test/test/LibDirectiveTest.java
- biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java
Also update tests to confirm rejarring fix in 894563bcf is good.
> Fix for issue #3376 to check whether Bnd plugin is applied to the gradle project

- aQute.libg/src/aQute/lib/json/JSONCodec.java
Fixes #3394
Signed-off-by: Amit Kumar Mondal <admin@amitinside.com>
> [bnd] Added functionality to override the global handlers of JSONCodec

- .gradle-wrapper/gradle-wrapper.properties
- biz.aQute.bndlib/src/aQute/bnd/classfile/builder/ClassFileBuilder.java
> Gradle 5.6.1

- biz.aQute.launcher/src/aQute/launcher/Launcher.java
Put all start/stop handling in one place so that we
correctly check for fragments and handle eager act.
> [launcher] Fragments and start/stop

- biz.aQute.bndlib/src/aQute/bnd/cdi/CDIAnnotations.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
We use a new static Jar method to locate resources in an embedded jar resource. This method does not require the entire embedded jar resource to be loaded in memory.
> cdi: Reduce resource consumption when processing beans.xml resources

- biz.aQute.bndlib/src/aQute/bnd/cdi/CDIAnnotations.java
We specifically exclude WEB-INF/classes from the folder support since it
acts as the base folder for WABs.
> cdi: Properly handle folders in Bundle-ClassPath

- CONTRIBUTING.md
Accidentally created it as a L4 when the others are L3.
> [contributions] Fix level of new WIP heading

- .gradle-wrapper/gradle-wrapper.properties
- biz.aQute.bnd.gradle/README.md
- gradlew
- maven/README.md
Also update gradlew to latest 5.6.2.
> gradle: Indicate README applies to the branch containing the README 

- biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestResolveTask.groovy
- biz.aQute.bnd/src/aQute/bnd/main/ResolveCommand.java
- biz.aQute.resolve/src/biz/aQute/resolve/Bndrun.java
- biz.aQute.resolve/src/biz/aQute/resolve/RunResolution.java
- biz.aQute.resolve/test/biz/aQute/resolve/ProjectResolverTest.java
- biz.aQute.resolve/test/biz/aQute/resolve/ResolveTest.java
- bndtools.core/src/org/bndtools/core/resolve/ResolveOperation.java
This method does not format any ResolutionException into errors on the
run.
Fixes https://github.com/bndtools/bnd/issues/3427
> resolver: Fix resolve method for CLI plugins

- .mvn/wrapper/maven-wrapper.properties
- maven/bnd-baseline-maven-plugin/pom.xml
- maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/index-folder-includes-excludes/pom.xml
- maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/index-folder/pom.xml
- maven/bnd-reporter-maven-plugin/pom.xml
- maven/bnd-run-maven-plugin/pom.xml
- maven/bnd-testing-maven-plugin/pom.xml
- maven/build.gradle
- maven/pom.xml
Maven 3.6.2 has a number of fixes including performance fixes. 
https://maven.apache.org/docs/3.6.2/release-notes.html
> mvnw: Update to Maven 3.6.2

- biz.aQute.launcher/src/aQute/launcher/Launcher.java
- docs/_chapters/300-launching.md
fixes https://github.com/bndtools/bnd/issues/3445
> Implement after-framework-init support for embedded activators

- aQute.libg/src/aQute/libg/uri/URIUtil.java
- aQute.libg/src/aQute/libg/uri/packageinfo
- aQute.libg/test/aQute/libg/uri/URIUtilsTest.java
- biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java
- biz.aQute.launcher/src/aQute/launcher/Launcher.java
> [launcher] Fix reporting output

- docs/_instructions/runstartlevel.md
> Fixed documentation -runstartlevel

- .travis.yml
- azure-pipelines.yml
- biz.aQute.bnd.runtime/build.gradle
- biz.aQute.bndall.tests/build.gradle
- biz.aQute.junit/bnd.bnd
- biz.aQute.junit/src/aQute/junit/Activator.java
- biz.aQute.junit/src/aQute/junit/plugin/ProjectTesterImpl.java
- biz.aQute.launchpad.tests/build.gradle
- biz.aQute.launchpad/build.gradle
- biz.aQute.tester.junit-platform/bnd.bnd
- biz.aQute.tester.junit-platform/resources/META-INF/services/org.junit.platform.engine.TestEngine
- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/BundleEngine.java
- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java
- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java
- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/plugin/ProjectTesterImpl.java
- biz.aQute.tester.test/.gitignore
- biz.aQute.tester.test/build.gradle
- biz.aQute.tester/bnd.bnd
- biz.aQute.tester/src/aQute/tester/plugin/ProjectTesterImpl.java
- docs/_chapters/310-testing.md
And reenable parallel builds for CI
> Junit platform tweaks

- docs/_chapters/310-testing.md
> [doc-fixes] Minor fixes for new JUnit-Platform docs

- .travis.yml
- azure-pipelines.yml
This reverts commit 81aaddda5b9f7606181ca58561c29f3b51c3a2f5.
Still seeing some spurious build failures in the CI builds.
> Revert "build: Re enable parallel builds in CI"

- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/PropertiesWrapper.groovy
- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/configuration/BeanProperties.java
- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/configuration/package-info.java
- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/BndrunContainer.java
- biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java
- biz.aQute.bndlib.tests/test/test/MacroTest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
We correctly add handling for setForceLocal to several places it was lacking. We also remove uninformative warnings when flattening properties. We clean up handling of projects/task properties for gradle and maven builds including not adding gradle objects to the properties for Bnd workspace model builds.
> Fixes to property handling

- biz.aQute.junit/src/aQute/junit/Activator.java
- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/BundleDescriptor.java
- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/BundleEngine.java
- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/BundleEngineDescriptor.java
- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java
- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java
- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/utils/BundleUtils.java
Updates to the activators for junit/tester and junit-platform. These use BundleTrackers to track test bundles.
> Junit activator updates

- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java
- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/JUnitEclipseListener.java
- biz.aQute.tester.test/test/aQute/tester/test/utils/TestBundler.java
Removed stray debugging. Tidied up a comment.
> [tester junit-platform] Minor cleanups

- docs/_instructions/runstartlevel.md
- docs/releases/4.3.0/instructions/runstartlevel.html
Fixes https://github.com/bndtools/bnd/issues/3535
> docs: Fix spelling of enum value

- .gradle-wrapper/gradle-wrapper.properties
- .travis.yml
- azure-pipelines.yml
- biz.aQute.bnd.gradle/README.md
- biz.aQute.bnd.gradle/build.gradle
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Index.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Resolve.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/TestOSGi.groovy
- biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBaselineTask.groovy
- biz.aQute.bnd.gradle/testresources/baselinetask1/build.gradle
- biz.aQute.bnd.gradle/testresources/indexplugin1/build.gradle
- biz.aQute.bnd.runtime/build.gradle
- biz.aQute.bndall.tests/build.gradle
- biz.aQute.launchpad.tests/build.gradle
- biz.aQute.launchpad/build.gradle
- biz.aQute.tester.test/build.gradle
- dist/build.gradle
- maven/pom.xml
- org.bndtools.p2/build.gradle
> Gradle and build updates

- bndtools.core/_plugin.xml
- bndtools.m2e/_plugin.xml
- bndtools.m2e/src/bndtools/m2e/MavenRunListenerHelper.java
> [bndtools.m2e] junit launcher doesn't understand maven profiles

- aQute.libg/src/aQute/lib/strings/Strings.java
- biz.aQute.bndlib.tests/test/test/MacroTest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
- docs/_macros/basenameext.md
- docs/_macros/extension.md
Fix extension macro and add new basenameext macro.
> Macro fixes

- biz.aQute.launcher/src/aQute/launcher/Launcher.java
- docs/_chapters/300-launching.md
The original model had 2 phases:
* framework inited
* framework started
* IMMEDIATE=true -> before bundles were started
* IMMEDIATE=false (or not set)-> after all bundles were started
After the start level and the work done for launching Eclipse
we had the following situation:
* framework inited
* IMMEDIATE = "AFTER_FRAMEWORK_INIT"
* IMMEDIATE=true || BEFORE_BUNDLES_STARTED -> before bundles were started
* IMMEDIATE=false (or not set) || AFTER_BUNDLES_STARTED -> after all bundles were started
* framework started
This meant that there was no different between BEFORE_BUNDLES_STARTED and
AFTER_BUNDLES_STARTED. Therefore, for 4.3.1 we moved to during the meeting:
* framework inited
* IMMEDIATE = "AFTER_FRAMEWORK_INIT"
* IMMEDIATE=true || BEFORE_BUNDLES_STARTED -> before bundles were started
* …
> [embedded activators] Framework start point

- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/BundleEngine.java
SingleTestExecutor is now deprecated. Refactored to an alternative.
Unfortunately, a key part of the suggested alternative in the deprecation note was package private. Had to go with a roll-your-own approach instead, but the code was simple enough to make this easy.
Fixes #3600.
> [junit-platform tester] Remove deprecation warning

- aQute.libg/src/aQute/lib/strings/Strings.java
- biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java
- biz.aQute.bndlib/src/aQute/bnd/build/ProjectTester.java
- biz.aQute.junit/src/aQute/junit/plugin/ProjectTesterImpl.java
- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java
- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/plugin/ProjectTesterImpl.java
- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/utils/BundleUtils.java
- biz.aQute.tester.test/src/aQute/tester/testclasses/junit/platform/ParameterizedTesterNamesTest.java
- biz.aQute.tester.test/test/aQute/tester/junit/platform/test/ActivatorTest.java
- biz.aQute.tester.test/test/aQute/tester/test/utils/TestBundler.java
- biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorTest.java
- biz.aQute.tester/src/aQute/tester/plugin/ProjectTesterImpl.java
This PR is a partial fix for #3580.
> [junit-platform tester] Allow quoted test names

- biz.aQute.bnd/src/aQute/bnd/main/EclipseCommand.java
- biz.aQute.bnd/src/aQute/bnd/main/bnd.java
> [eclipse] Small command to sync .settings directories in a workspace

- biz.aQute.bnd.annotation/bnd.bnd
- biz.aQute.bnd.annotation/src/aQute/bnd/annotation/spi/Constants.java
- biz.aQute.bnd.annotation/src/aQute/bnd/annotation/spi/ServiceProvider.java
- biz.aQute.bndlib.tests/test/test/annotationheaders/SPIAnnotationsTest.java
> [spi] providing the osgi.service capability for @ServiceProvider

- bndtools.core/src/bndtools/launch/AbstractOSGiLaunchDelegate.java
* Use the TerminationListener to tidy-up launch delegate code a little.
> [bndtools] Code tidy-up using TerminationListener

- build.gradle
This will help debugging failures on CI builds.
Fixes https://github.com/bndtools/bnd/issues/3614
> build: Collect test output and display only if the test fails

- build.gradle
Otherwise we have duplicate output.
> build: Display test output on test fail only if not --info

- docs/_chapters/650-windows.md
- docs/_instructions/runnoreferences.md
Manual page with tips for Windows users.
Implements #3644.
> Windows tips page

- biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
When a standalone workspace is created, always copy the -plugin
properties from the run into the workspace.
Fixes https://github.com/bndtools/bnd/issues/3509
> workspace: Copy -plugin properties for standalone workspace

- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java
We don't want to start a bundle to try and resolve it. But if attempting
to resolve a bundle does not succeed, we then call Bundle.start to
capture a BundleException with resolution failure information for the
test execution.
Fixes https://github.com/bndtools/bnd/issues/3664
> junit-platform: Capture real BundleException with resolve failure

- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java
- biz.aQute.tester.test/test/aQute/tester/bundle/engine/test/BundleEngineTest.java
Fixes #3581.
Could refactor this to make it nicer, but just get something that works for now.
> [junit-platform tester] Don't run tests that aren't in Test-Cases

- biz.aQute.junit/src/aQute/junit/JUnitEclipseReport.java
- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/JUnitEclipseListener.java
Some updates I made while reviewing/learning the code trying to see if
I could figure out https://github.com/bndtools/bnd/issues/3559. These
changes are improvements, but they did not appear to solve the issue.
> junit: Updates to the Eclipse reporting

- maven/bnd-maven-plugin/README.md
See https://github.com/bndtools/bnd/issues/3521#issuecomment-572695574
> maven: Add reproducible build section to bnd-maven-plugin README

- bndtools.core/bndtools.shared.bndrun
- bndtools.core/src/bndtools/nature/ToggleNatureAction.java
* fixes #3629 "Add Bndtools Project Nature" not completely working
Signed-off-by: Signed-off-by: Juergen Albert <j.albert@data-in-motion.biz>
> [BndTools] added project refresh after add nature

- biz.aQute.bndlib.tests/test/test/JarTest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
> Jar zipslip

- .github/workflows/cibuild.yml
See https://github.com/gradle/wrapper-validation-action
> gradlew: Validate wrapper jar

- bndtools.jareditor/src/bndtools/jareditor/internal/JarFileSystem.java
We failed to handle stale cache entries so that if a cached jar changed,
we failed to rebuild its node tree. This lead to showing entries in
the jar editor that were no longer present.
> jareditor: Check for staleness in roots cache

- biz.aQute.bndlib.tests/test/test/baseline/BaselineTest.java
- maven/bnd-baseline-maven-plugin/README.md
- maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-provider-require-bundle-version-change/pom.xml
- maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-provider-require-bundle-version-change/src/main/java/bnd/test/TestConsumerIface.java
- maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-provider-require-bundle-version-change/src/main/java/bnd/test/TestProviderIface.java
- maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-provider-require-bundle-version-change/src/main/java/bnd/test/package-info.java
- maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/pom.xml
- maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-provider-no-bundle-version-change/pom.xml
- maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-provider-no-bundle-version-change/src/main/java/bnd/test/TestConsumerIface.java
- maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-provider-no-bundle-version-change/src/main/java/bnd/test/TestProviderIface.java
- maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-provider-no-bundle-version-change/src/main/java/bnd/test/package-info.java
- maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/verify.groovy
> Add parameter to skip bundle version check

- biz.aQute.bnd.gradle/README.md
- biz.aQute.bnd.reporter/bnd.bnd
- biz.aQute.bndlib.tests/test/test/VersionTest.java
- biz.aQute.bndlib/src/aQute/bnd/build/Project.java
- biz.aQute.bndlib/src/aQute/bnd/build/model/conversions/RequirementListConverter.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/repository/BaseRepository.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapReqBuilder.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapabilityBuilder.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/Filters.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/RequirementBuilder.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/SyntheticBuilder.java
- biz.aQute.bndlib/src/aQute/bnd/version/VersionRange.java
- biz.aQute.junit/bnd.bnd
- biz.aQute.repository/src/aQute/bnd/deployer/repository/AbstractIndexedRepo.java
- biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java
- biz.aQute.resolve/src/biz/aQute/resolve/AbstractResolveContext.java
- biz.aQute.resolve/src/biz/aQute/resolve/DebugReporter.java
- bndtools.core/src/bndtools/editor/project/AbstractRequirementListPart.java
- bndtools.core/src/bndtools/tasks/AnalyseBundleResolutionJob.java
- bndtools.core/src/bndtools/tasks/BndBuilderCapReqLoader.java
- bndtools.core/src/bndtools/views/repository/ArbitraryNamespaceSearchPanel.java
- bndtools.core/src/bndtools/views/repository/PackageSearchPanel.java
- bndtools.core/src/bndtools/views/repository/ServiceSearchPanel.java
- bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionSuccessPanel.java
- bndtools.core/src/org/bndtools/core/templating/repobased/ReposTemplateLoader.java
- bndtools.core/test/bndtools/tasks/AnalyseBundleResolutionJobTest.java
- bndtools.release/src/bndtools/release/DiffHelper.java
- cnf/build.bnd
- maven/bnd-baseline-maven-plugin/README.md
A collection of fixes for resource capability and requirement parsing and building.
> Resource fixes

- biz.aQute.bndlib.tests/test/test/VersionTest.java
I was too lazy when I originally wrote the test to make it a
parameterized test. Fixed!
> test: Convert test to use parameters

- docs/_chapters/230-manifest-annotations.md
- Added shortcuts for MavenBndRepository GAVs
- Explained filter generation with the @Requirement
> [doc] Manifest Annotations

- bndtools.core/src/bndtools/editor/BndEditor.java
When the IEditorInput is not mappable to a resource
but we can map it to a Java File, we allow inputResource
to be null.
To load the editor model, we then create a standalone
Run for the project.
This class could use some major cleanup. One wonders
if by now there is not better editors support in 
Eclipse?
> [bndeditor] Fix for NPE while opening a file outside the workspace

- docs/_chapters/300-launching.md
* example about JaCoCo as a javaagent
* based on discussion in https://groups.google.com/forum/#!topic/bndtools-users/fjavKvFERBg
Signed-off-by: Christoph Rueger <chrisrueger@gmail.com>
> Add Example for using -javaagent parameter

- biz.aQute.bndlib/src/aQute/bnd/maven/MavenCommand.java
- biz.aQute.bndlib/src/aQute/bnd/maven/MavenDeployCmd.java
> [lgtm] Warnings

- bndtools.core/src/bndtools/wizards/project/NewBndProjectWizardPageOne.java
Signed-off-by: Alexander Bunkowski <alexander.bunkowski@bruker.com>
> Setting initial focus in new Bnd OSGi Project Wizard to project name text field.

- bndtools.core/src/bndtools/editor/BndEditor.java
- bndtools.core/src/bndtools/editor/project/RunFrameworkPart.java
Fixes #3791 and a couple of other minor related fixes.
> [BndEditor] Fix check for resource availability on resolve

- biz.aQute.remote/src/aQute/remote/agent/SocketRedirector.java
> [lgtm] Potential NPE pointed at by LGTM

- maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
Some Maven projects need to support different versions of Java across
different modules, e.g. a shared library that builds with Java 1.8 for
maximum compatibility plus an application module that takes advantage of
new language features in Java 11. The canonical way to handle this is
with Maven's Toolchain feature, which is supported by core plugins such
as the maven-compiler-plugin and maven-surefire-plugin.
bnd-testing-maven-plugin does not currently support Toolchains.
Instead, it launches java using whatever JDK was used to run mvn itself.
This make it impossible to support different Java versions in different
modules.
This change very simply adds the JAVA_HOME from the Maven Toolchain
manager if and only if one is defined by the POM. Projects that do not
specify a Toolchain are …
> Use Maven Toolchain JAVA_HOME to launch test runtime

- biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java
- biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java
This fix was added to the 5.1 master but had
API changes. This is similar without the API
changes.
basically allows a -executable: location='${@bsn}'
instruction to set the format of the path used
in the launcher executable jar. The default 
path can contain versions and since the path
is used for the OSGi location, new bundles
are created then the path changes. So you get
the same bsn installed several times. Not good
> [launcher] Support -executable location format

- aQute.libg/src/aQute/lib/bundles/package-info.java
- aQute.libg/src/aQute/lib/hierarchy/package-info.java
- biz.aQute.resolve/bnd.bnd
- biz.aQute.resolve/src/biz/aQute/resolve/package-info.java
- cnf/build.bnd
Update baselining after 5.0.1 release.
> Baseline 5.0.1

- biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java
> unwraps the InvocationTargetException to report the real error

- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/ReleasePluginImpl.java
Regression after commit a8117b64
> Fix: Indexing of released projects

- biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
- biz.aQute.repository/src/aQute/bnd/deployer/repository/packageinfo
- biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java
- biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiRepository.java
- biz.aQute.repository/src/aQute/bnd/repository/osgi/packageinfo
- biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java
- bndtools.core/src/bndtools/model/repo/RepositoryTreeLabelProvider.java
The getStatus() and isRemote() are now implemented to support the RepositoriesView
> [repos] OSGiRepository adapted to Bndtools reporting

- biz.aQute.repository/bnd.bnd
- biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java
- biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Repository.java
- biz.aQute.repository/src/aQute/bnd/repository/p2/provider/package-info.java
- biz.aQute.repository/src/aQute/p2/api/Artifact.java
- biz.aQute.repository/src/aQute/p2/api/package-info.java
- biz.aQute.repository/src/aQute/p2/packed/Unpack200.java
- biz.aQute.repository/src/aQute/p2/provider/ArtifactRepository.java
- biz.aQute.repository/src/aQute/p2/provider/P2Impl.java
- biz.aQute.repository/src/aQute/p2/provider/TargetImpl.java
- biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2IndexerTest.java
- biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2RepositoryTest.java
- biz.aQute.repository/test/aQute/p2/provider/P2ImplTest.java
- biz.aQute.repository/test/aQute/p2/provider/TargetImplTest.java
As the Pack200 class is deprecated in JavaSE-11 we use the unpack200 command.
> [P2Repository] Adds support for format="packed" (pack200)

- docs/_instructions/define-contract.md
> doc define-contract instruction

- docs/_macros/findproviders.md
Updated documentation of the newly added findproviders macro.
@pkriens : I was unsure about where to place the Maven part you suggested I add. If you had another place in mind, please let me know.
> Updated documentation of findproviders macro

- docs/_instructions/define-contract.md
> fixup -define-contract document

- .github/workflows/cibuild.yml
Lets try building gradle parallel in the CI build again...
> ci: Build gradle tasks in parallel

- .github/workflows/cibuild.yml
- biz.aQute.bndlib.tests/test/test/model/EETest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
- biz.aQute.repository/test/aQute/bnd/repository/p2/provider/EnabledIfUnpack200.java
- biz.aQute.repository/test/aQute/bnd/repository/p2/provider/EnabledIfUnpack200Condition.java
- biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2RepositoryTest.java
- build.gradle
Includes a number of fixes to build and test successfully on JDK 15-ea.
> Add JDK 15-ea build

- biz.aQute.bndlib/src/aQute/bnd/stream/EntryPipeline.java
- biz.aQute.bndlib/src/aQute/bnd/stream/MapStream.java
- biz.aQute.bndlib/src/aQute/bnd/stream/package-info.java
- biz.aQute.bndlib/test/aQute/bnd/stream/MapStreamTest.java
This works on Java 8 since it provides its own implementation.
> mapstream: Add takeWhile and dropWhile methods

- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/exporter/ReportExporterTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/generator/BasicReportGeneratorTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/generator/ConfiguredReportGeneratorTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/helpers/HeadersHelperTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/helpers/LocaleHelperTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/helpers/ManifestHelperTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/bundle/ComponentsPluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/bundle/ImportJarResourcePluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/bundle/ManifestPluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/bundle/MavenCoordinatePluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/bundle/MetatypesPluginTest.java
> [reporter] Use try-with-res

- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/maven/dto/MavenCoordinatesDTO.java
- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/entries/bundle/MavenCoordinatePlugin.java
- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/templates/blocks.twig
- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/templates/printer.twig
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/bundle/MavenCoordinatePluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/transformer/JtwigPrinterTest.java
> [reporter] improve bundle coordinates

- aQute.libg/test/aQute/libg/command/CommandTest.java
> Commands-Test should also run with JAVA_HOME

- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/JtwigTransformerPlugin.java
- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/TaggedFunctions.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/transformer/JtwigTransformerPluginTest.java
- biz.aQute.bnd.reporter/testresources/transformer/jtwigShowSection.twig
This we need to have a way inside the templates to check which section should be shown (ref. #3923).
> [reporter] templates should to show a subset of sections

- aQute.libg/src/aQute/lib/memoize/MemoizingSupplier.java
We use the same slot to hold the delegate supplier and its result.
This is possible since we don't need to hold them both at the same time.
> memoize: Reduce memory size of a MemoizingSupplier

- biz.aQute.bndlib/src/aQute/bnd/osgi/repository/ResourcesRepository.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java
It should have been there in the first place.
> resource: Move toCapabilities collector to ResourceUtils

- bndtools.core/src/bndtools/central/EclipseWorkspaceRepository.java
Whenever there is an update from a bundle build, we create a new
supplier. This ensure any supplied repository use the latest resources
and enables the repository to be usable until their is an update.
> workspacerepo: Replace repository supplier on each update

- aQute.libg/src/aQute/libg/uri/URIUtil.java
- biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java
- biz.aQute.repository/src/aQute/maven/provider/MavenBackingRepository.java
- biz.aQute.repository/src/aQute/maven/provider/SnapshotReleaser.java
If the maven metadata was fetched, not found
was not treated as an error.
> [maven] Bad handling of authentication error

- biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java
A change earlier has ceased to return the jar processing which included
localizing the manifest. The code always treated the file as a zip.
We change to use JarFile for File instead of JarInputStream to gain some
performance. We also disable Jar verification since we just want the
manifest.
> domain: Properly handle jar file localization

- biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomConfiguration.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/package-info.java
- biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java
- bndtools.test/workspace-comms/cnf/ext/repositories.bnd
- docs/_plugins/pomrepo.md
* fixes #3872
* moved from Exceptions status messages in the BndPomRepository
> created non-s versions of snapshot and release url properties

- aQute.libg/src/aQute/lib/memoize/CloseableMemoize.java
- aQute.libg/src/aQute/lib/memoize/CloseableMemoizingSupplier.java
- aQute.libg/test/aQute/lib/memoize/MemoizeTest.java
- biz.aQute.bndlib/src/aQute/bnd/build/Project.java
- biz.aQute.bndlib/src/aQute/bnd/build/ProjectGenerate.java
- biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
- biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceClassIndex.java
- biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceExternalPluginHandler.java
@pkriens I added a CloseableMemoize after our discussion today and fixed the workspace and project to be closeable and use it.
This is also based on a change to make Memoize an interface with peek and some monadic methods.
> Fix workspace closeable

- biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java
- biz.aQute.tester.test/src/aQute/tester/testclasses/bundle/engine/JUnit5ParameterizedSubclassTest.java
- biz.aQute.tester.test/src/aQute/tester/testclasses/bundle/engine/JUnit5ParameterizedTest.java
- biz.aQute.tester.test/src/aQute/tester/testclasses/bundle/engine/TestWithField.java
- biz.aQute.tester.test/test/aQute/tester/bundle/engine/test/BundleEngineTest.java
> [junit-platform] Handle singleton unresolveds

- aQute.libg/src/aQute/lib/memoize/CloseableMemoize.java
- aQute.libg/src/aQute/lib/memoize/CloseableMemoizingSupplier.java
- aQute.libg/src/aQute/lib/memoize/Memoize.java
- aQute.libg/src/aQute/lib/memoize/MemoizingSupplier.java
- aQute.libg/src/aQute/lib/memoize/ReferenceMemoizingSupplier.java
- aQute.libg/src/aQute/lib/memoize/RefreshingMemoizingSupplier.java
- aQute.libg/test/aQute/lib/memoize/CallOnOtherThread.java
- aQute.libg/test/aQute/lib/memoize/MemoizeTest.java
Lots of javadoc improvements and other doc updates. Some more tests.
> memoize: Change CloseableMemoize to not serialize accepts

- biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/InnerRepository.java
- biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java
> fixes BndPomRepo refresh error #3952

- biz.aQute.bnd/src/aQute/bnd/main/bnd.java
- biz.aQute.bndlib/src/aQute/bnd/build/ProjectGenerate.java
- biz.aQute.bndlib/src/aQute/bnd/junit/package-info.java
- biz.aQute.bndlib/src/aQute/bnd/maven/package-info.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
property files.
The date/time check wasn't looking for included
files and files from ancestors of the project. So
I've added those
Also added a generate command to bnd and added the
generate step to _par
> [generate] Make the output depend on the project's

- bndtools.core/src/bndtools/launch/BndDependencySourceLookupDirector.java
> [bndtools debug] Add BndDependencySourceContainer ahead of default

- bndtools.core/src/bndtools/launch/BndDependencySourceContainer.java
> [bndtools debug] Add -runfw to debug sources

- biz.aQute.bndlib/src/aQute/bnd/osgi/repository/AbstractIndexingRepository.java
We refactor adding a resource collection supplier into a protected
method.
> indexingrepo: Minor refactoring

- aQute.libg/src/aQute/lib/io/IO.java
- biz.aQute.bndlib/src/aQute/bnd/build/ProjectGenerate.java
- bndtools.builder/_plugin.xml
- bndtools.builder/src/org/bndtools/builder/BndSourceGenerateCompilationParticipant.java
- Force now cleans all files
- No check anymore
- Method to clean and check if build is needed
- Better error handling
- bndgenerate marker does not inherit other bnd marker
> [generate] Minor fixes

- cnf/build.bnd
- cnf/ext/junit.bnd
Update assertj dependency to 3.16.0
> Assertj 3.16

- biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
I profiled the build of the org.osgi.test.cases.framework project in OSGi which is a large projects and makes a bundle with hundreds (>260) nested bundles. Building the jar for this project has always been slow so I decided to dive deeper. 
I found 2 main hot spots for which fixes are in this PR. Any times mentioned in the commits were while profiling with YourKit and aren't precise. However, I did some more measurements on the OSGi build to compare 5.1.0-SNAPSHOT (pre-fix) against the two fixes in this PR (post-fix).
A parallel, incremental build with pre-fix took 15:06 on my system. With post-fix it takes 1:55 which is a major reduction in time. Even though this was an incremental build, because the Gradle plugin changed, the build reran all the jar tasks. So the jar tasks are running …
> Performance fixes

- biz.aQute.bnd.javagen/README.md
- docs/_instructions/generate.md
> [generate] docs update

- docs/_instructions/generate.md
> [docs] wrong first character

- biz.aQute.bndlib.tests/test/test/MacroTest.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
We don't want to propagate the exception to avoid deleting a valid multi
jar if one of its parts is bad.
> maven repo: Better handle invalid jar files

- biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/SettingsParserTest.java
- biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java
Rewrote `ConnectionSettings.normalize()` with plain regex: `java.net.URI` failed to parse expressions with wildcards; resulting string looked like "https://null".
> maven repo: fix URL normalization to support glob server IDs

- biz.aQute.bndlib/src/aQute/bnd/osgi/repository/AbstractIndexingRepository.java
- biz.aQute.resolve/src/biz/aQute/resolve/WorkspaceResourcesRepository.java
- bndtools.core/src/bndtools/central/EclipseWorkspaceRepository.java
- bndtools.m2e/src/bndtools/m2e/MavenWorkspaceRepository.java
This can allow subclasses to support indexing things other than File.
> abstractindexingrepo: Refactor to generify File

- aQute.libg/src/aQute/lib/map/Maps.java
- aQute.libg/src/aQute/lib/map/package-info.java
- aQute.libg/test/aQute/lib/map/MapsTest.java
Like Java 9's Map.of but it works on Java 8 which we still support.
This impl does not randomize order. It preserves the order.
> lib: Add Maps map builder API

- bndtools.m2e/src/bndtools/m2e/MavenWorkspaceRepository.java
> [m2e] Ensure MavenWorkspaceRepository calls listener callbacks

- bndtools.m2e/src/bndtools/m2e/MavenBndrunContainer.java
- bndtools.m2e/src/bndtools/m2e/MavenDependenciesRepository.java
- bndtools.m2e/src/bndtools/m2e/MavenWorkspaceRepository.java
> m2e: fix non-bundle naming in repository tree

- aQute.libg/src/aQute/lib/unmodifiable/ImmutableList.java
- aQute.libg/src/aQute/lib/unmodifiable/ImmutableSet.java
- aQute.libg/src/aQute/lib/unmodifiable/Lists.java
- aQute.libg/src/aQute/lib/unmodifiable/Maps.java
- aQute.libg/src/aQute/lib/unmodifiable/Sets.java
- aQute.libg/test/aQute/lib/unmodifiable/ListsTest.java
- aQute.libg/test/aQute/lib/unmodifiable/MapsTest.java
- aQute.libg/test/aQute/lib/unmodifiable/SetsTest.java
- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/BndrunContainer.java
- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/DependencyResolver.java
- biz.aQute.bnd/src/aQute/bnd/main/BaselineCommands.java
- biz.aQute.bnd/src/aQute/bnd/main/bnd.java
- biz.aQute.bndlib/src/aQute/bnd/component/HeaderReader.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/OSInformation.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
- bndtools.core/src/bndtools/editor/project/SubBundlesPart.java
- bndtools.core/src/bndtools/internal/testcaseselection/JavaSearchScopeTestCaseLister.java
- bndtools.core/src/bndtools/views/resolution/ResolutionView.java
- bndtools.core/src/bndtools/wizards/bndfile/EnableSubBundlesOperation.java
- bndtools.m2e/src/bndtools/m2e/MavenDependenciesRepository.java
- maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java
- maven/bnd-resolver-maven-plugin/src/main/java/aQute/bnd/maven/resolver/plugin/ResolverMojo.java
- maven/bnd-run-maven-plugin/src/main/java/aQute/bnd/maven/run/plugin/RunMojo.java
- maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
We also replace some Arrays.asList usage with the unmodifiables. 
We also fix some other bugs found when looking at usage of Arrays.asList.
> Fixes for unmodifiable types

- biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
- biz.aQute.bndlib/src/aQute/bnd/print/JarPrinter.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
- biz.aQute.repository/src/aQute/maven/provider/POM.java
- bndtools.core/src/bndtools/wizards/bndfile/EnableSubBundlesOperation.java
More usage of unmodifiable types.
> Unmodifiable uasge

- bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java
Fixes https://github.com/bndtools/bnd/issues/4085
> explorer: Handle standalone workspace so no NPE

- bndtools.core/src/bndtools/dnd/gav/BndDropTargetListener.java
- bndtools.core/src/bndtools/dnd/gav/GAVDropTargetListener.java
- bndtools.core/src/bndtools/dnd/gav/GradleDropTargetListener.java
- bndtools.core/src/bndtools/dnd/gav/MavenDropTargetListener.java
> dbd.gav: restructure as an event

- biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Config.java
- docs/_chapters/390-wrapping.md
- docs/_plugins/localindexrepo.md
- docs/_plugins/osgirepo.md
- docs/_plugins/p2repo.md
- Also removed an unused config property from the P2Config
- removed some odd characters in the wrapping md
With the LocalIndexRepo I would need some help. I can't make heads or tails out of some of the properties, 
> Added documentation for p2, osgi and local repo

- biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_10_0.properties
- biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_11_0.properties
- biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_12_0.properties
- biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_13_0.properties
- biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_14_0.properties
- biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_9_0.properties
Using the tool at https://github.com/bjhargrave/java-platform-packages,
I regenerated the ee properties files for Java 9 through 14. Ray has
already updated them for Java 15+.
> model: Update EE properties based upon introspection of the runtime

- bndtools.core/src/bndtools/editor/BndSourceEditorPage.java
> Allow plugins everywhere

- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/generator/ReportGeneratorBuilder.java
Closes #4150 
Am I right? @stbischof, @pkriens.
> [reporter] Use Class instead of class name to register default plugins

- .github/workflows/cibuild.yml
- cnf/ext/ossrh-settings.xml
- cnf/ext/repositories.bnd
- maven/build.gradle
Also remove OSSRH support since we no longer use it.
> ci: Using single job with matrix

- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
It always showed nothing for snapshot repos.
> mavenbndrepo: Fix tooltip to show snapshot repo information

- cnf/ext/central.mvn
- cnf/ext/osgi-snapshots.mvn
- cnf/ext/repositories.bnd
We can then just edit the one mvn file to add or remove snapshot
versions.
> build: Use one mavenbndrepo for release and snapshot urls

- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java
> [junit-platform] Log output to stdout instead stderr

- biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
We hoist some string building out of the loop.
> macro: Some minor String building improvements

- biz.aQute.bnd.gradle/publish.gradle
- cnf/build.bnd
> build: Update baseline for 5.1.2 release

- bndtools.core/src/bndtools/central/Central.java
- bndtools.core/src/bndtools/explorer/Model.java
> Avoid race condition resolving workspace promises

- bndtools.m2e/src/bndtools/m2e/MavenRunProvider.java
> [m2e] MavenRunProvider to handle SOURCES mode

- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/templates/printer.twig
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/transformer/JtwigPrinterTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/transformer/JtwigReadmeTest.java
add a description section into the component. 'service.description' property is used.
> [Reporter] show component-description in readme

- bndtools.core/src/org/bndtools/core/resolve/ResolveOperation.java
- bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionCanceledPanel.java
> fixed # 4235 NPE on Resolve job cancel

- docs/_instructions/dsannotations-options.md
This has been added with https://github.com/bndtools/bnd/pull/3121/files
> Document maximum version

- bndtools.core/src/bndtools/wizards/bndfile/BndRunFileWizard.java
- bndtools.core/src/bndtools/wizards/project/NewBndProjectWizard.java
- bndtools.core/src/bndtools/wizards/workspace/WorkspacePreviewPage.java
- bndtools.core/src/bndtools/wizards/workspace/WorkspaceSetupWizard.java
- bndtools.core/src/org/bndtools/core/ui/wizards/shared/ISkippableWizardPage.java
- bndtools.core/src/org/bndtools/core/ui/wizards/shared/ISkippingWizard.java
- bndtools.core/src/org/bndtools/core/ui/wizards/shared/TemplateParamsWizardPage.java
I had a need for custom parameters in a workspace template I was trying to set up.
Also had a need to configure a password in the template, so added support for password attributes.
> [template] Add parameter support for workspace templates

- biz.aQute.bnd/src/aQute/bnd/main/bnd.java
- docs/_commands/runtests.md
Fixes https://github.com/bndtools/bnd/issues/4264
> bnd: Add --tests option to the Bnd runtests command

- bndtools.core/src/bndtools/wizards/workspace/package-info.java
> [bndtools] Un-export bndtools.wizards.workspace

- biz.aQute.repository/src/aQute/bnd/deployer/repository/LocalIndexedRepo.java
- biz.aQute.repository/src/aQute/bnd/deployer/repository/packageinfo
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/RepoActions.java
- biz.aQute.repository/src/aQute/maven/api/IMavenRepo.java
- biz.aQute.repository/src/aQute/maven/api/package-info.java
- biz.aQute.repository/src/aQute/maven/provider/MavenBackingRepository.java
- biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java
- biz.aQute.repository/src/aQute/maven/provider/MetadataParser.java
- biz.aQute.repository/src/aQute/maven/provider/SnapshotReleaser.java
- biz.aQute.repository/src/aQute/maven/provider/packageinfo
> MavenBndRepository snapshot refresh function

- bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java
- bndtools.core.test/bnd.bnd
- bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessorTest.java
- bndtools.core.test/src/iface/bundle/MyForeignClass.java
More quick fixes for more situations.
> [quickfix] Add fixes for MissingField/MissingMethod

- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/BndrunContainer.java
- maven/bnd-maven-plugin/README.md
- maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
- maven/bnd-maven-plugin/src/test/resources/integration-test/test/pom.xml
- maven/bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy
- maven/pom.xml
Updates for reproducible builds for maven plugins.
> Maven reproducible builds

- biz.aQute.bndlib.tests/test/aQute/bnd/build/classindex/ClassIndexTest.java
- biz.aQute.bndlib.tests/test/test/DescriptorsTest.java
- biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
- biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceClassIndex.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Descriptors.java
> [classindex] Properly handle binary class name

- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/BndrunContainer.java
- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/DependencyResolver.java
- bndtools.m2e/src/bndtools/m2e/MavenWorkspaceRepository.java
> [m2e] fix dependency management resolving

- bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java
- bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessorTest.java
This PR was motivated by me trying to convert a build which contained a statement `FrameworkUtil.getBundleContext()`.
In this context the compiler can't tell if the name `FrameworkUtil` refers to a missing type or a missing variable, and so the internal error it generates is not an "UnknownType" but an "UnknownName". The quickfix processor was not set up to handle this.
Also in this PR: courtesy of #4291, many of the test cases for nested classes now work and can be re-instated. The only remaining case that doesn't work is the bare simple name referring to a nested type (which doesn't have any index support at the moment).
> [quickfix] Add support for static references to undefined types

- biz.aQute.launcher/src/aQute/launcher/Launcher.java
- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java
- biz.aQute.tester/src/aQute/junit/Activator.java
- biz.aQute.tester/src/aQute/junit/BasicTestReport.java
- biz.aQute.tester/src/aQute/junit/Tee.java
- bndtools.core.test/bnd.bnd
- bndtools.core.test/test.shared.bndrun
Some fixes to improve the situation with output from tests interleaving making the output unreadable.
> TestOSGi output interleaving

- docs/_chapters/180-baselining.md
> document @BaselineIgnore

- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java
Fixes https://github.com/bndtools/bnd/issues/4303
> junit-platform: Allow configuration of capturing stdout and stderr

- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/BndrunContainer.java
- maven/bnd-resolver-maven-plugin/README.md
- maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/pom.xml
- maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/resolve-infer-with-custom-bsn/pom.xml
- maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/resolve-infer-with-custom-bsn/src/main/java/com/acme/Foo.java
- maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/resolve-infer-with-custom-bsn/test.bndrun
- maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/verify.groovy
> BndrunContainer incorrectly assumes artifactId == osgi.identity

- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/JUnitEclipseListener.java
This allows biz.aQute.tester.junit-platform to be used with concurrency and have the Eclipse JUnit display still work properly.
Fixes #4308.
Seems to work properly, as evidenced by the following clip:
Of course, many of the tests fail because the tests themselves are not thread-safe. However, you can see that Eclipse is correctly reporting the test results - unlike the screenshot in  #4308 none of the tests are left displayed as unfinished or unstarted. You can also see from the clip that there are points where the GUI is displaying results from multiple tests simultaneously. 
I've been too lazy to write regression tests for this though - maybe one day...
> [junit-platform] Serialise JUnitEclipseListener

- aQute.libg/src/aQute/lib/io/FileTree.java
- aQute.libg/src/aQute/libg/glob/PathSet.java
- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/configuration/FileTree.java
With debug output, maven will show the toString output of configurable
items. So we add some toString methods.
> maven: Add some toString implementations for debugging

- biz.aQute.tester.junit-platform/bnd.bnd
- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java
- biz.aQute.tester.test/bnd.bnd
- biz.aQute.tester.test/test/aQute/tester/junit/platform/test/ActivatorJUnitPlatformTest.java
- biz.aQute.tester.test/test/aQute/tester/junit/platform/test/GogoShellTests.java
- biz.aQute.tester.test/test/aQute/tester/test/ActivatorTest.java
- biz.aQute.tester.test/test/aQute/tester/test/utils/TestRunListener.java
- biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorCommonTest.java
- biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorTest.java
If Gogo is in the environment, then in automatic mode the tester will register a "runtests" command that allows you to interactively run tests from the shell.
scope: tester
command syntax: runtests :my.bsn.name my.fq.ClassName my.fqClassName#forMethod
Fixes #3812
> [junit-platform] Added Gogo commandlet

- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/RepoActions.java
- biz.aQute.repository/src/aQute/maven/api/IMavenRepo.java
- biz.aQute.repository/src/aQute/maven/provider/MavenBackingRepository.java
- biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java
Added a menu entry on snapshots to refresh this
snapshot archive.
A few API changes to allow passing a force flag.
> [maven] Another try for the Maven Bnd Repository

- maven/bnd-baseline-maven-plugin/pom.xml
- maven/bnd-export-maven-plugin/pom.xml
- maven/bnd-indexer-maven-plugin/pom.xml
- maven/bnd-maven-plugin/pom.xml
- maven/bnd-reporter-maven-plugin/pom.xml
- maven/bnd-resolver-maven-plugin/pom.xml
- maven/bnd-run-maven-plugin/pom.xml
- maven/bnd-testing-maven-plugin/pom.xml
> Add Maven version prerequisite for all Maven plugins

- biz.aQute.repository/src/aQute/maven/provider/POM.java
Fixes https://github.com/bndtools/bnd/issues/4328
> pom: Check for null before doing macro replacement

- biz.aQute.bnd/src/aQute/bnd/main/bnd.java
- biz.aQute.repository/src/aQute/maven/provider/MavenBackingRepository.java
- biz.aQute.repository/src/aQute/maven/provider/MavenFileRepository.java
- biz.aQute.repository/src/aQute/maven/provider/MavenRemoteRepository.java
> [maven] More forcing

- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/JUnitEclipseListener.java
- biz.aQute.tester.test/src/aQute/tester/test/assertions/internal/CustomAssertionFailedError.java
- biz.aQute.tester.test/src/aQute/tester/test/assertions/internal/CustomJUnit3ComparisonFailure.java
- biz.aQute.tester.test/src/aQute/tester/test/assertions/internal/CustomJUnit4ComparisonFailure.java
- biz.aQute.tester.test/src/aQute/tester/test/assertions/internal/CustomMultipleFailuresError.java
- biz.aQute.tester.test/src/aQute/tester/testclasses/junit/platform/JUnitComparisonSubclassTest.java
- biz.aQute.tester.test/test/aQute/tester/junit/platform/test/ActivatorJUnitPlatformTest.java
> [junit-platform] Handle subclasses of comparison failure assertions

- biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
> fix: Run was not closed after export in ProjectBuilder

- biz.aQute.launcher/src/aQute/launcher/Launcher.java
The serviceregistration of the launcher is currently the only way, to retrieve the launcher arguments in the Framework. Especially for a lot of the Eclipse Bundles, it is necessary to have this information as early as possible. Thus the launcher needs to be registered right after the framework is started and not after all is done.. 
> [launcher] The launcher will now be registered as soon as possible

- biz.aQute.repository/src/aQute/maven/nexus/provider/Signer.java
- biz.aQute.repository/src/aQute/maven/provider/Releaser.java
- docs/_instructions/maven-release.md
> fixed gpg signing for MavenBndRepository release

- bndtools.core/src/org/bndtools/core/resolve/ResolveOperation.java
The model properties are not properly resolved for the special here
`${.}` macro. So make a copy and call replaceHere on the copy.
Fixes https://github.com/bndtools/bnd/issues/4396
> bndtools: Fixup model properties for resolving

- aQute.libg/src/aQute/lib/getopt/CommandLine.java
- biz.aQute.remote/src/aQute/remote/main/EnvoyDispatcher.java
- biz.aQute.remote/src/aQute/remote/main/Main.java
- biz.aQute.remote/test/aQute/remote/main/MainTest.java
Provide facility to define properties on the
command line for the frameworks loaded.
More information for the interfaces being listened on
> [bndremote] bndremote update

- biz.aQute.bnd.javagen/bnd.bnd
- biz.aQute.bndlib.tests/bnd.bnd
- biz.aQute.bndlib/src/aQute/bnd/bundle/annotations/Referenced.java
- cnf/ext/central.mvn
- maven/bnd-indexer-maven-plugin/pom.xml
- maven/pom.xml
Update dependencies for OSGi Core R8 release to maven central.
> OSGi Core R8 update

- biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
Enable a future where apiguardian supports packages.
> identify apiguardian on any type it supports

- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/WhileYouWereBusy.java
> Added documentation for WhileYouWereBusy class

- biz.aQute.bndlib/src/aQute/bnd/build/Project.java
- biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
> removed duplicate getReleaseRepo method

- bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java
> [builder] Improve error message for missing bnd.bnd

- biz.aQute.bndlib.tests/test/test/MacroTest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
- docs/_macros/bndversion.md
Signed-off-by: Jürgen Albert <j.albert@data-in-motion.biz>
> [#4485] adds macro to return the currently running bnd version

- biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java
We ignore certain members when looking for DS annotations such as static
members, synthetic methods, etc. However we process annotations on
ignored members using a stale value in the member field.
So now we avoid stale values in the member field and we check
if the member is ignored before processing its annotations.
Fixes https://github.com/bndtools/bnd/issues/4491
> ds: Fix handling of ignored members when processing classes

- biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java
Fixes #4478
@zhsc Could you confirm this fixes your problem?
> [launchpad] NPE with getServices

- bndtools.core/src/bndtools/model/repo/RepositoryTreeContentProvider.java
Prior to this fix, if there were bundle and non-bundle versions of a jar
in (eg) a MavenBndRepository, there would be two root entries - one
with the full BSN, and the other with a pseudo-BSN of the form group:artifact.
The plain jars would appear under the pseudo-BSN while the true bundles
would appear under both. With this fix, the bundles will be filtered from the
G:A node so that they only appear once under their actual BSN.
Fixes #3383.
> [repoviewer] Suppress bundles under GAV pseudo-BSNs

- README.md
- biz.aQute.bnd.gradle/README.md
- bndtools.test/tester/cnf/ext/repositories.bnd
- bndtools.test/workspace-comms/cnf/settings.gradle
- bndtools.test/workspace-comms/settings.gradle
- cnf/ext/repositories.bnd
- docs/_chapters/310-testing.md
- org.bndtools.p2/build.gradle
- org.bndtools.p2/features/bndtools.m2e/feature.xml
- org.bndtools.p2/features/bndtools.main/feature.xml
- org.bndtools.p2/features/bndtools.pde/feature.xml
Replace usage of and reference to bintray and jcenter.
More work is needed on test dependencies on bintray.
See #4525.
> Bintray sunset

- biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java
- biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2IndexerTest.java
- biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2RepositoryTest.java
See https://github.com/bndtools/bnd/issues/4525
> tests: Replace use of bintray repo with a jfrog repo

- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/ReleaseDTO.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/package-info.java
- biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
- docs/_instructions/maven-release.md
- docs/_plugins/maven.md
Fixes https://github.com/bndtools/bnd/issues/3784
Closes #4519.
> maven repo: enable forcing source and javadoc release for localmode

- cnf/ext/maven-plugin.bnd
- maven/README.md
- maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
- maven/pom.xml
Fixes https://github.com/bndtools/bnd/issues/4540
> maven: Raise maven dependency version to 3.3.9

- biz.aQute.bndlib/src/aQute/bnd/build/package-info.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/package-info.java
- cnf/build.bnd
Update baseline after 5.3.0 release.
> Baseline 5.3.0

- .github/workflows/cibuild.yml
Fixes https://github.com/bndtools/bnd/issues/4493
> build: Upload test-reports

- biz.aQute.bndlib/src/aQute/bnd/aspectj/plugin/AspectJ.java
- docs/_plugins/aspectj.md
> [aspect] A plugin to weave executable jars

- bndtools.jareditor/src/bndtools/jareditor/internal/JarFileSystem.java
We change to not return null for getChild and return a NullFileSystem
object instead.
Fixes https://github.com/bndtools/bnd/issues/4574
> jareditor: Avoid NPE in JarFileSystem

- bndtools.jareditor/src/bndtools/jareditor/internal/JarFileSystem.java
We better match the IFileSystem API contact to always return an
IFileStore for getStore even when there is some error.
> jareditor: Refactor to improve implementation

- biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java
The resolver was not loading the workspace repo when used in batch. This seems to work for the maven use case but if you had a real project, the workspace repo was added to the Bndrun, not the Workspace. The code always got the repos from the Bndrun. Not sure why we cannot always use the Workspace, after all the repos are defined on the Workspace.
> Resolver adds workspace repo to wrong Processor in non-interactive workspace mode

- docs/_instructions/reproducible.md
Fixes https://github.com/bndtools/bnd/issues/4593
> doc: Add documentation page for -reproducible

- .github/workflows/cibuild.yml
- .gradle-wrapper/gradle-wrapper.properties
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPluginConvention.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndProperties.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndUtils.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bundle.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/FileSetRepositoryConvention.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Index.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/PropertiesWrapper.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Resolve.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/TestOSGi.groovy
Move build to Gradle 7. Add Java 16 ci execution. Update Bnd Gradle plugin source to utilize Groovy 3 enhancements.
> Gradle 7.0

- biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/NexusCommand.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/package-info.java
- biz.aQute.repository/src/aQute/maven/nexus/provider/Nexus.java
- biz.aQute.repository/src/aQute/maven/nexus/provider/package-info.java
- biz.aQute.repository/src/aQute/maven/provider/MavenRemoteRepository.java
- biz.aQute.repository/test/aQute/maven/provider/FakeNexus.java
- biz.aQute.repository/test/aQute/maven/provider/MavenRepoTest.java
- Mitigates staging bug on Nexus that creates multiple repos
- Added commands in Nexus(Command) to work with staging repositories
- Minimized logging in HttpClient, it was too verbose
> Staging repos on Nexus

- biz.aQute.bnd.gradle/README.md
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Index.groovy
- dist/bnd.bnd
- org.bndtools.templating.gitrepo/.classpath
- org.bndtools.templating.gitrepo/.gitignore
Also, some other build fixes for a warning and misspelled project name.
> Fixes for Bnd Gradle plugins

- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndProperties.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndUtils.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bundle.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/FileSetRepositoryConvention.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Index.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Resolve.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/TestOSGi.groovy
Since groovy will realize double quoted strings as String when they
do not use interpolation, lets use them since they are more familiar
to my Java trained eyes.
We also fix some desired use of char literals to avoid them being String
literals in groovy.
> gradle: Use double quoted strings

- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
We need to know the bnd configuration files for a project in several
places. So we make a method to hold this logic.
> gradle: Use method to compute bnd configuration files

- biz.aQute.bndlib/src/aQute/bnd/osgi/Packages.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/eclipse/EclipseUtil.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
- bndtools.builder/src/org/bndtools/builder/BndProjectInfoAdapter.java
- bndtools.builder/src/org/bndtools/builder/BndSourceGenerateCompilationParticipant.java
- bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java
- bndtools.builder/src/org/bndtools/builder/validate/ProjectPathsValidator.java
- bndtools.core/src/bndtools/central/Central.java
- bndtools.core/src/bndtools/central/WorkspaceListener.java
- bndtools.core/src/bndtools/central/WorkspaceSynchronizer.java
Changed the builder & compiler participant to
not do any refresh files and markers inside 
the bnd lock
> [lockups] Moving non essential tasks outside the lock

- biz.aQute.launchpad.tests/test/aQute/xlaunchpad/LaunchpadConfigurationTest.java
- bndtools.builder/src/org/bndtools/builder/BndSourceGenerateCompilationParticipant.java
- bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java
- bndtools.core/src/bndtools/central/WorkspaceSynchronizer.java
- bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java
Ongoing changes to remove deadlocks and get nice clean builds after a branch change
> Ongoing changes to remove deadlocks and get nice clean builds after a branch change

- bndtools.core/_plugin.xml
- bndtools.core/bnd.bnd
- bndtools.core/src/bndtools/core/console/AnsiHandler.java
Provides an extension point to the console so programs
can clear the console with a common ANSI control code.
> [launch] Provide support for ANSI code clear to console

- aQute.libg/src/aQute/lib/unmodifiable/ImmutableList.java
- aQute.libg/src/aQute/lib/unmodifiable/ImmutableMap.java
- aQute.libg/src/aQute/lib/unmodifiable/ImmutableSet.java
- aQute.libg/test/aQute/lib/unmodifiable/ListsTest.java
- aQute.libg/test/aQute/lib/unmodifiable/MapsTest.java
- aQute.libg/test/aQute/lib/unmodifiable/SetsTest.java
Tests are added to verify the serialization.
> unmodifiable: Support serialization

- bndtools.core/src/bndtools/central/sync/WorkspaceSynchronizer.java
> [sync] Should be more careful in deleting

- bndtools.core/src/bndtools/central/sync/WorkspaceSynchronizer.java
> [sync] Do not clean & build

- biz.aQute.bnd.util/src/aQute/bnd/result/Err.java
- biz.aQute.bnd.util/src/aQute/bnd/result/Ok.java
- biz.aQute.bnd.util/src/aQute/bnd/result/Result.java
- biz.aQute.bnd.util/test/aQute/bnd/result/ResultTest.java
- biz.aQute.bnd/src/aQute/bnd/main/bnd.java
- biz.aQute.bndall.tests/test/biz/aQute/bnd/project/ProjectGenerateTest.java
- biz.aQute.bndall.tests/test/biz/aQute/externalplugin/ExternalPluginHandlerTest.java
- biz.aQute.bndlib/src/aQute/bnd/build/ProjectGenerate.java
- biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
- biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceClassIndex.java
- biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceExternalPluginHandler.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Descriptors.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/NexusCommand.java
- biz.aQute.repository/src/aQute/maven/nexus/provider/Nexus.java
- biz.aQute.resolve/src/biz/aQute/resolve/RunResolution.java
- biz.aQute.resolve/test/biz/aQute/resolve/RunResolutionTest.java
- bndtools.builder/src/org/bndtools/builder/BndSourceGenerateCompilationParticipant.java
- bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java
- bndtools.core/src/bndtools/launch/OSGiRunLaunchDelegate.java
- bndtools.jareditor/src/bndtools/jareditor/internal/JarFileSystem.java
- bndtools.jareditor/src/bndtools/jareditor/internal/TemporaryFile.java
This simplifies the generic signature. Some other implementation
improvements are made.
Test case is also added.
> util: Refactor Result to fix the error type as string

- biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java
- biz.aQute.bndall.tests/test/biz/aQute/launcher/LauncherTest.java
- biz.aQute.launcher/src/aQute/launcher/Launcher.java
We also fix tests to not care about stream of output for testing.
> launcher: Make sure output is not interleaved

- biz.aQute.bnd.util/src/aQute/bnd/memoize/CloseableMemoizingSupplier.java
- biz.aQute.bnd.util/src/aQute/bnd/stream/EntryPipeline.java
- biz.aQute.bnd.util/src/aQute/bnd/stream/MapStream.java
- biz.aQute.bnd.util/src/aQute/bnd/stream/package-info.java
- biz.aQute.bnd.util/test/aQute/bnd/stream/MapStreamTest.java
- biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/PluginsContainer.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
Refactor the PluginsContainer into a top level class.
We also add some new methods to MapStream and improve the CloseableMemoize implementation to not hold the supplier after initialization.
> PluginsContainer refactor

- biz.aQute.bnd.util/src/aQute/bnd/memoize/CloseableMemoizingSupplier.java
We restore the memoized field to be of type T which erases to
AutoCloseable. This requires an initial supplier interface which is
itself AutoCloseable so we can share the memoized field.
> memoize: Minor refactor to avoid casts to AutoCloseable

- org.bndtools.templating/src/org/bndtools/templating/engine/mustache/MustacheTemplateEngine.java
> [template] fix typo

- biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceRepository.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
- biz.aQute.bndlib/src/aQute/bnd/version/VersionRange.java
- biz.aQute.repository/src/aQute/bnd/deployer/repository/AbstractIndexedRepo.java
- biz.aQute.repository/src/aQute/bnd/deployer/repository/RepoResourceUtils.java
Also, some other improvements to the class and corrections of client misuse of isRange().
Fixes https://github.com/bndtools/bnd/issues/4720
> versionrange: Fix constructor to use infinity for high version on single version input

- .github/workflows/cibuild.yml
- bndtools.core.test/src/bndtools/core/test/editors/quickfix/AbstractBuildpathQuickFixProcessorTest.java
- bndtools.core.test/src/bndtools/core/test/utils/TaskUtils.java
- bndtools.core.test/src/bndtools/core/test/utils/WorkbenchExtension.java
- bndtools.core.test/src/bndtools/core/test/utils/WorkspaceImporter.java
This latest effort attempts to fix the race conditions by taking control of the build/refresh process instead of trying to sync with the autobuild. Seems to be working so far. If there are any issues, then we will have to disable it again.
Fixes #4253. Fixes #4553.
> [quickfix test] Another attempt at fixing race conditions

- biz.aQute.bndall.tests/test/biz/aQute/launcher/LauncherTest.java
LauncherTest sometimes has a transient failure which the current diagnostics don't tell us much about. Use soft assertions and asserting on the error list directly to perhaps be able to gather enough information to diagnose the root cause the next time that it happens.
> [bndall test] Better diagnostics for LauncherTest

- biz.aQute.bnd.gradle/build.gradle
- maven/build.gradle
- org.bndtools.p2/build.gradle
We set UTF-8 encoding for written properties files.
> build: Updates to build scripts

- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
- biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy
Updates to support using a composite build
> Gradle included build

- gradle-plugins/biz.aQute.bnd.gradle/build.gradle.kts
Maven Central requires these artifacts.
> gradle: Need to publish sources and javadoc artifacts

- bndtools.builder/bnd.bnd
- bndtools.builder/src/org/bndtools/builder/MarkerSupport.java
- bndtools.core.test/test.cocoa.macosx.x86_64.bndrun
- bndtools.core.test/test.gtk.linux.x86_64.bndrun
- bndtools.core.test/test.shared.bndrun
- bndtools.core.test/test.win32.x86_64.bndrun
> Squelch quickfix test

- biz.aQute.bnd/src/aQute/bnd/main/XmlRepoDiffCommand.java
- biz.aQute.bnd/src/aQute/bnd/main/bnd.java
- biz.aQute.bndlib.tests/test/test/xmlrepo/diff/XmlRepoDifferTest.java
- biz.aQute.bndlib.tests/testresources/xmlrepo/newer.xml
- biz.aQute.bndlib.tests/testresources/xmlrepo/older.xml
- biz.aQute.bndlib/src/aQute/bnd/differ/Element.java
- biz.aQute.bndlib/src/aQute/bnd/differ/XmlRepoDiffer.java
- biz.aQute.bndlib/src/aQute/bnd/differ/package-info.java
- biz.aQute.bndlib/src/aQute/bnd/maven/MavenCapability.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/package-info.java
- biz.aQute.bndlib/src/aQute/bnd/service/diff/Type.java
- biz.aQute.bndlib/src/aQute/bnd/service/diff/packageinfo
- docs/_commands/xmlrepodiff.md
> Introduced XML Resource Repository Differ

- bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java
- bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessor_WithSimpleOnBuildpath_Test.java
- bndtools.core.test/src/iface/bundle/InterfaceExtendingMyInterface.java
- bndtools.core.test/src/simple/pkg/ClassWithInterfaceExtendingMyInterface.java
Extra tests for some corner cases.
> Quickfix generic java classes

- biz.aQute.bndlib.tests/test/test/AnalyzerTest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Instruction.java
- docs/_chapters/820-instructions.md
Optional instructions are not warned about when unused.
Fixes https://github.com/bndtools/bnd/issues/4775
> instruction: Add flag to enable marking an instruction as optional

- bndtools.m2e/src/bndtools/m2e/BndConfigurator.java
> removed debug printout

- biz.aQute.bndlib.tests/test/test/MavenVersionTest.java
- biz.aQute.bndlib/src/aQute/bnd/version/maven/ComparableVersion.java
See https://issues.apache.org/jira/browse/MNG-6964
> mavenversion: Pick up fix from Maven 3.8.2

- gradle-plugins/biz.aQute.bnd.gradle/.project
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/AbstractBndrun.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BeanProperties.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndBuilderPlugin.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPlugin.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndWorkspacePlugin.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/Bndrun.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/Index.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/TestOSGi.java
Some minor code updates to the gradle plugin code.
> Gradle plugin updates

- biz.aQute.bndlib.tests/test/test/api/AbstractInterf2.java
- biz.aQute.bndlib.tests/test/test/api/Interf2.java
- biz.aQute.bndlib.tests/test/test/api3/SubClass.java
- biz.aQute.bndlib.tests/test/test/api3/SubInterface.java
- biz.aQute.bndlib.tests/test/test/api3/SuperClass.java
- biz.aQute.bndlib.tests/test/test/api3/SuperClassExtender.java
- biz.aQute.bndlib.tests/test/test/api3/SuperInterface.java
- biz.aQute.bndlib.tests/test/test/api3/SuperInterfaceImplementor.java
- biz.aQute.bndlib.tests/test/test/api3/package-info.java
- biz.aQute.bndlib.tests/test/test/baseline/BaselineTest.java
- biz.aQute.bndlib.tests/test/test/diff/DiffTest.java
- biz.aQute.bndlib.tests/test/test/xmlrepo/diff/XmlRepoDifferTest.java
- biz.aQute.bndlib/src/aQute/bnd/differ/Baseline.java
- biz.aQute.bndlib/src/aQute/bnd/differ/DiffImpl.java
- biz.aQute.bndlib/src/aQute/bnd/differ/Element.java
- biz.aQute.bndlib/src/aQute/bnd/differ/JavaElement.java
- biz.aQute.bndlib/src/aQute/bnd/service/diff/Diff.java
- bndtools.release/src/bndtools/release/ui/TreeContentProvider.java
- demo/bnd.bnd
- demo/src/test/api/AbstractInterf2.java
- demo/src/test/api/Interf2.java
- demo/src/test/api3/SuperClass.java
- demo/src/test/api3/SuperClassExtender.java
- demo/src/test/api3/SuperInterface.java
- demo/src/test/api3/SuperInterfaceImplementor.java
- demo/src/test/api3/package-info.java
Includes a refactoring of the new package-info support.
> Baseline updates

- bndtools.core/src/bndtools/editor/exports/ExportPatternsListPart.java
- bndtools.core/src/bndtools/refactor/CreateFileChange.java
- bndtools.core/src/bndtools/utils/CompositeTask.java
- bndtools.core/src/bndtools/utils/DependencyUtils.java
- bndtools.core/src/bndtools/wizards/project/AbstractNewBndProjectWizard.java
- bndtools.core/src/bndtools/wizards/project/NewBndProjectWizard.java
- bndtools.core/src/bndtools/wizards/workspace/WorkspaceSetupWizard.java
- bndtools.core/src/org/bndtools/core/jobs/GenerateIndexJob.java
- bndtools.core/src/org/bndtools/core/ui/wizards/shared/TemplateSelectionWizardPage.java
- bndtools.m2e/src/bndtools/m2e/BndConfigurator.java
- bndtools.m2e/src/bndtools/m2e/IndexConfigurator.java
- bndtools.utils/src/org/bndtools/utils/copy/ResourceCopier.java
- bndtools.utils/src/org/bndtools/utils/workspace/FileUtils.java
- org.bndtools.launch/src/bndtools/launch/OSGiJUnitLaunchDelegate.java
- org.bndtools.launch/src/bndtools/launch/OSGiRunLaunchDelegate.java
> replaced the usage of newChild with split as per #4805

- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/templates/blocks.twig
- biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/templates/printer.twig
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/transformer/JtwigPrinterTest.java
> [reporter] remove Feature-coordinates from Coordinate

- biz.aQute.bndlib/src/aQute/bnd/build/LibraryHandler.java
- docs/_instructions/library.md
> documentation update

- bndtools.test/tester/main-with-runners/src/test/MyTest.java
- bndtools.test/tester/my.bundle.of.test3/bnd.bnd
- bndtools.test/tester/my.fragment.of.test4/bnd.bnd
- org.bndtools.launch/src/bndtools/launch/OSGiJUnitLaunchDelegate.java
> Fix oneshot rerun

- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPlugin.java
If using toolchain, we should show the actual javac path.
> gradle: echo should display the path to the javac command

- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/Baseline.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BeanProperties.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndBuilderPlugin.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPlugin.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPluginConvention.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPluginExtension.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndUtils.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndWorkspacePlugin.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/Bundle.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BundleTaskConvention.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BundleTaskExtension.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/FileSetRepositoryConvention.java
Add javadoc to quiet Java 16 javadoc warnings.
> Gradle javadoc fixes

- docs/_macros/compare.md
> [Docs] update docs of macro compare

- DEV_README.md
> [bndtools] Updated DEV_README.md with howto for ExtensionFacade

- aQute.libg/test/aQute/bnd/exceptions/ExceptionsTest.java
- biz.aQute.bnd.runtime/src/aQute/bnd/runtime/snapshot/Snapshot.java
- biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java
- biz.aQute.launchpad/src/aQute/launchpad/junit/LaunchpadRule.java
- biz.aQute.launchpad/test/aQute/launchpad/BundleBuilderTest.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java
- biz.aQute.repository/src/aQute/maven/nexus/provider/Nexus.java
- biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorTest.java
- bndtools.core/src/bndtools/central/Central.java
- bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java
- bndtools.core/src/bndtools/views/repository/RepositoriesView.java
- bndtools.core/src/org/bndtools/facade/ExtensionFacade.java
- bndtools.m2e/src/bndtools/m2e/IndexConfigurator.java
- maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
> Fixes for 6.0 

- biz.aQute.bnd.util/bnd.bnd
- biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
- cnf/build.bnd
- cnf/ext/baseline.mvn
- gradle-plugins/biz.aQute.bnd.gradle/build.gradle.kts
Update baseline for 6.0.0 release.
> 6.0 baseline

- bndtools.core/src/bndtools/editor/project/OSGiFrameworkContentProvider.java
- bndtools.core/src/bndtools/editor/project/RepositorySelectionPart.java
- bndtools.core/src/bndtools/editor/project/RunFrameworkPart.java
> [build] Removed warning

- .gradle-wrapper/gradle-wrapper.properties
- gradle-plugins/biz.aQute.bnd.gradle/.project
- gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestBaselineTask.groovy
- gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestBndPlugin.groovy
- gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestBndrunTask.groovy
- gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestBundlePlugin.groovy
- gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestExportTask.groovy
- gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestHelper.groovy
- gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestIndexTask.groovy
- gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestResolveTask.groovy
- gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestTestOSGiTask.groovy
Update to latest 7.3 release candidate
> Gradle 7.3.rc5

- .github/workflows/cibuild.yml
- biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java
- biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/SettingsParserTest.java
- biz.aQute.bndlib.comm.tests/testresources/ws/cnf/simpleid.xml
- biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java
- biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java
- biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2RepositoryTest.java
- bndtools.test/tester/cnf/ext/repositories.bnd
- build.gradle
- cnf/ext/jfrog-settings.xml
- cnf/ext/repositories.bnd
Complete fix for simple id support in connection settings. The previous fix did not cover the parsing of settings.xml files.
> Settings fix

- biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java
- biz.aQute.bndlib/src/aQute/bnd/build/Project.java
> Fixed potential unclosed file Handle

- biz.aQute.bnd.util/src/aQute/bnd/stream/AbstractWhile.java
- biz.aQute.bnd.util/src/aQute/bnd/stream/DropWhile.java
- biz.aQute.bnd.util/src/aQute/bnd/stream/EntryPipeline.java
- biz.aQute.bnd.util/src/aQute/bnd/stream/TakeWhile.java
- biz.aQute.bnd.util/src/aQute/bnd/stream/package-info.java
- biz.aQute.bnd.util/test/aQute/bnd/stream/MapStreamTest.java
- biz.aQute.bnd.util/test/aQute/bnd/stream/WhileTest.java
- biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceLock.java
Static methods to provide dropWhile and takeWhile support for Java 8.
> Stream dropWhile/takeWhile

- biz.aQute.bnd/src/aQute/bnd/main/bnd.java
- biz.aQute.bndlib/bnd.bnd
- biz.aQute.bndlib/src/aQute/bnd/buildtool/ToolManager.java
- docs/_instructions/buildtool.md
A tool to update the workspace root with a build
tool like gradle, see buildtool.md for a
description.
> [build] A build tool manager

- cnf/ext/central.mvn
See https://jira.qos.ch/browse/LOGBACK-1591
> deps: Update logback to latest release

- cnf/ext/central.mvn
This uses the latest logback-classic.
> deps: Update felix.logback to latest release

- biz.aQute.bnd.util/src/aQute/bnd/unmodifiable/ImmutableList.java
- biz.aQute.bnd.util/src/aQute/bnd/unmodifiable/ImmutableMap.java
- biz.aQute.bnd.util/src/aQute/bnd/unmodifiable/ImmutableSet.java
Minor improvements to clean up the implementation.
> unmodifiable: implementation update

- aQute.libg/src/aQute/lib/collections/MultiMap.java
See https://github.com/bndtools/bnd/issues/4858
> #4858 Confusion in bndeditor/build/add dialog

- bndtools.core/src/bndtools/wizards/repo/RepoBundleSelectionWizardPage.java
> [ui] Improved logic

- aQute.libg/src/aQute/lib/io/FileTree.java
- biz.aQute.bndlib.tests/test/test/BuilderTest.java
- biz.aQute.bndlib.tests/test/test/ClassReferenceTest.java
- biz.aQute.bndlib/src/aQute/bnd/build/Project.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/Tool.java
Several users want a stream. So we add stream methods to support them
and avoid creating a list when none is wanted.
> filetree: Add stream methods

- biz.aQute.repository/test/aQute/bnd/deployer/repository/CachingUriResourceHandlerTest.java
Test code should not be asserting using the Java assert keyword.
> test: Replace incorrect use of assert keyword in test code

- biz.aQute.bndlib.tests/test/test/jpms/JPMSModuleInfoPluginTest.java
- biz.aQute.bndlib/src/aQute/bnd/plugin/jpms/JPMSModuleInfoPlugin.java
- docs/_chapters/330-jpms.md
> [jpms] specify multiple access flags in `-jpms-module-info;access=`

- maven/bnd-plugin-parent/pom.xml
Fixes https://github.com/bndtools/bnd/issues/5039
> maven: slf4j-api is provided scope

- maven/bnd-maven-plugin/pom.xml
- maven/bnd-plugin-parent/pom.xml
- maven/bnd-reporter-maven-plugin/pom.xml
It is not longer in use
This closes #5042
> Remove maven-compat dependency

- biz.aQute.bndlib/src/aQute/bnd/osgi/PluginsContainer.java
We move the distinct call to the "exit" point rather than calling
at each processor in the hierarchy when assembling the stream.
The issue with sub bundles was that the ProjectBuilder for a subbundle
has the main project's ProjectBuilder as its parent so the Builder
plugins are added at two levels of the hierarchy. But is also possible
for plugins to be duplicates on the hierarchy, so a distinct call is
needed to provide set semantics (no duplicates).
> plugins: Reduce to a single distinct call to remove duplicate plugins

- biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
WorkspaceData is managed in a thread safe way.
Fixes https://github.com/bndtools/bnd/issues/5054
> gestalt: Hoist gestalt data up into WorkspaceData

- biz.aQute.bnd.transform/bnd.bnd
- biz.aQute.bnd.util/src/aQute/bnd/stream/DropWhile.java
- biz.aQute.bnd.util/src/aQute/bnd/stream/TakeWhile.java
Missed a place to implement forEachRemaining.
> Spliterator forEachRemaining

- biz.aQute.launcher/src/aQute/launcher/Launcher.java
> [launcher] Fix a couple of typos in bundle install error msgs

- bndtools.m2e/src/bndtools/m2e/MavenRunListenerHelper.java
> bndtools.m2e: NPE when opening maven/bnd.bnd file in Bnd repo

- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/DependencyResolver.java
- bndtools.m2e/src/bndtools/m2e/MavenWorkspaceRepository.java
> [m2e] Multiple versions of an artifact not available in repository

- biz.aQute.bndlib.tests/test/test/FilterBuilderTest.java
- biz.aQute.bndlib/src/aQute/bnd/differ/Baseline.java
- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/Baseline.java
- maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java
- maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/verify.groovy
Fixes https://github.com/bndtools/bnd/issues/5082
> Update maven and gradle plugin output for baseline errors

- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPlugin.java
Gradle 7.4 has deprecated this method and we don't really need to use
it anyway.
> gradle: Avoid use of newly deprecated Provider.forUseAtConfigurationTime

- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPlugin.java
Use an Optional to hold the optional generate task.
> gradle: Updates to generate task support

- biz.aQute.bnd.util/src/aQute/bnd/unmodifiable/ImmutableIterator.java
- biz.aQute.bnd.util/src/aQute/bnd/unmodifiable/ImmutableList.java
- biz.aQute.bnd.util/src/aQute/bnd/unmodifiable/ImmutableMap.java
- biz.aQute.bnd.util/src/aQute/bnd/unmodifiable/ImmutableSet.java
- biz.aQute.bnd.util/test/aQute/bnd/unmodifiable/Holder.java
- biz.aQute.bnd.util/test/aQute/bnd/unmodifiable/ListsTest.java
- biz.aQute.bnd.util/test/aQute/bnd/unmodifiable/MapsTest.java
- biz.aQute.bnd.util/test/aQute/bnd/unmodifiable/SetsTest.java
Updates to immutable implementations for minor performance improvements.
> Immutable updates

- docs/_heads/private_package.md
> [doc] Another attempt at fixing hyphens

- aQute.libg/test/aQute/lib/json/JSONTest.java
- biz.aQute.bnd.reporter/bnd.bnd
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/helpers/FileHelperTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/any/ImportResourcePluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/bndproject/BndProjectContentsPluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/bndproject/CodeSnippetPluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/bndproject/CommonInfoProjectPluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/processor/FileNamePluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/workspace/BndWorkspaceContentsPluginTest.java
- biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/workspace/CommonInfoPluginTest.java
- biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java
- biz.aQute.bndlib.tests/test/test/BuilderTest.java
- biz.aQute.bndlib.tests/test/test/JarSignerTest.java
- biz.aQute.bndlib.tests/test/test/ManifestTest.java
- biz.aQute.bndlib.tests/test/test/bndmodel/BndModelTest.java
- biz.aQute.bndlib.tests/test/test/component/PermissionGeneratorTest.java
- biz.aQute.bndlib.tests/test/test/properties/PropertiesTest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
Update Jar STORE logic and make sure a test exercises it.
> Jar store test

- maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
- maven/bnd-maven-plugin/src/test/resources/integration-test/test/jar-test-api-bundle/verify.groovy
- maven/bnd-maven-plugin/src/test/resources/integration-test/test/jar-test-bnd-process-tests-goal-fragment/verify.groovy
- maven/bnd-maven-plugin/src/test/resources/integration-test/test/jar-test-bnd-process-tests-goal/verify.groovy
- maven/bnd-maven-plugin/src/test/resources/integration-test/test/jar-test-bnd-process-tests-skipIfEmpty/verify.groovy
- maven/bnd-maven-plugin/src/test/resources/integration-test/test/jar-test-impl-bundle/verify.groovy
- maven/bnd-maven-plugin/src/test/resources/integration-test/test/jar-test-in-build-pluginManagement-inheritance/verify.groovy
- maven/bnd-maven-plugin/src/test/resources/integration-test/test/jar-test-war-bundle/verify.groovy
- maven/bnd-maven-plugin/src/test/resources/integration-test/test/jar-test-wrapper-bundle/verify.groovy
> bnd-maven-plugin: jar goal does not include META-INF/maven content

- biz.aQute.bndlib/src/aQute/bnd/maven/PomPropertiesResource.java
- biz.aQute.bndlib/src/aQute/bnd/maven/package-info.java
- maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
We add a new constructor for bnd-maven-plugin to use.
> bnd-maven-plugin: Refactor to use PomPropertiesResource

- bndtools.core/src/org/bndtools/core/ui/icons/Icons.java
- docs/_chapters/790-reference.md
- docs/_layouts/default.html
- docs/css/style.scss
[search] Event loop exception using search dialog https://github.com/bndtools/bnd/issues/4957
A few years ago I replaced all image handling with one
single handling in Icons. 
I reasoned that since this was a static cache, I would
not run into any issues from a life cycle perspective. 
However, this issue indicates that it is still possible
to get a disposed image.
Since this image comes from the Icons handler, I am
not checking if the image has been disposed when
I find it in the cache. If so, it is recreated.
> Check disposed images 

- biz.aQute.bndlib.tests/test/test/VersionPolicyTest.java
- biz.aQute.bndlib.tests/test/test/versionpolicy/api/package-info.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
- docs/_chapters/170-versioning.md
Fixes https://github.com/bndtools/bnd/issues/5087
> analyzer: Warn when macros are used in Version annotation value

- bndtools.core/src/bndtools/editor/completion/BndHover.java
Hovering over a key now also gives expansion of
the header, including merges + decoration
> [hover] Add decorated expansion to macro hover

- docs/_includes/nav.htm
> [docs] Less effective with stackoverflow include

- biz.aQute.bndlib.tests/test/test/MacroTest.java
- docs/_chapters/820-instructions.md
- docs/_instructions/runbundles.md
- docs/_macros/decorated.md
Some more info about decorations
> [docs] Decorations

- docs/_includes/nav.htm
I though DuckDuckGo was less intrusive privacy wise than google but google seems to win hands on in finding the important topics. And I figured out how to do multiple site searches with google.
> [doc] Switched to google

- biz.aQute.bnd.test/src/aQute/bnd/test/net/EphemeralPort.java
- biz.aQute.bnd.test/src/aQute/bnd/test/net/package-info.java
- biz.aQute.bnd.test/test/aQute/bnd/test/net/EphemeralPortTest.java
- biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientProxyTest.java
> Ephemeral port injection

- biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/IndexedReposWithComms.java
Fixes https://github.com/bndtools/bnd/issues/5133
> test: Use ephemeral port for the socks server

- biz.aQute.repository/src/aQute/maven/provider/POM.java
There is not much the user can do about 3rd party poms.
> pom: Downgrade log message to debug for missing property

- biz.aQute.bndlib.tests/test/test/ProcessorTest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/AttributeClasses.java
> [bndlib] Improve AttributeClasses test

- biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
- biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceLock.java
These method take a callable and a function. The callable is called
while holding the write lock. The lock is downgraded to the read lock
and then the function is called with the result of the callable. The
result of the function is finally returned after releasing the read
lock.
> workspace: Add methods for write locking downgrading to read locking

- biz.aQute.bnd.test/src/aQute/bnd/test/jupiter/TemporaryDirectoryExtension.java
- biz.aQute.bnd.test/src/aQute/bnd/test/jupiter/package-info.java
- cnf/ext/central.mvn
- cnf/ext/junit.bnd
We use the new InjectingExtension base class from osgi-test.
> test: Refactor TemporaryDirectoryExtension

- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapReqBuilder.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java
Fixes https://github.com/bndtools/bnd/issues/5178
> Version parsing in resource creation

- biz.aQute.bndlib/src/aQute/bnd/plugin/jpms/JPMSModuleInfoPlugin.java
We use linked maps and sets and forEachOrdered on streams.
Fixes https://github.com/bndtools/bnd/issues/5183
> jpmsmodule: Updates for reproducibility

- biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java
> [ProjectLauncher] Trim whitespace on version during startlevel processing

- biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
We must also clear contained when resetting the analyzer to reanalyze.
This is necessary so when we reanalyze package-info class files, we
will recollect the package version from the Version annotation.
> analyzer: Reanalyze fix to recollect the package info version

- aQute.libg/src/aQute/lib/manifest/ManifestUtil.java
- aQute.libg/src/aQute/lib/manifest/package-info.java
- biz.aQute.bnd.transform/bnd.bnd
- biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/ManifestResource.java
- gradle/wrapper/gradle-wrapper.properties
> Refactor manifest writing code into a util package

- bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
When using version=snapshot or version=latest, we want Eclipse to use
the class files in the project's built jar and not the project's bin
folder. The project's built jar may contain transformed classes and
we want the Eclipse compiler to use the jar's classes and not the
project's untransformed classes which can lead to compilation errors.
When including the project entry in the class path container, Bndtools
will make the project's classes non-accessible which will make Eclipse
use the classes from the project's built jar. Source access via F3
still works.
This replaces the previous attempt of adding a `source` attribute which
the user must set.
> bndtools container: Use only jar for classes when version=latest

- gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BundleTaskExtension.java
- gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestBundlePlugin.groovy
- gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin1/build.gradle
- maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
Make generated manifest available to later executing tasks.
> Gradle manifest generated

- biz.aQute.bndlib/src/aQute/bnd/junit/package-info.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/package-info.java
> [analyzer] make bcpEntries collection public so we can interrogate it

- biz.aQute.bndlib.tests/test/test/JarSignerTest.java
Having this test will ensure that we don't break JarInputStream's
verification logic.
> jar: Update signer test to confirm JarInputStream verifies jar

- gradle-plugins/biz.aQute.bnd.gradle/build.gradle.kts
Additional changes can be made once we start building with Gradle 7.6.
> gradle: Build script improvements for new publish plugin version

- .github/workflows/cibuild.yml
- .github/workflows/codeql.yml
- .github/workflows/rebuild.yml
https://github.com/gradle/gradle-build-action
> Use gradle-build-action to speedup builds

- bndtools.core/src/bndtools/preferences/ui/BndBuildPreferencePage.java
Signed-off-by: Sean Bright <sean@seanbright.com>
> prefs: Remove extraneous parenthesis.

- maven/bnd-indexer-maven-plugin/src/it/index-folder-includes-excludes/pom.xml
- maven/bnd-indexer-maven-plugin/src/it/index-folder/pom.xml
- maven/bnd-plugin-parent/pom.xml
- maven/bnd-resolver-maven-plugin/src/it/parent/pom.xml
We remove the configuration for the unused plugin.
> Remove maven dependency plugin

- aQute.libg/src/aQute/lib/settings/Settings.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/package-info.java
- cnf/build.bnd
Update build to baseline against the latest Bnd release.
> Baseline 6.4.0

- maven-plugins/bnd-generate-maven-plugin/README.md
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/generate-test/bnd.bnd
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/generate-test/pom.xml
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/generate-test/template/test/test.txt
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/generate/bnd.bnd
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/generate/pom.xml
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/generate/template/test/test.txt
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/generator/pom.xml
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/generator/src/main/java/biz/aQute/bnd/testgen/TestGen.java
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/generator/src/main/java/biz/aQute/bnd/testgen/TestGenOptions.java
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/invoker.properties
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/pom.xml
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-buildpath/postbuild.groovy
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-dependency-management-error/pom.xml
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-dependency-management/pom.xml
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-maven-configuration-multiple-steps-mixed/pom.xml
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-maven-configuration-multiple-steps/pom.xml
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-maven-configuration/pom.xml
- maven-plugins/bnd-generate-maven-plugin/src/it/generate-no-rerun/pom.xml
- maven-plugins/bnd-generate-maven-plugin/src/it/generate/pom.xml
- maven-plugins/bnd-generate-maven-plugin/src/main/java/aQute/bnd/maven/generate/plugin/AbstractGenerateMojo.java
- maven-plugins/bnd-generate-maven-plugin/src/main/java/aQute/bnd/maven/generate/plugin/BndContainer.java
- maven-plugins/bnd-generate-maven-plugin/src/main/java/aQute/bnd/maven/generate/plugin/GenerateMojo.java
- maven-plugins/bnd-generate-maven-plugin/src/main/java/aQute/bnd/maven/generate/plugin/GenerateTestMojo.java
- maven-plugins/bnd-generate-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
> fixed missing build and testpath for bnd maven generator

- .mvn/wrapper/maven-wrapper.properties
- biz.aQute.bndlib.tests/test/test/MavenVersionTest.java
- biz.aQute.bndlib/src/aQute/bnd/version/maven/ComparableVersion.java
Update maven version to 3.8.7.
> Maven 3.8.7

- biz.aQute.repository/src/aQute/bnd/repository/fileset/FileSetRepository.java
This will provide more detail in Bnd errors which may be reported.
Fixes https://github.com/bndtools/bnd/issues/5498
> repo: Provide bsn+version in FileSetRepository.toString

- org.bndtools.launch/src/bndtools/launch/AbstractOSGiLaunchDelegate.java
"Launch if project contains errors" not honoured #5447
The code was bypassing the inherited checks from Java. I felt it was too dangerous to restore this so I used the code to do this check inline in the final check.
Refactored the code a bit to make it more readable.
This fixes #5447 
---
> Launcher check

- docs/_macros/if.md
> Better doc for if to handle confusion when condition macro is not set

- biz.aQute.bndlib.tests/test/test/BuilderTest.java
- docs/_chapters/920-faq.md
> 5555 Package default version faq. Fixed #5555

- biz.aQute.bndlib.tests/test/test/BuilderTest.java
> Set flag to not update default version

- docs/_instructions/jpms-module-info-options.md
- docs/_instructions/jpms-module-info.md
@rotty3000  please review
---
Foxs #5237
> Documentation for jpms

- biz.aQute.resolve/src/biz/aQute/resolve/Bndrun.java
> Fixes #5516. Generates a warning if -runframework is set but not -runfw

- biz.aQute.bndlib.tests/test/test/MultiReleaseTest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/JPMSModule.java
- biz.aQute.bndlib/src/aQute/bnd/plugin/jpms/JPMSMultReleasePlugin.java
Used META-INF/MANIFEST.MF but must be OSGI-INF/MANIFEST.MF.
---
> Used wrong path for the manifest in the versions directories. 

- bndtools.core/_plugin.xml
- bndtools.core/resources/unprocessed/serviceTemplates/java-service-api/$serviceName$.bndrun
- bndtools.core/resources/unprocessed/serviceTemplates/java-service-api/$srcDir$/$basePackageDir$/$serviceName$Service.java
- bndtools.core/resources/unprocessed/serviceTemplates/java-service-api/$srcDir$/$basePackageDir$/package-info.java
- bndtools.core/resources/unprocessed/serviceTemplates/java-service-api/bnd.bnd
- bndtools.core/resources/unprocessed/serviceTemplates/java-service-consumer/$srcDir$/$basePackageDir$/$serviceName$Consumer.java
- bndtools.core/resources/unprocessed/serviceTemplates/java-service-consumer/$srcDir$/$basePackageDir$/package-info.java
- bndtools.core/resources/unprocessed/serviceTemplates/java-service-consumer/bnd.bnd
- bndtools.core/resources/unprocessed/serviceTemplates/java-service-impl/$srcDir$/$basePackageDir$/$serviceName$Impl.java
- bndtools.core/resources/unprocessed/serviceTemplates/java-service-impl/$srcDir$/$basePackageDir$/package-info.java
- bndtools.core/resources/unprocessed/serviceTemplates/java-service-impl/bnd.bnd
- bndtools.core/resources/unprocessed/serviceTemplates/javaservice.xml
- bndtools.core/src/org/bndtools/core/ui/wizards/service/AbstractNewBndServiceMultiProjectWizard.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/NewBndServiceWizard.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/NewBndServiceWizardNonApiProjectPage.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/NewBndServiceWizardPageOne.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/NewBndServiceWizardPageTwo.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/ServiceApiProjectLocationGroup.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/ServiceApiProjectNameGroup.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/ServiceProjectTemplateParam.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/ServiceTemplateConstants.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/ServiceTemplateLoaderJob.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/java/NewBndJavaServiceWizard.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/java/NewBndJavaServiceWizardFactory.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/package-info.java
- bndtools.core/src/org/bndtools/core/ui/wizards/shared/BuiltInServiceTemplate.java
classes in org.bndtools.core.ui.wizards.service package and Java OSGi Service wizard in org.bndtools.core.ui.wizards.service.java package
> Initial commit for issue-5632.  Introduces service wizard support

- bndtools.core/src/org/bndtools/core/ui/wizards/service/NewBndServiceWizardPageOne.java
Fix for new template wizard UI bug
> Fix for UI bug

- biz.aQute.bndlib.tests/test/test/BuilderTest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
> Remove space from version before cleanup

- .github/scripts/ci-build.sh
- .github/scripts/ci-publish.sh
- .github/workflows/cibuild.yml
- .github/workflows/rebuild.yml
- .github/workflows/stale.yml
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/ReleaseDTO.java
- biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
- biz.aQute.repository/testresources/extra/test.bar
- biz.aQute.repository/testresources/extra/test.foo
- docs/_instructions/maven-release.md
This will upload extra artifacts from a project
Will fix #5678
>  upload/release of extra artifacts #5678 

- biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
- biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
- docs/_instructions/maven-release.md
> Use classifier instead of 'class' and archive instead of 'extra'

- bndtools.core/src/bndtools/editor/project/AvailableBundlesPart.java
- bndtools.core/src/bndtools/jface/util/FilteredTree.java
- bndtools.core/src/bndtools/jface/util/TreeFilter.java
- bndtools.core/src/bndtools/model/repo/RepositoryTreeLabelProvider.java
Typing in the filter box did a slow update. This PR uses a (copy of) the FilteredTree that is supposed to be much faster. Now also supports wildcards a la globbing
---
> Slow bundle dialog

- biz.aQute.bndlib/src/aQute/bnd/build/Run.java
- biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
- biz.aQute.bndlib/src/aQute/bnd/help/Syntax.java
- biz.aQute.resolve/src/biz/aQute/resolve/Bndrun.java
- biz.aQute.resolve/test/biz/aQute/resolve/StandaloneTest.java
- biz.aQute.resolve/testdata/standalone/merged.bndrun
- docs/_instructions/standalone.md
> 5673 Merged properties for standalone.

- aQute.libg/src/aQute/lib/io/IO.java
- aQute.libg/src/aQute/lib/io/package-info.java
- aQute.libg/src/aQute/lib/settings/Settings.java
- aQute.libg/src/aQute/lib/settings/packageinfo
- aQute.libg/test/aQute/lib/io/IOTest.java
- biz.aQute.bnd/src/aQute/bnd/main/bnd.java
- biz.aQute.bndlib.tests/test/test/ExtensionsTest.java
- biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
- biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java
- biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
- biz.aQute.bndlib/src/aQute/bnd/maven/MavenCommand.java
- biz.aQute.bndlib/src/aQute/bnd/util/home/Home.java
- biz.aQute.bndlib/src/aQute/bnd/util/home/package-info.java
- biz.aQute.remote/src/aQute/remote/main/Main.java
> Cleaned up the home directory and added a BND_HOME env var

- aQute.libg/src/aQute/lib/io/IO.java
- aQute.libg/test/aQute/lib/io/IOTest.java
> Oops, this got an NPE on windows

- maven-plugins/bnd-baseline-maven-plugin/README.md
- maven-plugins/bnd-baseline-maven-plugin/src/it/invalid-with-provider/invoker.properties
- maven-plugins/bnd-baseline-maven-plugin/src/it/invalid-with-provider/pom.xml
- maven-plugins/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/Base.java
- maven-plugins/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java
- maven-plugins/bnd-plugin-parent/pom.xml
> Allow to configure base via coordinates (and CLI argument)

- bndtools.builder/src/org/bndtools/builder/handlers/baseline/BaselineErrorHandler.java
If there is no package-info.java or packageinfo file then the reporting ended up on the project. This change will add it to the bnd.bnd file. It will first lookup the package in the Export-Package instruction and mark the clause with the package name. If not found, it will register it at the top of the bnd.bnd file.
Fixes #5731
> Baseline reporting only on project

- README.md
This will result in a more enjoyable experience when clicking the link.
> Fix maven plugins link in README.md

- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java
Fixes #5568
This is an alternative fix to what @bjhargrave has put forward in #5743, based on the analysis I put forward in #5568.
> [tester] Minimise scope of TCCL switch

- maven-plugins/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java
> Index only JAR artifacts in IndexerMojo

- bndtools.builder/src/org/bndtools/builder/decorator/ui/PackageDecorator.java
> Fixes #5752

- bndtools.pde/src/bndtools/pde/target/BndTargetLocation.java
- bndtools.pde/src/bndtools/pde/target/RepositoryTargetLocation.java
- bndtools.pde/src/bndtools/pde/target/RunDescriptorTargetLocation.java
> Replaces deprecated interfaces in BndTargetLocation

- biz.aQute.bndlib/src/aQute/bnd/osgi/resource/FileResourceCache.java
> Fixes aQute.bnd.osgi.resource.FileResourceCache.getResource(File, URI) does not take URI into account #5740 

- biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java
- biz.aQute.tester/src/aQute/junit/Activator.java
> Moved check for empty queue to top

- biz.aQute.bndlib.tests/test/test/component/DSAnnotationTest.java
- biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
> Removes Require-Capability for osgi.service AnyService

- docs/_chapters/305-startlevels.md
I found some broken links in the documentation and trying to fix.
> Update 305-startlevels.md - fix 404 link

- bndtools.core/src/bndtools/editor/project/AbstractRequirementListPart.java
- bndtools.core/src/bndtools/wizards/repo/RepoBundleSelectionWizardPage.java
> Speedup repository UI

- bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java
> reset filter in bndtools explorer (Eclipse bnd perspective)

- org.bndtools.p2/features/bndtools.main/feature.xml
> Remove unnecessary promise and function bundles

- biz.aQute.launcher/src/aQute/launcher/pre/EmbeddedLauncher.java
> Fixes #5811 Zip slip bug in EmbeddedLauncher

- bndtools.core/src/bndtools/editor/project/RunRequirementsPart.java
> Fixes 5813, commit page before resolve

- biz.aQute.bndlib.tests/test/test/baseline/BaselineTest.java
- biz.aQute.bndlib/src/aQute/bnd/differ/JavaElement.java
- bndtools.core/bnd.bnd
> Fixes #5808 Handle effective final clases

- org.bndtools.launch/src/bndtools/launch/AbstractOSGiLaunchDelegate.java
> Will not error check projects that are closed before launch

- biz.aQute.bndlib/src/aQute/bnd/properties/PropertiesLineReader.java
- biz.aQute.bndlib/test/aQute/bnd/properties/PropertiesLineReaderTest.java
Fixes https://github.com/bndtools/bnd/issues/5839
Fixes https://github.com/bndtools/bnd/issues/5843
> Improve PropertiesLineReader and add testcase

- docs/README.md
- docs/_config.yml
- docs/_data/sidebar.yml
- docs/_includes/sidebar.htm
- docs/_layouts/default.html
- docs/css/style.scss
- docs/run.sh
Sidebar can be maintained via `_data/sidebar.yml`
Preview:
> Structure side-bar  into groups

- biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceExternalPluginHandler.java
- bndtools.builder/src/org/bndtools/builder/CnfWatcher.java
> Allow main jars without Main-Class

- aQute.libg/src/aQute/libg/parameters/Attributes.java
- aQute.libg/src/aQute/libg/parameters/ParameterMap.java
- aQute.libg/src/aQute/libg/parameters/package-info.java
- aQute.libg/test/aQute/libg/parameters/AttributesTest.java
- biz.aQute.bnd.util/src/aQute/bnd/classfile/ClassFile.java
- biz.aQute.bnd.util/src/aQute/bnd/classfile/builder/ReflectBuilder.java
- biz.aQute.bnd.util/src/aQute/bnd/classfile/builder/package-info.java
- biz.aQute.bnd.util/src/aQute/bnd/classfile/package-info.java
- biz.aQute.bnd.util/test/aQute/bnd/classfile/builder/ReflectBuilderTest.java
- biz.aQute.bndlib.tests/test/test/annotationheaders/AnnotationHeadersTest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Descriptors.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/package-info.java
> Minor convenience functions to classfile and libg

- bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java
- bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java
- bndtools.core/src/bndtools/explorer/Model.java
- bndtools.jareditor/src/bndtools/jareditor/internal/JARTreePage.java
> SWT & Thread issues

- bndtools.core/src/bndtools/model/repo/RepositoryResourceElement.java
- bndtools.core/src/bndtools/views/resolution/ResolutionView.java
@pkriens based on your suggestions from previous PRs
> remove comments  from previous PRs

- aQute.libg/src/aQute/libg/re/Catalog.java
- aQute.libg/src/aQute/libg/re/RE.java
- aQute.libg/test/aQute/libg/re/BasicFunctionalityUnitTest.java
- aQute.libg/test/aQute/libg/re/RETest.java
> Minor improvements and extensions

- biz.aQute.repository/src/aQute/bnd/deployer/repository/LocalIndexedRepo.java
refs #5890
- added check for symbolic links for the base path in LocalIndexRepositories
> #5890 distinguish base path for repo path for sym-links

- biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
- bndtools.core/src/org/bndtools/core/ui/wizards/service/AbstractNewBndServiceMultiProjectWizard.java
Was asked by @scottslewis  to cleanup the refresh code.
---
> Do refresh in workspace write lock

- aQute.libg/src/aQute/libg/re/Catalog.java
- aQute.libg/test/aQute/libg/re/BasicFunctionalityUnitTest.java
> Correct handling of group names

- bndtools.core/src/org/bndtools/refactor/types/ComponentRefactorer.java
- bndtools.core/src/org/bndtools/refactor/types/DiverseRefactorer.java
- bndtools.core/src/org/bndtools/refactor/util/ASTEngine.java
- bndtools.core/src/org/bndtools/refactor/util/Cursor.java
- bndtools.core/src/org/bndtools/refactor/util/RefactorAssistant.java
- bndtools.core/test/org/bndtools/refactor/types/DiverseRefactorerTest.java
> Relevance and handling constructor/super in final field

- bndtools.core/src/org/bndtools/refactor/types/ComponentRefactorer.java
- bndtools.core/src/org/bndtools/refactor/types/GogoRefactorer.java
- bndtools.core/src/org/bndtools/refactor/util/RefactorAssistant.java
- bndtools.core/test/org/bndtools/refactor/types/ComponentRefactorerTest.java
- bndtools.core/test/org/bndtools/refactor/types/DiverseRefactorerTest.java
- bndtools.core/test/org/bndtools/refactor/types/GogoRefactorerTest.java
Changes for #5975
- I'd fixed the imports but only for the test cases :-( Had to call init() in each type of constructor
- Add/Remove component only close to type declaration
- Gogo only when the class is a component
---
> Fixes #5975. Changes in refactoring UI

- bndtools.core/src/org/bndtools/facade/package-info.java
- bndtools.core/src/org/bndtools/refactor/types/GogoRefactorer.java
- bndtools.core/test/org/bndtools/refactor/types/GogoRefactorerTest.java
- bndtools.core/test/org/bndtools/refactor/types/TestRefactors.java
- bndtools.core/test/org/bndtools/refactor/types/package-info.java
> Bug in GogoRefactorer, scrunch

- biz.aQute.bndlib.tests/test/test/ProcessorTest.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/MessageReporter.java
> getInfo did not properly fixup values from other processor in getInfo

- aQute.libg/src/aQute/lib/json/JSONCodec.java
- aQute.libg/src/aQute/lib/json/RecordHandler.java
- aQute.libg/src/aQute/lib/json/packageinfo
- aQute.libg/test/aQute/lib/json/JSONTest.java
> Added records to the JSONCodec class

- biz.aQute.bnd.exporters/bnd.bnd
[OSGi Subsystems creation/management support for Bndtools?](https://bnd.discourse.group/t/osgi-subsystems-creation-management-support-for-bndtools/403)
---
> Make subsystem exporter available to bnd

- bndtools.core/src/org/bndtools/refactor/util/ASTEngine.java
- bndtools.core/src/org/bndtools/refactor/util/RefactorAssistant.java
> Imports were lost for static fields  and method

- aQute.libg/src/aQute/lib/json/CollectionHandler.java
- aQute.libg/src/aQute/lib/json/Handler.java
- aQute.libg/src/aQute/lib/json/JSONCodec.java
- aQute.libg/src/aQute/lib/json/MapHandler.java
- aQute.libg/src/aQute/lib/json/ObjectHandler.java
- aQute.libg/src/aQute/lib/json/RecordHandler.java
- aQute.libg/test/aQute/lib/json/JSONTest.java
ChatGPT told me there is a getRecordComponent on class ... I was now guessing which methods/fields were the correct arguments to the constructor but that is solved now.
---
> Use RecordComponent instead of guessing

- .github/workflows/cibuild.yml
- .github/workflows/codeql.yml
- .github/workflows/rebuild.yml
> Fix gradle setup

- aQute.libg/src/aQute/lib/json/EnumHandler.java
- aQute.libg/src/aQute/lib/json/JSONCodec.java
- aQute.libg/src/aQute/lib/json/ObjectHandler.java
- aQute.libg/src/aQute/lib/json/RecordHandler.java
> div. improvements

- biz.aQute.bnd.annotation/src/aQute/bnd/annotation/spi/ServiceProviders.java
- biz.aQute.bnd.annotation/src/aQute/bnd/annotation/spi/package-info.java
- added PACKAGE as target
Tested successfully creation of multiple service providers at a package-info.java
> fixes #6036 ServiceProviders annotation

- biz.aQute.bndlib.tests/test/test/metatype/SpecMetatypeTest.java
- biz.aQute.bndlib/src/aQute/bnd/metatype/MetatypeAnnotations.java
> Allow duplicate pids in designates if one is for regular the other for

- biz.aQute.bndlib.tests/test/test/baseline/BaselineTest.java
- biz.aQute.bndlib/src/aQute/bnd/differ/Baseline.java
- biz.aQute.bndlib/src/aQute/bnd/differ/package-info.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java
- maven-plugins/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java
- Added new parameter to baseline mojo
- Added additional test to BaselineTest
- Added additional baseline plugin integration test
> Issue #6048: Ability to configure threshold for semantic versioning failures

- aQute.libg/src/aQute/lib/converter/Converter.java
- aQute.libg/src/aQute/lib/converter/SelectType.java
- aQute.libg/src/aQute/lib/converter/packageinfo
- aQute.libg/src/aQute/lib/json/Decoder.java
- aQute.libg/src/aQute/lib/json/JSONCodec.java
- aQute.libg/src/aQute/lib/json/MapHandler.java
- aQute.libg/src/aQute/lib/json/ObjectHandler.java
- aQute.libg/src/aQute/lib/json/RecordHandler.java
- aQute.libg/test/aQute/lib/json/JSONTest.java
> Adding records to JSONCodec

- biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
- biz.aQute.bndlib/test/aQute/bnd/osgi/AnalyzerTest.java
- biz.aQute.bndlib/test/aQute/bnd/osgi/providertype/TestProviderInheritance.java
- biz.aQute.bndlib/test/aQute/bnd/osgi/providertype/package-info.java
- biz.aQute.bndlib/test/aQute/bnd/osgi/providertype/packg/TestProviderInheritancePackage.java
- biz.aQute.bndlib/test/aQute/bnd/osgi/providertype/packg/package-info.java
> ProviderType: inheritance + package level

- biz.aQute.bndlib/src/aQute/bnd/differ/Baseline.java
> Baseline changes introduced a warning

- README.md
Linking bnd image to the bnd documentation
Linking release image to the release wiki page
Bugfixing links of issues and commit activity
> Bugfixing README.md

- docs/_plugins/osgirepo.md
Related https://github.com/bndtools/bndtools.github.io/issues/118
> update osgirepo max.stale description

- biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java
> NPE in Add to -buildpath Quickfix. 

- bndtools.jareditor/src/bndtools/jareditor/internal/JarFileSystem.java
> Check if file exists to prevent falsely opening it

- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/DependencyResolver.java
- maven-plugins/bnd-resolver-maven-plugin/src/it/resolve-from-multiple-artifacts/invoker.properties
- maven-plugins/bnd-resolver-maven-plugin/src/it/resolve-from-multiple-artifacts/pom.xml
- maven-plugins/bnd-resolver-maven-plugin/src/it/resolve-from-multiple-artifacts/postbuild.groovy
- maven-plugins/bnd-resolver-maven-plugin/src/it/resolve-from-multiple-artifacts/test.bndrun
> Adapted the sameExactVersion function to also check if the extension of two Maven artifacts are equal.

- biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/DependencyResolver.java
- maven-plugins/bnd-resolver-maven-plugin/src/it/resolve-large/invoker.properties
- maven-plugins/bnd-resolver-maven-plugin/src/it/resolve-large/pom.xml_ignore
- maven-plugins/bnd-resolver-maven-plugin/src/it/resolve-large/postbuild.groovy
- maven-plugins/bnd-resolver-maven-plugin/src/it/resolve-large/test.bndrun
fixes #6147
@pkriens I'm not sure if we want to keep the test active, as it runs very long. On my machine it takes about 6 minutes, as it has to check around 3000 dependencies.
> fixes StackOverflow in maven dependency resolution

- docs/README.md
- docs/_chapters/120-install.md
- docs/_data/sidebar.yml
- docs/_layouts/front.html
- docs/run.sh
> Tweaks for docs

- CONTRIBUTING.md
add example how to build and skip tests
> Aktualisieren von CONTRIBUTING.md

- .github/workflows/cibuild.yml
There are suddenly problems with Gradle runner with the test exists on Windows.
Disabling windows for now.
> Disable Windows for now

- CONTRIBUTING.md
- biz.aQute.bndlib.tests/test/test/ClazzTest.java
Closes #6261 
@reckart could you verify?
> disable test for JDK >=21

- biz.aQute.bnd/bnd.bnd
> Native code was not included in the bnd jar, fixes #6144

- gradle-plugins/biz.aQute.bnd.gradle/.project
Removal for providing oomph setups, without groovy nature
> remove usage of groovy nature

- docs/_chapters/150-build.md
- fix dead link to Maven Bnd Repo Plugin
- add example
- add some intermediate headlines for improved structure
Needed this to link to for the OCX presentation
> improve section about .pmvn files

- aQute.libg/test/aQute/lib/io/LineSeparatorBufferedReaderTest.java
- biz.aQute.bnd.util/test/aQute/bnd/unmodifiable/ListsTest.java
- biz.aQute.bnd.util/test/aQute/bnd/unmodifiable/MapsTest.java
- biz.aQute.bnd.util/test/aQute/bnd/unmodifiable/SetsTest.java
- biz.aQute.bndall.tests/test/biz/aQute/test/launchpad/LaunchpadWorkspace.java
- biz.aQute.bndlib.tests/test/test/BndEditModelTest.java
- biz.aQute.bndlib/src/aQute/bnd/connection/settings/SettingsParser.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
- biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
- biz.aQute.launchpad.tests/test/aQute/xlaunchpad/BeforeAfterTest.java
- biz.aQute.launchpad.tests/test/aQute/xlaunchpad/FO.java
- biz.aQute.launchpad.tests/test/aQute/xlaunchpad/LaunchpadConfigurationTest.java
- biz.aQute.launchpad.tests/test/aQute/xlaunchpad/LaunchpadRunnerBasicTest.java
- biz.aQute.launchpad.tests/test/aQute/xlaunchpad/Manual.java
- biz.aQute.launchpad.tests/test/aQute/xlaunchpad/WorkspaceTest.java
- biz.aQute.launchpad/test/aQute/launchpad/JunitRuleTest.java
- biz.aQute.tester.test/test/aQute/tester/bundle/engine/test/BundleEngineTest.java
- bndtools.core/src/bndtools/wizards/bndfile/BndRunFileWizard.java
I suddenly had 35 resource leaks warnings. These were all in tests and I recall there was a setting to ignore them in tests. I just fixed them here.
> Fixes resource leaks warnings in tests

- bndtools.core/_plugin.xml
- bndtools.core/src/bndtools/PartConstants.java
- bndtools.core/src/bndtools/perspective/BndPerspective.java
- bndtools.core/src/bndtools/wizards/newworkspace/Model.java
Fixes #6301. Renamed new bnd to a fragment new workspace version and restored the links
---
> Rearranged the bnd new workspace menu entries

- bndtools.core.services/bnd.bnd
- bndtools.core.services/src/org/bndtools/core/editors/quickfix/package-info.java
- bndtools.core.services/src/org/bndtools/pde/launchtobndrun/package-info.java
> Missing package in resolve for the #5829 PR

- bndtools.core.services/src/org/bndtools/core/editors/quickfix/package-info.java
- bndtools.core.services/src/org/bndtools/pde/launchtobndrun/LaunchToBndrun.java
- bndtools.core.services/src/org/bndtools/pde/launchtobndrun/LaunchToBndrunAction.java
- bndtools.core.services/src/org/bndtools/pde/launchtobndrun/package-info.java
> Had a dependency on the PDE feature.

- gradle/wrapper/gradle-wrapper.properties
> Gradle to 8.10.2

- .github/workflows/cibuild.yml
- biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorCommonTest.java
- biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorTest.java
- biz.aQute.tester/src/aQute/junit/system/BndSystem.java
> Reenable windows tests

- biz.aQute.bndlib/src/aQute/bnd/osgi/package-info.java
- bndtools.core/src/bndtools/editor/BndEditor.java
Fixes #6380 
---
Signed-off-by: Peter.Kriens@aQute.biz
> NPE in Resolve when running without project

- org.bndtools.launch/src/bndtools/launch/sourcelookup/containers/BndrunDirectiveSourceContainer.java
This is a continuation of https://github.com/bndtools/bnd/pull/6165 which fixed it for normal bundle bnd.bnd files. But the previous PR did not consider the -sub instruction feature of bnd where you can define multiple sub-jar per project. The repos inside -includeresource instructions of such sub-bnd.bnd files were not considered yet.
(see also https://bnd.discourse.group/t/generating-multiple-bundles-per-project/84)
Let's say you use the -sub instruction to have multiple sub-bundles resulting multiple .jar files generated for your project.
In a subbundle you are doing e.g. 
```
-includeresource: \
${repo;org.apache.poi:poi;latest}; lib:=true,\
```
to include / wrap a dependency from your `repo`
**Before this fix:**
When you were debugging and stepped into one of the files of …
> fix source lookup for sub-projects via -sub instruction

- docs/_chapters/160-jars.md
- docs/_heads/export_package.md
- docs/_instructions/exportcontents.md
- docs/_instructions/sub.md
Since we talked about sub-bundles / -sub today, I took the chance to improve the documentation around it.
> Improve documentation (e.g. for -sub, -exportcontents, Export-Package, ...)

- docs/_includes/searchbox.htm
fix a small mistake I did during the previous cleanup
> search: fix broken close button

- bndtools.core/src/bndtools/javasearch/BndtoolsJavaWorkingSetUpdater.java
See https://github.com/bndtools/bnd/issues/6474#issuecomment-2672077388
---
Signed-off-by: github-actions <github-actions@bndtools.org>
> Removed copyright header after granted ASL 2.0 license. 

- biz.aQute.bndlib/src/aQute/bnd/build/Project.java
> Fix javadoc of Project#getBundle

- org.bndtools.p2/features/bndtools.ecf/feature.xml
Fix for ecf feature.xml mishandling of dependencies.  Applies for issue #6514
> Fix for ecf feature.xml

- org.bndtools.p2/features/bndtools.ecf/feature.xml
> Replaced feature includes with plugin references in ecf feature.xml

- org.bndtools.p2/features/bndtools.ecf/feature.xml
> Improved ecf feature.xml by using require features

- DEV_README.md
- biz.aQute.bndlib/src/aQute/bnd/build/model/README.md
Based on https://github.com/bndtools/bnd/pull/6508#issuecomment-2733296245 
This adds a readme how to create the `.properties ` files for different JAVA / JDK versions in https://github.com/bndtools/bnd/tree/master/biz.aQute.bndlib/src/aQute/bnd/build/model
> add README how to generate JDK .properties

- docs/_chapters/210-metatype.md
- docs/_chapters/220-contracts.md
- docs/_instructions/contract.md
- docs/_instructions/define-contract.md
Closes https://github.com/bndtools/bnd/issues/6545
> docs: fix contract examples and cross link

- bndtools.core/src/bndtools/editor/BndSourceEffectivePage.java
Closes https://github.com/bndtools/bnd/issues/6524
**Tweaks for the Effective Tab in BndEditor**
- now the tooltips have scrollbars and allow to click into and copy the content to clipboard
- also I added a Checkbox "Show expanded values" to toggle between raw value and expanded value. for both table and source view
https://github.com/user-attachments/assets/1e162cf7-42d2-4dda-9d72-b675a805da87
> Effective: show textbox tooltips and checkbox

- bndtools.core/src/bndtools/editor/BndSourceEffectivePage.java
unfortunately in the last PR, the open provenance on double click in the table row broke.
Relates to #6525 and fixes bug introduced in #6571
> Effective View: fix broken double-click opener

- bndtools.core/src/bndtools/editor/BndSourceEffectivePage.java
> enable/disable checkbox for mergedProps

- biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java
- biz.aQute.repository/src/aQute/bnd/repository/maven/provider/RepoActions.java
fixes a bug introduced in previous PR  https://github.com/bndtools/bnd/pull/6581
> fix bug in Add sources in Maven Repo

- bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
Another attempt to fix https://github.com/bndtools/bnd/issues/6596
Successor of https://github.com/bndtools/bnd/pull/6599
During debugging I found why it is still not working. I found the index is build parallel in multiple threads and if there is a single shared empty.index file the threads have a problem with this (`org.eclipse.jdt.internal.core.search.indexing.AddJarFileToIndex.execute(IProgressMonitor)`), close the empty.index and start an (potentially in memory) reindexing of the actual .jar (which is what we want to prevent). So giving each project its own empty-projectname.index we don't run into race conditions of a shared empty.index
> create per-project empty.index

- bndtools.core/src/bndtools/model/resolution/CapReqComparator.java
- bndtools.core/test/bndtools/tasks/AnalyseBundleResolutionJobTest.java
- namespace 'osgi.ee' can contain multiple version List<Version>
- the previous code in CapReqComparator expected a single version
- e.g. there can be a `Provide-Capability: osgi.ee;osgi.ee="OSGi/Minimum"; version:List<Version>="1.0,1.1,1.2",osgi.ee;osgi.ee="JRE"; version:List<Version>="1.0,1.1,1.2,1.3"`
- testcase
Related Spec: 
- https://osgi.github.io/osgi/core/framework.namespaces.html#framework.namespaces.osgi.ee
- https://osgi.github.io/osgi/core/framework.namespaces.html#framework.namespaces-ee.namespace
> **osgi.ee Namespace definition**
> `version: A comma separated list of versions, comparisons must be done with version ordering because the version attribute must be declared with the List<Version> type.`
> ResolutionView: fix a ClassCastException in CapReqComparator for osgi.ee List<Version>

- biz.aQute.bndlib/src/aQute/bnd/build/Project.java
- biz.aQute.bndlib/src/aQute/bnd/build/package-info.java
to get access to the maven coordinates in the resolved bndrun containers from the bnd-maven-plugins
> [bndlib] Project-Container: add maven coordinates to the container

- biz.aQute.launchpad/src/aQute/launchpad/BundleSpecBuilder.java
- biz.aQute.launchpad/src/aQute/launchpad/package-info.java
- biz.aQute.launchpad/test/aQute/launchpad/BundleBuilderTest.java
> [launchpad] BundleBuilder to allow adding classes by copy w/recursion

- .github/workflows/docs_generate.yml
This PR is an attempt to run the /docs/generate.sh in the PR which generates content based on Java files and also manual content in  /_heads/_ext  etc. folders
> generate docs to PR

- .github/workflows/docs_generate.yml
+ harden runner from other scripts
> Docs: GH Action Generate: run on master merge

- biz.aQute.bndlib/src/aQute/bnd/help/Syntax.java
small fix.
And also a little test if the docs generation kicks in when merging to master :)
> docs: use colon for instruction

- .gitignore
- .mailmap
- .project
added root eclipse project
added .gitignore
_log for local build log ouputs
*.code-workspaces for vscode workspace naming
> added Peter Kirschner as contributor

- biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
- docs/_chapters/920-faq.md
Finetuning based on https://github.com/bndtools/bnd/pull/6559#pullrequestreview-3125903993
> wording: Imports that lack version ranges

- bndtools.builder/src/org/bndtools/builder/decorator/ui/PackageDecorator.java
Closes #6780
This fixes the problem that the project decorator was still showing the red `<excluded>` decorator when you deleted the corresponding package. 
Now the project decorator is always in sync with the package decorators and markers.
> fix dangling project decorator

- bndtools.builder/src/org/bndtools/builder/decorator/ui/PackageDecorator.java
Closes #6786 
This PR has initially been for the launcher. 
I  investigated a bit and leave the launcher as it is.
Because if I add the packages to `-privatepackage` or `Export-Package` then `AlsoLauncher#testAgent()` etc. fail.
So it seems that it has to be like this and I wont touch it. 
But nevertheless I will treak the decorator a little bit in the PR.
And I will also remove the warning marker creation again, because there is no mechanism like `-fixupmessages` to ignore this warning. And for the launcher this warning will stay forever. 
I tried make -fixupmessage work but it was a larger refactoring which I found too risky in the end.
> Tweak PackageDecorator for <excluded>

- cnf/ext/repositories.bnd
Changed ECF Remote Services SDK version to 3.16.5 (currently released version).
> Update ECF SDK version to current released version

- bndtools.core/src/org/bndtools/core/ui/wizards/service/NewBndServiceWizardPageOne.java
This provides a fix for issue #6812
> Fix for issue #6812

- biz.aQute.repository/src/aQute/p2/export/P2Export.java
- biz.aQute.repository/test/aQute/p2/export/P2PublisherTest.java
- biz.aQute.repository/testdata/p2-publish/ws-1/p1/bnd.bnd
hopefully that does not lock the file on windows
> P2Export: fix reuse META-INF from existing bsn.jar

- docs/_plugins/p2export.md
Additions to P2Export docs based on recent changes. 
See https://bnd.bndtools.org/plugins/p2export.html
> Docs: Update p2export.md
