aQute.libg/src/aQute/lib/memoize/Memoize.java, aQute.libg/src/aQute/lib/memoize/ReferenceMemoizingSupplier.java, aQute.libg/src/aQute/lib/memoize/RefreshingMemoizingSupplier.java, aQute.libg/test/aQute/lib/memoize/MemoizeTest.java, bndtools.core/src/bndtools/central/EclipseWorkspaceRepository.java
We now always index through building Resources from the built bundles.
This avoids the need to cache and staleness of that cache.
We now defer, through the use of memoized suppliers, creating Resources
until they are actually necessary. So until you need to resolve, we can
defer this Resource creation. So this can significantly reduce Bndtools
startup time since we do not need to parse .index.xml files or bundles.
If you never use the resolver, we never need to index the workspace
bundles.
=> workspacerepo: Remove use of .index.xml files

biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
In a test, the ws had '..' in the path and therefore failed to find that a project dir pointed to a directory.
This patch canonicalizes both paths.
=> [workspace] Canonicalize paths in getProjectFromDir

aQute.libg/test/aQute/lib/memoize/CallOnOtherThread.java, aQute.libg/test/aQute/lib/memoize/MemoizeTest.java
The timeout was always zero which means the expected result had to be
present within a millisecond.
=> test: Fix racy test

biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java, biz.aQute.tester.test/test/aQute/tester/bundle/engine/test/BundleEngineTest.java
Contains the remainder of the fix for #3882 - to handle the cases where method selectors and/or class selectors are used.
=> [junit-platform] Check for unresolved classes when selectors used

aQute.libg/src/aQute/lib/memoize/CloseableMemoize.java, aQute.libg/src/aQute/lib/memoize/CloseableMemoizingSupplier.java, aQute.libg/test/aQute/lib/memoize/MemoizeTest.java
If the wrapper supplier for a CloseableMemoize returns null, we treat
that as a close of the CloseableMemoize since we have no value to use.
=> memoize: Treat wrapped supplier returning null as a close

aQute.libg/src/aQute/lib/memoize/CloseableMemoizingSupplier.java, aQute.libg/test/aQute/lib/memoize/MemoizeTest.java
If in initial state, we get write lock, then get value and downgrade
to read lock before calling consumer.
=> memoize: Shorten code path for accept

biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceImpl.java, bndtools.m2e/src/bndtools/m2e/MavenBndrunContainer.java
addHashes had altered the encounter ordering for package capabilities
as they were copied to a HashSet and then possibly removed and replaced
in the capabilities if they were updated with hashes.
To keep a consistent ordering, we use a TreeMap to control the namespace
ordering and use "encounter" ordering on the sets. addHashes is fixed to
preserve the encounter ordering for the package capabilities.
Making an effort to have a defined ordering makes it easier when
regenerating indexes to compare with the prior revision of the index.
=> resource: Add standard ordering to capabilities and requirements

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bndall.tests/bnd.bnd, bndtools.utils/src/org/bndtools/utils/jdt/ASTUtil.java
`-noparallel: launchpad;task="test"` in a project's bnd.bnd file
will claim the category "launchpad" for the `test` task. Any other task,
including tasks from other projects, which claims the same category
will not run in parallel when using Gradle's `--parallel` mode.
Multiple categories and multiple task names per category can be
specified.
=> gradle: Add --noparallel instruction support to Bnd Gradle workspace

biz.aQute.bndlib/src/aQute/bnd/osgi/resource/FilterImpl.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java
The values from the filter strings are parsed into strings. But they
often need to be converted to typed values for the actual comparison
with the input maps. This change caches the most recent conversion since
it is highly likely that the value types are highly consistent over the
various input maps. So we can save a lot of conversion of value to type.
This can be particularly beneficial for bnd.hashes which are all
numerical and we can be searching for a specific hash value across all
the indexed resources of which can have many package capabilities each
with many hash values with which to compare. It is also very useful
for version attributes which are generally always of type Version.
This is the filter impl I wrote for OSGi R8.
=> filter: Use improved filter impl with caching of converted values

aQute.libg/src/aQute/libg/cryptography/Digester.java, aQute.libg/src/aQute/libg/cryptography/packageinfo, biz.aQute.bndall.tests/resources/ws-stalecheck/p2/bnd.bnd, biz.aQute.bndall.tests/test/biz/aQute/bnd/project/ProjectGenerateTest.java, biz.aQute.bndlib.tests/test/test/JarTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceRepositoryDynamic.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java
Proposed change to the workspace repositories
confusion.
Eclipse registers a workspace repository that
listens to builds. The Bndrun files register
some repository that scans the projects. 
The problem was that we did not mandate a driver to
register a Workspace repository. This introduced
the WorkspaceRepositoryMaker interface to allow
mostly the Bndrun to check if there was a workspace
repository present. Overall a mess, especially
because before BJ cleaned this up, we were using a 
very convoluted way to get to a repository because
the bndlib had no knowledge of repositories.
I ran into this because the ClassIndex & External
Plugins use a new Workspace.getResourceRepository() method
that tries to provide a single view on the Workspace
and its repositories. Since Gradle does _not_ …
=> [repository] Workspace repositories

biz.aQute.bndlib/src/aQute/bnd/build/ProjectTracker.java, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceRepositoryDynamic.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/WorkspaceRepositoryMarker.java, biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java, biz.aQute.resolve/src/biz/aQute/resolve/WorkspaceRepositoryMarker.java, biz.aQute.resolve/src/biz/aQute/resolve/WorkspaceResourcesRepository.java, bndtools.core/src/bndtools/central/EclipseWorkspaceRepository.java
We refactor to use ResourceUtils.matcher as a stream filter. This will
only create the filter once for the requirement rather than once for
each capability tested against a requirement.
When matching across multiple capabilities, as we do here, one should
prefer ResourceUtils.matcher over ResourceUtils.matches. The latter
always creates a new filter object which wastes time in reparsing the
requirement into a filter. Using matcher also allows any optimizations
that can be achieved from reusing the filter object for matches over
the multiple capabilities.
We also make WorkspaceRepositoryDynamic a WorkspaceRepositoryMarker so
others may recognize it if encountered. We also reduce to package
private to avoid making API at this point. We will likely improve this
area after this release.
=> Refactor WorkspaceRepositoryDynamic to reuse filter

aQute.libg/src/aQute/lib/strings/Strings.java, biz.aQute.bndlib/src/aQute/bnd/build/Container.java, biz.aQute.bndlib/src/aQute/bnd/build/DownloadBlocker.java, biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java, biz.aQute.bndlib/src/aQute/bnd/service/RepositoryPlugin.java, biz.aQute.bndlib/src/aQute/bnd/util/repository/DownloadListenerPromise.java, biz.aQute.bndlib/src/aQute/bnd/util/repository/package-info.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, biz.aQute.repository/src/aQute/maven/api/Archive.java, biz.aQute.repository/src/aQute/maven/api/Program.java, biz.aQute.repository/src/aQute/maven/api/Revision.java, biz.aQute.repository/src/aQute/maven/api/package-info.java, biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
We provide a means for maven repo types to supply maven attributes about artifacts through DownloadListeners into Containers which can then be examined by the maven dependency computation logic. pom.properties processing is the fall back for when artifacts come from non-maven repos such as the workspace repo.
This is done with limited API changes.
=> Better computation of maven dependencies

biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
If we get a maven classifier attribute from a repo, we should use it in
the generated maven dependencies.
=> pom dependencies: Use classifier if present and non-empty

biz.aQute.bnd.reporter/bnd.bnd, cnf/build.bnd
Recent enhancements to Bnd get maven metadata from the repository
plugin. So we don't need to specify the maven metadata for jtwig
anymore.
=> reporter: Remove -maven-dependencies instruction

biz.aQute.bnd/src/aQute/bnd/ant/BndTask.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
A Project's parent is the Workspace. When the Workspace is updated
(such as by editing cnf/build.bnd), the lastModified of the Workspace
is updated and so the lastModified of its Projects must also be updated.
So when the Projects rebuild, their Jar files will get the updated
lastModified time and so will appear to be changed to observers such as
Eclipse.
Fixes #4017
=> A Processor's lastModified must consider the parent Processor

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
Bnd properties can alter the -generate instruction, so we may need to
re-execute.
=> generate: Gradle generate task should be run if bnd properties change

LICENSE, cnf/build.bnd, maven/pom.xml, org.bndtools.p2/features/bndtools.m2e/feature.xml, org.bndtools.p2/features/bndtools.main/feature.xml, org.bndtools.p2/features/bndtools.pde/feature.xml
We also add SPDX-License-Identifier.
https://spdx.org/spdx-specification-21-web-version#h.twlc0ztnng3b
=> build: Clean up license notice to properly describe AL2 OR EPL2

biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
To make sure the splitting of the path elements properly handles
windows file names with drive:.
=> test: Use full windows file names in path

bndtools.core/_plugin.xml, bndtools.core/src/bndtools/command/BndExportJarHandler.java, bndtools.core/src/bndtools/command/BndExportRunbundlesHandler.java, bndtools.core/src/bndtools/command/BndResolveHandler.java, bndtools.core/src/bndtools/command/BndrunFilesParameterValues.java
Recently I've been exporting jars using the gradle tasks because its just faster for me to type into a terminal what I need instead of fishing around the Eclipse UI for the correct bndrun file and then clicking through the "Export Run descriptor" wizard.  
However, when I run `gradlew export` tasks from the CLI, I often will run into the problem of both the gradle export task and Eclipse builder running at the same time (because I have auto-refresh set to true for my Eclipse workspace).  So as you can expect having two builders (eclipse and gradle) running at the same time blows up often when they try to read/write the files
So I decided to add a new feature to Bndtools that will make it just as fast (minimal keystrokes) for me to execute this `export` operation.  I did this as Eclipse …
=> add parameterized commands for exporting and resolving bndrun files

bndtools.core/_plugin.xml, bndtools.core/src/bndtools/command/OpenProjectHandler.java, bndtools.core/src/bndtools/command/ProjectNamesParameterValues.java, bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java
Use the `Quick Access` `Cmd+3` and then type in a project name (or partial name) and you should see a new "open project" command available.
This will try to open the BndtoolsExplorer first and then falls back to PackageExplorer.  If neither are open, it will open the BndtoolsExplorer.
=> add "open project" command handler

biz.aQute.bndlib.tests/test/test/MacroTest.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, biz.aQute.repository/src/aQute/maven/api/Program.java, biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
We now have `noupdateOnRelease=true` option to disable updating the
index on release. So the original decision to not update index on
release of snapshots can be relaxed.
And some other fixes.
=> maven repo: Allow adding snapshots to index on release

aQute.libg/src/aQute/lib/memoize/CloseableMemoizingSupplier.java
Since we know all the objects are instances of AutoCloseable, we make
the erasure of the method AutoCloseable to avoid checkcast
instructions at call sites.
=> memoize: Elide checkcast instructions

aQute.libg/test/aQute/lib/memoize/MemoizeTest.java
The test failed in a CI build which took more than 100 ms to call
the supplier 10 times. So we increase the time-to-live to 300 ms.
=> memoize test: Increase time-to-live in test

aQute.libg/src/aQute/lib/memoize/Memoize.java, aQute.libg/src/aQute/lib/memoize/PredicateMemoizingSupplier.java, aQute.libg/src/aQute/lib/memoize/package-info.java, aQute.libg/test/aQute/lib/memoize/MemoizeTest.java
Sometimes you want to memoize something but that something may not be
ready. For example, it may return null until it can return a real value.
The new memoizer allows you to memoize a supplier along with a
predicate. The memoizer will memoize the first value from the source
supplier that is accepted by the predicate.
=> Add new memoizer which memoizes once the predicate accepts

bndtools.builder/src/org/bndtools/builder/MarkerSupport.java
If you export a package form another bundle and that
package has a baseline error, then this error is lost.
The bndlib project exports a package aQute.bnd.annotation.plugin
from the biz.aQute.bnd.annotation project. 
I added a Capability header to the BndPlugin and then
suddenly the bndlib was no longer built, but no errors
were marked.
After debugging it became clear that biz.aQute.bnd.annotation
was not baselined but the aQute.bnd.annotation.plugin
package caused a baseline error in bndlib.
The BaselineErrorHandler could not find 
the package when it tried to create a marker. It
therefore returned zero markers. The MarkerSupport
did not take the case into account where the
Error Handler had zero markers after it indicated
that it had a handler and returned.
This fix will create a …
=> [baseline] Lost baseline error

bndtools.core/src/bndtools/launch/AbstractOSGiLaunchDelegate.java
Two commits:
1. Change to honour the workspace settings pertaining to "build before launch" (fixes #4089).
2. Move the bnd launcher initialisation out of `buildForLaunch()` into `finalLaunchCheck()` (fixes #4095).
While I think these are nice fixes there is probably no rush to get them into 5.1-RC2. Who knows how long the "buildForLaunch" flag hasn't been honoured...
=> [bndtools launch] Launching fixes

aQute.libg/src/aQute/lib/unmodifiable/ImmutableList.java, aQute.libg/src/aQute/lib/unmodifiable/ImmutableMap.java, aQute.libg/src/aQute/lib/unmodifiable/ImmutableSet.java, aQute.libg/src/aQute/lib/unmodifiable/Lists.java, aQute.libg/src/aQute/lib/unmodifiable/Maps.java, aQute.libg/src/aQute/lib/unmodifiable/Sets.java, aQute.libg/test/aQute/lib/unmodifiable/MapsTest.java, aQute.libg/test/aQute/lib/unmodifiable/SetsTest.java, biz.aQute.bndlib/src/aQute/bnd/help/Syntax.java, biz.aQute.bndlib/src/aQute/bnd/osgi/About.java
For sets and maps, we hash using open addressing with linear probing to
get O(1) lookup. This will make the types more useful for larger
unmodifiable sets and maps.
=> unmodifiable: Hash using open addressing with linear probing

bndtools.core/src/bndtools/dnd/gav/BndDropTargetListener.java, bndtools.core/src/bndtools/dnd/gav/GAVDropTargetListener.java, bndtools.core/src/bndtools/dnd/gav/GradleDropTargetListener.java, bndtools.core/src/bndtools/dnd/gav/MavenDropTargetListener.java
Two fixes here:
- always move to the end of a line before inserting
- in the bnd(run) model, handle line continuations (if the line ends with a continuation add a continuation at the end of the inserted line, otherwise add one at the start)
=> dnd.gavs: handle line continuations

bndtools.core/src/bndtools/utils/MessageHyperlinkAdapter.java, bndtools.core/src/bndtools/utils/MessagesPopupDialog.java
=> bndtools: fix the messages dialog for missing workspace

biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, bndtools.builder/src/org/bndtools/builder/CnfWatcher.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerSourceManager.java, bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/central/EclipseWorkspaceRepository.java, bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java, bndtools.core/src/bndtools/central/WorkspaceListener.java, bndtools.core/src/bndtools/editor/BndEditor.java, bndtools.core/src/bndtools/editor/common/BndEditorPart.java, bndtools.core/src/bndtools/editor/pages/ProjectRunPage.java, bndtools.core/src/bndtools/editor/project/RepositorySelectionPart.java, bndtools.core/src/bndtools/editor/workspace/WorkspaceMainPart.java, bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java
We now have two callback queues. One for the first workspace which may
not be a Bnd Workspace but may be a default workspace. And another for
each Bnd Workspace.
This allows m2e code to use the first workspace callback queue
(onAnyWorkspace) since the underlying promise will be resolved on the
first call to getWorkspace.
Code for Bnd Workspace models builds can use the second workspace
callback queue (onCnfWorkspace) whose underlying promise is not
resolved until a Bnd Workspace is created. If the workspace converts
back to a default workspace (when the cnf project is deleted), then a
new Bnd Workspace queue is created waiting for the workspace to get
a cnf project again.
This is not a complete replacement of the getWorkspace code in Central
but seems to be the least disruptive change to …
=> central: Rework callbacks for workspace creation

biz.aQute.bndlib.tests/bnd.bnd, biz.aQute.bndlib.tests/test/test/ReferencedAnnotationTest.java, biz.aQute.bndlib.tests/test/test/referenced/annotation/testReferenced/TestReferenced.java, biz.aQute.bndlib.tests/test/test/referenced/annotation/testReferenced/package-info.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, cnf/ext/osgi-snapshots.mvn
Source code can now use `@Referenced(SomeClass.class)` to make a reference
to the specified types. This will cause Bnd to record a reference to the
type which can result in an Import-Package clause.
The Referenced annotation allows a non-code reference in source code.
This can be helpful if the referenced types are not directly referenced
in the source code but may be needed for some reflective purpose at
runtime and the developer wants to ensure that the necessary
Import-Package clause is generated.
=> osgi: Support for new OSGi Referenced annotation

bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java
The logic for finding an IFile for the workspace build file (e.g.
cnf/build.bnd) failed to address the case were multiple projects could
refer to the file. The main example is where the root of the workspace
is an Eclipse project which can be done to allow easy editing of files
in the root of the repository.
So now we better handle this case and just pick one of the IFile
references.
Fixes https://github.com/bndtools/bnd/issues/4140
=> central: Better handle multiple projects referring to build.bnd file

biz.aQute.bndlib/src/aQute/bnd/remoteworkspace/server/RemoteWorkspaceServer.java
Project.getSpecification directly created a Run
instead of using the static Run.createRun method.
This meant that getRunBundles() was not resolved
if the auto resolve was set.
=> [launchpad] Use Bndrun instead of Run

biz.aQute.bndall.tests/resources/launchpad/ws1/cnf/build.bnd, biz.aQute.bndall.tests/resources/launchpad/ws1/cnf/central.mvn, biz.aQute.bndall.tests/resources/launchpad/ws1/p1/batch-with-bundles.bndrun, biz.aQute.bndall.tests/resources/launchpad/ws1/p1/batch.bndrun, biz.aQute.bndall.tests/resources/launchpad/ws1/p1/beforelaunch.bndrun, biz.aQute.bndall.tests/test/aQute/launchpad/ResolveTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/help/instructions/ResolutionInstructions.java, biz.aQute.bndlib/src/aQute/bnd/help/instructions/package-info.java, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/BeforeAfterTest.java, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/FO.java, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/LaunchpadConfigurationTest.java, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/LaunchpadRunnerBasicTest.java, biz.aQute.launchpad/src/aQute/launchpad/BundleSpecBuilder.java, biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java, biz.aQute.launchpad/src/aQute/launchpad/LaunchpadBuilder.java, biz.aQute.launchpad/src/aQute/launchpad/package-info.java, biz.aQute.resolve/src/biz/aQute/resolve/Bndrun.java, docs/_instructions/resolve.md
A previous commit added resolve support for launchpad, this continues with some extra lp support.
- Able to set Remote Workspace on a build instead of always using auto discovery, for testing
- New resolve mode to reduce lag in IDE
- Some ban errors fixed, which makes me worry if these tests were running?
=> Launchpad resolve support

dist/bnd.bnd
hey @bjhargrave  I tested this in my app and was able to swap out the older `bndtools.runtime.applaunch.eclipse4` bundle with the new `org.bndtools.applaunch` bundle.
=> add org.bndtools.applaunch to distribution

biz.aQute.bndlib.tests/test/test/jpms/JPMSModuleInfoPluginTest.java, biz.aQute.bndlib/src/aQute/bnd/plugin/jpms/JPMSModuleInfoPlugin.java, docs/_chapters/330-jpms.md
=> improve naming of `access` values when defining `-jpms-module-info`

bndtools.core/src/org/bndtools/core/templating/repobased/ReposTemplateLoader.java
Fixes an error I noticed in the Eclipse log.
=> [bndtools.core] Fixed type of service.ranking for ReposTemplateLoader

biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java, biz.aQute.tester.test/src/aQute/tester/testclasses/junit/platform/JUnit4ContainerError.java, biz.aQute.tester.test/src/aQute/tester/testclasses/junit/platform/JUnit4ContainerFailure.java, biz.aQute.tester.test/src/aQute/tester/testclasses/junit/platform/JUnit5ContainerError.java, biz.aQute.tester.test/src/aQute/tester/testclasses/junit/platform/JUnit5ContainerFailure.java, biz.aQute.tester.test/test/aQute/tester/junit/platform/test/ActivatorJUnitPlatformTest.java, biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorTest.java
This is necessary as Jupiter reports container failures separately from the children if the container fails before the children are executed.
Fixes #4175.
=> [junit-platform] Report total failure count, not just test failures

biz.aQute.repository/src/aQute/maven/provider/MavenBackingRepository.java, biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java
Since there can be multiple URLs for snapshotUrl, an individual
backing repo cannot report no metadata, since the revision can be
present in a later backing repo. So we change to report no metadata
after all backing repos have been queried.
Fixes https://github.com/bndtools/bnd/issues/4204
=> mavenbndrepo: Report no metadata only after asking all backing repos

.github/workflows/cibuild.yml
This is needed by UI test cases to provide a frame buffer.
The GitHub Action unbuntu-latest os already has xvfb installed and up to date.
=> ci: Use xvfb-run to build on linux

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/TestCases.java
We now use the marker annotation
org.junit.platform.commons.annotation.Testable.
=> maven: Simplify junit5 enum value

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
The system.bundle host is always present by specification.
We also remove a duplicate warning for fragments.
=> analyzer: Don't warn for system.bundle host not found

biz.aQute.bndlib.tests/test/test/MacroTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenTestsPlugin.java
Stop erroring if sort list is empty. Warn is Test-Cases header is empty for bnd-process-tests.
See https://github.com/bndtools/bnd/issues/4213.
=> Maven Test-Cases header

biz.aQute.bndlib.tests/test/test/component/DSAnnotationTest.java, biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java, biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java, biz.aQute.bndlib/src/aQute/bnd/component/error/DeclarativeServicesAnnotationError.java, biz.aQute.bndlib/src/aQute/bnd/component/error/package-info.java
We now add the location information to the error message.
Fixes https://github.com/bndtools/bnd/issues/4171
=> ds: Add details to error messages for DS annotations processing

aQute.libg/src/aQute/lib/collections/MultiMap.java, aQute.libg/src/aQute/lib/collections/package-info.java, biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceClassIndex.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, bndtools.utils/src/org/bndtools/utils/collections/CollectionUtils.java
We create and use a new MultiMap.transpose(boolean noduplicates) method
to avoid duplicate bundle ids.
Fixes #4226
=> classindex: Avoid returning duplicate bundle ids

biz.aQute.bnd.gradle/build.gradle, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndUtils.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Index.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/PropertiesWrapper.groovy, maven/build.gradle, org.bndtools.p2/build.gradle
Gradle is introducing the ability to cache gradle configuration to
improve build start time. These changes are minor changes inline with
enabling this support. It will likely take gradle several releases to
get complete configuration caching to work and we will need to make
more changes as they do.
=> gradle: Update gradle code regarding configuration caching

bndtools.core/src/bndtools/launch/AbstractOSGiLaunchDelegate.java, bndtools.core/src/bndtools/launch/OSGiJUnitLaunchDelegate.java, bndtools.core/src/bndtools/launch/OSGiRunLaunchDelegate.java
Move the pre-launch validation logic from `OSGiRunLaunchDelegate` into `AbstractOSGiLaunchDelegate`, and remove the custom logic from `OSGiJUnitLaunchDelegate`. Net effect is to have both delegates using the same pre-launch validation.
Fixes #3954.
=> [bndtools launch] Unify launch delegates' pre-launch validation logic

maven/bnd-maven-plugin/README.md, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenTestsPlugin.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/TestCases.java
Users can then specify the `testng` value in maven configuration.
Developers must make sure that a proper TestNG execution bundle is
present in the test runtime. For example, if using JUnit Platform, then
a TestNG TestEngine implementation bundle must be available.
Fixes https://github.com/bndtools/bnd/issues/4213
=> maven: Add testng TestCases enum value

biz.aQute.bndlib.tests/test/test/ImportJavaTest.java, biz.aQute.bndlib.tests/test/test/importjava/ImportJava.java, biz.aQute.bndlib/src/aQute/bnd/help/Syntax.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, biz.aQute.bndlib/src/aQute/bnd/version/Version.java, biz.aQute.bndlib/src/aQute/bnd/version/VersionRange.java, biz.aQute.bndlib/src/aQute/bnd/version/package-info.java, docs/_instructions/noimportjava.md
This can be disabled with `-noimportjava: true`. The support allows
control over the specific java packages imported via the `Import-Package`
instruction. The support is only enabled if either the bundle imports
the `org.osgi.framework` package at version 1.9 (Core R7), or higher, or
if the bundle includes class files for Java 11, or higher.
Fixes #2507
=> Add support for importing java.* packages for OSGi Core R7 

CONTRIBUTING.md
In the last 12 months, Github introduced the "Draft" feature for pull requests. This is a more appropriate way to handle work-in-progress PRs rather than the "WIP-in-the-title" convention that we were using.
=> [contributing] Use draft PRs instead of WIP convention

biz.aQute.bndlib/src/aQute/bnd/plugin/maven/CentralCheck.java, biz.aQute.launcher/src/aQute/launcher/Launcher.java, bndtools.core/src/bndtools/central/InternalPluginTracker.java, bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java
- When the reload button is hit in the BndtoolsExplorer, the tree is also refreshed from disk
- Launcher reports errors during startup to the console, after startup it traces them
- Plugins were not detected because bndlib stayed in resolve and was never activated
=> Tree refresh when reload, reporting framework errors, detecting plugins

bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessorTest.java
Refer #4253 - temporarily disabling the integration test until we can determine the source of the flakiness.
=> [junit-platform] Disable integration test

.github/scripts/build.sh, .github/scripts/rebuild.sh
Otherwise the build can fail because the JVM will emit a
"Picked up JAVA_TOOL_OPTIONS" message to stdout which can break some
tests.
=> ci: Make sure to unset JAVA_TOOL_OPTIONS and _JAVA_OPTIONS

bndtools.core/src/org/bndtools/core/resolve/ResolutionResult.java, bndtools.core/src/org/bndtools/core/resolve/ResolveOperation.java
The change in 08946e7e38148570da8d51a81b3881b50aa10e01 to have ResolutionResult hold a RunResolution instead of the interesting parts did not account for the case where the ResolutionResult could be constructed with  a `null` RunResolution.
https://github.com/bndtools/bnd/blob/dceacf10560cde78cf3a11b115a0556f0d2e7eba/bndtools.core/src/org/bndtools/core/resolve/ResolveOperation.java#L81
https://github.com/bndtools/bnd/commit/08946e7e38148570da8d51a81b3881b50aa10e01#diff-d02a251dfce54dc358769bd379554ec0R62
=> Handle null resolution in ResolutionResult

bndtools.jareditor/src/bndtools/jareditor/internal/JARPrintPage.java
We use a JarFileSystem to view jar files. But the `jarf` scheme is only
known to the Eclipse File System (EFS) and not the JRE. So converting a
`jarf` URI to a URL fails. We use `EFS.getStore` to access URIs for
printing the jar. `EFS.getStore` also properly handles `file` URIs
for non-nested jar files.
Fixes https://github.com/bndtools/bnd/issues/4276
=> jareditor: Use `EFS.getStore` to access URIs for printing jars

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Resolve.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/TestOSGi.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBundlePlugin.groovy, biz.aQute.bnd.gradle/testresources/builderplugin1/build.gradle
When making test bundles for OSGi integration testing, we want the
generated Bundle-SymbolicName value to not conflict with that of the
main artifact. So if the archiveClassifier property is set, we append
it to the archiveBaseName to generate the Bundle-SymbolicName.
=> gradle: Use archiveClassifier in generated Bundle-SymbolicName value

bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessorTest.java, bndtools.core.test/src/simple/pkg/ClassExtendingAbstractExtendingMyParameterizedClass.java, bndtools.core.test/src/simple/pkg/MyParameterizedClass.java
Sometimes you get a "no such method" or "parameter mismatch" because the version of the method that you're trying to call is defined in a superclass that is not on the classpath. This patch will catch such occurrences and suggest adding the missing supertype.
=> [quickfix] Suggestions for overloaded methods

biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java, biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/utils/BundleUtils.java, biz.aQute.tester.test/test/aQute/tester/junit/platform/test/GogoShellTests.java
The current state of the tester is that if a `tester.names` filter is set the tester will run once and exit - the setting of `tester.continuous` is ignored. With this fix, the tester will instead continue to run if `tester.continuous` is set to true. It will respond to bundle updates, but it will only trigger a re-run of tests that match `tester.names`.
I've been wanting this feature when working on large and relatively slow integration tests (eg, `bndtools.core.test`). Often when you're working in a TDD scenario your focus is on a particular test method - you just want to quickly re-run that test while you're working on it to see the results. While working on the quick fix processor I found that the continuous testing really helped overcome the slow startup time of Eclipse, but this was …
=> [junit-platform] Make tester.names dynamic and work in continuous mode

biz.aQute.bnd.maven/bnd.bnd, biz.aQute.tester.test/.gitignore, cnf/ext/central.mvn, cnf/ext/maven-plugin.bnd, maven/pom.xml
The support bundle used versions from the Eclipse m2e for 2018-12.
These versions are newer than that of 3.1.1 which is used as the base
maven version of the maven plugins. So this prevents the maven plugins
from operating on maven version prior to 3.5.3 which is a long way
from 3.1.1. So we change to use the same versions for the support bundle
as for the maven plugins.
Fixes #4327
=> Support bundle for maven must use same versions as maven plugins

biz.aQute.bndlib/src/aQute/bnd/osgi/ActivelyClosingClassLoader.java
- ActivelyClosingClassLoader will try to figure out its own bundle in
OSGi and tries to load classes from there if non can be found before
refering to the system bundle.
=> Improved classloading for Plugins

bndtools.core/src/bndtools/RefreshReposHandler.java
The typo 'Refresing repositories...' (missing h) was fixed.
Signed-off-by: Michael Gerlich <Michael.Gerlich@bruker.com>
=> Fixes #4367: Fixed typo in 'Refresh Repositories' job name.

bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessorTest.java
Will fix the following case:
```java
package my.test.pkg;
class CustomSoftAssertions extends SoftAssertions {
CustomAssert assertThat(Custom actual) {
return proxy(CustomAssert.class, Custom.class, actual);
}
}
```
If assertj-core is not on `-buildpath`, then the above will generate an "Unknown type" for `SoftAssertions` and an "Unknown Method" for `proxy()`. Hovering over `SoftAssertions` would give you the quick fix, but hovering over `proxy()` would not. This is because Eclipse generates a placehold type binding of `my.test.pkg.SoftAssertions` for the missing type, and then the quick fix processor will look specifically in that package for the missing class - not finding it, it won't return any proposals.
This fix will instead search for the bare class name only if the package of the …
=> [quickfix] Handle undefined hierarchy when superclass is not fully-qualified

bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessorTest.java, bndtools.core.test/src/simple/pkg/RecursiveClass.java, bndtools.core.test/src/simple/pkg/RecursiveParameterizedClass.java
Track types that have been examined in a `Set` and skip any if they've already been examined. Main reason is to prevent recursion (fixes #4369).
=> [quickfix] Prevent StackOverflow on recursive types

biz.aQute.bnd.runtime/bnd.bnd, biz.aQute.remote/bnd.bnd
version=latest used the version from Orbit with a qualifier. This
artifact has useless maven metadata and update the dependencies section
of our maven metadata. So we now use the artifact from maven central.
=> deps: Fix gogo.runtime dependency to avoid Orbit version

bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessorTest.java, bndtools.core.test/src/iface/bundle/MyForeignRecursiveClass.java, bndtools.core.test/src/simple/pkg/ClassExtendingForeignRecursiveClass.java, bndtools.core.test/src/simple/pkg/GrandchildOfForeignRecursiveClass.java, bndtools.core.test/src/simple/pkg/RecursiveParameterizedClass.java
When Eclipse is unable to resolve the supertype of a class, it can incorrectly report the supertype binding of the class as being `java.lang.Object`. This fix instead looks at the type declaration's representation of the supertype instead of looking at the binding's representation of the supertype.
=> [quickfix] Better handling for subclasses of recursive classes

biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java
- getBundleDocURL not returns the BUNDLE_DOCURL Manifest header
Signed-off-by: Mark Hoffmann <m.hoffmann@data-in-motion.biz>
=> Fix Domain.getBundleDocURL to return correct manifest header

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java
On windows, entries on `-classpath` instruction can be passed to
`getJarFromName` which may attempt to make a `Glob` from the entry. On
Windows, the entry values can have backslashes which upset regex. So
we change to normalize the entry before passing to `Glob` which will
convert any backslash to forward slash. Since we only match file names
with the `Glob`, a pattern with forward slashes or backslashes wont match
the file name.
We also refactor to move shared logic into a private method.
Closes #4386
=> analyzer: Avoid regex errors on windows

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib.tests/test/test/VerifierTest.java, biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_1_6.properties, biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_1_7.properties, biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_1_8.properties, biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java, biz.aQute.resolve/test/biz/aQute/resolve/BndrunResolveContextTest.java, bndtools.core.test/test.shared.bndrun
We use the EEs system packages, instead of a hard coded "javax." prefix,
to avoid complaining about imports without versions.
Fixes #4388
=> verifier: Update to not complain about versionless imports of system pkg

biz.aQute.resolve/src/biz/aQute/resolve/Bndrun.java, biz.aQute.resolve/test/biz/aQute/resolve/RunResolutionTest.java
As discussed in #4082, the error message when `failOnChanges` is true is misleading.
The `Existing runbundles` line should display the current status in the `*.bndrun` file and not something modified.
Fixes: https://github.com/bndtools/bnd/issues/4082
=> resolve: improve error message

biz.aQute.bndlib.tests/test/test/jpms/JPMSModuleInfoPluginTest.java, biz.aQute.bndlib.tests/test/test/jpms/b/internal/Baz.java, biz.aQute.bndlib.tests/test/test/jpms/b/internal/package-info.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Descriptors.java, biz.aQute.bndlib/src/aQute/bnd/plugin/jpms/JPMSModuleInfoPlugin.java
The wording in
https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.7.26
is unclear about which packages in a module must be listed in the
ModulePackages attribute. It implies that packages which are not
exported, opened, or service implementation providers may not be
included. But advice in https://bugs.openjdk.java.net/browse/JDK-8255854
states that "The intention is that ModulePackages attribute, if present,
must list all packages in the module".
So we update the JPMS module info generation code to make sure all
contained packages in the bundle are listed in the generated
ModulePackages attribute.
Fixes https://github.com/bndtools/bnd/issues/4398
=> jpms: Make sure ModulePackages attribute includes all packages

biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java
The remote launcher did not properly set -runsystempackages
from the exported packages on the -runpath. This worked
on the first prepare, but the prepare did not clear the
class path. A second prepare cleared -runsystempackages
by recalculating it, but then the not cleared class path
prevented the analysis to see if it was exporting 
anything.
=> [remote] Caching of run path

biz.aQute.bnd.gradle/bnd.bnd, biz.aQute.bndlib/src/aQute/bnd/classindex/ClassIndexerAnalyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapReqBuilder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceImpl.java, biz.aQute.repository/src/aQute/bnd/repository/fileset/FileSetRepository.java, biz.aQute.resolve/src/biz/aQute/resolve/AbstractResolveContext.java, biz.aQute.resolve/test/biz/aQute/resolve/BndrunResolveContextTest.java, biz.aQute.resolve/test/biz/aQute/resolve/ResolveTest.java, bndtools.core.test/test.shared.bndrun
Multiple repositories can reference the same resources. For example an index generated in maven can refer to files in the local maven repo and the ImplicitFileSetRepository can also reference them. These repositories are constructed in different ways and they were not consistent. And we ended up with capabilities from each repository which should have been equals (and same hashCode) but were not. Bnd Versions cannot be compared with OSGi Versions. bnd.hashes attributes were not consistently present. Integers cannot be compared with Longs.
So this PR fixes these issues to avoid presenting equivalent capabilities to the resolver which horrible confused it.
Fixes #4382
=> resolve: Avoid presenting duplicate capabilities to the resolver

biz.aQute.bndlib.tests/test/test/CentralCheckVerifierPluginTest.java, biz.aQute.bndlib.tests/test/test/VerifierPluginTest.java, biz.aQute.bndlib/src/aQute/bnd/plugin/maven/CentralCheck.java
We convert the plugin to a VerifierPlugin and enhance the header
checks. The verifier plugin assumes that the proper POM is created from
the manifest headers.
The test verifies warnings are emitted when headers are missing and
also does some checks on the generated POMs.
Fixes https://github.com/bndtools/bnd/issues/1479
=> maven central check: Improve checking and add tests

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
The Repository spec requires the return Map value of findProviders to
have each input requirement as a key. In some cases, an empty map was
incorrectly returned.
Fixes https://github.com/bndtools/bnd/issues/4416
=> repository: Fix findProviders result to include input requirements

.github/workflows/cibuild.yml, bndtools.core.test/bnd.bnd, bndtools.core.test/build.gradle
This task is annoyingly flaky and breaks many CI builds. Until we can
stabilize this test, we remove it from CI execution.
See #4253
=> Disable bndtools.core.test testOSGi task in CI build

biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceImpl.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java, biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java
Since non-bundle artifacts may be present in repositories, we want to
filter them from the result when looking for bundles under the
assumption there is little value in including non-bundles in a
resolution result.
Fixes #4380
=> Filter out capabilities from non-bundle type resources

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/MarkerSupport.java
Without this fix, Bndtools generates an NPE during building if the cnf project is missing and continues to fail building even after the cnf project is added. This fixes #4401.
As a side effect, also introduces an error marker if the Bnd project is not inside the Bnd workspace. This fixes #4203.
This seems to work in my testing and not to break anything else, but it's hard to be sure without a decent set of regression tests. It would be good for us to smoke-test it on dev for a while before release.
=> [bndtools] Gracefully handle missing cnf

biz.aQute.bndlib/src/aQute/bnd/build/ProjectTracker.java
The project tracker (suddenly?) needs bnd files
to be present in the project. However, if you
create this file, the error is not cleared until the project tracker updates again.
This patch will force an update if the bnd file exist but it is not in the project tracker.
=> [projecttracker] Missing bnd files

bndtools.core/src/org/bndtools/core/resolve/ResolveOperation.java
The model properties are not properly resolved for the special here
`${.}` macro. Using the model Project as the resolve properties is
consistent with all other callers to RunResolution.resolve.
Fixes https://github.com/bndtools/bnd/issues/4396
=> bndtools: Use model Project as the properties for resolving

biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java, bndtools.core/src/org/bndtools/core/resolve/ResolveOperation.java
Before returning the model properties, we resolve the special
`${.}` here macro.
Fixes https://github.com/bndtools/bnd/issues/4396
=> bndtools: Resolve special `${.}` here macro in BndEditModel properties

biz.aQute.bnd.test/src/aQute/bnd/test/XmlTester.java, biz.aQute.bndlib.tests/test/test/component/DSAnnotationTest.java, biz.aQute.bndlib.tests/test/test/component/PermissionGeneratorTest.java, biz.aQute.bndlib.tests/test/test/metatype/SpecMetatypeTest.java, biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
If the factory component creates components which are services, also
provide the osgi.service capability for the service in addition to the
ComponentFactory service.
Fixes #4429
=> Emit service capability for services of factory components

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
- The unused packages did not report the proper 
instruction name used and it
- When a wildcard was used, it reported zero matches
Finds the proper header and wildcards are removed from
the unused packages for inclusion
=> [build] Unused packages

biz.aQute.bndlib.tests/test/test/BndEditModelTest.java, biz.aQute.bndlib.tests/testresources/standalone.bndrun, biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java, biz.aQute.bndlib/src/aQute/bnd/build/package-info.java, biz.aQute.bndlib/src/aQute/bnd/junit/package-info.java, biz.aQute.bndlib/src/aQute/bnd/maven/package-info.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/package-info.java, biz.aQute.bndlib/src/aQute/bnd/print/package-info.java, biz.aQute.bndlib/src/aQute/bnd/service/generate/package-info.java, bndtools.core/src/bndtools/editor/completion/BndHover.java
The macro expansion was not handling the expansion
of ${.} and the base correctly because the
BndEditModel did not properly set it.
I cleaned up the getProperties() method to be in
line with the use of inheritance of Processors. 
This made one test case fail. 
The BndEdit model has maintains a delta list for
the editor and a set of properties. In the previous
implementation of the getProperties() method the
returned Processor had these properties + the delta
as its properties. However, it also inherited from
the parent processor, which had the originals, which
by definition are supposed to be the same.
I removed this redundancy because I did not like the
shadowing and it made the code simpler. So
the untouched properties are now directly inherited from
the BndEditModel's project or …
=> [hover] BndEditor macro expansion

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
the gpg command can be extended and replaced, by putting a property gpg somewhere in the workspace. Till now, it was not possible to use macros and variables here. This commit chances this.
=> allow the use of macros in the gpg property

biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java, docs/_instructions/buildpath.md, docs/_instructions/maven-dependencies.md, docs/_instructions/maven-scope.md
Support for these instructions was added around 4.2.0 but never properly documented.
Fixes #4438
=> docs: Add documentation for -maven-dependencies and -maven-scope

.github/scripts/rebuild.sh, .gradle-wrapper/gradle-wrapper.properties, biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/build.gradle, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/FileSetRepositoryConvention.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Index.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBndPlugin.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestHelper.groovy, biz.aQute.bnd.gradle/testresources/builderplugin1/build.gradle, biz.aQute.bnd.gradle/testresources/indexplugin1/build.gradle
We change to avoid using `ProjectLayout.configurableFiles` which Gradle
has announced will be removed in Gradle 7.0.
Fixes https://github.com/bndtools/bnd/issues/4451
=> gradle: Avoid use of deprecated method to be removed in Gradle 7.0

.github/workflows/cibuild.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docsbuild.yml, aQute.libg/src/aQute/lib/link/Link.java, aQute.libg/src/aQute/libg/filelock/DirectoryLock.java, biz.aQute.bnd/src/aQute/bnd/main/RemoteCommand.java, biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bndlib/src/aQute/bnd/http/ProgressWrappingStream.java, biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java, biz.aQute.remote/src/aQute/remote/util/Link.java, biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2IndexerTest.java, biz.aQute.resolve/src/biz/aQute/resolve/ResolveProcess.java, biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/JUnitEclipseListener.java, biz.aQute.tester/src/aQute/junit/JUnitEclipseReport.java, biz.aQute.tester/src/aQute/junit/JunitXmlReport.java, bndtools.builder/src/org/bndtools/builder/BuildLogger.java
We avoid currentTimeMillis as it can change as the system clock is
changed. nanoTime only changes with the advancement of time.
=> Use nanoTime values for timeout computations

biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceRepositoryDynamic.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/MainClassNamespace.java
The Main-Class attribute was not trimmed. This
caused extraneous spaces to be at the end sometimes.
This trims the Main-Class and Bundle-Version now.
Also unrolled a stream loop because the check for
capabilities was 20 levels deep in a stream. This makes it impossible to single step or debug.
Unless there  is a demonstrable _and_ significant speed gain we should stop replacing plain old loops by streaming. Not only because it is hard to debug, it also looses the earlier context when you want to report something. Maybe if Java had true closures and no checked exception it might have been useful.
=> [resource] Main-Class attribute not trimmed

biz.aQute.bndlib.tests/test/test/ProcessorTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/OSInformation.java
Fixes #4466
Signed-off-by: Kees van Ginkel <kees@vanginkels.com>
=> 4466 recognise Apple silicon M1 processer as aarch64

bndtools.core.services/src/org/bndtools/core/editors/quickfix/AddBundleCompletionProposal.java, bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/AbstractBuildpathQuickFixProcessorTest.java, bndtools.core/src/bndtools/preferences/BndPreferences.java, bndtools.core/src/bndtools/preferences/QuickFixVersioning.java, bndtools.core/src/bndtools/preferences/ui/BndPreferencePage.java, bndtools.core/src/bndtools/preferences/ui/Messages.java, bndtools.core/src/bndtools/preferences/ui/messages.properties
Includes the following changes to quickfix handling:
* BSNs are only listed once even if multiple versions are available
* There is a new Bndtools preference that specifies the version handling policy:
** No version attribute (lowest version)
** "version=latest" (latest version)
* `AddBundleCompletionProposal` will add the appropriate version attribute (or omit
it entirely) according to the setting of that preference.
Fixes #4410.
=> [quickfix] Configurable version handling

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
The test task was already dependent on the -buildpath and -testpath
through the test task's dependencies on the compileJava and
compileTestJava tasks, respectively. We further ensure that the test
task is also dependent on the jars of any additional projects specified
through -dependson.
So like Eclipse, we now ensure all dependency jars (-buildpath,
-testpath, and -dependson) are built before the test task runs.
Fixes #4484
=> gradle: Add -dependson to test task inputs

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bndlib.tests/build.gradle, bndtools.core.test/build.gradle
Slight refactoring of the gradle task registration code for the bndrun-based tasks.
With the Bnd Gradle plugin change to include -dependson dependencies for the test task, we remove an explicit dependency on the jar task which was made for the same purpose.
Since we don't run the `:bndtools.core.test:testOSGi` task in the CI build, I removed the support for ignoring failures which did not really work as expected for the specific failure issues in the test execution.
=> Some minor fixes

biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, build.gradle
@juergen-albert:
> I stumbled upon this issue as I had -include with a http source in one of my cnf/ext files. The moment the include happened, we internally used getPlugin(HttpClient.class). This initialized the plugins with the properties that has been read up to this point. After all ext files have been loaded, the plugin definitions that came after this would not have been recognized.
Closes #4499 
We also fix the workspace to load the `cnf/ext/*.bnd` files in sorted order rather than however they are presented by the file system.
=> Clear plugins on properties changed

biz.aQute.tester.test/.gitignore, biz.aQute.tester.test/test/aQute/tester/junit/platform/test/ActivatorJUnitPlatformTest.java, biz.aQute.tester.test/test/aQute/tester/junit/platform/test/GogoShellTests.java, biz.aQute.tester.test/test/aQute/tester/test/ActivatorTest.java, biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorCommonTest.java, biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorTest.java, biz.aQute.tester/src/aQute/junit/constants/TesterConstants.java
We also fix javadoc for TESTER_DIR to state the correct default.
=> tester: Use standard location for test reports

biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
The documentation indicates the files are to be processed in
alphabetical order. However, File.compareTo uses a system dependent
ordering. On Windows, it is case-insensitive. On most Linux file systems
it would be case-sensitive. For consistency across all platforms, we
provide our own case-sensitive comparator to sort the file names. We
don't use case-insensitive since we could still get different orderings
based upon the order a case-sensitive file system returned case-variant
file names since the sort algorithm is stable.
=> workspace: Process cnf/ext/*.bnd files in sorted case-sensitive order

bndtools.core.test/src/bndtools/core/test/editors/quickfix/AbstractBuildpathQuickFixProcessorTest.java, bndtools.core.test/src/bndtools/core/test/utils/WorkbenchExtension.java
@bjhargrave  reported that simpleReference_toWorkspaceClass_suggestsBundles() was failing intermittently. I was able to reproduce in my workspace. Doing a clean before building seemed to make it pass.
When I tried it in my own workspace I had the same problem both in Gradle and through Bndtools. It would fail very consistently. When I tried to hook up the debugger and set a breakpoint on the test in question, it would pass consistently even with no other code changes.
I suspected a race condition: `local-proj` was not finished building/being indexed before the code was run. Added a wait in `proposalsFor()` (just before building the AST that generates the `IProblem` markers) to make sure that building was finished (so that the indexing would be finished) before running the test. This seems …
=> [quickfix] Test to wait for build to complete before running proposals

aQute.libg/src/aQute/lib/json/Decoder.java, aQute.libg/src/aQute/lib/json/Encoder.java, aQute.libg/src/aQute/libg/cafs/CAFS.java, biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java, biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib.tests/test/test/JarSignerTest.java, biz.aQute.bndlib.tests/test/test/ManifestTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java, biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java
The big fix here is that the `-digests` instruction's value is now actually used. Previously the value of the `-digests` instruction was ignored but using the instruction caused the default digest algorithms to be used.
There was also a bug in `ProjectLauncherImpl.executable()` which used the invalid "MD-5" digest algorithm name when `-digests` was not set. The bug above which ignored set digest values meant the invalid "MD-5" digest algorithm name was silently ignored. With the above bug fixed, using an older launcher with a newer bndlib will result in an `java.security.NoSuchAlgorithmException: MD-5 MessageDigest not available` exception unless `-digests` is set to a valid value.
=> Fixes to digest algorithms

biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/TestOSGi.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestTestOSGiTask.groovy, biz.aQute.bnd.gradle/testresources/testosgitask4/build.gradle
We have a use-case for being able to rename the `TestOSGi` task's test result directory, if necessary. So update the task to use Gradle's modern `DirectoryProperty` API.
=> Create a lazy DirectoryProperty for TestOSGi results directory.

aQute.libg/src/aQute/lib/zip/ZipUtil.java, aQute.libg/src/aQute/lib/zip/package-info.java, biz.aQute.bnd.gradle/build.gradle, biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib.tests/test/test/ResourcesTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Resource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ZipResource.java, biz.aQute.bndlib/src/aQute/bnd/print/JarPrinter.java, bndtools.core.test/test.shared.bndrun
ZIP extra fields are structured binary data. See section 4.5 of the
[ZIP File Format Specification][1]. We had incorrectly just placed UTF-8
encoded strings in the extra field and assumed that, when reading zip
files, we could decode the extra field as a UTF-8 encoded String.
However, the structured binary data of a ZIP extra field cannot be
safely decoded as UTF-8 data into a String and then re-encoded into
UTF-8 data when writing a ZIP file. This resulted in corrupting the
ZIP extra fields when wrapping a jar. It also means that use of the
"extra" attribute on certain instructions caused malformed ZIP extra
fields to be written to jars.
We fix Bnd to properly encode ZIP extra field information into Strings.
We do this to avoid making a breaking major change to the Resource API
where the …
=> Properly handle ZIP extra fields

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
Per request from @tjwatson, we now allow the resolution directive on
java imports to support optional resolution of a java import. This is
interesting to the [Apache Felix Atomos project][1].
[1]: https://github.com/apache/felix-atomos
=> analyzer: Allow resolution directive on java imports

bndtools.core/src/bndtools/launch/JUnitShortcut.java
I somehow produced the case, that Eclipse gave me the following Exception, when I tried to call Run as -> BND OSGi Testlauncher (JUnit):
```
java.lang.NullPointerException
at bndtools.launch.JUnitShortcut.isJUnit4(JUnitShortcut.java:233)
at bndtools.launch.JUnitShortcut.isTestable(JUnitShortcut.java:216)
at bndtools.launch.JUnitShortcut.gatherTests(JUnitShortcut.java:155)
at bndtools.launch.JUnitShortcut.gatherTests(JUnitShortcut.java:179)
at bndtools.launch.JUnitShortcut.gatherTests(JUnitShortcut.java:179)
at bndtools.launch.JUnitShortcut.gatherTests(JUnitShortcut.java:179)
at bndtools.launch.JUnitShortcut.gatherTests(JUnitShortcut.java:179)
at bndtools.launch.JUnitShortcut.customise(JUnitShortcut.java:129)
at bndtools.launch.JUnitShortcut.launchJavaElements(JUnitShortcut.java:91)
at …
```
=> Fixes possible NPE, if e.g. the check reaches java.lang.Object

aQute.libg/src/aQute/lib/zip/ZipUtil.java, aQute.libg/test/aQute/lib/zip/ZipUtilTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
The original method just always added the record for the "extra"
attribute. This could be a problem in wrapping an existing bundle.
So we now replace any existing bnd record in the extra field.
We also add some unit tests for the utility methods.
=> zip: Fix method to replace an existing bnd header in extra field

bndtools.core/src/org/bndtools/core/resolve/ResolutionProgressCallback.java
The initial implementation of the resolver progress would allocation 1% of the remaining ticks for each new requirement. I noticed that on any resolve of sufficient complexity that the progress bar was actually useful, this still resulted in the progress getting to 100% very quickly even while there was still a fair bit of work to do. Increasing this to 0.1% on each requirement make the progress bar a bit more useful.
=> [resolver] Increase number of ticks in resolver progress

bndtools.core/_plugin.xml, bndtools.core/src/bndtools/launch/JUnitShortcut.java
Fixes #4524:
* Context-sensitive launch for JUnit was not available unless junit-platform-commons was on the path or JUnit 4 was on the path, even if you are using Jupiter annotations.
* Context-sensitive launch for test methods with parameters.
* Context-sensitive launch works better with various different types of Jupiter test class.
=> [bndtools test] JUnit launching fixes

biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java
The check appears to occasionally contain an additional number of digits
[System Bundle]
Expecting:
"Id    Levl State Modified      Location
0     # Found bundle without a bsn [7], ignoring
0   ACTIV <>            System Bundle
1     10  ACTIV 201810132223  file:/home/runner/work/bnd/bnd/maven/target/m2/org/apache/felix/org.apache.felix.scr/2.1.12/org.apache.felix.scr-2.1.12.jar
2     11  ACTIV 201810132026  file:/home/runner/work/bnd/bnd/maven/target/m2/org/apache/felix/org.apache.felix.configadmin/1.9.10/org.apache.felix.configadmin-1.9.10.jar
3     12  ACTIV 202009131314  file:/home/runner/work/bnd/bnd/maven/target/m2/org/junit/platform/junit-platform-commons/1.7.0/junit-platform-commons-1.7.0.jar
4     12  ACTIV 202009131314 …
=> [AlsoLauncherTest] fix failure

biz.aQute.bndlib.tests/test/aQute/bnd/build/repo/WorkspaceRepositoryTest.java, biz.aQute.bndlib.tests/testresources/build-repo/ws/p1/bnd.bnd, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceClassIndex.java, docs/_instructions/dsannotations.md, docs/_macros/findproviders.md
The current findproviders macro can be used in bndrun files. If used in
a bnd file, it causes a circular build because it wants to search the
projects as well. This version of the macro can be used to exclude the
workspace.
Closes #4494.
=> Extend findproviders macro to select repositories to search

.github/workflows/cibuild.yml, .github/workflows/codeql-analysis.yml, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-export-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-bnd/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-deploy-no-dist-mgmt/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-deploy/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-snapshot/pom.xml, maven/bnd-reporter-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-run-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/pom.xml
We remove some encoding warnings and configure maven to avoid connection resets in the GitHub Actions builds.
=> Maven build fixes

biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2IndexerTest.java, biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2RepositoryTest.java
This avoids any issues with the contents of update-snapshot changing
and breaking the tests.
=> p2: Switch test to use a dedicated virtual p2 repo

docs/_chapters/250-resolving.md, docs/snapshot.html
- added a new tab "About"
- this tab contains a new section with description and explanation about the tool
- mention and link the Snapshot Viewer in the bnd manual / [resolving chapter](https://bnd.bndtools.org/chapters/250-resolving.html) ... Not sure this is the ideal place, but since it was about debugging, I think it fits.
Preview:
=> Snapshot viewer improvements

biz.aQute.bndlib.tests/test/test/ClazzTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Descriptors.java, docs/_macros/classes.md
`STATIC` and `INNER` are opposites.
Documentation for the classes macro is also updated to document some query types that were previously undocumented.
=> Update classes macro to add STATIC and INNER queries

aQute.libg/src/aQute/lib/strings/Strings.java, biz.aQute.bnd.runtime/test/aQute/bnd/runtime/snapshot/SnapshotTest.java, biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/BeforeAfterTest.java, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/FO.java, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/LaunchpadConfigurationTest.java, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/LaunchpadRunnerBasicTest.java, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/Manual.java, biz.aQute.launchpad/test/aQute/launchpad/LaunchpadTest.java, demo/bnd.bnd
Some testing fixes.
Some tests are sensitive to the versions of certain bundles. Using later versions of the
bundles can cause the tests to fail. Later versions of Felix SCR no
longer provide DS packages and the OSGi DS api bundle requires Core R7.
The Felix framework used is Core R6 and the launchpad API uses Core R6.
=> Test fixes

biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, biz.aQute.resolve/src/biz/aQute/resolve/ResolveProcess.java, biz.aQute.resolve/test/biz/aQute/resolve/RunResolutionTest.java, docs/_instructions/resolve.excludesystem.md
I had a use case where I also needed access to
the system resource. However, this is unfortunately
explicitly removed from the result.
This introduces a instruction -resolve.excludesystem
that by default excludes it but can be set to false
to include it in the result.
=> [resolve] Allow inclusion of the system resource

biz.aQute.bnd.gradle/build.gradle, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestHelper.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestIndexTask.groovy, biz.aQute.bnd.gradle/testresources/indexplugin1/build.gradle, bndtools.core/bndtools.cocoa.macosx.x86_64.bndrun, bndtools.core/bndtools.gtk.linux.x86_64.bndrun, bndtools.core/bndtools.shared.bndrun, bndtools.core/bndtools.win32.x86_64.bndrun, build.gradle, maven/pom.xml
Java 16  is now released. But Java 16 requires Gradle 7. Gradle 7 now uses Groovy 3 for Java 16 support. Groovy 3 requires a different version of Spock for testing.
So lots of changes being made. So this PR makes preparation for adding a  Java 16 build to the CI once Gradle 7 is released. This has been tested on a Gradle 7 nightly build `7.0-20210322000034+0000`.
=> Prepare for Java 16 and Gradle 7

aQute.libg/src/aQute/libg/map/package-info.java
All packages in aQute.libg are exported via the `-exportcontents`
instruction in the bnd file. The Export annotation caused Bnd to emit
a duplicate export warning.
=> lib: Fix bnd duplicate export warning

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/package-info.java, biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java, docs/_plugins/pomrepo.md
At the moment the PomRepository  can only read a maven-revision, a G:A:V without Type and Classifier.
When reading an Archive instead of an Revision , like BndPomRepository does, this could be fixed.
=> PomRepository should read maven GAV with Type and Classifier

biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPluginConvention.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndUtils.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Index.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/PropertiesWrapper.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Resolve.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/TestOSGi.groovy
Refactor implementation to work with Groovy 2 and 3
When we update the build's gradlew to 7.0, we will be building the
Bnd Gradle plugins with Groovy 3 but we still need to make sure they
run on older Gradle versions which use Groovy 2.
This necessitates some restructuring of the code to avoid some
unnecessary use of closures and to avoid references to private fields
inside the remaining closures. Groovy 2 and 3 seem to handle this
in a different and incompatible way, so we just avoid trying to do it
by copying the private field into a local variable which the closure
can capture.
=> Gradle 7 fixes

bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/AbstractBuildpathQuickFixProcessorTest.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessor_WithSimpleOnBuildpath_Test.java, bndtools.core.test/src/simple/pkg/ClassWithMethodReturningBoundFromAnotherBundle.java
Handles case where a type bound doesn't pass because of a missing common supertype.
Based on a real-world case that I encountered recently.
=> [quickfix] Handle bound mismatches

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/testresources/workspaceplugin1/test.simple/build.gradle
Since gradle can support compiling with different versions of java than
the version running gradle, we need to check the java toolchain, if one
is configured, to decide if it is safe to pass the --release flag to
javac.
=> gradle: Use the configured java toolchain to decide to use --release

.github/workflows/cibuild.yml, bndtools.core.test/src/bndtools/core/test/editors/quickfix/AbstractBuildpathQuickFixProcessorTest.java, bndtools.core.test/src/bndtools/core/test/utils/TaskUtils.java, bndtools.core.test/src/bndtools/core/test/utils/WorkspaceImporter.java
In order to try and overcome race conditions at startup, put in a callback that causes the tester to wait for the Workspace to be ready before proceeding.
This is a bit of a hack, but it seems to stabilise the tests - I ran it in my own CI instance on GitHub a few times and it seems to have succeeded on all platforms each time.
=> [bndtools test] Wait for cnf workspace before proceeding

biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java
If the header value does not start with `%`, then return the value
instead of incorrectly returning null.
We also fix to only translate when the first char is `%` rather than
any char being `%`.
Fixes https://github.com/bndtools/bnd/issues/4619
=> bndlib: Fix handling of manifest header value localization

bndtools.builder/src/org/bndtools/builder/validate/ProjectPathsValidator.java
Checks if the folder has at least one child
Fixes #4624
=> [path validation] Warning about .classpath when testsrc not present

.github/workflows/cibuild.yml
The previous change caused all the jobs to attempt to publish.
=> ci: Only publish from java 8 build

.github/workflows/cibuild.yml
This reverts commit 8bfccf54415b9f56bc74189c66c4597fc8599e24.
:bndtools.core.test:testOSGi is still intermittently failing in the CI build.
=> Revert "bndtools.core.test: Re-enable in CI build"

aQute.libg/src/aQute/lib/unmodifiable/ImmutableMap.java, aQute.libg/src/aQute/lib/unmodifiable/ImmutableSet.java, aQute.libg/test/aQute/lib/unmodifiable/MapsTest.java, aQute.libg/test/aQute/lib/unmodifiable/SetsTest.java
We change to use a short array instead of an int array to hold the hash
bucket. This limits the size of the set or map to 2^16-1 entries (since
we use unsigned short values) but that is plenty large.
Tests are added to verify the max size and whether an exception is
thrown if exceeded.
=> unmodifiable: Reduce storage use by one third for set and map

bndtools.builder/src/org/bndtools/builder/BndSourceGenerateCompilationParticipant.java, bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/BndtoolsDynamicReferenceProvider.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.core.services/src/org/bndtools/core/editors/quickfix/AddBundleCompletionProposal.java, bndtools.core/src/bndtools/central/Auxiliary.java, bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java, bndtools.core/src/bndtools/central/RepositoryUtils.java, bndtools.core/src/bndtools/central/sync/WorkspaceSynchronizer.java
Update bndCall to support after lock actions. bndCall will supply the operation an object to register an after lock
action. When the operation completes and the bnd lock is released,
bndCall will call each after action in order. This enables work to be
done after the bnd lock is released when that work does not need to be
done while holding the bnd lock. This can avoid deadlocks.
Making this part of bndCall makes it a common feature that callers can
use without rolling their own after lock processing.
=> bndCall after lock actions

bndtools.core/src/bndtools/central/Auxiliary.java
My previous fix broke Auxiliary which means Bndtools could not load any
repository plugins from the biz.aQute.repository bundle. Which meant
Bndtools could not build anything. Ooops.
=> bndtools.core: Fix broken Auxiliary

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy
These folders, particularly buildSrc, have special meaning to gradle.
So when adding folders from the rootDir, do not include these folders
by default.
Fixes https://github.com/bndtools/bnd/issues/4668
=> gradle: Don't include buildSrc or gradle folders by default

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy, biz.aQute.bnd.util/src/aQute/bnd/memoize/CloseableMemoize.java, biz.aQute.bnd.util/src/aQute/bnd/memoize/CloseableMemoizingSupplier.java, biz.aQute.bnd.util/src/aQute/bnd/memoize/Memoize.java, biz.aQute.bnd.util/src/aQute/bnd/memoize/MemoizingSupplier.java, biz.aQute.bnd.util/src/aQute/bnd/memoize/PredicateMemoizingSupplier.java, biz.aQute.bnd.util/src/aQute/bnd/memoize/ReferenceMemoizingSupplier.java, biz.aQute.bnd.util/src/aQute/bnd/memoize/RefreshingMemoizingSupplier.java, biz.aQute.bnd.util/test/aQute/bnd/memoize/MemoizeTest.java, biz.aQute.bndlib.tests/test/test/ExtensionsTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/junit/package-info.java, biz.aQute.bndlib/src/aQute/bnd/maven/package-info.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/package-info.java, biz.aQute.bndlib/src/aQute/bnd/print/package-info.java, biz.aQute.bndlib/src/aQute/bnd/service/generate/package-info.java, build.gradle
Refactor plugin support into the PluginsContainer class
The prior logic, in its attempt to avoid deadlocks, could expose a
child processor to zero parent plugins. So this meant that
creating or refreshing a workspace also required the caller to force the
workspace to load its plugins right away. Otherwise, when each
project initialized its plugins, they could attempt to access their
parent's plugins across multiple threads (e.g. gradle parallel build)
and all but one project could see the workspace as having zero plugins.
This has occurred in the OSGi build since it builds bnd plugins in cnf
and then refreshes the workspace to include the just built plugins.
This refactoring addresses this issue at the cost of some breaking API
changes to rarely overridden protected methods due to the
use …
=> PluginsContainer

biz.aQute.bndlib/src/aQute/bnd/maven/MavenCapability.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java, biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java, bndtools.m2e/src/bndtools/m2e/MavenWorkspaceRepository.java
Replacement for and closes #4674.
When an artifact has an extension (other than `jar`) and/or a classifier, the pseudo BSN must include these.
=> Handle pseudo BSNs in BndPomRepository as in MavenBndRepository

bndtools.core.services/bnd.bnd, bndtools.core.services/src/org/bndtools/core/sync/About.java, bndtools.core.services/src/org/bndtools/core/sync/SynchronizeWorkspaceWithEclipse.java, bndtools.core/src/bndtools/central/sync/WorkspaceSynchronizer.java, bndtools.core/src/bndtools/central/sync/package-info.java
Fixes #4695.
Does the following:
* Moved the sync component into `bndtools.core.services`. Doesn't change the functionality, but makes it more convenient to do live coding/debugging as the `bndtools.core.services` bundle can be restarted while Eclipse is still running.
* Made sure that the event listener callback is de-registered in `@Deactivate` (only important because of the previous point).
* Removed code that disables the autobuild.
* Removed code that does the refresh and build.
* Added cancellation checks to the bndCall `after` callbacks` and short-circuit their execution if it has been cancelled..
There still seems to be an issue on  newly-loaded workspace. as you get a "resource out of sync" problem if (eg) you try delete a project before refreshing it. It is possible I might need …
=> [sync] Remove rebuild from workspace sync

bndtools.core.services/src/org/bndtools/core/sync/About.java, bndtools.core/src/bndtools/central/sync/About.java, bndtools.core/src/bndtools/central/sync/SynchronizeWorkspaceWithEclipse.java, bndtools.core/src/bndtools/central/sync/WorkspaceSynchronizer.java, bndtools.core/src/bndtools/central/sync/package-info.java, bndtools.core/src/org/bndtools/core/ui/OnDisplayThread.java
Project creation failed because bndtools code created a new Eclipse project but this interacted badly with the synchronizer.
The bndtools project creation needs
to use the synchronization facilities. This makes the whole process a lot simpler and more reliable. Bndtools should create the project in the workspace and the synchronization then automatically creates the Eclipse projects.
However, this is non-trivial since it requires a new dialog for the bndtools project creation (which can then include the template selection).
So this patch disables the auto sync feature until this is done.
This patch also moves the synchronizer back in the core. This is a core feature that other parts of the core rely on. Imho bundles should be composed of cohesive functions; grouping based on non-cohesive …
=> [sync] Project creation

biz.aQute.bndlib.tests/test/test/WorkspaceTest.java, biz.aQute.bndlib.tests/testresources/w o r k s p a c e/cnf/build.bnd, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
There was a test, that looked exactly for what I want to change. This suggests, that it was intended behaviour and might break things. 
@njbartlett as the Test seems to have originated from you, can you comment on it?
Fixes #4667
=> Use extension name as suffix on include of bnd file

biz.aQute.bndlib.tests/test/test/component/DSAnnotationTest.java, biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java
This is to make sure SCR properly handles target property precedence
for DS 1.5.
=> ds 1.5: Mark component as 1.5 if it used satisfying condition target

biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/build.gradle, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPluginConvention.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPluginExtension.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndUtils.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/TestOSGi.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestHelper.groovy, bndtools.core.test/build.gradle, build.gradle, dist/build.gradle, maven/build.gradle, org.bndtools.p2/build.gradle
Gradle 7.1 is deprecating things including conventions and so we must react.
This is the first part which covers BndPlugin.
As a consequence, the minimum supported Gradle version is now 6.1 (from 5.3).
See #4699.
=> Gradle plugin updates

bndtools.utils/src/org/bndtools/utils/workspace/FileUtils.java
#4704 would have been easier to debug in the first instance if the error message from `mkdirs()` had been slightly more forthcoming with information. This commit fixes that.
=> [bndtools.utils] Improve diagnostics for mkdirs()

biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/AbstractBndrun.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/FileSetRepositoryConvention.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Index.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Resolve.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/TestOSGi.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestHelper.groovy, biz.aQute.bnd.gradle/testresources/exporttask1/build.gradle, biz.aQute.bnd.gradle/testresources/resolvetask1/build.gradle, biz.aQute.bnd.gradle/testresources/runtask1/build.gradle, biz.aQute.bnd.gradle/testresources/testosgitask1/build.gradle, biz.aQute.bnd.gradle/testresources/testosgitask2/build.gradle
This raises the minimum Gradle version to 6.7.
Previously deprecated methods and some obsolete setters are removed.
=> Add javaLauncher property to Gradle Bndrun and TestOSGi tasks

biz.aQute.bnd.gradle/build.gradle, biz.aQute.bnd.gradle/publish.gradle, build.gradle, dist/build.gradle, maven/build.gradle, org.bndtools.p2/build.gradle, settings.gradle
We use the JavaLauncher from Gradle 6.7 to always use Java 8 to
run the p2 code for our update site build. This means these tasks
can now run on any java for the gradle build as long as gradle can
find a Java 8 runtime.
=> Build p2 java8

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/testresources/workspaceplugin1/test.simple/build.gradle
Since we moved the minimum supported Gradle version to 6.7, we can
remove conditional code for older versions.
=> gradle: Remove conditional code for older Gradle version

bndtools.core.test/src/bndtools/core/test/editors/quickfix/AbstractBuildpathQuickFixProcessorTest.java, bndtools.core.test/src/bndtools/core/test/utils/LoggingProgressMonitor.java, bndtools.core.test/src/bndtools/core/test/utils/TaskUtils.java, bndtools.core.test/src/bndtools/core/test/utils/WorkspaceImporter.java
Introduces an IProgressMonitor implementation that logs output. Replaces the misguided synchronously() method and provides
more detailed diagnostics.
=> [quickfix test] Use logging progress monitor

biz.aQute.bnd.ant/src/aQute/bnd/ant/BaseTask.java, biz.aQute.bnd.ant/src/aQute/bnd/ant/BndTask.java, biz.aQute.bnd.ant/src/aQute/bnd/ant/DeployTask.java, biz.aQute.bnd.ant/src/aQute/bnd/ant/PackageTask.java, biz.aQute.bnd.ant/src/aQute/bnd/ant/PrepareTask.java, biz.aQute.bnd.ant/src/aQute/bnd/ant/ProjectTask.java, biz.aQute.bnd.ant/src/aQute/bnd/ant/ReleaseTask.java, biz.aQute.bnd.ant/src/aQute/bnd/ant/TestTask.java, biz.aQute.bnd.ant/src/aQute/bnd/ant/package-info.java
We centralize the call to the Bnd Project object for a basedir and
check the inputs and outputs for validity.
Fixes https://github.com/bndtools/bnd/issues/4724
=> ant: Handle when the basedir does not represent a Bnd project

bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java, bndtools.core.test/fodder.simple.bnd, bndtools.core.test/src/bndtools/core/test/editors/quickfix/AbstractBuildpathQuickFixProcessorTest.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessor_WithSimpleOnBuildpath_Test.java, bndtools.core.test/src/iface/embedded/Embedded.java, bndtools.core.test/src/iface/embedded/package-info.java
Sometimes you have bundles on your buildpath that embed (but don't export) classes that are part of the API of another bundle (the bndtools workspace itself does this). This results in "Discouraged Access"/non-API warnings. Adding a bundle that actually exports that API fixes the warning.
=> [quickfix] Add suggestions for "Discouraged Access"

bndtools.core.test/bnd.bnd, bndtools.core.test/test.cocoa.macosx.x86_64.bndrun, bndtools.core.test/test.gtk.linux.x86_64.bndrun, bndtools.core.test/test.shared.bndrun, bndtools.core.test/test.win32.x86_64.bndrun, cnf/ext/central.mvn, cnf/ext/junit.bnd
This also requires us to bump the version of JUnit Platform and friends so it's not the same version as Eclipse. That's ok because we're not testing Eclipse's testing functionality, so it doesn't matter if our test instance is not using the same version of JUnit that Eclipse 2020-06 is using.
Fixes #4766.
=> [quickfix test] Bump AssertJ

bndtools.core.test/test.win32.x86_64.bndrun
Forgot to bump the AssertJ version in the win32 resolved file.
=> [quickfix test] Bump AssertJ properly

biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java
Sometimes the engines will fail cryptically if the annotations can't be resolved for some reason (eg, reference an unresolvable extension class).
Fixes #4766.
=> [junit-platform] Resolve annotations in tryToResolveTestClass()

bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/AbstractBuildpathQuickFixProcessorTest.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessor_WithSimpleOnBuildpath_Test.java, bndtools.core.test/src/iface/bundle/MyForeignException.java, bndtools.core.test/src/simple/pkg/ClassThrowingExceptionExtendingExceptionFromAnotherBundle.java, bndtools.core.test/src/simple/pkg/ExceptionIndirectlyExtendingExceptionFromAnotherBundle.java, bndtools.core.test/src/simple/pkg/MyLocalException.java
This error can cause if one of the exception's superclasses is not on the classpath and so the compiler cannot tell that it is an exception.
=> [quickfix] Suggestions for CannotThrowType and UnhandledException

bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessor_WithSimpleOnBuildpath_Test.java, bndtools.core.test/src/simple/pkg/ClassThrowingExceptionExtendingExceptionFromAnotherBundle.java, bndtools.core.test/src/simple/pkg/ClassThrowingExceptionExtendingForeignException.java, bndtools.core.test/src/simple/pkg/ExceptionIndirectlyExtendingExceptionFromAnotherBundle.java, bndtools.core.test/src/simple/pkg/ExceptionIndirectlyExtendingForeignException.java
Constructor invocation has a different grammatical structure to standard method invocation so the previous PR #4772 did not handle those cases. This PR addresses those cases too.
=> [quickfix] Support constructor invocation throwing unhandled exceptions

biz.aQute.bndlib/src/aQute/bnd/build/ProjectGenerate.java, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceExternalPluginHandler.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java
- Multiple clauses using the same output conflicted.
Changed to prepare the steps so directory clean happens
before all steps. 
- Using plain maven JARs had a cast problem with versions.
Now supports bnd.info namespace for versions and
properly coerces the version to a bnd version.
- A JAR without a main class in the manifest can now be used.
If the JAR had no Main-Class, an error was reported. Now
the `classpath` option is first passed. If there is no
Main-Class in the manifest but the `classpath` is set
then we try the command anyway.
=> [generate] Problems with generate

bndtools.core/src/bndtools/launch/sourcelookup/containers/BndrunEESourceContainer.java
The source lookup configuration GUI would NPE internally if a JRE was selected on your bndrun which couldn't be found in your
workspace. Report "no children" in this case for slightly better UX.
=> [sourcelookup] Fix NPE on unknown JRE

bndtools.m2e/lifecycle-mapping-metadata.xml, bndtools.m2e/src/bndtools/m2e/BndConfigurator.java
We ran into the problem, that in certain situations a single project was build over and over again in eclipse when using the bndtools m2e connector.
it turned out, that a few things went wrong here. 
1. The bnd-maven-plugin supports two goals: bnd-process and bnd-process-tests. The `BndConfigurator`  however was only called for `bnd-process` and build the artifact and the test artifact. This is now separated.
2. We call the `maven-jar-plugin` after we updated all the decorators. This is something that m2e normally does not do and wasn't expecting. Thus the resulting jar comes as a surprise to eclipse, which causes the incremental builder to be called again and finally dribbles down to us. We never checked the delta that causes the build and blindly rebuild the jars. Thus the loops starts. …
=> fixed build loop in eclipse

bndtools.core.services/src/org/bndtools/core/editors/quickfix/BuildpathQuickFixProcessor.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/AbstractBuildpathQuickFixProcessorTest.java, bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessor_WithSimpleOnBuildpath_Test.java
Expressions like this:
`ClassA a = (ClassA)b;`
...that don't work because the full hierarchy of `ClassA` is not on the buildpath and the compiler cannot establish that `ClassA` is a subtype of b's class.
=> [quickfix] Fix for unknown cast caused by missing superclass

bndtools.core/src/bndtools/launch/util/LaunchUtils.java, bndtools.m2e/bnd.bnd, bndtools.m2e/src/bndtools/m2e/MavenRunListenerHelper.java, bndtools.m2e/src/bndtools/m2e/MavenRunProvider.java
If not resolver or test plugin has been set up properly, we internally ran into an NPE. The new error handling avoid the Exception and give a proper message to the user with a suggestion on how to fix it.
=> Improved error handler, if maven not setup properly

gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/AbstractBndrun.java, gradle-plugins/biz.aQute.bnd.gradle/testresources/resolvetask1/changefail.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/resolvetask1/create.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/resolvetask1/resolvefail.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/resolvetask1/same.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/bnd.bnd, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolve.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolve2.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolvechange.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolveerror.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolvenochange.bndrun
Like the maven plugins, the gradle plugins can now infer a -runee
from the compilation settings in the project. Specifically, the
release or targetCompatibility setting from the compileJava tasks is
used.
Fixes https://github.com/bndtools/bnd/issues/4142
=> gradle: Add -runee inferencing to the bndrun tasks

gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/AbstractBndrun.java, gradle-plugins/biz.aQute.bnd.gradle/testresources/testosgitask1/build.gradle, gradle-plugins/biz.aQute.bnd.gradle/testresources/testosgitask1/testosgi.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/bnd.bnd, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolve.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolve2.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolvechange.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolveerror.bndrun, gradle-plugins/biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolvenochange.bndrun
Like the maven plugins, the gradle plugins can now infer a -runrequires
from the archives configuration of the project. Each file in the
archives configuration is examined for its Bundle-SymbolicName header
in the manifest. If not found, the project's name is used.
Fixes https://github.com/bndtools/bnd/issues/4143
=> gradle: Add -runrequires inferencing to the bndrun tasks

biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java
Previously they were "message" level which always outputed. Now
they will only output if tester.trace is true.
Fixes #4808.
=> [junit-platform] Make skipped & aborted tests trace level

cnf/build.bnd, org.bndtools.launch/bnd.bnd
We disable importing of java.* packages which upsets the p2 packaging
code. This occurred because the bnd.bnd file for the new
org.bndtools.launch project did not put osgi.core on the buildpath.
As a safety measure, we also now use -noimportjava=true.
Also: fixed compile warning in Eclipse for references to code in the
bndtools.utils project, and removed the improper inclusion and exporting
of the bndtools.launch.util package from bndtools.core.
=> org.bndtools.launch: Fix break in the p2 installation

.github/workflows/cibuild.yml, .github/workflows/codeql-analysis.yml
'adopt' has been superseded by 'temurin'.
=> github action: Replace 'adopt' with 'temurin'

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomConfiguration.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/SearchRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/package-info.java, biz.aQute.repository/src/aQute/maven/api/IPom.java, biz.aQute.repository/src/aQute/maven/api/MavenScope.java, biz.aQute.repository/src/aQute/maven/api/package-info.java, biz.aQute.repository/src/aQute/maven/provider/POM.java, biz.aQute.repository/src/aQute/maven/provider/packageinfo, biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java, biz.aQute.repository/testdata/pomrepo/depManagementImport.xml, biz.aQute.repository/testdata/pomrepo/simpleDepManagement.xml, docs/_plugins/pomrepo.md
When using bnd to Work on top of maven Projects it is often useful to use the parant pom of the Project as BndPomRepository to get the necessary dependencies. Unfortunately they are then in the depencyManagement section and will not be seen by the Repo. 
This PR adds an addtional attribute to the repo to enable consideration of these dependencies. The default is `false` so the default behavior does not change.
Signed-off-by: Jürgen Albert <j.albert@data-in-motion.biz>
=> Adds support to consider dependencyManagement

bndtools.core/_plugin.xml
Status handlers are now in the `org.bndtools.launch` plugin but the `bndtools.core` `plugin.xml` had not been updated to reflect this fact so they weren't working.
=> [launch] Fix status handler registration

cnf/build.bnd
* -snapshot unset (commented out) is a snapshot build.
(e.g. 6.0.0-SNAPSHOT)
* -snapshot set to a value (e.g. RC1) is a release build with the
value as the Maven version qualifier. (e.g. 6.0.0-RC1)
* -snapshot set to the empty string is a release build with no
Maven version qualifier. (e.g. 6.0.0)
=> build: We change the build to allow using -snapshot to specify a Maven version qualifier

bndtools.core/_plugin.xml, bndtools.core/src/org/bndtools/facade/ExtensionFacade.java
A stray : meant that the property tester for the contextual
launch was being configured with an empty class. We were
handling the null case but not the empty string case. Removed
the stray colon and changed to handle both error conditions.
Fixes #4832.
=> [launch] Fix shortcuts disappearing

bndtools.core.test/src/bndtools/core/test/editors/quickfix/BuildpathQuickFixProcessor_WithEmptyBuildpath_Test.java
Suspect transient network errors were causing this test to be flaky.
Fixes #4849 (hopefully)
=> [quickfix test] Change empty buildpath test to avoid ref to JUnit

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenTestsPlugin.java
@rotty3000 could you have a look on this?
If you customize the `Bundle-SymbolicName` of the main bundle to 
`Bundle-SymbolicName: ${groupId}.${artifactId}` you need a way to manually customize the tests-bundle
```
Bundle-SymbolicName: ${groupId}.${artifactId}-tests
Fragment-Host: ${groupId}.${artifactId}
```
=> mvn - respect pre-set Bundle-SymbolicName Fragment-Host

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, docs/_instructions/includeresource.md
When using `-includeresource` Instructions to process files inside a jar, no extras Attributes had been processed.
Now it should handle:
`flatten:=BOOLEAN` - puts all files in the file-tree into one folder
`rename:=RENAME`  - maps the Path using a given recipe , Regex groups allowed on Folders and Files
@juergen-albert 
For your need: `-includeresource: newFoldername=@fromFolder/zipFile.zip!/InnerFolder1/InnerFolder2/*;rebase:=/");`
=> IncludeResouce handles extras in jars paths

bndtools.core/src/bndtools/explorer/Model.java
This workaround ensures that the action is performed on the display thread properly by rescheduling it on the display thread. Note that, previously it was also executed on the display thread, but underlying SWT/JFace didn't submit the task properly to the display thread. That's why, this MR ensures that we submit the task properly (or explicitly) to the display thread. The bug still exists in the SWT/JFace which needs to be fixed. Other plugins using `getTreeViewer().refresh()` from `PackageExplorerPart` are prone to crash the JVM as well.
Fixes #4854
=> Workaround fix for JVM Crash Issue while refreshing 'ProblemTreeViewer'

bndtools.core/src/bndtools/Activator.java, bndtools.core/src/bndtools/Plugin.java, bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java, bndtools.core/src/bndtools/wizards/project/ImportBndWorkspaceWizard.java, bndtools.core/src/bndtools/wizards/workspace/AddFilesToRepositoryWizard.java, bndtools.release/src/bndtools/release/Activator.java, bndtools.release/src/bndtools/release/ReleaseDialogJob.java, bndtools.release/src/bndtools/release/ReleaseHelper.java, bndtools.release/src/bndtools/release/WorkspaceAnalyserJob.java
f0928dab068431590c0a0c1abbbc454588e098f1 causes performance issues and possibly #4861. The way all projects were refreshed and the refreshing of project from a view refresher caused repetitive project refreshing.
This PR fixes Central.refreshProjects() to mark all projects changed before advising model listeners of the changes. It also removes refreshing projects from the view refresher. Projects should be refreshed only when some action is taken not in a UI view refresher which is itself responding to some taken action. I saw a stack trace where the view refresher refreshed the projects which ended back up in the view refresher refreshing the projects again!
Also, we should not be refreshing projects on the UI thread as that causes responsiveness issues.
So far this PR seems to address …
=> bndtools: Fix project refreshing causing performance issues

biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/BndrunContainer.java, gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/AbstractBndrun.java, maven/bnd-plugin-parent/pom.xml, maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/resolve-with-project-props/error.properties, maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/resolve-with-project-props/include.properties, maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/resolve-with-project-props/pom.xml, maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/resolve-with-project-props/test.bndrun
After setting the parent of the bndrun so the bndrun has access to the maven/gradle project properties, we clear any errors and force a refresh of the bndrun. The will enable the -include processing access to the maven/gradle project properties.
Closes #4881
=> bndrun: Force refresh after setting parent

bndtools.core.test/test.cocoa.macosx.x86_64.bndrun, bndtools.core.test/test.gtk.linux.x86_64.bndrun, bndtools.core.test/test.win32.x86_64.bndrun, bndtools.core/bndtools.cocoa.macosx.x86_64.bndrun, bndtools.core/bndtools.gtk.linux.x86_64.bndrun, bndtools.core/bndtools.win32.x86_64.bndrun, org.bndtools.remoteinstall/bnd.bnd
The remoteinstall bundle depended upon the remote.api bundle which
is not part of the main feature. So p2 cannot install the feature.
The remote.api bundle is not really well formed in that it duplicates
exports from bndlib which is already part of the main feature.
Since the remoteinstall bundle needed very little of the remote.api
code, we now just conditional package it into the remoteinstall bundle
to avoid another dependency.
=> remoteinstall: The feature was incomplete and could not install

bndtools.core/src/org/bndtools/facade/ExtensionFacade.java, bndtools.core/src/org/bndtools/facade/ExtensionServiceTracker.java
Using finalize is not recommended and is being planned for removal.
We update the service tracking code to close the ServiceTracker when
it detects the parent object has been garbage collected when called
at the customizer methods.
=> extensionfacade: Remove use of finalize

gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndWorkspacePlugin.java
During the conversion from Groovy source code to Java, the wrong
property name was used for the name of the cnf folder.
=> gradle: Use correct property name for bnd_cnf

gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestBundlePlugin.groovy, gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestIndexTask.groovy, gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestTestOSGiTask.groovy
Groovy 3.0 relocated XmlSlurper to groovy.xml and deprecated the
copy in groovy.util.
=> gradle: Use correct XmlSlurper class

bndtools.core/src/bndtools/central/Central.java
If a change to cnf was detected, we called workspace refresh without
regard to any running builders. This caused issues where the workspace
refresh closed repos while a builder was running.
We now refresh the workspace while holding the bndLock. We use a job
to handle this in case we need to wait for the lock and don't want to
block the notification (which could be the main) thread.
=> central: Refresh workspace inside bndLock for cnf change

cnf/ext/jfrog-settings.xml, cnf/ext/repositories.bnd
We rely upon the new simple glob support in ConnectionSettings to match
the URLs to the server id in the settings.
=> ci: Use settings created by setup-java action

.github/workflows/cibuild.yml, cnf/ext/jfrog-settings.xml, cnf/ext/repositories.bnd
We also use the settings.xml from the workflow to configure the credentials for the Bnd Workspace project release to jfrog.
=> Update workflow to compute canonical in matrix

.github/workflows/cibuild.yml
We save time in the builds for PRs. The rebuild workflow tests the
release function of the built Bnd.
=> ci: Only run publish step for canonical builds

biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java
We now name the method. It appears that some code instrumentation may
be "converting" a constructor to a method and then Bnd is upset. So
we name the member to provide evidence of the conversion.
=> ds: Improve error message for Reference annotation on method parms

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java, biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
The Maven repo can be configured to download an archive containing jars. These jars will then be added to the repos index. Currently they land in the local m2 repo with generically numbered names like: "groupid-artifactid-1.0.0-bin123.jar" 
When we export a bndrun, we add them with exactly that name. This makes it hard to identify what really is in there and also "looks bad".
Thus we now modify the classierfier to reflect the original jar name instead of the bin123.
=> better naming for archives as part of a multi zip

.github/scripts/rebuild-test.sh, build.gradle, gradle.properties, rebuild-with-local-plugin, settings.gradle
Previously, the next branch just uses the final snapshot before RC
builds start.
=> build: Update build to support using RC builds in next branch

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java, biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java
If a revision points to a pom file and transitive was false, the repo
didn't even acknowledge dependencies in this pom file, which beats the
purpose of the PomRepository all together. It will now use this
dependencies but will not go further.
Closes #4973
=> transitive=false will now look in the first level of pom revisions

biz.aQute.bndlib.tests/test/test/IncludeHeaderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, docs/_instructions/include.md
The code has, since at least 2010, defaulted to overwriting properties
in included files. That is, included files, by default, overwrite
properties in the including properties. A test case expects this
behavior.
The documentation however says the default is not to overwrite. Since
the code's behavior dates back at least 12 years, it would not be safe
to change the code to match the documentation as it would be a breaking
behavioral change. So we update the documentation to document the
actual behavior of the code.
=> include: Fix documentation regarding overwriting properties

biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceLock.java, biz.aQute.bndlib/src/aQute/bnd/build/package-info.java, biz.aQute.bndlib/src/aQute/bnd/remoteworkspace/server/RemoteWorkspaceServer.java, bndtools.builder/src/org/bndtools/builder/BndSourceGenerateCompilationParticipant.java, bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/BndtoolsDynamicReferenceProvider.java, bndtools.builder/src/org/bndtools/builder/CnfWatcher.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerSourceManager.java, bndtools.core.services/src/org/bndtools/core/editors/quickfix/AddBundleCompletionProposal.java, bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java, bndtools.core/src/bndtools/central/RepositoryUtils.java, bndtools.core/src/bndtools/central/sync/SynchronizeWorkspaceWithEclipse.java, bndtools.core/src/bndtools/central/sync/WorkspaceSynchronizer.java
We replace the use of Bndtools' bndLock with the Workspace's
ReentrantReadWriteLock. This allows us to use read locking in most
places and write locking only when necessary.
=> workspace: Utilize workspace ReentrantReadWriteLock for locking

biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bndlib/src/aQute/bnd/osgi/PluginsContainer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
Use PluginProvider to access plugins of parent
Instead of copying the parent's plugins into the child's plugins
container, we now use a PluginProvider to access the parent's plugins.
This better handles the case where the parent (e.g. Workspace) is
refreshed but the child is not. Any closeable plugins (like maven
repos) in the parent would linger in the child's plugins container.
Since the child no longer contains the parent's plugin objects,
it always has the correct view onto the parent's plugins.
=> Parent plugin provider

gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPlugin.java
While we do not need this as we configure the compile tasks, other
gradle plugins (like Eclipse) seem to care.
=> gradle: Set source/target for JavaPluginExtension/JavaPluginConvention

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java
Ensure that the validators are run on the model before the processor copies them into itself.
Fixes #5006
=> [validators] Fix marker generation for validators

cnf/ext/central.mvn
Bumps logback-classic from 1.2.8 to 1.2.9.
---
updated-dependencies:
- dependency-name: ch.qos.logback:logback-classic
dependency-type: direct:development
update-type: version-update:semver-patch
...
=> build: Bump logback-classic

biz.aQute.bndlib/src/aQute/bnd/build/Project.java, bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java
Originally the error/warning Location was set on the place where
the problem was detected. However, we switched to just
set the header & clause. The Default Error Handler then 
would lookup the header and clause and set the line, start, and
and end attributes.
However, since we delayed the reporting, we gave a processor.
This was a bare processor, so the findHeader had neither
the proper file, nor an inheritance chain, to find the
header clause combination. So all errors ended up at the
top line.
This patch makes the temporary processor that holds
the messages inherit from project.
It also removes an error on a low level routine that reported a missing dependency, this was handled in two places.
=> [markers] Markers lost their position

aQute.libg/src/aQute/lib/io/FileTree.java, aQute.libg/src/aQute/lib/io/IO.java
The FileTree results were sorted using simple Path.compareTo over the complete
Path. This updates the sorting to sort file names using the
IO.fileCollator like we use for sorting in the other IO list methods.
This will remove some file system dependency in the sort order while
providing a depth first traversal like Files.walk.
=> FileTree reproducible result

biz.aQute.bndlib/src/aQute/bnd/osgi/PluginsContainer.java
In a sub bundle project, the XML files for components
were generated multiple times. After debugging, I found
that the PluginContainer returned multiple instances
of the same plugin. 
This seems to have been caused by using the PluginProvider
mechanism to get the plugins from the parent. Although
this could be fixed, the easiest (and seemingly safest) 
solution was to just make the stream that returns the 
plugins distinct.
@BJ you might want to take a further look to see if
the logic is causing the traversal of the parent
hierarchy multiple times?
=> [issue] Plugins container returned duplicates

biz.aQute.bndlib/src/aQute/bnd/osgi/PluginsContainer.java, cnf/ext/central.mvn
In a sub bundle project, the XML files for components
were generated multiple times. After debugging, I found
that the PluginContainer returned multiple instances
of the same plugin.
This seems to have been caused by using the PluginProvider
mechanism to get the plugins from the parent. Although
this could be fixed, the easiest (and seemingly safest)
solution was to just make the stream that returns the
plugins distinct.
@BJ you might want to take a further look to see if
the logic is causing the traversal of the parent
hierarchy multiple times?
Signed-off-by: Peter Kriens Peter.Kriens@aqute.biz
=> Multiple identical plugins in plugins list

biz.aQute.bndlib.tests/test/test/PluginTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/PluginsContainer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/package-info.java
ParentPluginProvider led to an ordering problem where a plugin from the
parent would be selected over a plugin from the child. This issue
had been present before but ParentPluginProvider did not help.
So we remove ParentPluginProvider and define a PluginsSpliterator
which defines an ordering where the child's plugins are before the
parent's plugins. This also allows us to simplify the stream code
and avoid using flatMaps over a single item stream and using concat
to combine two streams. This is all handled in the spliterator
implementation by walking multiple spliterators in an order.
=> PluginsContainer ordering

bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java, bndtools.builder/src/org/bndtools/builder/DeltaWrapper.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainer.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
If an upstream classpath container element is updated, the builder
must rebuild the project.
Fixes https://github.com/bndtools/bnd/issues/5025
=> builder: Handle updates to classpath container elements

maven/bnd-baseline-maven-plugin/README.md, maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java
We add support for `bnd.baseline.diffignores` and
`bnd.baseline.diffpackages` properties to configure the `diffignores`
and `diffpackages` configuration options.
=> maven: Update bnd-baseline-maven-plugin with diff properties

biz.aQute.bndlib/src/aQute/bnd/osgi/About.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/AggregateRepository.java
If AggregateRepository was constructed with no repositories, then
findProviders would return an empty map which violated the contract
where the returned map must have each input requirement as a key.
We fix so that the returned map now follows the contact.
=> repository: Fix AggregateRepository to return proper results

biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceRepositoryDynamic.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/AggregateRepository.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/AugmentRepository.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/ResourcesRepository.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/package-info.java, biz.aQute.repository/src/aQute/bnd/deployer/repository/AbstractIndexedRepo.java, biz.aQute.repository/src/aQute/bnd/deployer/repository/CapabilityIndex.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, bndtools.m2e/src/bndtools/m2e/MavenImplicitProjectRepository.java
Since this is a common action in repository implementations, we add
2 methods to generate a result Map for findProviders. One is a valid
result Map when there are no present capabilities.
It is incorrect to return an empty Map. We fixed one occurrence of this
in MavenImplicitProjectRepository.
=> repository: Define util methods for building findProviders maps

biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java
Empty left collection is common in reduce with identity. We also avoid
mutating the right collection.
=> repository: Avoid collection mutation if possible

biz.aQute.bndall.tests/order-01.bndrun, biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java, biz.aQute.bndlib/src/aQute/bnd/build/JUnitLauncher.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.launcher/src/aQute/launcher/Launcher.java, biz.aQute.launcher/src/aQute/launcher/constants/LauncherConstants.java, biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java, biz.aQute.remote/bnd.bnd, biz.aQute.remote/src/aQute/remote/plugin/RemoteProjectLauncherPlugin.java, org.bndtools.launch/src/bndtools/launch/OSGiJUnitLaunchDelegate.java, org.bndtools.launch/src/bndtools/launch/OSGiRunLaunchDelegate.java
We no longer call calculatedProperties during updateFromProject since
that is too soon. We now call calculatedProperties from getRunProperties
so it is done just as it is needed.
For ProjectLauncher.calculatedProperties, we no longer set a number of
values since they are already handled in
ProjectLauncherImpl.getConstants as launcher properties which are
then set as framework properties by Launcher.createFramework. So we
then needed to modify RemoteProjectLauncherPlugin to override
calculatedProperties to set the framework properties.
Fixes #5061
=> launcher: Refactor to call calculatedProperties later

biz.aQute.bndlib/src/aQute/bnd/build/ProjectGenerate.java
If a plugin threw an exception it was ignored
BJ, can this still be in 6.2?
=> [generate] Exception ignored

biz.aQute.bnd.util/src/aQute/bnd/unmodifiable/ImmutableMap.java
We avoid reading array elements we don't need and avoid double writes
to index field.
=> immutable: Reduce the amount of reads and writes on iteration

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientTest.java, biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/SettingsParserTest.java, biz.aQute.bndlib.comm.tests/testresources/ws/cnf/valid.xml, biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java, biz.aQute.bndlib/src/aQute/bnd/connection/settings/ServerDTO.java, biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java, biz.aQute.bndlib/src/aQute/bnd/service/url/URLConnectionHandler.java, biz.aQute.bndlib/src/aQute/bnd/service/url/packageinfo, docs/_instructions/connection-settings.md
This change fixes  #5035
Sometimes a host limits the number of connections
because it sees too many connections from one client
as an attack.
This patch enables a `maxConcurrentConnections` field in the Maven XML or in the ServerDTO. If this is 0, no limit is applied. Otherwise the connection to that host will be limited to that number. Different hosts can have different numbers.
The implementation is unsophisticated. The client uses
the URL Connection Handler to get this limit from the
ServerDTO. If not zero, he URL Connection Handler is then used
as a key in a map to a Semaphore that is initialized with the
URL handler maxConcurrentConnections value.
Each connection to that host will then first acquire a
token and will return it at the end.
To simplify the code, a dummy semaphore is …
=> [http client] Limit the # of concurrent connections

docs/Gemfile, docs/Gemfile.lock, docs/_chapters/400-commands.md, docs/_chapters/800-headers.md, docs/_chapters/825-instructions-ref.md, docs/_chapters/850-macros.md, docs/_chapters/855-macros-ref.md, docs/_layouts/default.html, docs/css/style.scss
Each page indicates its class (Project,Workspace,Analyzer,...)
as a class property in the YAML header. We were not showing this
This change adds a button to the page that specifies this class property.
Also rewrote the index pages to be a bit more compact
=> [doc] Use of class

biz.aQute.bndlib/src/aQute/bnd/build/LibraryHandler.java
replaces the e.printStacktrace with some real error logging
=> improve error reporting in the Library Handler

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
This can be used to configure the classpath container to hide
certain packages from Eclipse.
=> bndtools: Support negation on packages attribute entries

aQute.libg/src/aQute/lib/exceptions/BiConsumerWithException.java, aQute.libg/src/aQute/lib/exceptions/BiFunctionWithException.java, aQute.libg/src/aQute/lib/exceptions/BiPredicateWithException.java, aQute.libg/src/aQute/lib/exceptions/ConsumerWithException.java, aQute.libg/src/aQute/lib/exceptions/Exceptions.java, aQute.libg/src/aQute/lib/exceptions/FunctionWithException.java, aQute.libg/src/aQute/lib/exceptions/PredicateWithException.java, aQute.libg/src/aQute/lib/exceptions/RunnableWithException.java, aQute.libg/src/aQute/lib/exceptions/SupplierWithException.java, aQute.libg/src/aQute/lib/exceptions/package-info.java
When we moved to 6.1 (not a major release) we lost
the package aQute.lib.exceptions because we also
made it available via aQute.bnd.util.
This would've been a nice use case for my shading
code but until we've got something like that we cannot
just remove a package in a minor release.
This is causing so much pain in all my builds that
I am restoring it, unfortunately now having a 
duplicate. 
I am ok to deprecate one of them but this is
a giant pita.
This is the content of the package  at 5.3.0
=> [libg] Restore old package

biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java
Remove setting of -resourceonly=true since we need the Builder to run
the VerifierPlugins to process the -jpms-module-info instruction.
=> launcher: ProjectLauncherImpl.executable() Builder is not resourceonly

docs/_includes/head.htm, docs/_includes/nav.htm, docs/_sass/base.scss, docs/css/style.scss
Most searches end up in the jungle since bnd
is not the most popular tool. Added a search bar
that limits the search to *.bndtools.org & 
bnd.discourse.group.
Seems to be quite effective.
Also removed the ugly red blob for the release 
and replaced the color with a menu indicator. 
=> [doc] Added custom search bar

biz.aQute.bndlib.tests/test/test/InstructionTest.java, biz.aQute.bndlib.tests/test/test/MacroTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/header/Attrs.java, biz.aQute.bndlib/src/aQute/bnd/header/package-info.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Instructions.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, bndtools.core/src/bndtools/editor/completion/BndHover.java, docs/_chapters/820-instructions.md
A series of improvements to the decoration support.
1. Unused literals at the front of the decorator are added to the front of the decorated Parameters. So this will allow adding items at the front which is important for negations in things like conditional package.
2. Handles duplicate keys in the Parameters. This is useful when decorating a Parameters which supports duplicate keys.
3. Supports the removal of an attr by using the `!` value in the decorator.
4. Supports not overwriting an existing attr by prefixing the attr name with `~` in the decorator. This allows the decorator to supply default attr values which do not overwrite supplied values.
5. Adds decoration support to more Bnd instructions. `-conditionalpackage`, `-privatepackage`, `-includepackage`, and `-includeresource` now …
=> Decoration updates

biz.aQute.bndlib.tests/test/test/InstructionTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Instructions.java, docs/_chapters/820-instructions.md
The attribute value "!" is used on some places such as import package
to indicate that attribute should be removed from the result. So we
need to allow decoration to decorate an attribute with the "!" value.
=> decoration: Fix attribute removal support to allow "!" value

.gitignore, biz.aQute.bndlib.tests/test/test/AnalyzerTest.java, biz.aQute.bndlib.tests/test/test/ProcessorTest.java, biz.aQute.bndlib/src/aQute/bnd/header/Attrs.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/AttributeClasses.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, docs/.gitignore
In  #5136 i observed that the fix suggested was not really helping to solve the confusion about the internal attributes. Internal attributes crept in as a quick hack to solve a problem but there were many similar problems. This is a proposal to define this concept properly. 
It was observed that Analyzer decided to not learn a package if there was already an attribute set on that package in the manifest. However, over time lots and lots of 'internal' attributes entered the fray. 
This patch defines the concept of internal attributes and an `isInternal` method and a toExternal to clean up an Attrs.
It also creates constant in Constants that holds all the internal attributes. However, isInternal will treat any attribute key that starts with an INTERNAL_PREFIX ('-internal-') as internal. …
=> [analyzer] Internal attributes not well defined

biz.aQute.bndlib/src/aQute/bnd/build/Container.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java
The Project knows the bsn, but there are was no constructor to use.
So we add a new constructor and use it to capture the actual bsn.
For other cases, we also add a method to compute the bsn from a file
by using the file name and removing the trailing ".jar", if any.
Fixes https://github.com/bndtools/bnd/issues/5090
=> container: Add new constructor which takes bsn

cnf/build.bnd, gradle-plugins/biz.aQute.bnd.gradle/build.gradle.kts, maven/bnd-baseline-maven-plugin/README.md, maven/bnd-baseline-maven-plugin/pom.xml, maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-consumer/pom.xml, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/verify.groovy, maven/bnd-export-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/pom.xml, maven/bnd-maven-plugin/pom.xml, maven/bnd-plugin-parent/pom.xml, maven/bnd-reporter-maven-plugin/pom.xml, maven/bnd-resolver-maven-plugin/pom.xml, maven/bnd-run-maven-plugin/pom.xml, maven/bnd-testing-maven-plugin/pom.xml
When baselining fails in m2e, you only get an exception that it failed
but you have no useful information since that we only sent to the slf4j
log which you don't see in Eclipse. So we change the plugin to behave
like the gradle baseline task. It now writes a baseline report to a
file in the output directory and, if the baseline fails, the contents
of the report are made part of the failure exception.
=> Bnd baseline maven report

biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
In command line maven, maven always supplies artifact files which are
the built jar. Either in m2 or in a project's target folder.
However, in m2e, probably since the jar goal is not normally executed,
the artifact file for another project the reactor is for the project's
target/classes folder. This causes jar name matching in
-includeresource to fail since it matched in the file name and all the
file names for these project artifacts is "classes".
So we change the plugin to supply the directory classpath entries with
a file name which is synthesized from the artifact information. This
will then be matched to -includeresource references in m2e as well as
command line maven.
Fixes https://github.com/bndtools/bnd/issues/5081
=> bnd-maven-plugin: Set alternate source for classpath directories

aQute.libg/src/aQute/libg/command/Command.java
We still sometimes see "Stream closed" exceptions in parallel builds when using the bnd-testing-maven-plugin.
There was a previous fix in #4509 which already fixed most of these issues for us.
The reason we have these issues is because we also use the spotless-maven-plugin which [executes its SpotBugsMojo using AntBuilder](https://github.com/spotbugs/spotbugs-maven-plugin/blob/aa8a2b1bcd3556ac26c0dcbec7d963b6bd4edd0d/src/main/groovy/org/codehaus/mojo/spotbugs/SpotBugsMojo.groovy#L1082).
The AntBuilder [replaces](https://github.com/apache/groovy/blob/301fef366dbf0aa7f1f30faeb9b14a07927fbd98/subprojects/groovy-ant/src/main/java/groovy/ant/AntBuilder.java#L261-L308) System.in/out/err streams and closes these streams when it has finished execution.
So if meanwhile bnd started using System.in …
=> Catch exceptions when copying stdin in Command

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
While this is outside of the OSGi specification, which does not
address Java 1.1 as it was already superseded by Java 1.2 when OSGi
was first released, Equinox uses the osgi.ee name of JRE instead of
JavaSE. Since Java 1.1-only bundles are minuscule and Java 1.1 is
outside of the OSGi specifications, we just follow what the framework
implementation does.
=> ee: For Java 1.1, we change the osgi.ee name to JRE

gradle-plugins/biz.aQute.bnd.gradle/build.gradle.kts
Bumps com.gradle.plugin-publish from 0.20.0 to 0.21.0.
=> build(deps): Bump com.gradle.plugin-publish in /gradle-plugins

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiRepository.java
Potentially long running polling work should not be done on the
scheduled executor.
=> repo: Update polling code to run in normal executor

biz.aQute.bnd.util/src/aQute/bnd/result/Err.java, biz.aQute.bndall.tests/resources/ws-1/cnf/build.bnd, biz.aQute.bndall.tests/src/biz/aQute/bndall/tests/plugin_1/CallablePlugin.java, biz.aQute.bndall.tests/test/biz/aQute/externalplugin/ExternalPluginHandlerTest.java, biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceExternalPluginHandler.java, biz.aQute.bndlib/src/aQute/bnd/osgi/PluginsContainer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java, biz.aQute.bndlib/src/aQute/bnd/service/Plugin.java
Update the external plugin support to allow external plugins to implement Plugin and RegistryPlugin whose methods are called by Processor.customize to supply information
to plugins including any attributes on the -plugin instruction.
=> External plugin customize

biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ManifestResource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/PropertiesResource.java
We place the manifest writing logic into a ManifestResource class
which allows adding the manifest to a Jar as a resource and get
proper output.
=> jar: Refactor manifest writing into a ManifestResource class

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
This is useful for version=snapshot or version=latest when the
project's built jar contains transformed classes and we want the
Eclipse compiler to use the jar's classes and not the project's
untransformed classes which lead to compilation errors.
By adding `ide=jar-only` to the -buildpath entry, Bndtools
will include the built jar and not include the project in the
class path container.
=> bndtools container: Allow user to exclude project and have only jar

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
To be more general, we reframe the attribute to `source` with the
default value of `project`. This is the prior behavior.
So saying `source=none` on a -buildpath entry, Bndtools
will include the built jar and not include the project in the
class path container.
In the future, other values of `source`, such as a file, could be
specified. But for now, the value `project` includes the project in
the classpath. All other values do not include the project.
=> bndtools container: Rename ide to source

bndtools.builder/src/org/bndtools/builder/classpath/BndContainer.java
When using version=snapshot or version=latest, we want Eclipse to use
the class files in the project's built jar and not the project's bin
folder. The project's built jar may contain transformed classes and
we want the execution (including testing) to use the jar's classes and
not the project's untransformed classes which can lead to
NoClassDefFoundErrors.
So for the runtime class path, we exclude the project bin folders when
the project is not `version=project`.
=> bndtools container: Only use project for runtime when version=project

.github/workflows/cibuild.yml, .github/workflows/docs.yml, .github/workflows/rebuild.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Set permissions for GitHub actions

biz.aQute.bndlib/src/aQute/bnd/build/Container.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java
Normally, Bnd expects the bsn of a bundle built in the workspace to be
prefixed by the project name. This convention allows a quick lookup
from a bsn to find the project which builds the bundle with the bsn.
However, sometimes you need to refactor code, or when transforming,
use a completely different bsn for one of the sub bundles. The bundle
building works fine. But if another project refers to the bsn which
is not prefixed by the project name, Bnd cannot find the bundle and
fails.
Bnd could just exhaustively search the workspace but this would be cost
prohibitive in very large workspaces such as Open Liberty.
So this change introduces a "project" attribute which can be used on
a buildpath/testpath entry to name the project in which to look for the
bsn. So this does not affect the …
=> Support a "project" attribute to name the bsn source project

biz.aQute.bndlib/src/aQute/bnd/build/Project.java, gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPlugin.java
Use standard "publish" task group to avoid too many group names.
=> Gradle task group

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientServerTest.java, biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, docs/_instructions/connection-settings.md
The documentation specified a -connection-log instruction 
but the code did not implement it. This patch
sets the log when the http client's -connection-log
when the property is set.
=> [httpclient] Implement log as specified in doc

bndtools.core/src/bndtools/explorer/Model.java
Another desperate attempt to fix the JVM crash
in the bndtools explorer. 
This fix coalesces some update events by waiting 
10 ms before starting to do the UI work.
This should reduce the rate at which we call SWT 
and this _might_ solve this stupid SWT bug
=> #5062 JVM crash

.github/workflows/cibuild.yml, .github/workflows/codeql.yml, .github/workflows/rebuild.yml, .github/workflows/wrapper.yml
Sometimes gradle wrapper validation fails due to network issues.
By separating the wrapper validation into its own workflow, we can
easily rerun the failed workflow without rerunning all the longer
running workflows.
=> ci: Separate Gradle Wrapper validation into its own workflow

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
Closes: #5248
Signed-off-by: Elias Menon <eliasmenon@gmail.com>
=> builder: Avoid modifying manifests of conduit jars

biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java
There was a recent change https://github.com/bndtools/bnd/commit/dd2f0c56f9c102b9b7aa969c389787f541e76528 that took a shortcut to calculate the embedded packages unconditionally. It used the bundle class path analysis to analyze all the jars in the executable. 
However, this significantly slows down Eclipse but worse, it then tries to reinterpret the annotation headers. In my case, I got 3 types on the Bundle-Activator.
The analysis should only be done when it is needed and I'd suggest to do it either in a separate Builder or try to analyze the manifests for speedup.
This patch just makes the analysis conditional but that is a temporary fix to make it compatible with the the previous code.
This needs to be cherry picked for 6.3.0 since it is a very serious regression.
Fixes  #5257 …
=> [export] JPMS module info calculation fails

biz.aQute.bndlib.tests/test/test/InstructionTest.java, biz.aQute.bndlib.tests/test/test/ProcessorTest.java, biz.aQute.bndlib.tests/test/test/ProjectTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, bndtools.core/src/bndtools/editor/completion/BndHover.java, docs/_chapters/820-instructions.md, docs/_instructions/runbundles.md
The decoration changes to always include literals was not backward
compatible since it added literals for the `-runbundles`.
After some discussion we decided to add `++` for decorations
that always add literals and a single `+` for the 6.2 behavior
of not adding literals.
Since we use decorations requiring adding literals in our own build,
this changes adds support for `++` decoration while `+` decoration
still adds literals.
After this build is complete, we will following with changing our
build to use `++` where necessary and also change the `+` behavior
back to not adding literals.
=> [decoration] Backward compatibility (Phase 1)

biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, cnf/build.bnd
Complete the change to restore not adding literals for `+` decoration.
=> Decoration phase2

cnf/build.bnd, cnf/includes/bndtools.bnd
With the reversion to having + decorations not include literals, we
can stop using the "{xxx}" construct to be non-literal.
=> build: Remove use of "{xxx}" non-literals on + decorations

.github/scripts/rebuild-build.sh
This is useful for checking the Bnd version used to build Bnd.
=> ci: Display build dependencies for rebuild-build

gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BundleTaskExtension.java
Instead of setting a manifest object in the task so that we can
set the effective manifest, after building we merge the generated
manifest into the existing manifest object.
Fixes https://github.com/bndtools/bnd/issues/5275
=> gradle: Avoid setting a manifest object

gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BundleTaskExtension.java, gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestBundlePlugin.groovy, gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin1/build.gradle, gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin2/build.gradle
If Bundle-SymbolicName and/or Bundle-Version are not specified in the
bnd instructions, then BundleTaskExtension will set default values
based upon the Jar task's archiveBaseName, archiveClassifier, and
archiveVersion properties. However, these Jar task properties are not
considered inputs to the Jar task. They are just considered as
parts of the archiveFile property which is an output property.
Setting the defaults as input properties means that Gradle will consider
them as part of the build cache key. This is important since the values
can end up in the build jar's manifest.
Fixes https://github.com/bndtools/bnd/issues/5279
=> gradle: Make default Bundle-SymbolicName and Bundle-Version inputs

maven/bnd-testing-maven-plugin/README.md, maven/bnd-testing-maven-plugin/src/it/test-failure/bnd.bnd, maven/bnd-testing-maven-plugin/src/it/test-failure/invoker.properties, maven/bnd-testing-maven-plugin/src/it/test-failure/pom.xml, maven/bnd-testing-maven-plugin/src/it/test-failure/src/main/java/bnd/test/FailingBndTest.java, maven/bnd-testing-maven-plugin/src/it/test-failure/src/main/java/bnd/test/SimpleBndTest.java, maven/bnd-testing-maven-plugin/src/it/test-failure/test.bndrun, maven/bnd-testing-maven-plugin/src/it/test-ignore-failure/bnd.bnd, maven/bnd-testing-maven-plugin/src/it/test-ignore-failure/invoker.properties, maven/bnd-testing-maven-plugin/src/it/test-ignore-failure/pom.xml, maven/bnd-testing-maven-plugin/src/it/test-ignore-failure/postbuild.groovy, maven/bnd-testing-maven-plugin/src/it/test-ignore-failure/src/main/java/bnd/test/FailingBndTest.java, maven/bnd-testing-maven-plugin/src/it/test-ignore-failure/src/main/java/bnd/test/SimpleBndTest.java, maven/bnd-testing-maven-plugin/src/it/test-ignore-failure/test.bndrun, maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
This can be set from the command line with:
-Dbnd.testing.failure.ignore=true
Fixes https://github.com/bndtools/bnd/issues/5295
=> maven: Add testFailureIgnore configuration to bnd-testing-maven-plugin

maven/bnd-baseline-maven-plugin/pom.xml, maven/bnd-export-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/pom.xml, maven/bnd-maven-plugin/pom.xml, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPackagingPlugin.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPackagingTestsPlugin.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenTestsPlugin.java, maven/bnd-reporter-maven-plugin/pom.xml, maven/bnd-resolver-maven-plugin/pom.xml, maven/bnd-run-maven-plugin/pom.xml, maven/bnd-testing-maven-plugin/pom.xml
Fixes https://github.com/bndtools/bnd/issues/5286
Also improves output of help goal for the mojos.
=> maven: Compute extension from packaging type

maven/bnd-maven-plugin/README.md, maven/bnd-maven-plugin/src/it/jar-test-war-bundle/pom.xml, maven/bnd-maven-plugin/src/it/jar-test-war-bundle/postbuild.groovy, maven/bnd-maven-plugin/src/it/test-war-bundle/pom.xml, maven/bnd-maven-plugin/src/it/test-war-bundle/postbuild.groovy, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java, maven/bnd-plugin-parent/pom.xml, maven/bnd-reporter-maven-plugin/pom.xml, maven/pom.xml
When using war packaging, we now also explode the war into the
webappDirectory.
This change also rename the configuration element to webappDirectory
to align with maven-war-plugin. The configuration is aliased to the old
name of warOutputDir.
Also, fixes for the incremental build support of the packaging goals
are added.
=> Improve handling of webappDirectory when building a wab

cnf/ext/junit.bnd, gradle-plugins/biz.aQute.bnd.gradle/build.gradle.kts, gradle-plugins/build.gradle.kts, gradle-plugins/settings.gradle.kts
Update osgi-test dependency and some build cleanups.
=> Build updates

biz.aQute.repository/src/aQute/maven/provider/POM.java
Fixes https://github.com/bndtools/bnd/issues/5318
=> repository: Detect recursive macro expansion in pom properties

biz.aQute.bnd.util/src/aQute/bnd/unmodifiable/Lists.java, biz.aQute.bnd.util/src/aQute/bnd/unmodifiable/Sets.java, biz.aQute.bnd.util/src/aQute/bnd/unmodifiable/package-info.java, biz.aQute.bnd.util/test/aQute/bnd/unmodifiable/ListsTest.java, biz.aQute.bnd.util/test/aQute/bnd/unmodifiable/SetsTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapReq.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapReqBuilder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/DeferredComparableValue.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/DeferredValue.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/DeferredValueEntry.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/DeferredValueMap.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/FilterImpl.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceImpl.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
The osgi.content capability must hold the SHA-256 value of the
resource. But this value is rarely used. So, when building a resource
from a file, we defer the SHA-256 calculation until actually needed.
The can help performance of FileSetRepository used by bndtools m2e.
However, we do need the hashCode of the SHA-256 value early, so use
a substitute hashCode value based upon the File object. This is not
perfect since two files can hold identical content and the hashCode of
their SHA-256 values should be identical. But in practice, this should
work when creating a resource from a file since the early need for the
hashCode of the SHA-256 value is in the computing of the hashCode of
the capability so it can be inserted in a set. But creating a resource
from a file only creates a single …
=> resource: Defer SHA-256 calculation into the future

biz.aQute.resolve/src/biz/aQute/resolve/Bndrun.java, biz.aQute.resolve/test/biz/aQute/resolve/RunResolutionTest.java
I think this was caused by faster window machines.
The reason for the operation was USE_CACHE which
can only happen if the bndrun file did not pick up
the time of the included file.
I've added a 100 ms delay before taking a time,
this 100 ms should be more than the resolution of
the file system.
So setting the time on the included file was not
seen as later than the project file.
I also added checks to see what the cache reason is
before we call getRunBundles().
Lets see what happens
=> [cached resolve] The test failed on Windows

biz.aQute.remote/src/aQute/remote/util/Link.java, docs/_chapters/300-launching.md
The code always used system.out to print tracing information. This
has been made optional with a system property `aQute.remote.util.Link.trace`,
if it is set to "true", the trace will send output to the console. Otherwise
it is silent.
Closes #5420
=> [remote link] Made tracing optional

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
Since we care about the file and not just the artifact object, we check
the file name for ending in ".jar" (jar extension) instead of relying
on the artifact reporting the "jar" type.
Fixes https://github.com/bndtools/bnd/issues/5349
=> maven: Use actual file name for jar file type test

biz.aQute.bndlib.tests/test/test/model/EETest.java, biz.aQute.bndlib/src/aQute/bnd/build/model/EE.java, biz.aQute.bndlib/src/aQute/bnd/build/model/package-info.java
@timothyjward as suggested in https://github.com/bndtools/bnd/pull/5357#issuecomment-1225557691
=> Add EE.getReleaseTarget() method

biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
https://github.com/bndtools/bnd/commit/c7f942b0d4fe67403ec0de949dd8e90d5d0069e2 incorrectly changed osfile to use forward slash path.
Fixes https://github.com/bndtools/bnd/issues/5364
=> macro: Fix osfile macro to return OS specific path

bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java, bndtools.core/src/bndtools/explorer/Model.java
As a try, I've increased the coalesce time
and then also tried to rearrange some of the overridden
methods. Instead of calling the super last, moved it
to first.
Bit desperate ... it is pretty ok now, it happens
to me once every month. But very frustrating that
we cannot pin this down.
If anybody has a full crash report, appreciated.
=> [jvm crash in swt] It is still happening

biz.aQute.bndlib.tests/test/test/WorkspaceTest.java, biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceLock.java
We use a queue since there will be more mutations than traversals. We only mark thread as holding read lock once it actually does. We only check for write upgrade when tryLock times out so we can potentially avoid traversing the queue.
Tests are also added.
=> workspace: Fixes to workspace lock write-upgrade detection

maven/bnd-maven-plugin/README.md
Fixes https://github.com/bndtools/bnd/issues/5375
=> maven: Document access to Maven properties in Bnd instructions

biz.aQute.bndall.tests/plugin-2.bnd, biz.aQute.bndall.tests/src/biz/aQute/bndall/tests/plugin_1/CallablePlugin2.java, biz.aQute.bndall.tests/test/biz/aQute/externalplugin/ExternalPluginHandlerTest.java, biz.aQute.bndlib/src/aQute/bnd/build/ProjectGenerate.java, biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceExternalPluginHandler.java, biz.aQute.bndlib/src/aQute/bnd/build/package-info.java, biz.aQute.bndlib/src/aQute/bnd/service/externalplugin/ExternalPlugin.java, biz.aQute.bndlib/src/aQute/bnd/service/externalplugin/ExternalPluginNamespace.java, biz.aQute.bndlib/src/aQute/bnd/service/externalplugin/package-info.java, docs/_chapters/875-external-plugins.md, docs/_instructions/generate.md
- Will not pick highest version when multiple plugins are found
- Version range attribute supported on external plugins
- Added version range to @ExternalPlugin
=> [external plugins] Added versioning support

biz.aQute.bndlib/src/aQute/bnd/osgi/OSInformation.java, biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java, biz.aQute.resolve/src/biz/aQute/resolve/ProjectResolver.java, biz.aQute.resolve/test/biz/aQute/resolve/ResolveTest.java
This patch adds a default native capability when
there is no native capability is set. The default
capability reflects the native environment in which
the resolver runs.
=> [resolve] Add a default native capability when none set

maven/bnd-reporter-maven-plugin/src/main/java/aQute/bnd/maven/reporter/plugin/ExportMojo.java
fixes:
```
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to write the report at /home/stbischof/dev/git/org.eclipse.aaa.bbb/prototype/core/target/docs_a_metadata.json
at aQute.bnd.maven.reporter.plugin.ExportMojo.execute (ExportMojo.java:132)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:301)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:211)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:165)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:157)
```
=> reporter - create dirs for exported file

biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java
`SummaryGeneratorListener.getSummary()` can return `null` in some circumstances (eg, if no tests are found). This PR puts some protections in place.
Fixes #5402
=> [junit-platform] Handle null summary if no tests found

biz.aQute.bndlib/src/aQute/bnd/build/Project.java
This patch will not block the saving of the files
when the export fails. Then the next time it 
all falls in place again.
=> [#5395] -export failure deadlock]

bndtools.core/src/bndtools/Plugin.java, bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java, bndtools.core/src/bndtools/explorer/Model.java
I was able to consistently crash the VM by
selecting a binary class file in rt.jar from
the VM project item and then closing the VM project item.
After hundreds of trials I found that the bug was
triggered when the getTreeViewer().refresh() was
called during a model update. For the record,
this happened on the main thread so I cannot
see any issue with this.
I then made the refresh conditional on a change
in the filter text field. For this, an
AtomicBoolean dirtyFilter was added.
This seemed to work fine now.
Of course this does not remove the bug. There
is an SWT bug lurking but closing an tree item
in the bnd explorer will no longer trigger it.
Fixes #5062
=> #5062 JVM Crash in bndtools explorer

biz.aQute.bnd.maven/bnd.bnd, bndtools.m2e/bnd.bnd
In recent versions (2022-06 and later) of Eclipse the version of the M2E maven runtime bundle has stopped matching the M2E version and now uses a higher version related to the maven it packages. We need to be able to use this if M2E support is to keep working.
Fixes #5417
=> [m2e] Expand bundle version ranges for M2E imports

biz.aQute.bndlib.tests/test/test/baseline/BaselineTest.java, biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
There is nothing which requires the first release to use version 1.0. Especially with the desire to rename things at major boundaries, it is not unexpected that the first release of an artifact may be version 2.0 or 3.0. And in this case, a warning about missing baseline is noise.
=> baseline: Avoid warning at major version boundaries

bndtools.m2e/bnd.bnd, bndtools.m2e/src/bndtools/m2e/AbstractMavenRepository.java, bndtools.m2e/src/bndtools/m2e/Activator.java, bndtools.m2e/src/bndtools/m2e/BndConfigurator.java, bndtools.m2e/src/bndtools/m2e/IndexConfigurator.java, bndtools.m2e/src/bndtools/m2e/LaunchPropertyTester.java, bndtools.m2e/src/bndtools/m2e/M2ETypeAccess.java, bndtools.m2e/src/bndtools/m2e/MavenBndrunContainer.java, bndtools.m2e/src/bndtools/m2e/MavenDependenciesRepository.java, bndtools.m2e/src/bndtools/m2e/MavenImplicitProjectRepository.java, bndtools.m2e/src/bndtools/m2e/MavenImplicitProjectRunListener.java, bndtools.m2e/src/bndtools/m2e/MavenRunListenerHelper.java, bndtools.m2e/src/bndtools/m2e/MavenRunProvider.java, bndtools.m2e/src/bndtools/m2e/MavenWorkspaceRepository.java, bndtools.m2e/src/bndtools/m2e/ServiceAwareM2EConfigurator.java, bndtools.m2e/src/bndtools/m2e/WorkspaceProjectPostProcessor.java
The latest m2e updates have moved methods in internal packages. This breaks m2e support in Bndtools where we were going around the official API. This is primarily an attempt to remove the usage of internal types in an effort to remain compatible between versions. Furthermore we need to coexist in scenarios where:
* A maven project change listener whiteboard is built in to M2E 2+ and replaces the one we created
* Services are used for M2E objects such as IMaven - access these in a consistent way
* Public lookup methods now exist, but we must still use reflection while 1.x is supported
A good deal of cleanup will be possible once we have a base of 2.0, but for now this is a good next step.
Known issues: The bndrun "Browse Repos" section populates, but then disappears again after about a …
=> [m2e] Remove references to internal packages and avoid static methods

maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
If one wants to customize the name of the artifact build for a project in a Maven build, the property `project.build.finalName` can be set respectively has to be used the following approach:
```
<project>
...
<build>
<finalName>${project.artifactId}-${qualifiedVersion}</finalName>
...
<Execute a mojo that creates the 'qualifiedVersion' property>
...
<Execute the `bnd-maven-plugin:jar` goal>
</build>
</project>
```
Unfortunately the `bnd-maven-plugin:jar` goal does not consider properties that are only created by other previous mojo executions for the same project.
The reason is that the `finalName` is read directly from the `MavenProject`'s `Build` object, which is created at the beginning of the (project) build and whose field values are only resolved against the properties initially …
=> Resolve artifact's finalName immediately before BndMaven*Plugin execution

maven/bnd-plugin-parent/pom.xml
Reverts bndtools/bnd#5324
maven-deploy-plugin 3.0.0 requires (the not yet released) maven 3.9.0 to deploy maven plugins. https://issues.apache.org/jira/browse/MNG-7055
```
[INFO] --- maven-deploy-plugin:3.0.0:deploy (default-deploy) @ bnd-indexer-maven-plugin ---
Warning:  
Warning:  You are about to deploy a maven-plugin using Maven 3.8.6.
Warning:  This plugin should be used ONLY with Maven 3.9.0 and newer, as MNG-7055
Warning:  is fixed in those versions of Maven only!
Warning:  
```
So until maven 3.9.0 is released and we update to use it, we cannot use maven-deploy-plugin 3.x.
=> Revert "build(deps): Bump maven-deploy-plugin from 2.8.2 to 3.0.0 in /maven"

maven/bnd-generate-maven-plugin/src/main/java/aQute/bnd/maven/generate/plugin/BndContainer.java
Due to the use of the wrong workspace folder some remnant directories have been created in the projects root directory instead of the target directory
=> temp workspace was created in the wrong location

biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceExternalPluginHandler.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ActivelyClosingClassLoader.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.launcher/src/aQute/launcher/minifw/BundleClassLoader.java, biz.aQute.launcher/src/aQute/launcher/pre/EmbeddedLauncher.java
All classes in the hierarchy need to call the registerAsParallelCapable method.
=> classloader: Update class loader classes to register as parallel

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java, biz.aQute.bndlib/src/aQute/bnd/build/package-info.java, biz.aQute.bndlib/src/aQute/bnd/maven/package-info.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/package-info.java, biz.aQute.bndlib/src/aQute/bnd/print/package-info.java, biz.aQute.bndlib/src/aQute/bnd/service/generate/package-info.java
Bnd was changed a couple of years ago to have a default expand when there were no instructions like -includeresource, Private-Package, etc. The implementation decided to put the whole output directory of the project directly in the to be build JAR. This meant that the normal processing did not happen. You had to use -exportcontents to export packages.
This PR changes the following
- It introduces a magic keyword for the `from:` directive. If this is `project`, it will search the class path entry that is the project's output directory and will include only from there. Therefore, doing a `-includepackage *;from:=project` will include the _whole_ project output directory.
- Created a set of EXPAND_HEADERS in Constants. The -includresource was not include.
- Updated the Project builder to set …
=> #5407 Decision to include project bin directory

bndtools.core/src/bndtools/wizards/project/NewBndProjectWizardPageOne.java
Work around to allow NewBndProjectWizardPageOne to function as subclass of NewJavaProjectWizardPageOne in Eclipse 2022-12 release.
As described in this comment:  https://github.com/bndtools/bnd/issues/5239#issuecomment-1399331939 starting 
in Eclipse 2022-12 going forward a module section/control was added to NewJavaProjectWizardPageOne class. This UI is also used in the validation done by NewJavaProjectWizardPageOne. In the subclass implementation of NewBndProjectWizardPageOne, the createControl method does not initialize the module section, as it's not needed for Bnd project creation. Since the NJPWPO alidation depends upon the module section/control initialization, the NewBndProjectWizardPageOne does not function properly in Eclipse 2022-12+.
This work around overrides methods and …
=> Work around for issue #5239

bndtools.builder/src/org/bndtools/builder/BndtoolsDynamicReferenceProvider.java, bndtools.core/src/bndtools/central/sync/WorkspaceChange.java
I could not get Eclipse to recognize the dependency between the cnf project changes and the other projects. So I used the new notifier mechanism to get changes in the workspace. When the repos are reported to be ready (and it is not the first time) a new full build is started.
Notice that whenever the registration is done, the notifier will send init/repos. That is why the first time it is ignored.
=> #5060 No automatic build when build.bnd changes

bndtools.core/src/org/bndtools/core/ui/wizards/shared/TemplateParamsWizardPage.java
Improved handling of template defaults in TemplateParamsWizardPage to allow brackets '<' and '>' at beginning and end to represent values that must be changed to complete the wizard.
=> Improve handling of template defaults

.github/workflows/wrapper.yml, org.bndtools.launch/src/bndtools/launch/AbstractOSGiLaunchDelegate.java
- use submonitor
- realized we'd be prompting inside the bnd lock ...
- made getAllProjects(ws) static
- done early exit when no prompt exists
---
=> Update after Fr. Krieg's request

biz.aQute.bndlib.tests/test/test/annotationheaders/StdAnnotationHeadersTest.java, biz.aQute.bndlib.tests/test/test/annotationheaders/div/HeaderWithValues.java, biz.aQute.bndlib.tests/test/test/annotationheaders/div/Target.java, biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java
Added support for macros in the @Header (meta) annotation
Closes #5530
---
=> #5530  @Header did not support macros

biz.aQute.bndlib.tests/test/test/MultiReleaseTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/About.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/plugin/jpms/JPMSMultReleasePlugin.java
The analyzer therefore ignored multi release jars. The analyzer is now fixed up with the default properties __versiondefaults__ is not set, will never overwrite though.
Also fixed a small oversights:
* If the JAR already contains a module-info.class then it will not be overridden.
* The delta calculations will not set the module info flag
---
=> Default properties were not set in the analyzer

docs/_chapters/150-build.md
* based on forum post https://bnd.discourse.group/t/stop-gradle-from-stepping-on-eclipses-long-toes/295
=> Add section about target-dir

biz.aQute.bndlib/src/aQute/bnd/osgi/ActivelyClosingClassLoader.java, biz.aQute.launchpad.tests/bnd.bnd, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/WorkspaceTest.java, biz.aQute.launchpad.tests/workspace.bndrun
If a class was not found it reverted to OSGi but not in a very good way, this could cause NPEs. This patch removes the NPE possibility and actually now searches all bundles that import or require the bndlib. This should probably make the Auxiliary extension superfluous that is used in Eclipse/bndtools.
---
=> Fixes NPE in classloading

biz.aQute.bndlib.tests/test/test/ImportJavaTest.java
The recent changes for when bnd should add imports for java.* packages missed tests that ensure packages are added when no -noimportjava instruction is present. No behaviour was broken, but we should protect against regressions by explicitly testing for the expected behaviour in this case.
See also #5585
=> Add tests for default java import behaviours

biz.aQute.tester.junit-platform/bnd.bnd, biz.aQute.tester.junit-platform/src/aQute/junit/system/BndSystem.java, biz.aQute.tester.junit-platform/src/aQute/junit/system/package-info.java, biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java, biz.aQute.tester.test/bnd.bnd, biz.aQute.tester.test/test/aQute/tester/junit/platform/test/ActivatorJUnitPlatformTest.java, biz.aQute.tester.test/test/aQute/tester/junit/platform/test/ExitCode.java, biz.aQute.tester.test/test/aQute/tester/junit/platform/test/GogoShellTests.java, biz.aQute.tester.test/test/aQute/tester/test/ActivatorTest.java, biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorCommonTest.java, biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorTest.java, biz.aQute.tester/src/aQute/junit/Activator.java, biz.aQute.tester/src/aQute/junit/JUnitEclipseReport.java, biz.aQute.tester/src/aQute/junit/system/BndSystem.java, biz.aQute.tester/src/aQute/junit/system/package-info.java, bndtools.core.test/bnd.bnd
- Added a BndSystm.exit method that could be overridden
- this was added to the aQute.bnd.tester
- Adapted the applicable code to call BndSystem.exit
- Changed the test code to override the exit
Fixes #5114
---
=> Removed use of SecurityManager

maven-plugins/bnd-maven-plugin/src/it/mr-jar/README.txt, maven-plugins/bnd-maven-plugin/src/it/mr-jar/invoker.properties, maven-plugins/bnd-maven-plugin/src/it/mr-jar/pom.xml, maven-plugins/bnd-maven-plugin/src/it/mr-jar/postbuild.groovy, maven-plugins/bnd-maven-plugin/src/it/mr-jar/src/main/java/bnd/mr/example/HttpClient.java, maven-plugins/bnd-maven-plugin/src/it/mr-jar/src/main/java/bnd/mr/example/Main.java, maven-plugins/bnd-maven-plugin/src/it/mr-jar/src/main/java11/bnd/mr/example/HttpClient.java, maven-plugins/bnd-maven-plugin/src/it/mr-jar/src/main/java9/bnd/mr/example/HttpClient.java
It compiles a class HttpClient in three flavors:
- default version (Java 8) that uses a library to perform some task not part of JDK 8
- version 9 (Java 9) that uses the now build in support added in JDK 9
- version 11 (Java 11) that uses the new Java HttpClient added in JDK 11
This emulates what one often find in external libs where OSGi headers has to be added as part of a maven build.
----
@pkriens (FYI @stbischof) Here we go with an MR-Maven-Build that is a common setup (e.g. on the [clickhouse-jdbc](https://github.com/ClickHouse/clickhouse-java) driver), currently it shows the following issues:
1. BND generates a module-info.class (but only in the versioned folders) even though JPMS is not enabled in the BND instructions
2. Java 9 + Java 11 Manifests import the package …
=> Add an example to verify maven multi-release jar build with maven

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
This is from #5130. This fix does not overwrite the internal source info for a package when it has already been set. 
Fixes #5130
=> Do not overwrite source info for packages 

biz.aQute.repository/src/aQute/p2/packed/Unpack200.java
The command was deprecated in later VMs
Fixes #5649
=> Updated Pack200 class to handle the absence of the command

biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java, biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Repository.java, biz.aQute.repository/src/aQute/bnd/repository/p2/provider/package-info.java
See https://bnd.discourse.group/t/multirelease-jar-and-resolution/308/7 for the sob story
It is complicated.
MRJs are now build as a SupportingResource. This is the primary resource and some other resources you need to properly resolve. For an MRJ this is a synthetic resource that contains a capability unique for the MRJ that requires the EE and the requirements specific for the EE.
I.e. in some places we need to be careful that we expand a Resource. These places are few.
In the P2Indexer, we had an optimization for refresh. The existing Resource objects were reused if the MD5 of a request matched the existing resource. If the existing resource was used, then there were two situations. The existing index had been parsed from the network. In that case things worked fine since the …
=> P2 Repositories lost synthetic resources for MRJs

biz.aQute.bnd.util/src/aQute/bnd/classfile/MethodParametersAttribute.java
A method parameter may not have a name.
Fixes https://github.com/bndtools/bnd/issues/5689
=> classfile: Properly handle unnamed MethodParameter

.github/workflows/cibuild.yml, .github/workflows/rebuild.yml
Java 20 is now supported by Gradle 8.1.
`:bndtools.core.test:testOSGi` tests are flaky and Java 20 seems to result
in consistent failures. So we disable this test on CI and remove the
use of `xvfb-run` as the runner since we don't need it with this test
disabled.
=> ci: use Java 20 instead of Java 19

gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPlugin.java, gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndUtils.java, gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BundleTaskExtension.java, gradle-plugins/biz.aQute.bnd.gradle/src/test/groovy/aQute/bnd/gradle/TestBundlePlugin.groovy, gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin5/build.gradle, gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin5/settings.gradle, gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin5/src/main/java/com/example/main/Main.java, gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin5/util/build.gradle, gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin5/util/src/main/java/com/example/util/Util.java
Using an ArtifactView avoids ordering issues when the Jar task is
realized prior to the compileClasspath configuration being modified
just before resolution.  It makes the attributes used to resolve
libraries more predictable, and prevents an internal behavior change in
Gradle 8.2 from affecting this process.
This also avoids modifying attributes on Gradle-created configurations,
which should be avoided.
=> gradle: Use an ArtifactView for jar library elements selection

cnf/ext/junit.bnd, gradle-plugins/biz.aQute.bnd.gradle/build.gradle.kts, gradle-plugins/biz.aQute.bnd.gradle/src/main/java/aQute/bnd/gradle/BndPlugin.java, gradle-plugins/biz.aQute.bnd.gradle/testresources/baselinetask1/build.gradle, gradle-plugins/biz.aQute.bnd.gradle/testresources/baselinetask2/build.gradle, gradle-plugins/biz.aQute.bnd.gradle/testresources/baselinetask4/build.gradle, gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin1/build.gradle, gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin3/build.gradle.kts, gradle-plugins/biz.aQute.bnd.gradle/testresources/builderplugin4/build.gradle, gradle-plugins/biz.aQute.bnd.gradle/testresources/indexplugin1/build.gradle, gradle-plugins/biz.aQute.bnd.gradle/testresources/testosgitask1/build.gradle
We cannot currently use Gradle 8.2 in the build due to https://github.com/gradle/gradle/issues/25609. The gradle plugin build requires no warnings (`--warning-mode=fail`). Once that fix is released, we can update the build to the fixed Gradle release.
=> Preparation to upgrade build to Gradle 8.2

biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, docs/_instructions/maven-release.md
The archive option used the context given in the RepositoryPlugin.put
as the base processor. This is true for the release process but
the `-buildrepo` option had a special install method in Project. This
method created a processor per file. This copied processor did 
not have the same file base nor did it collect the warnings and
errors.
=> Maven release archive option

maven-plugins/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java
=> When base is set but artifact not found, failOnMissing will be applied

biz.aQute.bndlib/src/aQute/bnd/build/7.1.0.bnd, biz.aQute.bndlib/src/aQute/bnd/osgi/About.java, biz.aQute.bndlib/src/aQute/bnd/osgi/package-info.java, cnf/build.bnd, gradle-plugins/README.md, gradle-plugins/gradle.properties, maven-plugins/bnd-plugin-parent/pom.xml
=> Start of 7.1.0

bndtools.m2e/src/bndtools/m2e/BndConfigurator.java
This PR prevents MojoExecutionExceptions when using the bndtools m2e plugin and maven-jar-plugin 3.x.
The exception occurs when saving files when "Build Automatically" is enabled. The first automatic build after saving the file works fine. On subsequent builds the artifact is set which causes the following exception to be thrown:
```
!SUBENTRY 1 org.eclipse.m2e.core 4 0 2023-09-09 13:30:47.366
!MESSAGE Failed to execute mojo org.apache.maven.plugins:maven-jar-plugin:3.3.0:jar {execution: default-jar}
!STACK 0
org.apache.maven.plugin.MojoExecutionException: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them.
at org.apache.maven.plugins.jar.AbstractJarMojo.execute(AbstractJarMojo.java:315)
at …
```
=> Fix MojoExecutionException in m2e plugin when using maven-jar-plugin 3.x

docs/_chapters/200-components.md, docs/_chapters/310-testing.md
This makes it easier to find the linked content.
=> Fix a few broken links

cnf/includes/bndtools.bnd
Fixes issue #5783
Since all `org.eclipse.jdt.internal.corext.refactoring` packages moved I updated the `eclipse.importpackage` rule to not add `bundle-symbolic-name` or `bundle-version` attributes for all of them.
This does result in many warnings about unused imports for `org.eclipse.jdt.internal.corext.refactoring.*` during the build.  Not sure if there is a better way to avoid that.  The other option is to place the rule in the `bnd.bnd` for only `bndtools.core` since that is the only bundle I see that actually uses anything from `org.eclipse.jdt.internal.corext.refactoring` but maybe that will change in the future?
=> Handle the internal refactoring packages moving bundles

cnf/includes/bndtools.bnd
=> Add package attribute "manipulation" to be ignored

biz.aQute.bndlib.tests/test/test/jpms/JPMSModuleInfoPluginTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/JPMSModule.java, biz.aQute.bndlib/src/aQute/bnd/plugin/jpms/JPMSModuleInfoPlugin.java, biz.aQute.bndlib/test/aQute/bnd/osgi/JPMSModuleTest.java
See  #5792
This PR fixes the module name. Expect a PR from @ppkarwasz for the second part
---
=> Cleans up the module names according to JPMS rules.

biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java, biz.aQute.bndlib/src/aQute/bnd/build/model/package-info.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java
For completeness, added missing mutator methods to the `BndEditModel` (I needed these for something else I'm working on).
=> [bndlib] Add mutator methods for -runbundles+ to BndEditModel

bndtools.core/src/bndtools/model/repo/RepositoryBundleUtils.java
Related to #5816 
This PR changes the behaviour of the .bndrun Editor when adding a bundle from a Repo to the Run Bundles panel,
a) via drag&drop
b) via the +-Button in the Run Bundles panel
The goal is that a version-range is used from the bundleVersion (inclusive) to the next major version (exclusive)
Before this change:
- bundle was added like `org.apache.felix.scr;version='2.2.2'` (which means "[2.2.2 and everything above](https://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#d0e2221)", which could be surprising, as it looks like an exact version match if you don't know the spec)
After this change:
- bundle gets added like org.apache.felix.scr;version='[2.2.2,3.0.0)'
Gets added as this.
Now it looks similar to what happens in the Run Requirements: …
=> use VersionRange when adding bundle to Run Bundles

aQute.libg/src/aQute/lib/comparators/Comparators.java, aQute.libg/src/aQute/lib/comparators/package-info.java, aQute.libg/test/aQute/lib/comparators/ComparatorsTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/package-info.java, biz.aQute.resolve/src/biz/aQute/resolve/AbstractResolveContext.java, biz.aQute.resolve/src/biz/aQute/resolve/package-info.java, biz.aQute.resolve/test/biz/aQute/resolve/ResolveTest.java, biz.aQute.resolve/test/biz/aQute/resolve/ResolverTester.java
=> Changed the comparators for Resource, Capability, and Requirement

bndtools.core.test/test.shared.bndrun, bndtools.core/bndtools.shared.bndrun
Noticed some errors when running the test Eclipse instances that were related to being unable to find SAX parsers. Adding the packages to boot delegation seems to fix the problem.
=> [bndtools] Update boot delegation directive to find missing SAX parsers

bndtools.core/src/bndtools/editor/project/AbstractRequirementListPart.java, bndtools.core/src/bndtools/editor/project/RepositoryBundleSelectionPart.java, bndtools.core/src/bndtools/model/repo/DependencyPhase.java, bndtools.core/src/bndtools/model/repo/RepositoryBundleUtils.java, bndtools.core/src/bndtools/wizards/repo/RepoBundleSelectionWizardPage.java, bndtools.core/test/bndtools/wizards/repo/RepoBundleVersionToRangeTest.java
Part 2 of #5816 handling the `-runrequires` part.
The following behavior is handled: Adding a bundle / bundleversion to the `-runrequires` section via Drag&Drop or the `+`-Button Wizard.
1. Adding / dragging a Workspace Bundle
Expected Result: bnd.identity;id='com.my.bundle'
2. Adding / dragging a repo bundle-version (leaf node)
Expected Result: bnd.identity;id='org.apache.felix.logback';version:Version='[1.0.2,2.0.0)'
3. Adding / dragging a repo bundle (root node without version)
Expected Result: bnd.identity;id='org.apache.felix.logback'
**-runrequires drag & drop**
- 1 & 2 are workspace bundles 
- 3 & 4 are Maven repo bundles
**-runrequires via + button**
```
-runrequires: \
bnd.identity;id='my.workspacebundle.core',\
bnd.identity;id='my.workspacebundle.core.apiservices',\ …
```
=> handle drag/drop/adding to -runrequires

biz.aQute.bndlib/src/aQute/bnd/service/Actionable.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/RepoActions.java, bndtools.core/src/bndtools/utils/HierarchicalLabel.java, bndtools.core/src/bndtools/utils/HierarchicalMenu.java, bndtools.core/src/bndtools/utils/LabelParser.java, bndtools.core/src/bndtools/views/repository/RepositoriesView.java, bndtools.core/test/bndtools/wizards/repo/HierarchicalLabelTest.java
This PR adds more Copy to Clipboard actions to a revision of a leaf entry of a Repository item:
For example for an entry of `com.fasterxml.jackson.core.jackson-databind` : 
`com.fasterxml.jackson.core:jackson-databind:2.13.4` is added to clipboard
The content of this tooltip when you hover over a leaf-entry is added:
```
com.fasterxml.jackson.core.jackson-databind
General data-binding functionality for Jackson: works on core streaming API
com.fasterxml.jackson.core.jackson-databind
SHA-256: C9FAFF420D9E2C7E1E4711DBEEBEC2506A32C9942027211C5C293D8D87807EB6
Coordinates: com.fasterxml.jackson.core:jackson-databind:2.13.4
```
is added to the clipboard.
I found this helpful because the tooltip currently cannot be copy pasted and the tooltip contains useful information.
``` …
```
=> Repositories View: MavenRepo: Add more copy to clipboard action menu entries on right click

bndtools.core/src/bndtools/views/repository/RepositoriesView.java
Fixes a small bug just found after https://github.com/bndtools/bnd/pull/5859 was merged.
It fixes the problem, that copy to clipboard on a RepoBundle did not copy anything to the clipboard.
@pkriens could you merged that too please?
=> Fix empty bundle info

bndtools.core/src/bndtools/editor/BndEditor.java
now you can click on Resolve multiple times which opens a new window everytime, so you can e.g. compare different results
Based on comment in https://github.com/bndtools/bnd/pull/5862#issuecomment-1792268413
=> make Resolve Window non-modal

biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java, bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionSuccessPanel.java, bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionWizard.java
Based on https://github.com/bndtools/bnd/pull/5863#issuecomment-1792931273
> I think you need to probably look what happens if you include the optional requirements. This will I think edit the BndEditModel but this can of course be edited from the main editor window as well now.
> 
> You need to make sure that if it can only be updated from one window. There is properties support in this class but optimistic locking is fine with me as well. If it has changed, you refuse to update.
When any other UI part / view changes something to the underlying BndEditModel (e.g. in the main window I edit and save the `.bndrun` file or I update optional requirements in one of the resolve windows then this change is detected and further updates fail.
The same behavior applies when clicking the "Update" …
=> Conflict handling when having multiple Resolve-results open and changes happen in resolve window(s) vs main window

biz.aQute.resolve/src/biz/aQute/resolve/ResolveProcess.java, bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionResultsWizardPage.java
Attempt to produce a more readable message from a failed Resolution instead of just "Resolution failed!"
New sentence reads:
> Resolution failed! You are missing a dependency containing the package / capability: "some.other.missing.package" (in version [2.3.0,3.0.0)). This is required by my.package.foo version=1.0.0).
Feel free to suggest better / different wording. But my goal was to make it an english sentence. 
I even thought about adding something like "e.g. search on google for `'some.other.missing.package jar'` and add that to your repository).
I tested it by removing some libraries on purpose from `central.maven` (then click on refresh Repositories) and then click "Resolve". This caused a previously successful resolution to fail.
This is just a first draft. If there is an agreement …
=> Improve Resolve failed message and make it more helpful

bndtools.core/src/bndtools/editor/common/HelpButtons.java, bndtools.core/src/bndtools/utils/EditorUtils.java, bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionResultsWizardPage.java, bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionSuccessPanel.java, bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionWizard.java
A few tweaks. See commit messages for details.
- added the word "not" in error message
- the ResolutionWizzard had a Help-Button (lower left) which was without function. I think it was there by default ,but nobody added functionality. I now linked to the manual (Resolving section)
- give two button methods from earlier  more appropriate names
Can be merged if no objections.
=> Fix typo error message, add help to Resolution Wizard, Method renaming

bndtools.core/src/bndtools/refactor/PkgRenameParticipant.java
* fixes #5891
* this fixes the NoClassDefFoundError: org/eclipse/jdt/internal/corext/refactoring/rename/RenamePackageProcessor because RenamePackageProcessor seems to be internal
* we loose a tiny bit of detail in the Rename dialog method but renaming works again
This sentence
was created by the touched code:
We loose the part of the sentence when the "Rename subpackages" checkbox was checked.
The checkbox is still working. It is just the sentence in the UI which does not mention this anymore.
I think that is a negligible compromise.
Edit:
I found that that package is marked as internal: `org.eclipse.jdt.internal.corext.refactoring.rename;x-internal:=true`
> The x-internal Directive
> The x-internal directive can be used in an Export-Package header to specify whether the package is an …
=> Remove usage of internal class RenamePackageProcessor

bndtools.core/src/bndtools/model/repo/RepositoryResourceElement.java
* before this change: double clicking on a result entry  of an Advanced search (e.g. by package name) nothing happened
* after this change: the jar of the bundle opens. this is now same behavior as double clicking on a bundleVersion in the repo browser without advanced search filtering
* filter the RepoBrowser e.g. by a specific package name
* then double click on one of the search results
* Expected Result: The Jar Viewer should open this entry.
=> open jar on dblclick on AdvancedSearch entry

bndtools.core/src/bndtools/core/console/AnsiHandler.java
fixes #5884
Not sure why console is null, but since it is passed from outside Eclipse framework it is not under our control. we should just handle the null case.
=> Avoid NPE in AnsiHandler.java

biz.aQute.bnd.reporter/bnd.bnd, biz.aQute.bnd/bnd.bnd, biz.aQute.launchpad.tests/bnd.bnd, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/FO.java, biz.aQute.launchpad.tests/test/aQute/xlaunchpad/LaunchpadRunnerBasicTest.java, biz.aQute.launchpad.tests/workspace.bndrun, biz.aQute.launchpad/bnd.bnd, biz.aQute.launchpad/missing.bndrun, biz.aQute.launchpad/runsystempackages.bndrun, biz.aQute.tester.test/base.bndrun, biz.aQute.tester.test/biz.aQute.tester.bndrun, biz.aQute.tester.test/bnd.bnd, biz.aQute.tester.test/bundleenginetest-noengines.bndrun, cnf/ext/central.mvn
Needed a newer framework in a test.
- Added Felix 7.0.5 to the repo
- Updated launchpad projects to use proper org.osgi.framework on -testpath
- Updated a number of bndrun files
Somehow also the reporter needed an update
- Updated parboiled
- Updated asm
=> Framework move to OSGi 1.10 & Felix 7.0.5

biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java
Currently if one creates a model from scratch the BndEditModel prefer the header-like one over the minus instruction.
To not confuse users with the old variant, this one give precedence over the header-like and also deprecate the old header like variant.
=> Prefer the minus instruction over the header like variant

biz.aQute.resolve/src/biz/aQute/resolve/AbstractResolveContext.java, biz.aQute.resolve/src/biz/aQute/resolve/BndResolutionException.java, biz.aQute.resolve/src/biz/aQute/resolve/ResolutionExceptionWithDetails.java, biz.aQute.resolve/src/biz/aQute/resolve/ResolveProcess.java
1st draft of an attempt to improve and enrich the Resolution failure output with information about blacklisted items which were not considered for resolution. The goal is to make it easier to spot resolution failure because of a too broad blacklist. This is based on a real use case (see https://github.com/bndtools/bndtools.workspace.min/pull/11#issuecomment-1827377986 ) where the blacklist was the reason for failed resolving, but the current tooling gave no indication about this.
Although it was an OSI-layer 8 problem, it would have made the chase easier, if there was some kind of pointer to the `-runblacklist`
```
Resolution failed. Summary:
⇒ Bundle: servicetest.consumer cannot be resolved
⇒ Extender: &(osgi.extender=osgi.component)(version=[1.5.0,2.0.0)) cannot be resolved
⇒ because …
```
=> Show blacklisted req/caps on resolve failure

bndtools.core/bnd.bnd
Finally had to give in, is adding the org.eclipse.jdt.ui bundle as Require-Bundle because it is sooooooo difficult to keep package packages, it is much better split :-(
Fixes #5908 I hope.
---
=> #5908 Split package problems in eclipse

bndtools.core/bndtools.shared.bndrun
Eclipse seems to use boot delegation for javax.*. Since we're not doing this in our debug setup, we get errors. This patch just does the same brain damaged thing
Eclipse is doing to mitigate even brain deader
bundles. Yes, I am frustrated, bnd fixed this problem 20 years ago!
Fixes #5911
---
=> Eclipse hack boot delegation

biz.aQute.bndlib.tests/test/aQute/bnd/osgi/resource/CapReqBuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapReqBuilder.java, bndtools.core/bnd.bnd, bndtools.core/src/bndtools/views/ViewEventTopics.java, bndtools.core/src/bndtools/views/repository/AdvancedSearchDialog.java, bndtools.core/src/bndtools/views/repository/RepositoriesView.java, bndtools.core/src/bndtools/views/resolution/ResolutionView.java
During debugging some dependency issues the ResolutionView is a valueable tool to see who requires and provides what. I wished it would be possible to e.g. "click" on a package and do an advanced search for it in the Repositories Browser to see which bundle(s) provide(s) this capability
Suggestion for the problem above.
- Double Clicking on an entry of the ResolutionsView (Requirements and Capabilities) now opens the AdvancedSearch of Repository Browser in the "Other" tab and prefills the fields for namespace and filter.
- Existing behavior is kept ( Clicking on a Java Class in Requirements still opens the java file in the editor) (TODO Although I noticed some flaky behavior where the loaders are sometimes cleared so that the class does not open.  )
- this speeds up workflows where you …
=> Add double click handler resolutionview

biz.aQute.bndlib.tests/test/aQute/bnd/osgi/resource/CapReqBuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java, bndtools.core/src/bndtools/model/resolution/CapReqMapContentProvider.java, bndtools.core/src/bndtools/model/resolution/RequirementWrapper.java, bndtools.core/src/bndtools/views/resolution/ResolutionView.java
- First draft to show simple counters to easier spot unresolved requirements.
- reqs resolution := optional are not counted as unresolved.
=> Show numResolved / numUnresolved in resolution view

docs/_chapters/130-concepts.md, docs/_chapters/790-reference.md, docs/_data/sidebar.yml
=> Clarify configuration file format

bndtools.core/src/bndtools/model/resolution/CapReqMapContentProvider.java, bndtools.core/src/bndtools/model/resolution/CapabilityLabelProvider.java, bndtools.core/src/bndtools/model/resolution/RequirementWrapper.java, bndtools.core/src/bndtools/model/resolution/RequirementWrapperLabelProvider.java, bndtools.core/src/bndtools/tasks/BndBuilderCapReqLoader.java, bndtools.core/src/bndtools/tasks/ResourceCapReqLoader.java, bndtools.core/src/bndtools/views/resolution/ResolutionView.java
this allows more fine grained Glob filtering e.g. on the resource name e.g. using "FROM:*mypackage" which allows to filter reqs and caps based on their underlying resources
In the example below I have selected
- a bundle
- and the complete Maven Central repo in the repo browser
- the requirements I have filtered so that I only see requirements coming from my bundle which contains the letters "obs" in the resource name
This is very handy in the use case where I am particularly interested in e.g. requirements of a particular resource. 
E.g. in my case I wanted to find out all reqs of my bundle which are not satisfied by Maven Central so that I can drag them into .bnd Editor "Customize Imports" and mark them as _optional_
=> Resolution view: allow reqs/caps filtering on the tooltip text

aQute.libg/src/aQute/libg/re/Catalog.java, aQute.libg/src/aQute/libg/re/RE.java, aQute.libg/test/aQute/libg/re/RETest.java
- group name handling for Options
- added a few constants
- group matching safety checks
---
=> small corrections on RE

biz.aQute.bndlib.tests/test/test/IncludeResourceTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/DirectoryResource.java, docs/_instructions/includeresource.md
=> Added an option to add a directory as a jar/zip file

biz.aQute.bndlib/src/aQute/bnd/osgi/repository/BridgeRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomRepository.java, biz.aQute.repository/test/aQute/bnd/repository/maven/helpers/MavenRepoTestHelper.java, biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java, biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java, biz.aQute.repository/testdata/pomrepo/simpleGetViaBSNAndGAV.xml
Closes #5961 
This PR should fix the problem that for a valid OSGi bundle MavenBndRepository.get(bsnOrGav) can be used with bsn or gav and returns something. 
BndPomRepostory.get() instead only works with the bsn for a valid OSGi bundle. (Non OSGi bundles which do not have a bsn meta data can only be looked up by gav wich works as expected)
This PR's goal is to make both repos behave the same and support bsn or gav for OSGi bundles.
=> BndPomRepository should support both bsn and gav like MavenBndRepository

bndtools.core/src/org/bndtools/refactor/util/RefactorAssistant.java, bndtools.core/test/org/bndtools/refactor/types/ComponentRefactorerTest.java
The RefactorAssistant lazily initialized the imports translation. However, the fixup() method that cleaned up any unused imports assumed it was initialized. So if there was a case without any resolved import, the fixup failed.
=> Imports were lazily handed but the fixup required the original imports

bndtools.jareditor/src/bndtools/jareditor/internal/JarFileSystem.java
See https://github.com/eclipse-platform/eclipse.platform/issues/1114
---
=> NPE on File System Compare

.github/workflows/cibuild.yml, .github/workflows/rebuild.yml
The Dependabot #5988 fails to rebuild. I suspect this is caused by asymmetry in the upload/download actions. So lets try with readable versions.
---
=> Dependency bot does not get the action/upload version bumped

maven-plugins/bnd-resolver-maven-plugin/README.md, maven-plugins/bnd-resolver-maven-plugin/src/it/parent/pom.xml, maven-plugins/bnd-resolver-maven-plugin/src/it/verify/invoker.properties, maven-plugins/bnd-resolver-maven-plugin/src/it/verify/pom.xml, maven-plugins/bnd-resolver-maven-plugin/src/it/verify/test.bndrun, maven-plugins/bnd-resolver-maven-plugin/src/main/java/aQute/bnd/maven/resolver/plugin/VerifierMojo.java
The  goal provides a way to validate that a set of run bundles is a valid resolution. It does this by creating a set of run requirements requiring each run bundle by identity and performing a resolve operation. This resolve operation forbids any capabilities that come from bundles not in the list of run requirements. If the resolution succeeds then it is further checked against the orginal run requirements.
If these checks pass then we know that:
* The resolution is valid
* The resolution satisfies the original run requirements
This is useful for CI when we want to test that a checked-in bndrun file has been correctly resolved.
Fixes #5984
=> Add a verify goal to the bnd-resolver-maven-plugin

maven-plugins/bnd-resolver-maven-plugin/src/it/verify/pom.xml, maven-plugins/bnd-resolver-maven-plugin/src/it/verify/test.bndrun, maven-plugins/bnd-resolver-maven-plugin/src/main/java/aQute/bnd/maven/resolver/plugin/VerifierMojo.java
The test case used to test the verifier was too simple, and failed to identify that the wrong requirement was being tested in the ResolutionCallback. This commit makes the test more extensive, and fixes the bug.
=> Fixes for the bnd-resolver-maven-plugin verification

biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java, biz.aQute.bndlib/src/aQute/bnd/component/ReferenceDef.java
The error messages when handling field/constructor injection with Collection types are somewhat confusing, in that they don't explain what the correct usage would be. This is particularly problematic with collection subclasses. This commit attempts to improve the error messages, and to improve the naming of an internal field which is used to track the fact that a DS reference is a collection type which is not `Collection` or `List`
See also #5994
=> Improve error reporting for DS annotations

bndtools.core/src/bndtools/wizards/project/NewBndProjectWizard.java
During the template selection the finish button was enabled but this can't happen because we miss the name. This is a mess because it is based on the Java Wizard but we do not need most of the information. Should be rewritten but not on my list right now.
---
=> Finish button enabled during template selection

bndtools.core/src/bndtools/editor/project/RunRequirementsPart.java
This fixes the problem that the runrequirements get deleted if you click the resolve button too fast when the runrequirements part has not been loaded yet.
Closes #6028
=> refreshFromModel() before resolving

bndtools.core/src/bndtools/launch/util/LaunchUtils.java, bndtools.m2e/src/bndtools/m2e/MavenRunProvider.java
After some thinking, I came to the decision that it is hard to decide, wether or or no resolving is required.
So the best way seems to present a meaningful message to the user.
This proposal presents a possible solution
=> fixes #5982 create an error message

bndtools.jareditor/src/bndtools/jareditor/internal/JarFileSystem.java
Turns out the path we gave it was not absolute.
---
=> Still had NPEs in the null file system

biz.aQute.bndlib.tests/test/test/ProcessorTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
@chrisrueger is working on editing the plugins. Since merged properties, the edit panes in the build.bnd 
editor and the bnd.bnd editor are a bit of a mess. 
This change in processor adds the concept of a PropertyKey, where the Property Key links the Processor that defines the property and the actual key. So a merged property is translated to a properly sorted set of ProperyKeys and can then be edited with the BndEditModel.
Unfortunately, the BndEditModel had no proper knowledge of the Processor. For this reason, a findProcessor method was added to Workspace and Project to find the a Processor that is properly linked with inheritance.
---
=> Add support for PropertyKeys, where these records pair the Processor/key

bndtools.core/src/bndtools/central/sync/SynchronizeWorkspaceWithEclipse.java
Fixes #6077. Stupid mistake. I activated a watcher and that deleted the project before the wizard was finished because it did not exist in the bnd workspace. I would like to remove the Java Wizard since we have all our details in the cnf/build.bnd
---
=> Synchronizer Eclipse/Bnd was activated

biz.aQute.bndlib.tests/test/test/BndEditModelTest.java, biz.aQute.bndlib.tests/test/test/PropertiesTest.java, biz.aQute.bndlib.tests/test/test/bndmodel/BndModelTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/SubProject.java, biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.resolve/src/biz/aQute/resolve/Bndrun.java, biz.aQute.resolve/test/biz/aQute/resolve/ResolveTest.java, biz.aQute.resolve/test/biz/aQute/resolve/ResolverTester.java, bndtools.core/_plugin.xml, bndtools.core/src/bndtools/editor/BndEditor.java, bndtools.core/src/bndtools/editor/project/RepositoriesEditModel.java, bndtools.core/src/bndtools/editor/workspace/PluginsPart.java, bndtools.core/src/org/bndtools/core/resolve/ResolveOperation.java
Now properly reflects the inheritance structure of Processor chains
@chrisrueger I made a few changes to your code, please verify
---
=> Update of BndEditModel

biz.aQute.repository/src/aQute/p2/api/Artifact.java, biz.aQute.repository/src/aQute/p2/api/package-info.java, biz.aQute.repository/src/aQute/p2/provider/ArtifactRepository.java
Closes [issue #6062](https://github.com/bndtools/bnd/issues/6062).
=> add access artifact properties through api

bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionFailurePanel.java, bndtools.core/src/org/bndtools/core/resolve/ui/UnresolvedRequirementsContentProvider.java
This PR adds a search bar to this view:
I found that helpful, because before I could never make sense of that list, because I couldn't "see" / or "find" anything (can't see the forest for the trees). 
Now the search bar at least allows to search for anything from the error message above, and maybe find what is of interest for you. 
Note on search bar positioning: The search bar currently is at the bottom, because I could't find a way to add it below the "Unresolved requirements" header. I managed to add it right _above_ the "Unresolved requirements" header, but there I did not like it because it does not look like it belongs to the "Unresolved requirements".
Maybe because it is a collapsible tree or some view panel which does not allow this. I don't know.
I personally don't find that bad, …
=> Add search bar to Unresolved requirements in ResolutionFailedPanel

biz.aQute.bnd/src/aQute/bnd/main/MbrCommand.java, biz.aQute.repository/bnd.bnd, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenVersionResult.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/Mbr.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MbrUpdater.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/RepoActions.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/package-info.java
This PR is a suggestion for bnd's [MbrCommand](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd/src/aQute/bnd/main/MbrCommand.java) e.g. `bnd mbr update -s micro` but making it available in bndtools' UI. 
This adds a context menu when you Right-Click on a _MavenBndRepo_ like this:
This allows to increase versions of a full `central.mvn` maven index file. 
Similar functionality already exists if you right-click on a **single** RepoBundle-**Revision**. This suggestion here basically does it for the whole repository. 
I added a Dry-Run-Option which does _not_ modify the .mvn file, but instead copies the result to the Clipboard.
I am not sure if this is a good idea, since it can take some time depending on the size of the repo and the user might not notice it... UX isn't great. I …
=> Repository Browser: Add context menu action "Update Revisions :: To higher MICRO / MINOR / MAJOR revision"

biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java
See https://github.com/bndtools/bnd/issues/6123#issuecomment-2126543736 and https://bnd.bndtools.org/instructions/connection-settings.html
this helps to notice at least in the a logfile that HTTP Connection settings were overwritten in a `connection-settings.xml` or `settings.xml` or set via `-connection-settings`
this can help to save hours of painful debugging when you have forgotton about those settings.
This PR adds a log output like this:
**slf4j logger**
```
[main] INFO aQute.bnd.connection.settings.ConnectionSettings - [ConnectionSettings] Read from file: /Users/home/.bnd/connection-settings.xml (See https://bnd.bndtools.org/instructions/connection-settings.html for more information)
```
**bnd processor.trace() system.out**
```
[ConnectionSettings] Read from file: …
```
=> improve logging for connections settings files

aQute.libg/src/aQute/lib/collections/SortedList.java, aQute.libg/src/aQute/lib/collections/package-info.java
=> Implement new JDK21 SortedSet and List methods for SortedList

biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java, bndtools.core/_plugin.xml, org.bndtools.templating.gitrepo/resources/processed/org/bndtools/templating/jgit/initialrepos.txt
This PR basically changes the default value for a repo index file when adding / editing repos via plugin editor. The previous default was not good, because it contained the `${.}` which causes some surprising behavior.
Not sure if this is related to https://github.com/bndtools/bnd/commit/f37f8574b7e887644c036cea073d19d853072159
the ${.} in the default-value caused to expand the value always to an absolute path on the harddrive of the developer editing and saving the file. if you accidentally commit this, then it wil fail on other machines. Let's just define the name, relative to the build.bnd . it can still be changed manually
**Steps to reproduce:**
1. Add a  MavenBndRepository to the `build.bnd` a config like below
Notice an `index=${.}/central.maven; \` is added (because this was the …
=> build.bnd: avoid resolving default containing ${.} to absolute path

biz.aQute.bndlib/src/aQute/bnd/wstemplates/TemplateID.java, bndtools.core/src/bndtools/wizards/newworkspace/Model.java, org.bndtools.templating.gitrepo/resources/processed/org/bndtools/templating/jgit/initialrepos.txt
Closes #5955
from initialrepos.txt, because in https://github.com/bndtools/bnd/issues/5955 we kind of agreed to remove https://github.com/bndtools/workspace workspace template and just keep the bndtools/bndtools.workspace.min , because workspace templates will most likely be superseded by Template Fragments
After this the Create Workspace dialog looks like this for new users.
=> Workspace templates: remove old bndtools/workspace

bndtools.core/bndtools.cocoa.macosx.aarch64.bndrun, bndtools.core/bndtools.cocoa.macosx.x86_64.bndrun, cnf/ext/central.mvn
Closes #6185 
It seems we can stay on older Eclipse 4.25 but use a higher SWT version which has fixed the SWT bug (see https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012).
With this fix I was able to use Eclipse with latest Temurin JDKs like
- OpenJDK Runtime Environment Temurin-17.0.11+9
- OpenJDK Runtime Environment Temurin-21.0.3+9
and it looks as usual again:
=> upgrade SWT to 3.126 to fix MacOS / JDK bug

bndtools.core/src/bndtools/central/EclipseWorkspaceRepository.java, bndtools.core/src/bndtools/wizards/project/NewBndProjectWizard.java, org.bndtools.templates.template/resources/bndrun.help.xml, org.bndtools.templates.template/resources/project.help.xml
This fixes the problem, that newly created "project template"-projects required a Eclipse restart to show up in the **New Bnd Project** wizard.
See https://bnd.discourse.group/t/enabling-template-repositories-by-default/460/5
This PR makes sure that new Project templates always / immediately show up in the "New Bnd OSGi Project" wizard, after creation.
=> fix new project templates not showing up

bndtools.core/src/bndtools/central/RepositoriesViewRefresher.java
Closes #6213 
This is an improvement of commit 0e1fac345 in PR #6191
We now hook into the RepositoriesViewRefresher which already gets triggered after projects have been built to update the Repositories list. The only thing which is missing here is a Refresh of the EclipseWorkspaceRepository, which is needed so that new "Project template projects" show up immediately in the "New Project" wizard.
The advantage over PR is than no manual user action is needed (e.g. no click on "Refresh button in Repositories browser")
1. Open **File / New / Bnd OSGi Project** and create a Template project e.g. mustache
Give it a name and click finish.
2. quickly Open **File / New / Bnd OSGi Project** again and check if the new template appears.
=> Refresh the EclipseWorkspaceRepository in RepositoriesViewRefresher

biz.aQute.bndlib/src/aQute/bnd/help/instructions/ResolutionInstructions.java, biz.aQute.bndlib/src/aQute/bnd/help/instructions/package-info.java, biz.aQute.resolve/src/biz/aQute/resolve/Bndrun.java, biz.aQute.resolve/src/biz/aQute/resolve/RunResolution.java, docs/_instructions/resolve.md
Sometimes you have e.g. a basic bnd(run) that can be resolved and others that include that file and add other instructions or bundles. In such a case developers may hit resolve on reflex and can result in diverging -rundbundes over time. Resolve never is an option to prevent developers from accidentally doing this.
=> introduces resolve never option for bnd(run)

bndtools.core/src/bndtools/javasearch/JavaSearchStartupParticipant.java
Closes #6199
This hopefully fixes the NPE in `org.eclipse.jface.resource.JFaceResources.getResources(Display)` which expects the current display
**For the record:** I did not do the same in `JavaSearchStartupParticipant.stop()` because then I got the following when exiting the Debug Eclipse instance:
```
g! 2024-08-17 13:06:01,117 [Framework stop - Equinox Container: 08c6cf07-37df-4845-b378-a729e987b66a] ERROR org.eclipse.equinox.logger - Error stopping startup participant
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Display.syncExec(java.lang.Runnable)" because the return value of "org.eclipse.swt.widgets.Display.getCurrent()" is null
at bndtools.javasearch.JavaSearchStartupParticipant.stop(JavaSearchStartupParticipant.java:51)
at …
```
=> Fix NPE by executing JavaSearchStartupParticipant.start() in Display.getCurrent()

maven-plugins/README.md, maven-plugins/bnd-maven-plugin/README.md, maven-plugins/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
Based on comment https://github.com/bndtools/bnd/issues/6221#issuecomment-2296567709
This fixes a problem where a 'mvn process-classes' picked up `target/classes/META-INF/MANIFEST.MF` from a previous build and produced a new MANIFEST.MF based on the results of the previous build... which should not happen.
We now delete the existing `target/classes/META-INF/MANIFEST.MF` if it exists.
Now this gives consistent results for the following case:
```
mvn clean process-classes
mvn clean process-classes
```
or 
`mvn clean process-classes`
followed by a
`mvn process-classes`
@pkriens I wonder how this PR affects the statement in 
https://github.com/bndtools/bnd/blob/c1bb1658ee3cdd4d7052a3722af3afb107f96828/maven-plugins/bnd-maven-plugin/README.md?plain=1#L111
=> bnd-maven plugin: delete existing MANIFEST.MF from previous build

biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, maven-plugins/bnd-generate-maven-plugin/src/main/java/aQute/bnd/maven/generate/plugin/BndContainer.java
Fixes a Bug, where the created project for the code generator in maven is invalid, if no bnd file exists.
=> checks Project validity and handles projects without bnd.bnd file

biz.aQute.bndlib.tests/test/test/ResourceTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java, bndtools.core/src/bndtools/model/repo/RepositoryBundleVersion.java, bndtools.core/src/bndtools/model/repo/SearchableRepositoryTreeContentProvider.java, bndtools.core/src/bndtools/views/repository/RepositoriesView.java
For debugging purposes it is useful to identify bundles containing substitution packages (especially such without a version range)  (see https://docs.osgi.org/specification/osgi.core/8.0.0/framework.api.html#org.osgi.annotation.bundle.Export.Substitution and  https://docs.osgi.org/specification/osgi.core/8.0.0/framework.module.html#i3238802 and
https://docs.osgi.org/specification/osgi.core/8.0.0/framework.module.html#framework.module-import.export.same.package ). 
I added this to the Repo-Browser on **Right Click on a Repo / Copy to Clipboard / Bundles with Substitution packages**. It outputs a simple list to the clipboard which can be pased to a texteditor for further analysis. In the future this might be refactored into more sophisticated solution but for the moment it is already …
=> RepoView: Add to Clipboard: Bundles with substitution packages / self-imports

biz.aQute.bndlib.tests/test/test/MultiReleaseTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceImpl.java
Added a content cap in the synthetic resource so equals works. Turned out hashcode did not work well in ResourceImpl so also fixed this.
Fixes #6212
---
=> #6216 no locations in synthetic resources made for MRJs.

biz.aQute.repository/src/aQute/maven/provider/POM.java
- For the simple get() method, simply use DOM methods instead of going through XPath
I have tried to profile the issue again, but so far have not been able to encounter the situation where this `get()` method is called again. I even tried setting a breakpoint in the method while using Eclipse "in production" - but so far, the breakpoint did not hit again...
=> Issue #6273: Accessing POM via XPath is very slow

bndtools.core/src/bndtools/views/resolution/ResolutionView.java
the wording of the button for  hideSelfImportsFilter was not clear and misleading.
After working on https://github.com/bndtools/bnd/pull/6270 I finally understood what this button actually does.
=> Resolution view: improve wording of hideSelfImportsFilter Button

docs/_instructions/init.md
this fixes the  Error: YAML Exception reading bnd/docs/_instructions/init.md: (<unknown>): mapping values are not allowed in this context at line 4 column 13
and finally makes the init macro appear in the list
=> fix docs build of init.md instruction

biz.aQute.remote/src/aQute/remote/agent/AgentServer.java
With a remote agent and remote console running exception (stack traces) on the agent will printout to the remote console resulting in a clattered output as the shell tries to interpret them as commands.
```
g! gogo: CommandNotFoundException: Command not found: org.osgi.framework.BundleException:
g! gogo: IOException: no matches found: org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1352)
g! gogo: EOFException: Expected file name for redirection
g! gogo: IOException: no matches found: org.apache.felix.framework.Felix.installBundle(Felix.java:3287)
g! gogo: IOException: no matches found: org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
g! gogo: IOException: no matches found: …
```
=> Print remote agent stack traces to the System.err instead of remote console

biz.aQute.bndlib/src/aQute/bnd/wstemplates/FragmentTemplateEngine.java, bndtools.core/src/bndtools/wizards/newworkspace/NewWorkspaceWizard.java
- show green icon for bndtools org (ours) or 3rd-party with a specific commit SHA
```
-workspace-templates \
bndtools/workspace-templates/gradle; \
name=gradle; \
description="Setup gradle build for bnd workspace", \
bndtools/workspace-templates/maven; \
name=maven; \
description="Use the maven directory layout for sources and binaries", \
bndtools/workspace-templates/osgi; \
name=osgi; \
description="OSGi R8 with Felix distribution", \
mnlipp/de.mnl.osgi/de.mnl.osgi.bnd.repository/workspace-template#b96e0a8877bad1c68cdc050d5854829253ef63bb; \
name=IndexedMavenRepository; \
description="Provide an OSGi repository derived from a subset of one or more maven repositories"
```
would show all green (notice the commit SHA at the end of the last entry):
- show greyish icon for 3rdParty template …
=> improve TemplateFragment icons

biz.aQute.bndlib/src/aQute/bnd/service/Registry.java, biz.aQute.bndlib/src/aQute/bnd/service/RepositoryPlugin.java, biz.aQute.bndlib/src/aQute/bnd/service/tags/Tags.java, biz.aQute.repository/test/aQute/bnd/repository/maven/provider/WorkspaceTest.java
As discussed with @pkriens today:
- The Repo Browser does not show 'resolve' tag anymore, for repos which do not have defined a tag
- instead only if developer has manually entered a tag in a repo it is shown
Also fixed a bug I discovered regarding Repository implementations which currently do not implement the `Tagged` interface. Those repositories should still be considered for resolution by default (as if they have the `resolve` tag). This is e.g. the case for any custom Respository plugin in the wild which `implements Repository` but not Tagged (because Tagged interface is just being added in 7.1.0)
=> Improve repo tagging

biz.aQute.bndlib.tests/test/test/ProcessorTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
=> Added a method to get the Macro references from a Processor

maven-plugins/bnd-maven-plugin/src/it/bnd-process-conditional/README.txt, maven-plugins/bnd-maven-plugin/src/it/bnd-process-conditional/invoker.properties, maven-plugins/bnd-maven-plugin/src/it/bnd-process-conditional/other.bnd, maven-plugins/bnd-maven-plugin/src/it/bnd-process-conditional/pom.xml, maven-plugins/bnd-maven-plugin/src/it/bnd-process-conditional/postbuild.groovy, maven-plugins/bnd-maven-plugin/src/it/bnd-process-conditional/src/main/java/org/example/impl/Config.java
This adds a testacse where conditional package is used with  bnd-process
=> Add testcase for conditional packages with bnd-process

docs/_chapters/170-versioning.md, docs/_heads/import_package.md, docs/_macros/range.md
Closes #6372 
In this PR:
- fixed a broken link
- added new links to existing pages where I thought it would improve understanding (by inter-connecting already existing related pages)
- added more examples for `versionmask` and `range` macro
=> Docs: Fix broken link to version policy

maven-plugins/bnd-baseline-maven-plugin/pom.xml, maven-plugins/bnd-reporter-maven-plugin/pom.xml
It has shown that the invoker-test in this setup could pull in an outdated artifact if it is not declared as a *direct* dependency.
This adds an explicit dependency to biz.aQute.bnd.maven so we always use the current build version.
This was extracted from
- https://github.com/bndtools/bnd/pull/6362
as it actually do not belong to that change and is a configuration change only that can be merged independently.
=> Add explicit dependencies to biz.aQute.bnd.maven

bndtools.builder/src/org/bndtools/builder/CnfWatcher.java
This fixes an annoyance, that Bndtools Workspace Problem Markers in `/cnf/build.bnd` where not removed from Eclipse's Problem-View, although you have fixed a problem. The reason was that model.getErrors() and model.getWarnings() used by org.bndtools.builder.MarkerSupport.setMarkers(Processor, String) where never cleared, so the errors and warnings where always re-added.
@pkriens we just talked about this today
1. Make a syntax error in `/cnf/build.bnd `
2. check Eclipse's Problem view that it creates an error marker of type `Bndtools Workspace Problem Marker`
3. Now fix the syntax error.
Expected behavior:
- The marker should also be removed from Eclipse's Problem view
Actual behavior before fix:
- the marker stayed there (in fact it was deleted but re-added...but very quickly)
=> Remove fixed bnd workspace problem markers from Problem view again

biz.aQute.launcher/src/aQute/launcher/Launcher.java
Related to #6370
hope to fix a Java 24 build problem, where the Launcher isn't working with Java 24.
@pkriens is this something which should still go to 7.1.0 ?
And also: I added Java 23 temporarily to the build (Java 24 was not available in the Github actions... probably because it is still early access @timothyjward ). But maybe we already see something with JDK23. 
@scordio Are you able to test this fix in your build with Java 24 to see if it fixes your problem?
=> Fix Bnd Launcher with Java 24

bndtools.core/src/bndtools/central/sync/WorkspaceChange.java, bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java
This improves the DX in the following scenario:
When you edit any file inside the `cnf` folder like `/cnf/build.bnd` and you Save the file before this fix, a FULL build was always triggered (by `CnfWatcher.java`), even if `Project / Build Automatically` was disabled. (and such a build can take very long and can become anoying in cases where you need tweak build.bnd) 
Now a build is only triggered if `Build Automatically`  is **enabled**. This at least gives the developer a knob to disable the build-on-change behavior in cases where you work on the file and want to save it a few times along the way (without waiting for a build everytime)
A warning is written the Error Log to make it visible somewhere:
**Note:** The "Reload Workspace" Button in the Bndtools Explorer is also affected by this …
=> cnf change: prevent full build although 'Build automatically' is disabled

docs/_includes/footer.htm, docs/css/style.scss
this makes it easier to send a link to a specific section to somebody. just hover over the headline and click on the little '#' symbol. now copy&paste the URL in the browser which contains the #anchor to this section.
=> Docs: add anchor links to all headlines

biz.aQute.bndlib.tests/test/test/MavenTest.java
---
Signed-off-by: github-actions <github-actions@bndtools.org>
=> The https://repository.springsource.com repo disappeared

aQute.libg/src/aQute/lib/json/JSONCodec.java
The parseString method skips whitespace after the " or ' character. This is obviously wrong. next() was called instead of read to 'eat' the quote character
---
Signed-off-by: github-actions <github-actions@bndtools.org>
=> Whitespace after the quote character is skipped

aQute.libg/src/aQute/lib/utf8properties/PropertiesParser.java, aQute.libg/src/aQute/lib/utf8properties/UTF8Properties.java, aQute.libg/src/aQute/lib/utf8properties/package-info.java, aQute.libg/test/aQute/lib/utf8properties/UTF8PropertiesTest.java, biz.aQute.bndlib.tests/test/test/ProcessorTest.java, biz.aQute.bndlib.tests/testresources/provenance/bnd.bnd, biz.aQute.bndlib/src/aQute/bnd/build/MagicBnd.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java, biz.aQute.bndlib/src/aQute/bnd/build/package-info.java, biz.aQute.bndlib/src/aQute/bnd/maven/package-info.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.bndlib/src/aQute/bnd/osgi/package-info.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/package-info.java, biz.aQute.bndlib/src/aQute/bnd/print/package-info.java, biz.aQute.bndlib/src/aQute/bnd/service/generate/package-info.java, bndtools.core/src/bndtools/editor/BndEditor.java, bndtools.core/src/bndtools/editor/BndSourceEffectivePage.java, bndtools.core/src/org/bndtools/core/ui/ExtendedFormEditor.java
adds a first draft of an readonly "Effective Source view" of a Bnd Editor based on comment https://github.com/bndtools/bnd/pull/6401#issuecomment-2540856340
> It shows you all the effective properties with inheritance and includes.
- supports find text via CMD+F
- add Syntax highlighting (same as Source view)
This is a nice additional debugging tool, because it makes things visible to the human eye, which were previously hidden. 
Comment about code: I reused some code of the JarEditor (JarPrintPage.java) and added search-dialog and syntax highlighting. Sorry if this is not state-of-the-art Eclipse JFace code.
=> first draft of Effective tab for BndEditor

docs/_instructions/nouses.md
=> improve description of -nouses

aQute.libg/src/aQute/libg/re/Catalog.java, aQute.libg/src/aQute/libg/remote/sink/RemoteSink.java, biz.aQute.bndlib/src/aQute/bnd/build/model/EE.java, biz.aQute.bndlib/src/aQute/bnd/build/model/clauses/ImportPattern.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java
I just ran spotbugs on libg and bndlib and checked for a few low hanging fruits like dead store variables.
=> Fix some spotbugs findings

bndtools.core/src/bndtools/wizards/newworkspace/NewWorkspaceWizard.java, bndtools.core/src/org/bndtools/core/ui/wizards/shared/TemplateSelectionWizardPage.java, org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/Cache.java, org.bndtools.templating.gitrepo/src/org/bndtools/templating/jgit/GitHub.java
This PR is about error handling the following two wizards:
This shows an ErrorDialog the UI when there are problems fetching from Github. The error message also includes a hint to https://bnd.bndtools.org/instructions/connection-settings.html because sometimes you have a ~/.m2/settings.xml with some credentials which can lead to "Bad Credentials" http errors from the Github API, but before this fix you had no idea what was going on, because the UI was blank and the existance of ~/.m2/settings.xml is easily forgotten
The message reads (wording improvements welcome):
> 
> Failed to load from template loader (Load workspace templates from GitHub repositories) See Error Log for stack trace: 
> java.io.IOException: Error (HTTP 520) - no response: TaggedData [tag=, code=520, modified=Thu Jan 01 …
=> Workspace Templates: show error when fetching templates from Github

bndtools.jareditor/resources/plugin.xml
Now that PDE is shipping the jar editor I noticed since a while that a folder/project .BndtoolsJAREditorTempFiles is shown, even though there is a filter to hide it.
Looking a bit closer it seems to me that while it was renamed three years ago to start with a dot the actual filterExpression was not adjusted (only the description/name)
=> Fix missing '.' in filter name

biz.aQute.bndlib/src/aQute/bnd/osgi/MessageReporter.java
`MessageReporter#details` return `null` instead of `this` leading to NPE if one relies on chaining method calls.
=> Fix MessageReporter#details return null instead of this

biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/configuration/BndConfiguration.java, biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/configuration/package-info.java, maven-plugins/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
Currently if one loads the configuration with
`aQute.bnd.maven.lib.configuration.BndConfiguration` then only the
configuration itself is loaded, but actually some implicit configuration later apply (e.g. from the maven project configuration)
that is currently only performed by the `AbstractBndMavenPlugin`.
This extracts this logic from the `AbstractBndMavenPlugin` into the
`BndConfiguration` class for the following benefits:
- making the `AbstractBndMavenPlugin` maintain less code in the execute
method
- allow other users of `BndConfiguration` to easily inherit common
defaults
- separation of concerns, easier to debug and understand
=> Extract code to automatically derive data from maven-project

bndtools.core/src/bndtools/wizards/newworkspace/NewWorkspaceWizard.java
We have some upcoming templates with longer names. In order to display them better we should make the column a bit wider
=> Template Fragments Wizard: increase column with of template name

maven-plugins/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
According to aQute.service.reporter.Reporter.SetLocation.line(int) javadoc "Line 0 is the top line" but BuildContext#addMessage says "Use 1 (not 0) for the first line" so when converting from bnd location > build context we need to add one to the line.
=> Fix of-by-one error in AbstractBndMavenPlugin

docs/_heads/export_package.md, docs/_instructions/exportcontents.md, docs/_instructions/sub.md
I accidentally removed them earlier, but they were needed in the overview pages.
=> add back summary in markdown frontmatter block

docs/_config.yml, docs/robots.txt
everything under urls like https://bnd.bndtools.org/releases/ will be excluded from the sitemap.xml and via robots.txt, so that google (hopefully) does not crawl them
Why? e.g. https://bnd.bndtools.org/releases/4.0.0/instructions/sub.html contains outdated information from previous releases. but the problem is those pages dilute the search results in google and sometimes outdated pages come up first. it is better for bnd / bndtools that current information is preferred.
=> docs: exclude /releases urls from search engines

biz.aQute.bndlib/src/aQute/bnd/build/JUnitLauncher.java, biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java, biz.aQute.remote/src/aQute/remote/plugin/RemoteProjectLauncherPlugin.java
Currently if one wants to extend a Project launcher it is required to completely reimplement the launch() method even if one only wants to add some argument to the commandline. Also things like returncode handling and reporting of results need to be implemented again.
This now adds a new method `ProjectLauncher#getCommand() `that externalize the process of creating a commandline, this also allows to access the final commandline from the outside (e.g. to show it to the user) or further customize it.
=> Add a ProjectLauncher#getCommand for easier extension

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
instead of project bnd.bnd
This fixes the problem that previously, when you had sub-subbundles, then Warning / Error Markers where always shown at the parent bnd.bnd in the project, instead of in the sub-bundle's .bnd file (where the warning actually belongs to).
Now it is showing up correctly in the sub-bundle's .bnd file if it is comming from a sub-bundle, or if it is a normal bundle, it shows at the bnd.bnd as it already was the case.
**Before:**
- actual: warning is shown for project `bnd.bnd`  (see _Resource_ column), but it actually belongs to the sub-bundle
- when I double click the warning, I go to the project `bnd.bnd` file
- the graphical marker in the bndeditor  is in the project `bnd.bnd`
**After:**
- Correct: warning is shown for the sub-bundle .bnd file (see _Resource_ …
=> sub-bundles: show warning markers in sub .bnd file

biz.aQute.bndlib/src/aQute/bnd/build/Container.java, biz.aQute.bndlib/test/aQute/bnd/build/ContainerTest.java
Currently if a Container is pointing to an exploded bundle one gets an exception when calling getManifest because it assumes it is always a jar file.
This now adds support fo reading such "exploded" bundles as well that are a folder.
=> Support reading the manifest from an exploded bundle

docs/_instructions/library.md
Here is a suggested for improving the -library instruction. I have heard it being mentioned a couple of times. But I think the current documentation is missing some examples to illustrate the usefulness (as in "what can I do with it, and when would I use it"?)
Here is what I did:
1. added a introductory sentence
2. added examples
3. moved one section "Creating libraries" from the bottom higher up. To me that improves the reading flow and now is basically: 
- What is it
- examples
- how to create
- how to use
=> Docs: Improve docs for -library instruction (add examples)

bndtools.core/src/bndtools/editor/BndSourceEffectivePage.java
Closes #6498
Now Effective Table View (which was correct) and Effective Source View (which was wrong) now display the same value, respecting the provenance.
=> BndEditor: fix incorrect Effective Source View

biz.aQute.bndlib.tests/test/test/ProcessorTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
Closes #6491
As suggested in the ticket 
> bnd should at least warn when it encounters the second and subsequent Import-Package statements.
This PR has some history / discussion and this description is updated to reflect the state of this PR at 2025/03/09.
(You can skip most of the initial discussions until https://github.com/bndtools/bnd/pull/6493#issuecomment-2704114749 )
This PR addresses a "usability" problem with [-include ](https://bnd.bndtools.org/instructions/include.html) which is mainly about this behavior:
> By default, the properties in the included file overwrite the properties that were set in the same file as the -include instruction.
```
Import-Package: root
-include: a.bnd
Import-Package: a.b. ('the first loser": this gets unintuitively overwritten)
```
The problem is …
=> -include: Show warning on counter-intuitive overwriting of properties

biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.resolve/src/biz/aQute/resolve/package-info.java, biz.aQute.resolve/test/biz/aQute/resolve/RunResolutionTest.java
Closes #6481 
- add method Project.getRepositories()
- override it in BndRun to provide a different list of plugins than Project
=> allow sub-classes of project to provide repos

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
Fixes a problem discovered here: https://github.com/bndtools/bnd/pull/2902#issuecomment-2711865033
Related to https://github.com/bndtools/bnd/issues/2803 
It basically reduces the number of warnings in `-pedantic=true` mode regarding 
- Require-Capability
- Provide-Capability
- Export-Package
`Duplicate name osgi.service used in header: 'osgi.service;objectClass:List<String>="com.fooA";uses:="com.fooB",osgi.service;objectClass:List<String>="com.fooC";uses:="com.fooD"...`
Also it fixes the `BuilderTest.testNoDuplicateWarningForHeadersThatAllowDuplicates()` which was not working at all, because the `pedantic=true` was not passed to the `Verifier` (Processor). So this test should have failed already, but it did not, because the `pedantic=true` had no effect.
=> Verifier: don't warn "Duplicate name" for caps/req (when pedantic=true)

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib.tests/test/test/model/EETest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Descriptors.java
This reduces warning noise with pedantic:true regarding the warning "Imports that lack version ranges". This warning is not useful for packages from the JDK like java. , javax.net. , javax.security. (and maybe more), because JDK packges have no version. we did not add "javax." because it would be too broad, as there are packages out there not coming from the JDK (e.g. javax.xml.bind)
For example we had lots of warnings like:
```
Imports that lack version ranges: [javax.net.ssl.SSLSessionContext]
Imports that lack version ranges: [javax.net.ssl.SSLSocket]
```
But since those are JDK packages, they do not have version. 
See https://bnd.discourse.group/t/how-to-handle-imports-that-lack-version-ranges-warning-pedantic-true/504
=> Reduce pedantic warnings "Imports that lack version ranges" for some JDK packages

biz.aQute.bndlib/src/aQute/bnd/help/Syntax.java, docs/_instructions/pedantic.md
Closes #6507 
This is not really a fix, but a band-aid.
Adjust description of the warning, so at least it is mentioned somewhere. unfortunatelly I could not figure out how to reliably sync the `Processor.pendatic` field with the `.bnd` files on change. The problem is that `Processor.pedantic` can be set via `.bnd` files but also via `Processor.setPedantic(boolean)` e.g. from testcases, there is some magic hen-egg-caching going on in `Processor.begin()` and `Processor.getProperties()` 
- in the end I was not able to figure out, what to call in which order so that the **Workspace Refresh Button** behaves the same as an Eclipse restart.
If anybody has a better idea, feel free.
=> -pedantic: Add hint that Eclipse restart is required

bndtools.core/src/bndtools/editor/project/RunRequirementsPart.java
this fixes the problem that the Resolve button did not "see" changes of included .bndrun files (e.g. -include: shared.bndrun). So when you changed something in an include and pressed the "Resolve" button , then the "Resolve" process would still see the old state when the BndEditor was initially opened and as if the change to -include: shared.bndrun would not have happened. Previous workaround was to close and open the BndEditor of the actual .bndrun file again
(you can also use this [workspace3.zip](https://github.com/user-attachments/files/19620021/workspace3.zip))
1. Create `a.bndrun`
`-include: shared.bndrun` 
2. Create a `shared.bndrun`
```
-runrequires: \
bnd.identity;id='bar.impl',\
bnd.identity;id='bar.consumer',\
bnd.identity;id='org.apache.felix.gogo.command',\ …
```
=> bndrun: refresh model before Resolve to get changes of included .bndrun files

bndtools.core/src/bndtools/editor/BndEditor.java, bndtools.core/src/bndtools/editor/project/RunRequirementsPart.java
This fixes a double-resolve when having resolveMode=AUTO introduced by my laster PR https://github.com/bndtools/bnd/pull/6550
I needed to make the reallySave() method public, so I can call it from the Resolve button action in the RunRequirements part
=> Fix double-resolve when having resolveMode=AUTO

bndtools.core/src/bndtools/views/resolution/ResolutionView.java
when double clicking on a File inside the JAR viewer, an NPE is thrown because the ResolutionView tries to analyze this file but cannot find it.
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.runtime.IPath.toFile()" because the return value of "org.eclipse.core.resources.IFile.getLocation()" is null
at bndtools.views.resolution.ResolutionView$1.partActivated(ResolutionView.java:177)
at org.eclipse.ui.internal.WorkbenchPage$2.run(WorkbenchPage.java:4887)
at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4884)
at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:215)
at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$2.run(PartServiceImpl.ja …
```
=> Fix NPE in ResolutionView when opening a file inside the JARViewer

bndtools.core/src/bndtools/editor/project/AbstractRequirementListPart.java
This fixes the problem that an Advanced Search result cannot be drag/dropped ont 
- Run Editor / Requirements
- Run Editor / Blacklist
Before this PR it resulted in Exception:
```
Error adding one or more requirements
Error generating requirement
Unable to derive identity from an object of type RepositoryResourceElement
```
=> allow dropping advanced search result to reqs

bndtools.core/src/bndtools/views/repository/AdvancedSearchDialog.java, bndtools.core/src/bndtools/views/repository/SearchPanel.java, bndtools.core/src/org/bndtools/core/ui/icons/Icons.java
By removing call to `image.dispose()` in RepoView/AdvancedSearchm because the image is created via `Icons.image()` which is a shared / cached image instance where Icons.java class takes care of calling `.dispose()` at the appropriate time.
Closes https://github.com/bndtools/bnd/issues/6322
=> fix Image already disposed error

bndtools.core/src/bndtools/editor/pkgpatterns/PkgPatternsListPart.java
Closes https://github.com/bndtools/bnd/issues/6565
this fixes the bug that after saving e.g. a change to the _optional_ checkbox, _version_ or _name_ did not have an effect immediatelly and the UI element of the checkbox was not in sync with the actual values in the source tab and also in the table viewer
Now after the fix the state of the UI Elements and source are always in sync after saving. Bonus: the current selection of values (multiple selections) is remembered.
This fix goes hand in hand with https://github.com/bndtools/bnd/pull/6564
=> fix Customize Imports forgets selection after save

biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java, bndtools.core/src/bndtools/editor/BndSourceEffectivePage.java, bndtools.core/src/bndtools/editor/completion/BndHover.java
Closes #6525
- add a new option to show the properties as merged properties (group the properties by stem)
- works in table and source view
- refactored BndSourceEffectivePage slightly. I removed the functions from ColSpec and introduced record PropertyRow which is populated in getTableData()
- added: hovering over 'key' column now also shows the Syntax.HELP text like the sourceViewer does
=> Effective view: show merged properties

bndtools.core/src/org/bndtools/refactor/util/ASTEngine.java, bndtools.core/src/org/bndtools/refactor/util/RefactorAssistant.java
Closes https://github.com/bndtools/bnd/issues/6521
It seems ASTParser now has a stricter check on the options (see https://github.com/eclipse-jdt/eclipse.jdt.core/pull/3063/files#diff-5155d744fdf221c04316cc2e0751b9ed207740927ccb1a36d82f85ca4e2bee5cR277)
Based on some manual code analysis, debugging and a fix from somebody else [here](https://github.com/anjlab/eclipse-tapestry5-plugin/commit/fc149b5ea04eb9e260659b44113efc9f15f694e2#diff-3383f8a572a18d2bcbe9fca95ac81a225654d66263a02dcdaf1a68cef187b480L484-R480) 
we now pass the `javaproject` to configure the parser, which should contain everything needed, instead of a Map.
Note: this is experimental. I will merge it and revert if it is not working. 
Unfortunately this is a bit hard to test and debug, because it happens only with **Eclipse > …
=> try to fix error "Missing system library"

biz.aQute.repository/bnd.bnd, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/RepoActions.java, biz.aQute.repository/src/aQute/bnd/repository/maven/util/RepoActionsUtil.java
Relates to https://github.com/bndtools/bnd/issues/6578#issuecomment-2840463367
This adds the "Add Sources" feature - known from MavenBndRepository - to download source code for a Repo Revision 
also to BndPomRepository.
It shares the same code with a minor refactoring.
=> addSources context menu for BndPomRepo

bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
It seems https://github.com/bndtools/bnd/pull/6597 did not really work.
This is a new attempt to fix https://github.com/bndtools/bnd/issues/6596
=> get DiskIndex.SIGNATURE via reflection

bndtools.m2e/bnd.bnd, cnf/ext/central.mvn, maven-plugins/bnd-maven-plugin/pom.xml, maven-plugins/bnd-plugin-parent/pom.xml, maven-plugins/bnd-reporter-maven-plugin/pom.xml
- plexus-build-api had CVEs
- org.sonatype.plexus has moved to org.codehaus.plexus
Closes https://github.com/bndtools/bnd/issues/6598
=> upgrade plexus-build-api to 1.2.0

CONTRIBUTING.md
Related to #6609 
This adds the content of the current page https://bndtools.org/development.html to github CONTRIBUTING.md because this is a better place.
I will forward the old URL to the CONTRIBUTING.md
Advantage:
- Developer setup instructions in a single place
- no jumping between websites
=> move dev-setup from bndtools website to CONTRIBUTING

biz.aQute.bnd.reporter/bnd.bnd, biz.aQute.bnd/bnd.bnd, biz.aQute.http.testservers/bnd.bnd, bndtools.core.test/test.cocoa.macosx.aarch64.bndrun, bndtools.core.test/test.cocoa.macosx.x86_64.bndrun, bndtools.core.test/test.gtk.linux.x86_64.bndrun, bndtools.core.test/test.shared.bndrun, bndtools.core.test/test.win32.x86_64.bndrun, bndtools.core/bndtools.cocoa.macosx.aarch64.bndrun, bndtools.core/bndtools.cocoa.macosx.x86_64.bndrun, bndtools.core/bndtools.gtk.linux.x86_64.bndrun, bndtools.core/bndtools.shared.bndrun, bndtools.core/bndtools.win32.x86_64.bndrun, bndtools.test/tester/cnf/ext/central.mvn, cnf/ext/central.mvn, org.bndtools.templating/bnd.bnd
@stbischof pointed out 3 CVEs in https://mvnrepository.com/artifact/biz.aQute.bnd/biz.aQute.bnd.reporter/7.1.0 because of an old Guava version. 
This is an attempt upgrade to the latest version. 
This seems possible.
The only case where Guava 19.0 is still needed is for `biz.aQute.bndlib.comm.tests` which uses no-longer maintained `littleshoot proxy` (https://mvnrepository.com/artifact/org.littleshoot/littleproxy)
=> Update to latest guava 33.4.8

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerSourceManager.java
Closes https://github.com/bndtools/bnd/issues/6593
This PR does mainly 2 things:
- it removes a "hack" in `MavenBndRepository.get()` which was using the +-prefixed jar file (e.g. +somedependency-6.1.17.jar) which is created by "Add sources" in the repo browser. This had negative side effects because those +jars were put into the build output e.g. by `-includeresources`. 
- It improves the Eclipse Source attachment lookup to properly use bnds integrated mechanism to get a -sources.jar if it exists via the BSN_SOURCE_SUFFIX (bsn + ".source") mechanism
Note: I did not change the "Add sources" behavior. The +-jar with included sourcecode under OSGI-OPT is still created. I initially had it and it is reflected in the discussions below, but I reverted that. 
- for the initial issue …
=> rework Add sources & calculateSourceAttachmentPath

biz.aQute.bndlib/src/aQute/bnd/build/RepoCollector.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.core.services/src/org/bndtools/core/editors/actions/BndRunAnalyzer.java
This makes the Eclipse Source Attachments work also for sub-bundles. This is especially useful for  pure wrapper bundles which contains only sub-bundles to wrap non-osgi jars and all projects in the workspace only have a build-path reference to the wrapper bundle, but not to the wrapped actual jars (which have the `-sources.jar` in `~/.m2` repo).
Also improved how the version is used, but also using `Container.getVersion()` in case `Container.getAttributes().get(Constants.VERSION_ATTRIBUTE)` is `null`. This makes it work for cases where a ${repo} reference specifies an explicit version (not latest) e.g.` -includeresource: ${repo;org.apache.lucene:lucene-analyzers-common;[4.0.0,4.0.1)};lib:=true`
```
-resourceonly: true
-sub: *.bnd
```
And there are a bundle of subbundles wrapping the …
=> Eclipse: Support source attachments for sub-bundles + ${repo} refs

biz.aQute.tester.junit-platform/bnd.bnd
Restrict version range to more explicitly reflect the limitation expressed in #6651.
The Import-Package directives for junit-platform now specify an exclusive upper bound of 1.13 to indicate that a version < 1.13 is required.
=> [junit-platform] Restrict upper end of version range

bndtools.core/_plugin.xml
based on discussion https://github.com/bndtools/bnd/issues/6642#issuecomment-3022090707
This is an attempt to fix the problem that newer Eclipse version took over the .bnd extension and opened in an Eclipse editor instead of the bndtools' BndEditor.
=> Set bndeditor as default for bnd extensions

org.bndtools.launch/src/bndtools/launch/sourcelookup/containers/BndrunDirectiveSourceContainer.java
This allows to view the source code attachment for classes in the Runframework. For example I needed to debug org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse which did not find the sourcecode, although I have it in my local ~/.m2 maven repo and (downloaded via bndtools repo browser).
This change fixes it by using the same lookup mechanism as for other bundles
Notice the different icon.
=> bndtools: fix Eclipse sourcelookup for runfw

biz.aQute.bnd/src/aQute/bnd/main/bnd.java, docs/_commands/compile.md, docs/_instructions/executable.md
because `bnd compile` alone just compiles .java files to class files but will fail for workspace bundles which require another bundle (because compile expects the built .jar  of that dependent bundle on the classpath, but the .jar is not there unless bnd build has created the jar file). So kind of a henn-egg problem.
My use case was this:
I'm trying to build my workspace with it (instead of gradle) but somehow. 
I first tried 
```
cd mybndworkspace
```
```
bnd clean
bnd build
```
That has produced `/generated/xxx.jar` files per bundle but the jar files did not contain the .class files of the bundle. 
After thinking about it, because ```build``` expects the classes to be _compiled_ first.
So I went ahead and tried
```
bnd clean
bnd compile
```
Unfortunatelly compile failed as soon as it …
=> [CLI] Change bnd build to also compile

aQute.libg/src/aQute/lib/getopt/CommandLine.java, biz.aQute.bnd/src/aQute/bnd/main/AddCommands.java, biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bndlib/src/aQute/bnd/wstemplates/FragmentTemplateEngine.java, biz.aQute.bndlib/src/aQute/bnd/wstemplates/package-info.java, bndtools.core/src/bndtools/wizards/newworkspace/NewWorkspaceWizard.java, docs/_commands/add.md, docs/_commands/exportreport.md, docs/_commands/nexus.md, docs/_commands/remote.md, docs/_commands/remove.md, docs/_commands/repo.md, docs/_commands/resolve.md
This will add the Eclipse Template Fragment Functionality to the CLI
https://bnd.bndtools.org/chapters/620-template-fragments.html
`bnd add workspace --fragment osgi --fragment gradle myworkspace`
or short:
`bnd add workspace -f osgi -f gradle myworkspace`
this will create a new workspace 'myworkspace' with two template fragments for osgi and gradle
```
NAME
add                         - Add a project, workspace, plugin or workspace
template fragment to the workspace
SYNOPSIS
add <what> ...
Available sub-commands: 
plugin                      - Add a plugin 
project                     - Create a project in the current workspace 
fragment                    - Add a template fragment to the current
workspace 
workspace                   - Create a bnd workspace in the current folder 
More …
```
=> [CLI] add 'bnd add fragment' command  to add template fragments

biz.aQute.bnd/src/aQute/bnd/main/AddCommands.java, docs/_commands/add.md
Let's first discuss this in more detail, as I see potential security risks with this option to specify a custom tempate fragment index by url. (@peterkir @pkriens )
Successor of https://github.com/bndtools/bnd/pull/6685/
=> CLI: remove -i / --index option for add workspace and add fragment

docs/_chapters/180-baselining.md
Add some more links to Maven plugin and semantic versioning specs. This closes #6691
=> Clarify major version 0 with respect to baselining

.github/workflows/docs_generate.yml
The paths
- 'docs/_heads/_ext/**'
- 'docs/_instructions/_ext/**'
- 'docs/_commands/_ext/**'
contain manual extensions of generated pages. whenever there is a change in one of the _ext folders then the docs generation should also start.
=> docs: trigger docs-gen also on _ext folder changes

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
This is an attempt / idea to improve the pedantic warning "Imports that lack version ranges" .
=> Improve warning for optional Imports w/o version

docs/README.md, docs/_config.yml, docs/_includes/footer.htm, docs/_includes/head.htm, docs/css/github.dark.css, docs/css/style.scss
and copy to clipboard button .
Use same theme (github.dark) as on bndtools.org
e.g. code areas now look like this
=> docs: add syntax highlighter for code snippets

docs/_chapters/920-faq.md
because it is error prone to manually keep it in sync and github pages does not support the jekyll toc plugin
=> docs: remove toc of FAQ

biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, bndtools.core/src/bndtools/views/repository/RepositoriesView.java
this makes the previously hidden [CachedFileRepo](https://github.com/bndtools/bnd/blob/fda9509b81a0e61b90c4600d68ead2cf6b43d9ec/biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java#L640) visible in the repo-browser. It helps devs to know what's going on behind the scenes e.g. because this bnd-cache contains the ProjectLauncher which is automatically added to exportable .jars. But so far it has been unclear where this launcher is magically coming from. So this is an attempt to make this repo visible.
Btw: I found there is the instruction https://bnd.bndtools.org/instructions/nobuildincache.html which can disable this cache completely (@amitjoy might be interesting in context of Launcher too for you)
TODO 
I found the following places where this bnd-cache is mentioned. 
- …
=> RepoBrowser: show the bnd-cache repo

biz.aQute.repository/src/aQute/p2/export/P2Export.java
In #6790 we only signed FileResource but feature jars e.g.  `org.eclipse.update.feature` are of type `JarResource`
=> Fix missing signing of JarResource

maven-plugins/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/AbstractBndMavenPlugin.java
This avoids rebuilding the jar when nothing has changed, and in projects with subproject, avoids downstream project recompilations.
=> Switch to the correct BuildContext API

biz.aQute.repository/src/aQute/p2/export/P2Export.java, org.bndtools.p2/bnd.bnd
Currently the p2Export jar does not contain a MANIFEST.MF and thus the build fails with "Cannot install /org.bndtools.p2/generated/org.bndtools.p2.jar into Local because Could not create a pom from Maven metainfo properties nor manifest information"
But bnd automatically creates a normal jar (what bnd usually does) with META-INF/MANIFEST.MF. 
BUT: if you give the p2export jar the same filename then the normal jar is overwritten. 
This PR fixes the problem and now simply reuse an existing jar if it already exist. 
That way the result the p2export jar has also `META-INF/MANIFEST.MF` and als `META-INF/maven/*` files if configured.
=> p2: use existing jar to reuse manifest

org.bndtools.p2/bnd.bnd
remove the empty instructions to hopefully fix the deployment of org.bndtools.p2 to `dist/m2` and ultimately to jfrog
=> fix org.bndtools.p2 release

biz.aQute.repository/src/aQute/p2/export/P2Export.java, biz.aQute.repository/testdata/p2-publish/ws-1/p1/bndtools.ecf.feature.bndrun, biz.aQute.repository/testdata/p2-publish/ws-1/p1/expected-feature.main.xml, biz.aQute.repository/testdata/p2-publish/ws-1/p1/expected-feature.pde.xml
Closes #6841 
add more p2 update site references
- to artifacts.xml as <references> same as in content.xml
- to feature.xml as <discovery> tag
Let's see if that helps.
=> P2Export: Try to fix Update ECF P2 Update Site not recognized during installation

biz.aQute.bnd/src/aQute/bnd/main/BuildCommands.java, biz.aQute.bnd/src/aQute/bnd/main/BuildWatcher.java, biz.aQute.bnd/src/aQute/bnd/main/bnd.java, docs/_commands/build.md, docs/_commands/dev.md, docs/_commands/run.md
The goal is to have an IDE-independent live coding workflow known from the javascript / npm world e.g. "vue-cli serve" ([see](https://cli.vuejs.org/guide/cli-service.html)) which starts a dev-webserver and allows for hot code reloading when changes are detected. It should basically do the same what Eclipse "Build automatically" is doing, but without Eclipse. So I can use any text editor VSCode, vim etc.
A workflow could look like:
```
cd mybndworkspace
bnd dev mywebapp/launch.bndrun
```
or multiple `.bndrun` files
```
cd mybndworkspace
bnd dev mywebapp/launch.bndrun mywebapp/launch2.bndrun
```
The `dev` command initially checks if any project needs rebuilding, and if yes it does a full build of the workspace before launching the bndrun files. Otherwise the bndrun files are launched …
=> [CLI] new Command: bnd dev & bnd build -watch for continuous build run workflow
