bndtools/bnd

biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java, biz.aQute.launcher/test/aQute/launcher/plugin/ProjectLaunchImplTest.java
Better fix for setting projectLauncher.cwd == project.base
See discussion at https://github.com/bndtools/bndtools/pull/982
=> Always setup cwd as same as project base

biz.aQute.launcher/test/aQute/launcher/plugin/ProjectLaunchImplTest.java, biz.aQute.launcher/test/ws/p1/.gitignore
I found the test could fail depending upon the execution order because
the tests shared the same Workspace object and tearDown deleted and did
not recreate the target dir. This could cause FNFE.
=> launcher test fix: PR #746 introduced a test ordering issue

biz.aQute.bnd.annotation/build.gradle, biz.aQute.bnd.gradle/build.gradle, biz.aQute.bnd/build.gradle, biz.aQute.bndlib/build.gradle, build.gradle, cnf/build.bnd, cnf/gradle/maven-artifacts.gradle, org.osgi.impl.bundle.repoindex.cli/build.gradle, org.osgi.impl.bundle.repoindex.test/bnd.bnd, org.osgi.impl.bundle.repoindex.test/test/org/example/tests/cli/TestCommandLine.java
Certain bnd projects are released to maven central. These commits build the needed maven artifacts for those projects as part of the normal bnd build. For the projects which opt-in (by applying cnf/gradle/maven-artifacts.gradle), the project's build will create a pom file, a -sources.jar and a -javadoc.jar in addition to the .jar.
=> Build maven artifacts

biz.aQute.bndlib/src/aQute/bnd/service/repository/SearchableRepository.java, biz.aQute.repository/src/aQute/bnd/jpm/Repository.java
Expose the browse/search URL of the SearchableRepo, so that Bndtools can go to a hosted JPM instead of the public one on jpm4j.org
=> Expose browse URL from SearchableRepo

biz.aQute.bndlib/src/aQute/bnd/build/Project.java
Speeds up Project.prepare()
I was very surprised by the line I commented out and how much extra processing that caused in my environment. The triedGetBundle didn't seem to do much, but it seemed safer to put it there just in case extra getBundle() calls are made.
Signed-off-by: Carter Smithhart <carter.smithhart@gmail.com>
=> Performance fixes

biz.aQute.bnd.gradle/bnd.bnd
=> gradle plugin: Exclude bndlib pom from META-INF

biz.aQute.bndlib/src/aQute/bnd/osgi/Packages.java
The method referenced getByFQN instead of getByBinaryName. Also
getByBinaryName was broken since it always return null.
Fixes https://github.com/bndtools/bnd/issues/782
=> bndlib: Fix Packages.containsBinaryName

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
This allows one to say "gradle export.foo" without failure because the
plugin created an export.foo task in every project even when the project
did not have a foo.bndrun file.
=> gradle: define export.x and runbundles.x tasks iff x.bndrun file exists

biz.aQute.bnd.gradle/build.gradle
The bnd gradle plugin should target a specific gradle version rather than
just the version of gradle used to compile bnd.
=> gradle plugin: Target a specific gradle version: gradle 2.0

org.osgi.impl.bundle.repoindex.test/bnd.bnd
This change clears Discouraged warnings from the new classpath container
in bndtools.
=> build: Add packages=** to -buildpath entries that need it

biz.aQute.bnd.test/bnd.bnd, biz.aQute.bnd/bnd.bnd, biz.aQute.bndlib.tests/bnd.bnd, biz.aQute.bndlib/bnd.bnd, biz.aQute.repository/bnd.bnd, biz.aQute.resolve/bnd.bnd, org.osgi.impl.bundle.repoindex.cli/bnd.bnd, org.osgi.impl.bundle.repoindex.test/bnd.bnd
Recent changes mean a number of projects no longer need packages=* to
remove Discouraged warnings. Also narrowed packages for some older
bundles.
=> Cleanup packages

biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
This recursion caused out of memory errors.
Fixes https://github.com/bndtools/bnd/issues/724
Helped-by: Andreas Kuhtz @akuhtz
=> bndlib: Remove recursion in macro warning

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
Currently Project.getSourcepath returns a collection with getSrc in it.
When bnd changes to support multiple source folders via
Project.getSourcepath, the gradle plugin will ready to support it.
Also removed the use of relativePath since it is not necessary as the
sourcesets accept File objects.
=> gradle: Change plugin to use Project.getSourcepath instead of getSrc

biz.aQute.bndlib.tests/src/test/WorkspaceTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, gradle.properties
The Workspace defaults did not show up as keys in the Workspace because the processor did not directly use the Workspace.getDefaults() properties but created an intermediate. Therefore no keys were see, therefore the merge properties did not work for defaulted keys.
=> [build] Processor defaults

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, settings.gradle
Some bnd types have non-private fields with the "same" name as the
getter method. For example: sourcepath and getSourcepath. Groovy
was picking the field instead of the getter. This caused an error
when the impl details of the field changed while the method did not.
So we now always use method calls in the Groovy code to make sure we
always call the getter and not access the field.
Replaces https://github.com/bndtools/bnd/pull/856.
=> gradle plugin: Use method names for bnd types

gradle.properties
After fixing https://github.com/bndtools/bnd/pull/857
=> build: Revert to using latest gradle plugin

cnf/gradle/maven-artifacts.gradle, dist/build.gradle
Some bnd types have non-private fields with the "same" name as the
getter method. For example: sourcepath and getSourcepath. Groovy
was picking the field instead of the getter. This caused an error
when the impl details of the field changed while the method did not.
So we now always use method calls in the Groovy code to make sure we
always call the getter and not access the field.
=> gradle: Use method names for bnd types

biz.aQute.repository.aether/src/aQute/bnd/deployer/repository/aether/AetherRepository.java, biz.aQute.repository.aether/src/aQute/bnd/deployer/repository/aether/MvnVersion.java, biz.aQute.repository.aether/test/aQute/bnd/deployer/repository/aether/MvnVersionTest.java
Simplify parsing using a single regex.
Added more tests and changes parseString method to throw
IllegalArgumentException instead of return null if the string argument
was invalid.
This is a replacement for https://github.com/bndtools/bnd/pull/854
Reported-by: Rafał Krzewski <rafal.krzewski@caltha.pl>
=> maven version: Support additional forms of maven versions

biz.aQute.bnd.gradle/.classpath, biz.aQute.bnd.gradle/build.gradle, biz.aQute.bnd.gradle/resources/META-INF/gradle-plugins/biz.aQute.bnd.builder.properties, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bundle.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, gradle.properties
A new Bundle task type is defined which extends the Jar task type and
uses the bnd Builder class to make the jar into a bundle. An
biz.aQute.bnd.builder plugin is defined which, when applied to a project
modifies the jar task to use the bnd Builder class to make the jar into
a bundle.
=> Gradle builder plugin: Add gradle support for non-Workspace environments

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
This will allow the Bundle task type to be used with having the java
plugin applied to the project _if_ the user either sets the values or
otherwise ensure the main SourceSet and compile Configuration exist.
=> gradle plugin: delay setting default values until necessary

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
This avoids the need for the user to set a SourceSet or for the default
SourceSet to exist when -sources is not set.
Also quote jar name for -includeresource.
=> Gradle sourcepath only if sources true

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
Since we quote the jar path for -includeresource, we also need to escape
any quote chars in the path.
=> gradle plugin: Escape any quote chars in jar file path

biz.aQute.bndlib.tests/src/test/VerifierTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
The pattern for invalid file names was using CLOCK$ and not CLOCK\$ so any name ending in CLOCK was wrong. 
#917 Close
=> [verifier] clock recognized as invalid file name

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
Issue: https://github.com/bndtools/bnd/issues/915
Use fuzzy version grokking logic when comparing manifest and package versions - exactly as we do later, via `cleanupVersion`
Alternative solution: https://github.com/bndtools/bnd/pull/914
=> [analyzer] use fuzzy version logic when comparing manifest version to package version

bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java, bnd-maven-plugin/src/test/resources/integration-test/test/pom.xml, bnd-maven-plugin/src/test/resources/integration-test/test/test-wrapper-bundle/README.txt, bnd-maven-plugin/src/test/resources/integration-test/test/test-wrapper-bundle/bnd.bnd, bnd-maven-plugin/src/test/resources/integration-test/test/test-wrapper-bundle/pom.xml, bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy
The project might just want to wrap some other jars. This fix will test
for the target/classes dir and if it is not a directory, it will not
add it to bnd's classpath or the -includeresource directive.
Also added a new test project to the integration-test to test building
a project with no source code.
Fixes https://github.com/bndtools/bnd/issues/925
=> bnd-maven-plugin: Handle projects with no source code

biz.aQute.bndlib.tests/src/test/BuilderTest.java
These failures were because a Windows path is not a valid URI.
Using the new File(...).toUri() does work in all cases.
Signed-off-by: Marc de Jonge <marcdejonge@gmail.com>
=> Fixed 2 testcases in the BuilderTest that failed on Windows

aQute.libg/src/aQute/lib/tag/Tag.java, aQute.libg/src/aQute/libg/sed/Sed.java, biz.aQute.bnd/src/aQute/bnd/main/BaselineCommands.java, biz.aQute.bnd/src/aQute/bnd/main/DiffCommand.java, biz.aQute.bndlib/src/aQute/bnd/component/TagResource.java, biz.aQute.bndlib/src/aQute/bnd/make/metatype/MetaTypeReader.java, biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java, biz.aQute.bndlib/src/aQute/bnd/metatype/TagResource.java, biz.aQute.repository/src/aQute/bnd/deployer/repository/providers/ObrContentProvider.java
We want the output build on *ix and windows systems to be the same to
avoid baselining failures.
Closes https://github.com/bndtools/bnd/pull/908
=> Use LF line endings in output files for build consistency

aQute.libg/src/aQute/lib/io/IO.java, aQute.libg/src/aQute/libg/remote/source/SourceFS.java, aQute.libg/test/aQute/lib/remote/RemoteTest.java, appveyor.yml, biz.aQute.repository/test/aQute/bnd/deployer/repository/TestFixedIndexedRepo.java, biz.aQute.repository/test/aQute/bnd/deployer/repository/TestLocalIndexGeneration.java, biz.aQute.repository/test/aQute/bnd/deployer/repository/TestLocalIndexedRepo.java, biz.aQute.repository/test/aQute/bnd/deployer/repository/TestLocalObrGeneration.java, biz.aQute.repository/test/aQute/bnd/deployer/repository/TestMultipleLocalIndexGeneration.java, biz.aQute.repository/test/aQute/bnd/deployer/repository/wrapper/TestWrapper.java
We now use AppVeyor to CI build bnd. This showed a number of test failures on Windows (which did not fail on *ix). This PR includes fixes for these failures so that bnd now builds/tests clean on Windows.
=> Fixes for Windows

biz.aQute.bndlib.tests/src/test/annotationheaders/AnnotationHeadersTest.java, biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/ParameterisedAnnotation.java, biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/UsingAttrs.java, biz.aQute.bndlib/src/aQute/bnd/annotation/headers/RequireCapability.java, biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java
Example:
@RequireCapability(ns="foo", filter="(foo=${value})")
public @interface Foo { String value(); }
@Foo("hello")
public class MyComponent { ... }
==> Require-Capability: foo; filter:="(foo=hello)"
=> Parameterise @RequireCapability filter using annotation attributes

biz.aQute.bndlib.tests/src/test/LauncherTest.java, biz.aQute.junit/src/aQute/junit/Activator.java, demo/src/test/Juni4TestCase.java, demo/src/test/TestCase1.java
The @RunWith annotation was creating new TestSuite objects that were not correctly reported to Eclipse. Due to the JUnit4Adapter we did not properly flatten the list. I.e. we assumed always had a Test under the JUnit4Adapter
We now properly recurse.
Fixes #661
=> [junit] junit 4 "unrooted" tests with parametrized tests

biz.aQute.bnd.gradle/bnd.bnd
Then users do not need to set -pluginpath to point to
biz.aQute.repository since the matching version of that code is packaged
in the gradle plugin.
Part of the solution for https://github.com/bndtools/bnd/issues/970
=> gradle: Include biz.aQute.repository code in gradle plugin

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
The jar task would rebuild if any of the -buildpath dependencies change
but when a -dependson dependency changes, the jar task would not rebuild.
The OSGi build uses -dependson for packaging projects like osgi.ct to
depend up on the various ct projects. But when a ct project rebuilt, the
osgi.ct project would not rebuild the packaging jar. This change means
that the jar task will rebuild if the jar of any dependency in -buildpath
or -dependson changes.
=> gradle plugin: jar task rebuild for -dependson project's artifact changes

aQute.libg/src/aQute/lib/converter/Converter.java, aQute.libg/src/aQute/lib/json/JSONCodec.java, aQute.libg/src/aQute/lib/json/UUIDHandler.java
I regularly use UUIDs as identifiers, and when using for example the REST provider, I also want to use UUIDs there as arguments or attributes from my returning (DTO) class. To support this, I added an UUID handler to the JSONCodec to convert UUID from/to String, and also add a conversion in the Converter class when resultType is UUID.class.
=> Support UUID class in Converter and JSONCodec

org.osgi.impl.bundle.repoindex.lib/src/org/osgi/service/indexer/impl/BundleAnalyzer.java, org.osgi.impl.bundle.repoindex.lib/src/org/osgi/service/indexer/impl/GeneratorState.java, org.osgi.impl.bundle.repoindex.lib/src/org/osgi/service/indexer/impl/RepoIndex.java, org.osgi.impl.bundle.repoindex.lib/src/org/osgi/service/indexer/impl/URLResolver.java, org.osgi.impl.bundle.repoindex.lib/test/org/osgi/service/indexer/impl/TestIndexer.java
Sometimes the standard template or default URL calculation is not sufficient. When a URI resolver is set, it takes over and it can calculate any URI based on the file under consideration.
=> [resolver] Added a URI resolver interface

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, build.gradle, settings.gradle
The gradle plugin runs too late to alter the gestalt of the workspace.
So we remove that from the plugin and change the settings.gradle and
build.gradle files to set the gestalt.
=> gradle: bnd plugin cannot set gestalt

biz.aQute.bndlib/src/aQute/bnd/build/Project.java
This is now consistent with how Builder tests -nobundles.
=> isNoBundles: Use boolean test rather than presence test

biz.aQute.bndlib.tests/src/test/ProjectTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java
NB: restoring this work from a private branch that was lost some time ago. The work was done on behalf of a client.
The purpose of this is to allow for a buildpath to be set on the cnf project containing all of the content of one or more repositories. This then enables type-level searches over those repository contents in Eclipse.
For example:
-buildpath: org.apache.*
-buildpath: *; repos='Build Repo*'
Peter is aware of this work and the implementation corresponds with his specification.
=> Wildcard BSN in buildpath with repository filter

biz.aQute.bndlib/src/aQute/bnd/osgi/resource/WireImpl.java, biz.aQute.resolve/src/biz/aQute/resolve/AbstractResolveContext.java, biz.aQute.resolve/src/biz/aQute/resolve/ResolveProcess.java, biz.aQute.resolve/test/biz/aQute/resolve/ResolveProcessTest.java, biz.aQute.resolve/testdata/repo7/index-aries.xml, biz.aQute.resolve/testdata/repo7/index-gemini.xml, biz.aQute.resolve/testdata/repo7/index-local.xml, biz.aQute.resolve/testdata/repo7/index.xml
When doing a _required_ resolve the ResolveProcess should still populate the optional candidates so that other tools can decide whether to pull them in.
=> ResolveProcess does not populate optional candidates

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, build.gradle, settings.gradle
The static getWorkspace method caches the Workspace. When using the
gradle daemon, the daemon process never notices updates to bnd files
since the Workspace and thus all Projects are cached.
=> gradle: Create a new Workspace object each build

biz.aQute.bndlib.tests/src/test/LauncherTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, cnf/build.bnd, demo/bnd.bnd, demo/x.bndrun
bndrun files must not depend upon the project (bnd.bnd). They only
inherit from the workspace.
Fixes https://github.com/bndtools/bnd/issues/980
=> bndrun: export must not reference project properties

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bndlib.tests/src/test/MavenVersionTest.java, biz.aQute.bndlib/src/aQute/bnd/version/MavenVersion.java, biz.aQute.repository.aether/src/aQute/bnd/deployer/repository/aether/AetherRepository.java, biz.aQute.repository.aether/src/aQute/bnd/deployer/repository/aether/ConversionUtils.java
Since gradle users will use the standard gradle project version property and that property will likely be in maven "format", we use the MavenVersion class to parse it into a form suitable for use on the Bundle-Version manifest header.
=> gradle: Use MavenVersion class to parse gradle project version property

.travis.yml, maven/bnd-indexer-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java, maven/pom.xml
* The indexer should only index compile and runtime dependencies by default. Other scopes may be added using configuration if desired
* The output index should be attached to the project so that it can be installed and deployed
* The output index should also include a .gz version for more efficient file serving from remote repositories
=> bnd-indexer-maven-plugin improvements

biz.aQute.bnd.embedded-repo/bnd.bnd
Using latest cause these bundles to be used over the bundles in the
workspace we wanted to test.
=> embedded repo: Use proper version numbers for embedded bundles

maven/bnd-indexer-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/pom.xml
This avoids the need to pass a version property to the integration
pom.
=> maven: Use @project.version@ in integration tests

maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/in-build/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-bnd/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-bnd/src/main/resources/META-INF/MANIFEST.MF, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/verify.groovy
If the bundle is part of the current build then resolve will resolve to the target directory, not the remote location it was just deployed to. This was wrong!
=> [indexer-maven-plugin] Make sure we use remote URLs when we say we will

biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java
The system packages from the EE and `-runsystempackages` omitted any version, so they could not resolve against a filter such as `(&(osgi.wiring.package=javax.xml.parsers)(version>=0.0.0))`.
If this patch works I would like it to be a candidate for inclusion in 3.0.1.
=> Fix bndtools/bndtools#1177: error resolving EE caps

maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java
Maven lets you output artifacts with a _type_ which can be different from the file extension. Previously we set both to XML. The output is XML, but lots of things output XML. I am therefore changing the output type to _osgi-index_.
=> [indexer-maven-plugin] Output artifact type too generic

biz.aQute.repository/bnd.bnd, biz.aQute.resolve/bnd.bnd
This was changed to a fragment while having issues with the Kepler resolver. Since we have updated now to Luna for 3.1, we should revert this to be a normal bundle.
=> repository: Revert to being a bundle

biz.aQute.remote/src/aQute/remote/agent/AgentServer.java, biz.aQute.remote/test/biz/aQute/remote/RemoteTest.java
In order to preserve the bundle ordering when launching remote a LinkedHashMap implementation is given to the update() method of the Agent.
However, internally the ordering is lost again by using HashSets for toBeStarted and toBeInstalled. Also changing these to LinkedHashSets saves the bundle ordering. 
I added a junit test to verify this.
And yes, I *know* that one shouldn't depend on bundle ordering :-)
=> Preserve bundle order from bndrun file when launching remote

biz.aQute.repository/src/aQute/bnd/jpm/Repository.java
While working on a bndtools style workspace on a recent plane trip, JPM was complaining about not being online and killing the project builder even though all of the bundles were there locally and already cached.  With this small change it lets cached files be return successfully before trying for online connectivity.
=> better offline support for JPM repo

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, maven/bnd-baseline-maven-plugin/.gitignore, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
We include the jar content already assembled by maven/gradle with `setJar` instead of using `-includeresource` to avoid conflict with any user instructions in the bnd file.
=> plugins: Use Builder.setJar instead of -includeresource

biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
It turned out that each sub bundle build was clearing the map with the other sub bundles. This caused only the last sub bundle to remain in that map. I.e. the workspace repository only showed the last sub bundle.
The project now clears the map before the overall build. Sub bundle builds remove and add their name + version to  this map.
=> [build] Multiple sub bundles did not show up in Workspace Repository

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bundle.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
We need to compile the call to `super.copy()` with `@CompileStatic` to
avoid a Groovy 2.4 error where the `super.copy()` call instead results in
calling `this.copy()` causing a StackOverflowError.
See <https://discuss.gradle.org/t/gradle-2-8-causes-stackoverflowerror-on-super-call/12348>
for a discussion.
=> gradle: Change Bundle class to avoid Groovy 2.4 error

biz.aQute.bnd.gradle.tests/test/biz/aQute/bnd/gradle/TestBundlePlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
In some circumstances, pom files can appear in the resolved artifacts. We make sure only artifacts of type jar are used for the builder's classpath.
Issue discovered by @rotty3000.
=> gradle: Ensure only jar type artifacts in builder classpath

biz.aQute.bndlib.tests/src/test/baseline/BaselineTest.java, biz.aQute.bndlib/src/aQute/bnd/differ/Baseline.java, maven/bnd-baseline-maven-plugin/pom.xml, maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/settings.xml, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/bnd.bnd, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-consumer/pom.xml, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-consumer/src/main/java/bnd/test/TestConsumerIface.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-consumer/src/main/java/bnd/test/TestProviderIface.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-consumer/src/main/java/bnd/test/package-info.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-provider/pom.xml, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-provider/src/main/java/bnd/test/TestConsumerIface.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-provider/src/main/java/bnd/test/TestProviderIface.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/invalid-with-provider/src/main/java/bnd/test/package-info.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-no-previous/pom.xml, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-no-previous/src/main/java/bnd/test/TestConsumerIface.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-no-previous/src/main/java/bnd/test/TestProviderIface.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-no-previous/src/main/java/bnd/test/package-info.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-previous-same/pom.xml, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-previous-same/src/main/java/bnd/test/TestConsumerIface.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-previous-same/src/main/java/bnd/test/TestProviderIface.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-previous-same/src/main/java/bnd/test/package-info.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-provider/pom.xml, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-provider/src/main/java/bnd/test/TestConsumerIface.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-provider/src/main/java/bnd/test/TestProviderIface.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-provider/src/main/java/bnd/test/package-info.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/verify.groovy
Tests for the bnd-baseline-maven-plugin, and a fix for the Baseline class when it is used to baseline two bundles with different symbolic names
=> Baseline improvements

biz.aQute.bnd.gradle.tests/test/biz/aQute/bnd/gradle/TestBundlePlugin.groovy, biz.aQute.bnd.gradle.tests/testresources/builderplugin1/bnd.bnd, biz.aQute.bnd.gradle.tests/testresources/builderplugin1/build.gradle, biz.aQute.bnd.gradle.tests/testresources/builderplugin1/other.bnd, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
This will allow the user to specify included bnd files from the gradle
DSL.
Fixes https://github.com/bndtools/bnd/issues/1213
=> gradle: Support -include in jar task manifest

biz.aQute.bnd.gradle.tests/test/biz/aQute/bnd/gradle/TestBundlePlugin.groovy, biz.aQute.bnd.gradle.tests/testresources/builderplugin1/bnd.bnd, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
project.name, project.output, project.buildpath, project.sourcepath. Then
these can be used in macros in the bnd instructions.
Also removed nonexistent dirs from sourcepath since the Builder would
complain.
=> gradle: Set common bnd properties for non-workspace users

biz.aQute.bndlib.tests/src/test/AnnotationsTest.java, biz.aQute.bndlib/src/aQute/bnd/annotation/metatype/Configurable.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Annotation.java
Use class name and reflection instead
=> Fixes #1228 - biz.aQute.bnd.annotation-3.0.0 pulls in biz.aQute.bndlib

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, rebuild-with-local-plugin, settings.gradle
We now avoid throwing and discarding an exception when checkErrors should ignore failures.
Also some build improvements to support building with recently built gradle plugin.
=> gradle: Simplify ignoreFailures by using optional arg to checkErrors

settings.gradle
We simplify the support by using the gradle uri method. This is safer
since relative paths are resolved agains the directory of the
settings.gradle script rather than the current working directory.
=> build: Simplify support for relative file urls to the bnd gradle plugin

aQute.libg/src/aQute/lib/utf8properties/PropertiesParser.java, aQute.libg/test/aQute/lib/utf8properties/UTF8PropertiesTest.java
The cr/lf combination for the \\ escape was not properly handled. Have added tests that now test all combinations of \r, \r\n, and \n for all specification and tests against the original Properties parser.
=> [properties] Window troubles

aQute.libg/src/aQute/lib/utf8properties/PropertiesParser.java
Use actual property key name in the examples in the error message.
=> Tweak error message in PropertiesParser

biz.aQute.bndlib.tests/src/test/ProcessorTest.java
Test `${uri;.}` returns the base URI of the Processor.
=> uri macro: Add another test

aQute.libg/src/aQute/lib/utf8properties/PropertiesParser.java, aQute.libg/test/aQute/lib/utf8properties/UTF8PropertiesTest.java
`%x` supports integral values and char is not one. So we convert to an Integer.
=> properties parser: A char is not a number

biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/lib/deployer/FileRepo.java, biz.aQute.repository/src/aQute/bnd/deployer/repository/wrapper/InfoRepositoryWrapper.java, biz.aQute.repository/src/aQute/bnd/deployer/repository/wrapper/Plugin.java, biz.aQute.resolve/test/biz/aQute/resolve/ProjectResolverTest.java, biz.aQute.resolve/test/biz/aQute/resolve/repository/JpmRepoTest.java
There are a couple resolver tests that were leaving behind a 'tmp' directory even though the tests were passing. There were a few issues contributing to this, but mostly we are just not closing things (PersistentMaps and Resources) after we are done using them.
This also changes Workspace.close() to call it's parent's (Processor) close() method as well for additional cleanup.
=> Resolve various locked file issues under Windows

biz.aQute.bndlib.tests/src/test/MacroTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
Properties.getProperty will return null for non-String values. Groovy
users can think they are putting a String value when it is really a
GString value.
Fixes #1270
Also some other problems I found during this work.
=> Defend against non-String values

biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
bndlib is not thread safe. This synchronization was not really changing
that and resulted in deadlocks where one thread would get the versionMap
lock and then request the Project lock, while another thread would get
the Project lock and then request the versionMap lock.
=> bndlib: Remove synchronization which causes deadlocks

biz.aQute.bndlib.tests/src/test/MacroTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Packages.java
As discussed with @pkriens, this adds support for `${packages;exported}`. Useful when wrapping other bundles, and the exported packages of that bundle should be exported by the wrapper as well.
Signed-off-by: Paul Bakker <paul.bakker@luminis.eu>
=> Added support for ${packages;versioned}

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
This is primary a problem under windows in combination with the gradle-bundle-plugin and the gradle daemon. I was not able to write some test for verification, but it is obvious, that files which are added by the setClasspath method are not registered for close.
=> Close jar file streams that were set as classpath when closing

biz.aQute.bndlib/src/aQute/bnd/build/ProjectTester.java, biz.aQute.junit/src/aQute/junit/Activator.java
ProjectTester does not own the test-results folder and must not clear it out. Plain junit test results may also be in this folder.
=> test: Do not clear test-results folder

biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java, biz.aQute.bndlib/src/aQute/bnd/build/packageinfo, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
When a bundle has no content headers defined (*_Package, -includeresource, etc) then it will include the contents of the bin directory and not export anything.
(Considered adding a ${packages;VERSIONED} macro but that would make it confusing if they added anything themselves, then they would suddenly loose that feature.)
Fixes #1291.
=> #1291 [build] Default content for bundle

biz.aQute.bndlib/src/aQute/bnd/differ/JavaElement.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
Skipping synthetic classes in the diff.
Fixes #1296
=> #1296 Baselining "cross compiler" fails when using switch on an enum

biz.aQute.bnd/src/aQute/bnd/main/RemoteCommand.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
Copy/paste error led to bnd rejecting requiring osgi.identity. Also cleaned up messages and added checks to prevent providing osgi.ee and osgi.native.
=> verifier: osgi.identity can be required

biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
This will make sure bnd sees method references used in Java 8 and imports the necessary packages.
=> Parse and process MethodType constant pool entries

biz.aQute.resolve/src/biz/aQute/resolve/AbstractResolveContext.java
=> Avoid UnsupportedOperationException in resolver

biz.aQute.bndlib.tests/src/test/metatype/SpecMetatypeTest.java, biz.aQute.bndlib/src/aQute/bnd/metatype/MetatypeAnnotations.java
Since Designate is a metatype annotation, it should be processed only
on classes selected by the -metatypeannotations instruction, whose value
defaults to "*".
=> Process Designate annotation based upon -metatypeannotations instruction

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
The Builder collects that latest modified time of it source material
such as bnd files and included files. The Jar collects the latest
modified time of all its contents including the Builder which built it.
So we modify the expandJar method to only write files out when either the
file does not exist or the file is older than the Jar last modified time.
For incremental builds, this should avoid writing any output files if
none of the input material to the built Jar has changed. Thus we avoid
downstream dependencies from rebuilding because unchanged files were
rewritten.
Alternative to bndtools#1316
=> bnd-maven-plugin: Avoid writing output if not out-of-date

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/bnd.bnd, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-wrapper-bundle/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy
If a user wants to avoid replacing  `SNAPSHOT` with `${tstamp}` in qualifier in `Bundle-Version`, the `-snapshot: SNAPSHOT` instruction can be used.
For example, to retain SNAPSHOT in the POM version 
```
<version>0.0.1-SNAPSHOT</version>
```
in the `Bundle-Version` header, put the following in the `bnd.bnd` file:
```
-snapshot: SNAPSHOT
```
=> bnd-maven-plugin: Allow automatic SNAPSHOT replacement override

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
In some circumstances, the parent project's POM will not be on the local
file system but will be in a maven repo. In this case,
MavenProject.getFile() will return null.
=> bnd-maven-plugin: Handle repository based parent POM

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-api-bundle/src/main/resources/org/example/api/aresource.txt, maven/bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy
The BuildContext.hasDelta method is used to find if any project source
has changed since the last build. The jar is built only if there is a
delta or the builder inputs are newer than the target/classes dir.
=> bnd-maven-plugin: Avoid building jar in memory if possible

maven/bnd-maven-plugin/README.md, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java, maven/bnd-maven-plugin/src/test/resources/integration-test/test/bnd.bnd, maven/bnd-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-api-bundle/bnd.bnd, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-api-bundle/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-wrapper-bundle/bnd/other.bnd, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-wrapper-bundle/bnd/wrapper.bnd, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-wrapper-bundle/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy
Add `<bndfile>` pom configuration element which specifies an alternate bnd
file path. This will allow the bnd file to be other than 'bnd.bnd' in
project root.
Add `<bnd>` pom configuration element which can hold, via CDATA, a bnd
file. The bnd properties in this element are used if there is no bnd
file found for the project. This will allow the bnd properties to be
carried in the pom.
Fixes https://github.com/bndtools/bnd/issues/1293
Fixes https://github.com/bndtools/bnd/issues/952
=> bnd-maven-plugin: Add support for alt bnd file path and bnd-in-pom

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-api-bundle/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/bnd.bnd, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-wrapper-bundle/bnd/wrapper.bnd, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-wrapper-bundle/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy
If unset, Bundle-SymbolicName is set to the project artifactId. If
unset, Bundle-Name is set to the project name.
Closes https://github.com/bndtools/bnd/pull/1336
=> bnd-maven-plugin: Set Bundle-SymbolicName and Bundle-Name from project

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
Use BuildContext.isIncremental to decide to always build if not incremental.
Defer setting builder classpath until the decision is made to build.
This may help with problems in #1346.
=> bnd-maven-plugin: Improve incremental build performance

biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
SNAPSHOT is only replaced if the qualifier equals SNAPSHOT or ends with
-SNAPSHOT.
=> snapshot: Clean up code to be more precise about SNAPSHOT replacement

build.gradle, cnf/build.bnd, maven/bnd-baseline-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/pom.xml, maven/bnd-maven-plugin/pom.xml, maven/pom.xml
This is in preparation to release to a maven repo once the new maven
repo support is integrated.
We also take advantage of recent improvements to the -pom and -snapshot
instructions and the versionmask macro.
=> build: Use maven SNAPSHOT versions

biz.aQute.bndlib.tests/src/test/MacroTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
The ${range} macro created an error when it was used without the @ target set. Added a feature to indicate to the macro processor that the replacement should be the literal text of the macro so it can be expanded again later.
=> [macro] Literal expansion

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
Fixes https://github.com/bndtools/bnd/issues/1405
=> bnd-maven-plugin: Force build if the manifest is not present in target

cnf/.gitignore
=> build: .gitignore maven repo .mvn files when building non-SNAPSHOT

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
Fixes https://github.com/bndtools/bnd/issues/1422
=> gradle: Add outputs for exports.* and runbundles.* tasks

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
The problem we encountered is - we don't usually specify ranges nor versions in the import-packages block. We didn't find a way of doing it and this change should provide us such functionality. 
What it does: if you provide an empty consumer-policy your versions won't be automatically generated.
=> DIAFAMPS-4 allowing to not specify package versions

biz.aQute.bndlib.tests/src/test/BuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
I’ve moved the copying of sources from the -buildpath JARs inline with the copying of the binary package, it will therefore follow exactly the same logic.
Fixes #1320
=> #1320 -sources: true does not handle split packages properly

maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/helloworld-for-indexer-testing/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-bnd/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-snapshot/pom.xml, maven/bnd-maven-plugin/README.md, maven/bnd-maven-plugin/src/test/resources/integration-test/test/pom.xml
https://issues.apache.org/jira/browse/MJAR-210 has removed
useDefaultManifestFile in maven-jar-plugin 3.0.
Fixes https://github.com/bndtools/bnd/issues/1456
=> maven: Avoid useDefaultManifestFile

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/RepoActions.java
I see there is a date/time problem with the file dates. The JAR write sets the file date to bnd highest last modified resource in the manifest and that somehow disagrees with file date of the binary jar. When we build the class path and ask for the binary file we see the sources are older and ignore them. :-(
The file date of the sources file is now > binary JAR.
=> [maven] Sources don’t work

maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java, maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
It's a common practice to enable plugins which are used in most projects in the parent pom. However, sometimes there is a need to not run a specific plugin in one of the projects. Maintaining different parent poms for this is too much work, therefore plugins usually have a skip option which can be enabled in such "special" projects.
This pull request adds the skip option to all three maven plugins
=> Add skip option to maven plugins

biz.aQute.bnd.gradle/bnd.bnd
bnd jar includes resolver code but is missing from gradle plugin
=> gradle: gradle plugin is missing resolver code

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bndlib/src/aQute/bnd/osgi/ZipResource.java
With a configuration set up using files:
dependencies {
compile files('lib/foo.jar')
}
The jar is not in the resolvedConfiguration. See we now use the getFiles
method on Configuration and then probe each file to make sure it is a
zip file before adding to the builder class path.
Closes #1484
=> gradle: bundle task type did not handle plain files in configuration

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndProperties.groovy
Gradle 2.14 has changed the property lookup for ExtensionAware objects
like Project. Instead of consulting the ext properties before asking the
extension object, it now consults the extension object first. This means
that if the extension object implements propertyMissing, it must throw
a MissingPropertyException for 'ext' and also look in the ext properties
before its own properties to preserve the prior behavior.
Fixes https://github.com/bndtools/bnd/issues/1495
See also https://discuss.gradle.org/t/bnd-plugin-broken-in-2-14/17983
=> gradle: Fix bnd extension property lookup for Gradle 2.14

biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java
adding runblacklist to the known_properties will fire the corresponding
PropertyChangeEvent which is needed to fix issue 1397 in BndTools.
Signed-off-by: Marc Schlegel <maschlegel@gmail.com>
=> 1504: BndEditModel does not handle -runblacklist

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
- When user supplies a valid URL, now reports specific errors relating
to failures in including the named resource.
- No longer gives spurious errors after valid URL includes.
Fixes #1534
Signed-off-by: Elias N Vasylenko <eliasvasylenko@gmail.com>
=> Better error handling for -include of URL resources.

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
This avoids throwing InvocationTargetException if the promise failed.
=> maven index: Call Promise.getFailure() to wait for promise to resolve

biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java, biz.aQute.repository/src/aQute/maven/provider/POM.java
packaging type "eclipse-plugin" leads to extension .jar
Signed-off-by: Florian Pirchner <florian.pirchner@gmail.com>
=> Fixes #1531 Packaging "eclipse-plugin" (tycho)

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientTest.java, biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java, biz.aQute.bndlib/src/aQute/bnd/http/URLCache.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
If a file was asked multiple times with the same URL then the locking and caching mechanisms was screwed up.
Removed the file locking for now and use an in memory cache lock.
=> [httpclient] The URL caching mechanism failed

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiRepository.java, biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java, biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java
- Fixed the extension in the file name to be jar
- Use the JSON file for timestamping because the real file gets the remote time
- Improved cache location alg.
=> [osgirepo] Too many downloads

biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
This provides for a consistency in inheriting trace/pedantic/exceptions
from "parent" processors. It also allows exceptions to be set in the
gradle script and be inherited by the project builders.
=> setExceptions: Use the Processor.use method to inherit settings

aQute.libg/src/aQute/lib/filter/Filter.java, biz.aQute.bndlib.tests/src/test/ProcessorTest.java
This will ensure any things needed by the test are loaded using the
current OS settings before changing the OS system properties.
=> native test: Use current OS before changing OS system properties

biz.aQute.bndlib/src/aQute/bnd/osgi/repository/XMLResourceParser.java
The replaced code generated 1000s of not very useful trace outputs.
=> Reduce amount of trace output

README.md, biz.aQute.bndlib.tests/src/test/diff/DiffTest.java, biz.aQute.junit/.settings/org.eclipse.jdt.launching.prefs
biz.aQute.junit now uses Java 6 as the base Java level.
=> Remove all dependencies on Java 5

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
When putting the exception in the Reporter, unwrap
InvocationTargetExceptions to report the underlying cause. Also if trace,
log the exception as info level.
Fixes https://github.com/bndtools/bnd/issues/1601
=> exception: Unwrap InvocationTargetException to record the cause

biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java, biz.aQute.repository/src/aQute/maven/provider/POM.java, biz.aQute.repository/test/aQute/maven/provider/CentralTest.java
Cleaned up usage of promise and fixed a deadlock problem with calling
Promise.getValue in a synchronized block. Also fixed some NPEs.
=> promise: Concurrency fixes in MavenRepository

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
We now avoid waiting for each promise to resolve in some order. The
promises can resolve in any order. The method will return when all
promises have resolved.
=> mavenrepo: Improve use of Promises in sync

biz.aQute.bndlib/src/aQute/bnd/build/Container.java
Not sure how this ever worked but the repository can change the
file path when the DownloadListener calls back. However the 
Container did not replace its file.
=> [build] Container did not replace file from Downloadblocker

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java, biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java, build.gradle
We now use a normal executor with an unbounded queue and thread timeout
for normal Executor needs. A scheduled executor remains available for
tasks needing a schedule.
=> executors: Use 2 executors: One normal and one scheduled

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
The LoggingProgressPlugin will log the exception as an error and it will
be printed out.
=> httpclient: Don't send exception to task progress

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
With the caller-runs rejection policy, we still make progress even on
very large workloads.
=> executor: Reduce thread count to 64

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientTest.java, biz.aQute.bndlib/src/aQute/bnd/service/url/TaggedData.java, biz.aQute.bndlib/src/aQute/bnd/service/url/packageinfo, biz.aQute.repository/src/aQute/maven/nexus/provider/Nexus.java, biz.aQute.repository/src/aQute/maven/provider/MavenRemoteRepository.java, biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
When the input stream was not closed, we never closed the 
progress listener task.
Made TaggedData closable and fixed the code that used the Http Client with a PUT
=> [http] PUT users did not close the input stream

biz.aQute.bndlib/src/aQute/bnd/build/Project.java
This reverts commit c35b0df1fde84e9352c25a286235f2dc7779fa98.
See https://github.com/bndtools/bndtools/issues/1462
=> Revert "project: Use Strategy.LOWEST for -testpath"

biz.aQute.bnd/src/aQute/bnd/main/ResolveCommand.java, biz.aQute.resolve/src/biz/aQute/resolve/ProjectResolver.java
PR #1663 can result in adding multiple workspace resource repositories to a project, especially in a Bndtools use where the Project can live for a long time over multiple resolve operations.
Also, since ProjectResolver now always adds a workspace resource repository, we need to stop the bnd resolve command from also doing it.
=> Fix for #1663

.travis.yml, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/testresources/workspaceplugin1/build.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin1/settings.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin2/build.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin2/settings.gradle, biz.aQute.bndlib.tests/src/test/ProjectTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, build.gradle, settings.gradle
The original meaning of offline was whether the workspace had any
BndListeners. This is moved to another field/method and offline can now
be used to record whether the workspace is in offline mode and should
avoid network access.
=> workspace offline: Repurpose meaning of offline for no network access

biz.aQute.bndlib.tests/src/test/PluginTest.java, biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
The plugins were inherited but also recreated. This was inefficient but also could cause duplication of equals was not properly implemented.
No inherit the object references from the parent and only create plugins for the local level.
=> Deduplication of plugins

biz.aQute.repository/src/aQute/maven/provider/POM.java, biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java
Any unrecognized entities get the ‘&’ replaced by a question mark.
This can potentially cause problems in a CDATA section.
=> [pom] Skip entities

biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java
Change exists to check remote repo
It was including the local repo in the exists check, but since we likely
just built the jar and put it in the local repo via the -buildrepo
instruction, including the local repo in the exists check causes release
to do nothing.
=> Maven repo exists

biz.aQute.resolve/src/biz/aQute/resolve/BndResolver.java, biz.aQute.resolve/src/biz/aQute/resolve/ProjectResolver.java, biz.aQute.resolve/src/biz/aQute/resolve/ResolverValidator.java, biz.aQute.resolve/src/biz/aQute/resolve/packageinfo, biz.aQute.resolve/test/biz/aQute/resolve/ResolveTest.java, biz.aQute.resolve/test/biz/aQute/resolve/repository/JpmRepoTest.java
Previously many cases were using the caller's thread and some cases were
using a created Executor in the ResolverImpl.
=> resolver: Use Processor's executor for resolving

biz.aQute.remote/api.bnd
If biz.aQute.remote.api doesn't export aQute.bnd.util.dto, bnd emits the
warning:
> biz.aQute.remote.api: Export aQute.remote.api,  has 1,  private references [aQute.bnd.util.dto]
=> Fix "private reference" warning in biz.aQute.remote

biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBndPlugin.groovy
The check task is an aggregation/lifecycle task and should not have had
the OSGi test actions on it. So we create a new testosgi task upon which
check depends.
=> gradle: Move OSGi Test actions from 'check' task to new 'testOSGi' task

biz.aQute.resolve/src/biz/aQute/resolve/ResolveProcess.java, biz.aQute.resolve/test/biz/aQute/resolve/repository/JpmRepoTest.java
- Improve exception with collected failed requirements
When resolving fails, use the failed requirements collected by the
AbstractResolveContext to supplement the unresolved requirements in the
thrown exception.
- Handle inverting a wire to the system resource
A wire to the system resource could incorrectly result in the inversion
throwing an IllegalStateException.
=> Resolve fixes

maven/bnd-baseline-maven-plugin/pom.xml, maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/verify.groovy, maven/bnd-export-maven-plugin/pom.xml, maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java, maven/bnd-indexer-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java, maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/LocalIndexerMojo.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java, maven/bnd-testing-maven-plugin/pom.xml, maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
Bnd uses slf4j, so this is consistent.
=> maven: Switch to use slf4j for logging in maven plugins

docs/_chapters/920-faq.md
Updated `optional:=true` to `resolution:=optional` in order to make optional imports 1) not display a warning from bnd and 2) actually be optional in OSGi.
Fixes #1772
Signed-off-by: Gary Sheppard <gsheppard@esri.com>
=> Fixed #1772 (optional imports)

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
This can happen when there is no -runbundles instruction in the bndrun
file.
Fixes https://github.com/bndtools/bnd/issues/1770
=> gradle: Handle null return for BndEditModel.getRunBundles()

biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
Also, register directive is not defined for requirement.
=> verifier: service.loader register can be empty string

aQute.libg/src/aQute/lib/strings/Strings.java, aQute.libg/src/aQute/libg/generics/Create.java, biz.aQute.repository/src/aQute/bnd/deployer/repository/RepoResourceUtils.java, biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java
Now that we use newer java versions, we can make some older methods
varargs for easier usage.
=> libg: Convert some old methods to varargs

aQute.libg/src/aQute/lib/exceptions/Exceptions.java, aQute.libg/src/aQute/lib/exceptions/packageinfo
This matches the spec for DS failure string output in DS 1.4 spec.
=> exceptions: Add a toString method

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
This property can be read and set by build scripts.
=> gradle: Add destinationDir property to export.* and runbundles.* tasks

maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java
String.format uses C-style substitution, not {} as the logger does.
=> Fixed format string

maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
I'm not a maven plugin expert, but apparently this solves the referenced issue. Let me know what do you think.
Solve https://github.com/bndtools/bnd/issues/1839
Signed-off-by: Matteo Rulli <matteo.rulli@flairbit.io>
=> bnd-testing-maven-plugin ignores maven.test.skip/skipTests props - #1839

biz.aQute.bndlib/src/aQute/bnd/url/DefaultURLConnectionHandler.java
DefaultURLConnectionHandler.matches always returned 'true'. Change return value to 'false' if matchers exists, but none of them matches the url.
=> url: fix default return value

aQute.libg/src/aQute/lib/utf8properties/PropertiesParser.java, aQute.libg/test/aQute/lib/utf8properties/UTF8PropertiesTest.java
Older versions of bnd did not allow continuation of lines in bnd files.
When the parser was replaced in bnd 3.1, the new parser began to
continue comments. This restores the original behavior so that a comment
ends at the end of line.
=> bnd file: Comment lines are not continued

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java, biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
If a component class has an annotated method for which the compiler
generates a bridge method, javac will copy the annotations onto the
bridge method. Bnd must ignore bridge methods.
Fixes https://github.com/bndtools/bnd/issues/1546
=> ds annotations: Ignore bridge methods

docs/_instructions/connection-settings.md
As mentioned in #1880 the filename for the bnd connection settings is wrong in the documentation
Should be `~/.bnd/connection-settings.xml` instead of `~/.bnd/settings.xml`
=> Fixed bnd connection-settings filename

biz.aQute.bndlib/src/aQute/bnd/osgi/repository/XMLResourceParser.java
XMLResourceParser extends Processor which makes it Closable but it failed
to make sure the input stream is closed.
Fixes https://github.com/bndtools/bndtools/issues/1623
=> Fix resource leak in XMLResourceParser

aQute.libg/bnd.bnd, biz.aQute.junit/bnd.bnd, biz.aQute.launcher/bnd.bnd, biz.aQute.remote/bnd.bnd, biz.aQute.repository.aether/bnd.bnd, biz.aQute.repository/bnd.bnd, biz.aQute.repository/src/aQute/bnd/repository/p2/provider/package-info.java, biz.aQute.resolve/bnd.bnd, biz.aQute.tester/bnd.bnd, org.osgi.impl.bundle.repoindex.ant/bnd.bnd, org.osgi.impl.bundle.repoindex.api/bnd.bnd, org.osgi.impl.bundle.repoindex.api/src/org/osgi/service/indexer/packageinfo, org.osgi.impl.bundle.repoindex.cli/bnd.bnd, org.osgi.impl.bundle.repoindex.lib/bnd.bnd
New `-diffpackages` features is used for `biz.aQute.junit`.
=> Enable Baselining in most projects

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bndlib.tests/src/test/ProjectTest.java, biz.aQute.bndlib/src/aQute/bnd/build/JUnitLauncher.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
The output folder had to be removed from the buildpath for bndtools and
the gradle plugin since it is not part of the compile path.
Project builder must add the output folder to the builder classpath.
=> buildpath: Remove output folder from buildpath

biz.aQute.bndlib.tests/src/test/diff/DiffTest.java, biz.aQute.bndlib/src/aQute/bnd/differ/JavaElement.java
Baselining should be about binary compatibility and the only the erased
signature matters. Prior to this fix, adding generics to code which did
not alter the erased signature would result in a MAJOR baseline change
as the differ saw a method added and a method removed.
Also, the diff failed to properly rate changing the return type from
void or Object to some other type. Changing from void to non-void or
from Object to some other type is equivalent to replacing the method.
=> baseline: Compare on erased types and handle void/Object return types

biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bundle.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBundlePlugin.groovy, biz.aQute.bnd.gradle/testresources/builderplugin1/build.gradle, biz.aQute.bnd.gradle/testresources/builderplugin1/bundle.bnd
This replaces the configuration property and defaults to the
compileClasspath property of the sourceSet property.
=> gradle: Update Bundle task type to use classpath property

biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy, biz.aQute.bnd.gradle/testresources/baselinetask1/build.gradle, biz.aQute.bnd.gradle/testresources/baselinetask2/build.gradle
Accept more input types for bundle to baseline and baseline. Include
baseline report text in message when a mismatch. Add @OutputFile to
avoid rebaselining unnecessarily.
=> gradle: Baseline task type improvements

aQute.libg/src/aQute/libg/generics/Create.java, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bndlib.tests/src/test/ProjectTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.resolve/src/biz/aQute/resolve/Bndrun.java, maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java, maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
And a number of other fixes including avoiding rewriting -savemanifest output on release.
=> Avoid rebuilding jars on release

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy, biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java, biz.aQute.bndlib/src/aQute/bnd/differ/DiffImpl.java, biz.aQute.bndlib/src/aQute/bnd/differ/packageinfo, maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java
DiffImpl is made Formattable. Use `%#S` to get the nicely formatted, multil-line output of the changed elements in a Diff including all children. `#` flag triggers this alternate format. `%#S` instead of `%#s` limits the output to just changed elements instead of all elements. Specify a width for the alternate format, e.g. `%#2S`, will indent each line of the output by the specified width.
=> Improvement to baseline diff formatting

biz.aQute.bndlib/src/aQute/bnd/build/Project.java
Builder.build() sets the jar name to the bsn so even if the jar has no
manifest, the jar name is always the bsn.
Fixes https://github.com/bndtools/bnd/issues/518
=> project: Handle -nomanifest when saving jar

biz.aQute.junit/src/aQute/junit/JunitXmlReport.java
The exception message can be null. Adding null value to map caused NPE.
=> junit: Handle null exception message

biz.aQute.launcher/src/aQute/launcher/Launcher.java, biz.aQute.launcher/src/aQute/launcher/constants/LauncherConstants.java
Allow override of any of the launcher constants as 
well as allowing to override calculated org.osgi.framework.storage
property when set as system property. That is, the following
forces the framework dir regardless of other settings.
java -Dorg.osgi.framework.storage=fw -jar foo.jar
=> [launcher] #1952  Executable JAR working directory

biz.aQute.bndlib/src/aQute/bnd/build/Classpath.java, biz.aQute.bndlib/src/aQute/bnd/build/JUnitLauncher.java, biz.aQute.bndlib/src/aQute/bnd/differ/Baseline.java, biz.aQute.bndlib/src/aQute/bnd/osgi/packageinfo, biz.aQute.bndlib/src/aQute/bnd/version/MavenVersion.java, biz.aQute.bndlib/src/aQute/bnd/version/VersionRange.java
- Removed some unnecessary couplings between packages that made the reuse of the version package and aQute.bnd.osgi cumbersome. This includes moving Classpath to the build package and moving constants into the version package.
- Added a reason field to the Baseline package info (info) structure and the bundle info (binfo) structure that specifies the root reason.
=> Baselining fixes

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java, biz.aQute.bndlib.tests/src/test/metatype/SpecMetatypeTest.java, biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java, biz.aQute.bndlib/src/aQute/bnd/metatype/MetatypeVersion.java, biz.aQute.bndlib/src/aQute/bnd/metatype/OCDReader.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Descriptors.java
=> Support for new DS 1.4/Metatype 1.4 property name mapping rules

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
The inputs.files jar statement means the task will depend on the jar
task.
=> gradle: No reason to depend on assemble for testOSGi and release tasks

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy
The gradle.ext.bndWorkspaceConfigure property can be set to a closure
that is passed the Workspace object after construction. The closure can
then further configure the Workspace object.
=> gradle: Support configuring Workspace after construction

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/PropertiesWrapper.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBundlePlugin.groovy, biz.aQute.bnd.gradle/testresources/builderplugin1/bnd.bnd, biz.aQute.bnd.gradle/testresources/builderplugin1/build.gradle
‘task’ stub provides access to the task’s gradle properties. ‘project’
stub provides access to the project’s gradle properties.
=> gradle: Provide access to gradle properties for bnd files

biz.aQute.junit/bnd.bnd, biz.aQute.junit/src/aQute/junit/Activator.java, biz.aQute.junit/src/aQute/junit/JunitXmlReport.java, biz.aQute.junit/src/aQute/junit/runtime/OSGiTestCase.java, biz.aQute.launcher/bnd.bnd, biz.aQute.launcher/src/aQute/launcher/Launcher.java, biz.aQute.launcher/src/aQute/launcher/SimplePermissionPolicy.java, biz.aQute.launcher/src/aQute/launcher/minifw/Context.java, biz.aQute.launcher/src/aQute/launcher/minifw/MiniFramework.java, biz.aQute.tester/bnd.bnd, cnf/ext/central.mvn
This PR properly uses OSGi 4.2 companion code jars to target OSGi 4.2 runtimes. The Launcher code had to revert from using the Bundle Wiring API to the older Package Admin api for refreshing bundles.
Fixes https://github.com/bndtools/bnd/issues/1985
Closes https://github.com/bndtools/bnd/pull/1986
=> Support OSGi 4.2 runtimes with junit/tester/launcher

aQute.libg/src/aQute/lib/zip/ZipUtil.java, biz.aQute.bndlib/src/aQute/bnd/osgi/FileResource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/URLResource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ZipResource.java
If a resource is called to write itself out, then use the buffer if it already had been created, otherwise just write out the resource. This can avoid creating the buffer entirely for some resources.
=> resource: avoid buffer creation

aQute.libg/src/aQute/lib/io/IO.java, biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/EmbeddedResource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/FileResource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ZipResource.java
Their use can pin files. So for Windows, we just use the input stream for large files rather than a mapped byte buffer.
Also, the Jar building logic is concentrated in a single class now.
=> resource: Avoid using mapped ByteBuffers on Windows

aQute.libg/src/aQute/lib/io/IO.java, aQute.libg/test/aQute/lib/io/IOTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java, biz.aQute.bndlib/src/aQute/bnd/osgi/URLResource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ZipResource.java
This avoids need to create ByteArrayInputStream and then a new byte array to hold the read data.
=> jar: Use zip entry size, if known, to allocate byte array

biz.aQute.bndlib/src/aQute/bnd/build/Container.java, biz.aQute.bndlib/src/aQute/bnd/build/DownloadBlocker.java, biz.aQute.bndlib/src/aQute/bnd/util/repository/DownloadListenerPromise.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
We convert the promise resolved with null to a DownloadBlocker failure.
So for https://github.com/bndtools/bndtools/issues/1694, the Container will not return a null file.
=> Better handle cases where repo provided null file

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java, biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java
Even if the value is a single element, the resulting <property> element
must be an array also.
=> ds: Array annotation elements have array properties

maven/bnd-baseline-maven-plugin/pom.xml, maven/bnd-export-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/pom.xml, maven/bnd-maven-plugin/pom.xml, maven/bnd-resolver-maven-plugin/pom.xml, maven/bnd-shared-maven-lib/pom.xml, maven/bnd-testing-maven-plugin/pom.xml
The effective pom takes these URLs from the parent pom and adds the
child pom’s folder name making them invalid URLs. So we have to repeat
in each pom.
=> maven: We need to repeat some URLs to avoid them being “extended”

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy
For some reason, Gradle is throwing a ResolveException when it should
not. Getting a ResolvedConfiguration should not throw an exception.
Fixes https://github.com/bndtools/bnd/issues/2024
=> gradle: Better handle resolve errors in baseline task defaults

aQute.libg/src/aQute/lib/utf8properties/PropertiesParser.java, aQute.libg/test/aQute/lib/utf8properties/UTF8PropertiesTest.java
The properties parser now detects missing delimiters after 
a quoted string. We could still do checks when we know
what the header means but I think this catches more
of the problems.
=> Bnd gets confused by ill-formed bundle references #1864

maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java
On projects without distributionManagement, releaseDistroRepo is null, inserted at the head of the list and it causes Aether to throw a NPE.
It is difficult to test because the current maven baseline tests rely on distributionManagement with a local repo to find a baseline, and this happens only after a baseline has been found. It might be possible by setting settings to offline, and provisioning a test m2 local repository, but I hope a NPE fix does not warrant so much maven pain. :grin: 
There is a workaround with:
```xml
<properties>		
<bnd.baseline.include.distribution.management>false</bnd.baseline.include.distribution.management>
</properties>
```
=> Issue #2040: Fix NPE when a project has no distributionManagement

biz.aQute.bndlib.tests/src/test/AnalyzerTest.java, biz.aQute.bndlib.tests/src/test/dynamicimport/DynamicImport.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, docs/_heads/import_package.md
Packages in Import-Package marked with resolution:=dynamic will be moved to the DynamicImport-Package entry after expansion takes place.
The test demonstrates packages get their version attribute added and are properly expanded, and moved to DynamicImport-Package (added after the existing instruction, and removed from Import-Package), and that other imported packages are not affected.
I see no regression risk unless someone used resolution:=dynamic in an existing build... but then again, as far as I know the directive "resolution" is reserved by the OSGi spec.
=> Support DynamicImport-Package expansion (issue #2038)

biz.aQute.bnd/src/aQute/bnd/main/ResolveCommand.java, biz.aQute.resolve/src/biz/aQute/resolve/Bndrun.java, maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/resolve/DependencyResolver.java, maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
Overload with a method that takes a Converter if custom conversion is
necessary. This avoids most users from being exposed to a list of
VersionedClauses and having to supply a Converter.
Also fixed potential NPE in ResolveCommand where a null List could be
returned. Also restored isOk check before displaying output.
=> bndrun: Restore resolve method to return a String

biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
If the macro is used multiple times it finds the first occurrence. Attempting to find the reported string is very complex since this string can contain macros so the source is different from what is reported. 
=> [macro] Properly report position of the error and warning macros.

biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java
Some RepositoryPlugin::toString returns stateful information of the repository so they won't
be picked up if you have ordered/selected repositories in .bnd(run) files
=> Use RepositoryPlugin::getName to get repository names where applicable

biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java, biz.aQute.launcher/src/aQute/launcher/Launcher.java
This means by default, the ProjectLauncher will use the same java to
launch the project as is running Bnd. Otherwise, you use whatever the
default java on the platform which is now Java 9 on my system unless
JAVA_HOME is configured to point to some other Java. And JAVA_HOME
is unset in Eclipse.
This PR allows the test cases which launch a child VM to use the same Java runtime. This allows the tests to pass in Eclipse when you have Java 9 installed since the various frameworks used by test cases do not properly work under Java 9.
=> launcher: Use java.home to find default java executable

biz.aQute.bndlib.tests/src/test/resource/CapReqBuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapReqBuilder.java, docs/_instructions/runrequires.md
Fixes #1996
Example:
-runrequires: bundle; bsn=org.example.foo; version=1.0
which translates to:
-runrequires: osgi.identity; filter:=‘(&(osgi.identity=org.example.foo)(version>=1.0.0))’
=> Support abbreviated syntax for -runrequires

maven/bnd-export-maven-plugin/README.md, maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java, maven/bnd-export-maven-plugin/src/test/resources/integration-test/test/export-from-inputbundles/pom.xml, maven/bnd-resolver-maven-plugin/README.md, maven/bnd-resolver-maven-plugin/src/main/java/aQute/bnd/maven/resolver/plugin/ResolverMojo.java, maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/resolve-from-inputbundles/pom.xml, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/resolve/DependencyResolver.java, maven/bnd-testing-maven-plugin/README.md, maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
This is to make the option more self-documenting. The old name,
useDefaults, was too vague.
=> maven: Rename option to useMavenDependencies

maven/bnd-indexer-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/index-deployment-repo-no-dist-mgmt/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-deploy-no-dist-mgmt/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-deploy-no-dist-mgmt/src/main/resources/META-INF/MANIFEST.MF, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/verify.groovy, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/resolve/DependencyResolver.java
It is possible (and often recommended) to configure your deployment repositories using command line properties, as these may vary depending on the user. This is done using one of several properties such as [altReleaseDeploymentRepository](https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#altReleaseDeploymentRepository).
The indexer can't find these repos (as they aren't in the project model) and so blows up. This is less than ideal! We need to pay attention to these properties and to add them to the list of possible indexer locations if they are defined.
=> bnd-indexer-maven-plugin misses deployment repo properties

dist/build.gradle
It seems that on windows, passing the fileTree to inputs could keep
some of the files open in the daemon preventing them from being
deleted and replaced in the next build operation.
=> build: Pass closure instead of fileTree to inputs

aQute.libg/src/aQute/libg/uri/URIUtil.java, aQute.libg/test/aQute/libg/uri/URIUtilsTest.java
This fixes bugs when the relative URL in the `-standalone` instruction contains spaces or other characters not allowed in URIs.
=> lib: Handle spaces in reference for URIUtil

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java
Timing could cause init to be called before setProperties. We also set
inited under synchronized.
Fixes https://github.com/bndtools/bnd/issues/2084
=> pom repo: Defer marking inited until after init completed

biz.aQute.junit/src/aQute/junit/Activator.java
Since fragment bundles are never started or active, we need to check the
active state of the fragment's host.
=> test: Properly handle Test-Cases header in fragment bundles

cnf/ext/central.mvn
This prevents an unnecessary increase in the dependency version for biz.aQute.tester. Without this change it is possible for bundle integration tests to stop working when moving from 3.3.0.REL to 3.4.0.RC3 (for example if they include JUnit 4.11 in their runbundles).
=> Move JUnit dependency version back to 4.11

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
This new property replaced the deprecated SourceSetOutput classesDir
property. Gradle 4.1 builds issue a nasty warning when using that
deprecated property.
We still work on Gradle version 3 and 2.
This change also solves the problem of running the gradle test methods
twice which caused failures with Gradle 4.0.
=> gradle: Use SourceDirectorySet outputDir property for Gradle 4

biz.aQute.bndlib/src/aQute/bnd/build/Project.java
Gradle is aggressive about deleting bin folders when something changes.
Since it does this after the Bnd Projects are first prepared, we need
to ensure the output folders are recreated if necessary on future
calls to prepare.
=> prepare: Always make sure primary output folders exist

biz.aQute.bndlib.comm.tests/bnd.bnd, biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientProxyTest.java, biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/SettingsParserTest.java, biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/Standalone.java, biz.aQute.bndlib.comm.tests/testresources/proxy-types.xml, biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java, biz.aQute.bndlib/src/aQute/bnd/connection/settings/ProxyDTO.java, cnf/ext/central.mvn
Fixes #2108 
This PR changes the Proxy DTO to use a String, rather than a type. This, in turn, lets bnd support URL schemes other than HTTP. The rest of the PR fixes up the usage of the DTO, and adds two new tests
* A test to ensure that the parser doesn't blow up when it encounters an https proxy type
* A test to ensure that the HTTPS proxy actually uses HTTPS
The tests are also updated to ensure that the requests actually go through the proxy when they're supposed to.
=> Add support for HTTPS proxies

aQute.libg/src/aQute/lib/utf8properties/ThreadLocalCharsetDecoder.java, aQute.libg/src/aQute/lib/utf8properties/UTF8Properties.java
CharsetDecoders are not thread-safe. We use thread locals to avoid
always having to create new decoders for each invocation.
Reported by @rotty3000.
=> utf8: Avoid sharing CharsetDecoders between threads

biz.aQute.launcher/src/aQute/launcher/Launcher.java
This was already fixed by BJ in https://github.com/bndtools/bnd/commit/1ad80861fd0c20eca994e34d5198be8a3efd21d7
But it reappeared as part of https://github.com/bndtools/bnd/commit/deaa9651d5f7dab1368eeabbe58076e98df95490
However, I think the implementation of https://github.com/bndtools/bnd/commit/1ad80861fd0c20eca994e34d5198be8a3efd21d7 is the correct one
=> Fix Launcher isFragment check to work without PackageAdmin

maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/resolve/DependencyResolver.java
Using just HashMap can lead to traversal ordering differences across JVM impls.
=> maven: Used LinkedHashMap to ensure consistent ordering on traversal

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
Otherwise, the merged property ends up including ",," which is then
warned about later when parsing as an Empty clause.
=> processor: Ignore empty property values when merging properties

biz.aQute.bndlib/src/aQute/bnd/osgi/FileResource.java
So we remove the change Peter made to handle the file changing (in only
a single place). If, in the future, we want to handle the file changing
underneath a FileResource object, this class will need more extensive
changes.
=> resource: FileResource wraps a file which should not change

biz.aQute.bndlib/src/aQute/bnd/osgi/repository/XMLResourceParser.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/packageinfo, biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java
If the hash of the current URI does not match the repository name in the
index, then the URI was changed since the index was written and the
index is invalid. So we read the repository from the URI.
Replaces https://github.com/bndtools/bnd/pull/2164
=> p2repo: Use hash of URI for repository name to detect changes in URI

biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java
This change also improves the text of the warning message that occurs when an annotation cannot be loaded to check whether it is a component property annotation.
=> Avoid DS annotation scanning when there is no @Component annotation

biz.aQute.bndlib.tests/bnd.bnd, biz.aQute.bndlib.tests/src/test/annotationheaders/StdAnnotationHeadersTest.java, biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/AnnotatedAnnotation.java, biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/UsingAnnotatedAnnotation.java, biz.aQute.bndlib.tests/src/test/annotationheaders/multiple/std/PetstoreAppComponent.java, biz.aQute.bndlib/bnd.bnd, biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java, biz.aQute.bndlib/src/aQute/bnd/make/metatype/MetaTypeReader.java, biz.aQute.bndlib/src/aQute/bnd/metatype/DesignateReader.java, biz.aQute.bndlib/src/aQute/bnd/metatype/OCDReader.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Annotation.java, biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java, biz.aQute.bndlib/src/aQute/bnd/xmlattribute/ExtensionDef.java, cnf/ext/osgi-snapshots.mvn
This is a first attempt at supporting the OSGi R7 bundle annotations, it includes some minor refactoring of the annotation processing logic to make things a little more consistent, as well as support for `@Requirement` and `@Capability`. `@Header` is also processed, but for some reason it never makes it into the output manifest.
This seems worth merging as is, as I know that both @bjhargrave and I will be talking about this support at the OSGi Community Event next week, and if this is integrated we can demonstrate using a Bndtools DEV driver.
=> Support for Bundle annotations

biz.aQute.bndlib/bnd.bnd
This avoids the need for the standard bundle annotations to be on the build path, and lets us use them at runtime
=> Repackage the standard Bundle annotations

biz.aQute.bndlib.tests/src/test/component_extra/DSPropertyAnnotationsTest.java, biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java
When using a ComponentPropertyType annotation on a DS component the properties are merged into standard XML and no special runtime knowledge is needed. We should therefore avoid bumping the required version needlessly
=> Be more lenient with required DS version

biz.aQute.bndlib.tests/src/test/ResourcesTest.java, biz.aQute.bndlib/src/aQute/bnd/junit/JUnitFramework.java, biz.aQute.bndlib/src/aQute/bnd/make/MakeCopy.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Resource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/URLResource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ZipResource.java, biz.aQute.bndlib/src/aQute/bnd/testing/DSTestWiring.java, biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java, biz.aQute.remote/src/aQute/remote/plugin/RemoteProjectLauncherPlugin.java
On Windows, using a jar:file: URL locks the file. This is for 2 reasons.
One, unless setUseCaches(false) is set, the JarURLConnection will hold
the created JarFile open in a cache. Two, even then, the JarURLConnection
holds a FileURLConnection keeps an open input stream on the file and
there is no way to close this inputstream.
So we completely avoid using jar:file: URLs by inspecting the URL and
using either a FileResource or a ZipResource to read the item described
by the URL.
Closes #2184
=> resource: Fix file locking when using jar:file: URL

biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Resource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ZipResource.java
When using `-include: jar:file:/somefile!/someentry`, Bnd will extract the resource to a tmp file and then include the tmp file. The tmp file is then deleted but we left it in the included file list. This PR stops that.
Also the PR avoids opening `jar:file:` URLs directly to avoid Windows file locking issues. It uses `Resource.fromURL` instead to access the resource which avoids the file lock issue on Windows.
=> Don't add tmp files to included list

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
If we let the archiveName default, then setting project.version can
cause gradle to add a file, which Bnd will not generate, to the jar task
outputs. This can cause gradle to think outputs have changed when they
have not. So we set jar.archiveName so that it will not default to the
name of an artifact that Bnd may not generate.
=> gradle: Set jar.archiveName to name of first generated artifact

aQute.libg/src/aQute/lib/io/IO.java, aQute.libg/test/aQute/lib/io/IOTest.java
When path to the local Maven repository is a symlink:
file ~/.m2/repository
returns
/home/user/.m2/repository: symbolic link to /home/user/.cache/m2/repository/
MavenRepository fails with:
java.nio.file.FileAlreadyExistsException: /home/user/.m2/repository
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
at java.nio.file.Files.createDirectory(Files.java:674)
at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
at java.nio.file.Files.createDirectories(Files.java:727)
at aQute.lib.io.IO.mkdirs(IO.java:753)
at …
=> Support the path to local Maven repository to be a symbolic link

maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/verify.groovy, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/resolve/DependencyResolver.java
Fixes #2198 (scopes not filtering dependencies).
Signed-off-by: Simon Chemouil <simon.chemouil@lambdacube.fr>
=> maven dependency resolver: proper scope filtering

biz.aQute.bndlib/src/aQute/bnd/junit/JUnitFramework.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/util/repository/DownloadListenerPromise.java, biz.aQute.bndlib/src/aQute/bnd/util/repository/package-info.java
When a class in a package implements a provider type interface in the
same package, exporting that package must not result in a provider import
range for the substitutable import. So we don't consider interfaces when
they are implemented by a class in the same package as triggering
provider range import.
=>  analyzer: Don't use provider import range for self implemented interface 

biz.aQute.bndlib/src/aQute/bnd/osgi/repository/XMLResourceParser.java
The referral element is read but the XML parser was not moved
to the end tag, causing the whole parsing to fail. This patch
simply makes sure the parser is moved ahead the same way it is
done for other XML elements such as resources. Fixes #2210.
Please note that there is currently no unit test for referrals, or the
bug would have been caught. This patch merely fixes the bug 
but I have no time to add a test case.
=> index: parse referrals correctly

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
hasProperty was apparently not being called on the options object and
thus never returned true resulting in a warning from gradle.
=> gradle: Test for property on correct object

biz.aQute.bndlib.tests/src/test/BuilderTest.java, biz.aQute.bndlib.tests/src/test/ExportAnnotationTest.java, biz.aQute.bndlib.tests/src/test/VersionPolicyTest.java, biz.aQute.bndlib.tests/src/test/export/annotation/DummyInterface.java, biz.aQute.bndlib.tests/src/test/export/annotation/package-info.java, biz.aQute.bndlib/src/aQute/bnd/header/Parameters.java, biz.aQute.bndlib/src/aQute/bnd/header/packageinfo, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
This does not include anything for the substitution attribute of the annotation, as I have no idea how to implement that, but it does cover the attributes and uses behaviour. The commit also deprecates the bnd annotation.
=> Add support for the standard @Export annotation

aQute.libg/src/aQute/libg/command/Command.java
=> Inherit standard input from parent process in Command.execute

biz.aQute.bndlib.tests/src/test/BndEditModelTest.java, biz.aQute.bndlib.tests/testresources/standalone.bndrun, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
There does not seem to be a good reason to copy the content of the Run file into
the standalone "Workspace". When we do this, the properties are duplicated at
both levels.
As a result it becomes impossible to remove a key from a BndEditModel... in
`BndEditModel#loadFrom(InputStream)` we do a "clear" which involves repopulating
the map from the content of the workspace, but in the standalone case this just
reloads from whatever the content of the file was when first opened. So you
cannot delete a key from the map.
=> Don't duplicate properties in standalone Workspace

docs/_chapters/300-launching.md
This pull-request fixes the first example of http://bnd.bndtools.org/chapters/300-launching.html where runrequires was missing "s".
=> docs: fix typo runrequire -> runrequires

aQute.libg/src/aQute/lib/collections/Iterables.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
We also use Set as the first argument type to show distinctness.
=> iterables: use a better member class name

biz.aQute.bndlib.tests/src/test/annotationheaders/StdAnnotationHeadersTest.java, biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/AnnotatedAnnotation.java, biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java
Using the cardinality or resolution attributes of the Requirement annotation resulted in an upper cased value in the manifest which caused bnd to complain.
=> Avoid using upper case for generated requirement directives

biz.aQute.bndlib.tests/bnd/noactivator.bnd, biz.aQute.bndlib.tests/src/test/BuilderTest.java, biz.aQute.bndlib.tests/src/test/MakeTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
The Verifier was complaining that a bundle did not have a bundle
activator when it was able to see the outer bundle's Bundle-Activator
property.
=> processor: getUnprocessedProperty must respect the local only filter

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
The extension must not be based upon the jar name which could be based
upon the project name. So now we set the jar name to the correct
classifier and always use the extension jar.
=> maven: Use correct extension for sources and javadoc artifacts

docs/_instructions/runsystempackages.md
Typo in runsystempackages' example.
=> docs: fix typo runsystempackage -> runsystempackages

biz.aQute.repository/src/aQute/bnd/deployer/repository/wrapper/InfoRepositoryWrapper.java, biz.aQute.repository/test/aQute/bnd/deployer/repository/wrapper/TestWrapper.java
=> InfoRepositoryWrapper: Ensure we always return (at least) an empty list

biz.aQute.bndlib/src/aQute/bnd/osgi/repository/ResourcesRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
We change the IndexFile.findProviders method to now use ResourcesRepository since it always includes the input requirements in the result.
=>  maven: findProviders must always include the requirements in result 

aQute.libg/src/aQute/lib/collections/SortedList.java, aQute.libg/src/aQute/libg/command/Command.java, aQute.libg/src/aQute/libg/command/packageinfo, biz.aQute.bndlib.tests/src/test/ParseHeaderTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/header/Parameters.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
A new method is added to Parameter to return a list of the keys with duplicate markers removed.
Some other fixes are also in this PR.
=> Handle duplicate values allowed in some instructions such as -runvm

biz.aQute.bndlib.tests/src/test/MavenVersionTest.java, biz.aQute.bndlib/src/aQute/bnd/differ/DiffPluginImpl.java, biz.aQute.bndlib/src/aQute/bnd/differ/JavaElement.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java, biz.aQute.bndlib/src/aQute/bnd/version/ComparableVersion.java, biz.aQute.bndlib/src/aQute/bnd/version/MavenVersion.java, biz.aQute.bndlib/src/aQute/bnd/version/Version.java, biz.aQute.bndlib/src/aQute/lib/deployer/FileRepo.java
We use the code from maven, with some modifications, to do the sorting:
https://github.com/apache/maven/blob/5988085525a39025a9f3d7cfb0592d42261abaf0/maven-artifact/src/main/java/org/apache/maven/artifact/versioning/ComparableVersion.java
Thanks to @mnlipp for the pointer to the maven-artifact code.
Fixes https://github.com/bndtools/bnd/issues/2287
=> mavenversion: Handle strange maven qualifier sorting rules

biz.aQute.bndlib.tests/src/test/MacroTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
Returns the result of calling list1.retainAll(list2).
Complements new ${removeall} macro.
=> macro: Add ${retainall;list;list} macro

biz.aQute.bndlib/src/aQute/bnd/osgi/Resource.java
We now use a URI object to decode the string and toAbsolutePath to
ensure the path is not relative.
Fixes https://github.com/bndtools/bndtools/issues/1834
This should solve the problem in this bug since the home UNC folder is
no longer referenced since we are not resolving to a URI of that folder.
=> resource: Avoid URI resolve which fails badly with UNC names on Windows

.gradle-wrapper/gradle-wrapper.properties, aQute.libg/src/aQute/libg/sed/ReplacerAdapter.java, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java, build.gradle, cnf/build.bnd
Add support to Bnd to build the identical jar reproducibly. This requires Bnd to not cause variation which is done by `-reproducible: true` which results in jar file entries having a constant time stamp.
Furthmore, the build itself must not add variation to manifest entries like Bundle-Version using a time stamp of the build time. For the Bnd build, the build is changed to use the current time if the git workspace if dirty or the commit time of the tip commit of the git workspace is clean.
The combination of these will allow anyone to checkout a specific commit and build the same jars.
=> Reproducible jars

aQute.libg/src/aQute/libg/glob/AntGlob.java, aQute.libg/test/aQute/libg/glob/AntGlobTest.java
Review of ant behavior means this must be supported since users will
expect to use / or \ as separators in the glob expression.
=> antglob: Allow \ as a separator in glob

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBndPlugin.groovy, biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolve.bndrun, biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolvechange.bndrun, biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolveerror.bndrun, biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolvenochange.bndrun, biz.aQute.bnd.gradle/testresources/workspaceplugin7/test.simple/export.bndrun
Update Export task type to also function in workspace model builds so I can use the task type from the BndPlugin for the export and runbundles tasks.
=> Gradle export task

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
These method never return null, so we can elide null checks in stream
pipelines.
=> clazz: Use new interfaces/annotations methods

biz.aQute.junit/src/aQute/junit/JUnitEclipseReport.java
countTestCases() includes ignored tests.
Fixes https://github.com/bndtools/bnd/issues/2377
=> junit: Use getTests().size() for JUnit4TestAdapter

biz.aQute.bndlib.tests/bnd.bnd, biz.aQute.bndlib.tests/src/test/ProcessorTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, cnf/ext/central.mvn, cnf/ext/junit.bnd
Make sure that when error() and warning() call location(), they do so on the current owner process instead of on themselves.
Includes a test case.
=> Processor: capture error/warning locations as well as the messages.

docs/_heads/include_resource.md
This section is rather important and collapses into an unreadable mess on the website.
Hopefully being in a code block will retain the formatting.
See http://bnd.bndtools.org/heads/include_resource.html for the current page.
=> Fix formatting of iclause definition

maven/bnd-export-maven-plugin/README.md, maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java, maven/bnd-indexer-maven-plugin/README.md, maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/LocalIndexerMojo.java, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/index-folder-includes-excludes/pom.xml, maven/bnd-resolver-maven-plugin/README.md, maven/bnd-resolver-maven-plugin/src/main/java/aQute/bnd/maven/resolver/plugin/ResolverMojo.java, maven/bnd-resolver-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/configuration/Bndruns.java, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/configuration/Bundles.java, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/configuration/FileTree.java, maven/bnd-testing-maven-plugin/README.md, maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java, maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/pom.xml
The Ant-style glob support was refactored into a FileTree class which
is used in several places for plugin configuration as a complex config
type.
`<bndruns>` configuration can now take:
- `<bndrun>` elements naming a specific file
- `<include>` elements specifying an Ant-style glob to include from the
project basedir
- `<exclude>` elements specifying an Ant-style glob to exclude from the
project basedir
`<bundles>` configuration can now take:
- `<bundle>` elements naming a specific file
- `<include>` elements specifying an Ant-style glob to include from the
project basedir
- `<exclude>` elements specifying an Ant-style glob to exclude from the
project basedir
The recent support for Ant-style globbing in the indexer plugin was
also modified to use this common function and the …
=> maven: Support include/exclude Ant-style globs in bndruns/bundles config

maven/bnd-baseline-maven-plugin/README.md, maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/Base.java, maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java, maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java, maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java, maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/LocalIndexerMojo.java, maven/bnd-resolver-maven-plugin/src/main/java/aQute/bnd/maven/resolver/plugin/ResolverMojo.java, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/configuration/Bndruns.java, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/configuration/Bundles.java, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/configuration/FileTree.java, maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
Also add some javadoc to configuration methods.
Fixes https://github.com/bndtools/bnd/issues/2404
=> maven: Remove readonly=true for better Eclipse pom editing experience

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy
In the off chance that the cnf project has project dependencies, we need
to make sure they are also included in the project graph.
=> gradle: Add cnf to the project graph so that dependencies are processed

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
If the build makes a jar which is used to load a plugin, we need to get
a new class loader when the project is refreshed to access the updated
plugin class.
=> plugins: Discard the plugin class loader on refresh

aQute.libg/src/aQute/lib/strings/Strings.java
We move all the emptyValue handling into the finisher function since
that is really the only place it must be processed.
=> strings: Simplify joining Collector

aQute.libg/src/aQute/lib/io/IO.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
This avoids issues when moving the temp file to the target file.
Fixes https://github.com/bndtools/bnd/issues/2401
=> windows: Create temp file on same volume as target file

biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
This avoids issues when using paths in replacement strings in ${replace}
macro.
=> workspace: Canonicalize file paths to use forward slash

biz.aQute.bndlib.tests/src/test/annotationheaders/StdAnnotationHeadersTest.java, biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/AttributeDirectiveOverriding.java, biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/ExtenderCapReq1.java, biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/ExtenderCapReq2.java, biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/ExtenderCapability.java, biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/ExtenderRequirement.java, biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java
* members of `@Requirement` and `@Capability` can be overridden by using the same member name with no `@Attribute` or `@Directive`. 
* `@Attribute` and `@Directive` can override annotation members from higher up the chain.
=> Support the remaining features of Bundle annotations

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndUtils.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Resolve.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/TestOSGi.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBndPlugin.groovy, biz.aQute.bnd.gradle/testresources/workspaceplugin6/build.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin6/settings.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/build.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin6/test.simple/resolve2.bndrun, biz.aQute.bnd.gradle/testresources/workspaceplugin7/build.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin7/settings.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin7/test.simple/build.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin7/test.simple/export2.bndrun, biz.aQute.bnd.gradle/testresources/workspaceplugin9/build.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin9/test.simple/build.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin9/test.simple/testOSGi2.bndrun
If the build.gradle file declares buildscript, a new class loader will
be used for plugins that is different than the one used for
settings.gradle. This can mean than the Bnd gradle plugin can be loaded
by each class loader and then using task types (like TestOSGi) in build
scripts can result in class cast type issues.
We work around this in the Bndrun, Export, Resolve and TestOSGi task
types by avoiding typed references to Bnd types like Workspace and
Project since the values passed by settings.gradle will use the class
loader for settings.gradle which may be a different class loader than
used by build.gradle.
=> gradle: Work with Bnd plugin loaded in two class loaders

biz.aQute.bndlib/bnd.bnd, biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java, biz.aQute.launcher/bnd.bnd, biz.aQute.repository/bnd.bnd
When running outside of an OSGi framework, Bnd still needs access to
some org.osgi packages. We adjust how those are included in the bnd jars.
Fixes #2471
=> build: Adjust inclusion of org.osgi packages

biz.aQute.bnd.gradle/.gitignore, biz.aQute.bnd.gradle/publish.gradle
We download the binaries from Maven Central and then populate the project
artifacts with these binaries. These are then published to the Gradle
Plugin Portal as if they were built by the project.
This publish script needs to be executed _after_ each release is
available in Maven Central so that the same binaries are also available
from the Gradle Plugin Portal.
Fixes https://github.com/bndtools/bnd/issues/2468
=> gradle: Script to publish binary plugin to Gradle Plugin Portal

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java
If a pom is encountered with transitive false before the pom is
encountered as a root pom, then it will fail to be parsed.
See https://groups.google.com/d/msg/bndtools-users/_AbaKPmhkKg/JjPJHe-8BgAJ
=> maven: Fix Traverser to remove timing issue

biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
Per the Jar Manifest spec, there must always be a blank line after the
main attributes even if there are no individual sections.
This change also emits a blank line after each individual section. The
Jar Manifest spec does not require this but the java.util.jar package
does this when writing a manifest.
=> jar: Make sure there is always a blank line after manifest main attrs

biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBndPlugin.groovy, biz.aQute.bnd.gradle/testresources/workspaceplugin9/test.simple/build.gradle
This enables testrun.xxx tasks of type TestOSGi for each xxx.bndrun file
in a project.
=> gradle: Add testrun.* task rule for Bnd Workspace build

biz.aQute.junit/src/aQute/junit/JunitXmlReport.java
Iterating over the entrySet resulted in a concurrent modification
exception. This change should avoid this.
=> junit: Fix concurrent modification exception possibility

docs/_instructions/connection-settings.md
Just a small typo I stumbled upon: </trus> should be </trust>
=> docs: Fix a small typo in code example for connection-settings.xml file

biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java, cnf/ext/osgi-snapshots.mvn, cnf/ext/repositories.bnd
Promise 1.1.1 runs callbacks on current thread when the promise is
already resolved. This avoids thread context switches.
=> Use promise 1.1.1 from OSGi

biz.aQute.bndlib/src/aQute/bnd/osgi/Annotation.java
Otherwise the code used the bndlib class loader to attempt to load the
annotation class again which can fail if the annotation class is
part of a plugin and not bndlib.
=> annotation: Fix converter hook to use annotation class

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
Fall back to the system bundle if a plugin fails to load a class. 
Otherwise the bndlib that hosts Processor must import the JRE.
=> [plugins] Plugin class space

aQute.libg/src/aQute/lib/io/ByteBufferDataInput.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
And some other general fixes and performance tweaks.
=> clazz: Avoid byte[] allocation for crawling code attributes

aQute.libg/src/aQute/lib/xmldtoparser/DomDTOParser.java
This was introduced in 4.1 so we do not need to
be backward compatible.
=> [xmldtoparser] Removed dependency

aQute.libg/src/aQute/lib/utf8properties/PropertiesParser.java, aQute.libg/test/aQute/lib/utf8properties/UTF8PropertiesTest.java, biz.aQute.bndlib.tests/src/test/PropertiesTest.java
- Fixed escaping quotes in quoted strings 
the properties parser in test mode assumed
that an unescaped quote always signals the end
of the quoted string. However, if it is preceded
by an odd number of backslashes in the output
then it will be escaped by the OSGi header parser
- Moved test to JUnit 4
=> [properties parser] Quote escapes

aQute.libg/src/aQute/lib/io/FileTree.java, biz.aQute.bnd/src/aQute/bnd/main/ResolveCommand.java, biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bnd/test/aQute/bnd/main/testrules/WatchedTemporaryFolder.java, maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java, maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java, maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java, maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/LocalIndexerMojo.java, maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java, maven/bnd-resolver-maven-plugin/src/main/java/aQute/bnd/maven/resolver/plugin/ResolverMojo.java, maven/bnd-shared-maven-lib/src/main/java/aQute/bnd/maven/lib/configuration/FileTree.java, maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
The `bnd runtests` command was broken for the OSGi CT execution. runtests must not require or search for a "real" workspace folder. It must either use the specified folder or the current working directory for the workspace. 
This PR also includes a number of other fixes/improvements made concurrently with fixing runtests behavior.
=> Bnd runtests fix

biz.aQute.junit/src/aQute/junit/Activator.java
In Groovy it is possible (and stupid) to name
methods with a quoted string. 
Don't handle the case yet when the method name contains a comma ... Not sure how to handle that since the name 
comes from Eclipse JUnit so we can't escape as I recall.
=> [junit] Groovy test case method names

biz.aQute.bndlib.tests/src/test/component/WildcardComponents.java, biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java, biz.aQute.bndlib/src/aQute/bnd/make/component/ServiceComponent.java
PDE projects tend to have a Service-Component
header like "OSGI-INF/*.xml", which is valid
SCR header. However, this clashes with the bnd
generation since it will append the xml file paths
to the end of this header. SCR will then see 
components twice. Once matched by the wildcard
and once literal.
Unfortunately, many PDE projects are in progress
to moving the annotations based components so they 
have a hybrid situation. This makes it impossible 
for them to remove the Service-Component wildcard 
since then no longer the hardcoded files are found.
Rock and a hard place.
So this patch will match the calculated paths
in the old ServiceComponent class  and the more
modern DSAnnotations class against any wildcard
patterns. The static method that does this is located
in DSAnnotations.
Sucks …
=> [component] Service-Component & wildcards

biz.aQute.junit/src/aQute/junit/Activator.java
This patch makes the tester handle the case that the
host of a fragment is lazy. The code did not take
STARTING hosts as active so it though the fragment host
was not alive yet.
There can be no confusion with a hanging activator
since the launcher would have reported that as an error.
=> [tester] Fragments & Lazy

biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java, biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiRepository.java, biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java
The refresh() method in OSGiRepository invoked getIndex with refresh set to false. This meant that the index was not updated even though it was changed. The current test tests whether or not refreshing the repository actually updates the index by checking their last modified times. Furthermore, the added tests checks whether refreshing notifies RepositoryListenerPlugin instances.
=> Issue #1930: Set refresh to true when refreshing

biz.aQute.bndlib.tests/src/test/fragments/FragmentTest.java, biz.aQute.bndlib.tests/src/test/fragments/imports/ImportFramework.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/version/VersionRange.java, docs/_heads/fragment_host.md
A fragment is loaded in the same class loader
as the host. It is therefore wrong to import
any package that is defined in the host of
a fragment.
This change will subtract all host packages from the references.
=> [fragments] No Import of host

biz.aQute.bndlib.tests/src/test/ClazzTest.java, biz.aQute.bndlib.tests/src/test/typeuse/A.java, biz.aQute.bndlib.tests/src/test/typeuse/B.java, biz.aQute.bndlib.tests/src/test/typeuse/C.java, biz.aQute.bndlib.tests/src/test/typeuse/D.java, biz.aQute.bndlib.tests/src/test/typeuse/E.java, biz.aQute.bndlib.tests/src/test/typeuse/F.java, biz.aQute.bndlib.tests/src/test/typeuse/G.java, biz.aQute.bndlib.tests/src/test/typeuse/H.java, biz.aQute.bndlib.tests/src/test/typeuse/I.java, biz.aQute.bndlib.tests/src/test/typeuse/OuterE.java, biz.aQute.bndlib.tests/src/test/typeuse/OuterF.java, biz.aQute.bndlib.tests/src/test/typeuse/TypePath.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Annotation.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ClassDataCollector.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ClassDataCollectorRecorder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ClassDataCollectors.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
We were only handling some usage cases (target_types 0x00-0x17). We now
support all scenarios. We use a new visitor method to supply type use
information before calling the visitor method with the annotation.
=> Improve TYPE_USE support of annotations

biz.aQute.bnd/src/aQute/bnd/main/RepoCommand.java, biz.aQute.bnd/src/aQute/bnd/main/XRefCommand.java, biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Descriptors.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/packageinfo, biz.aQute.bndlib/src/aQute/bnd/service/progress/ProgressToOutput.java, biz.aQute.bndlib/src/aQute/bnd/service/progress/packageinfo
bnd
- dependencies - show all used dependencies in the workspace
- collect - extract a set of resources from a set of jars and copy to an output jar
- classtoresource - Convert class names to resource path
- packagetoresource - Convert package to resource path
repo
- repo copy
- repo sync
- repo index
xref
A lot of filtering options to analyze large setups
=> [command] Additional commands for xref and repo

biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java
We should not handle collections or ServiceReference<Logger> or
ComponentServiceObjects<Logger>, etc. Only simple fields, parameters.
=> ds: fix Logger support

biz.aQute.bndlib.tests/src/test/annotationheaders/StdAnnotationHeadersTest.java, biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java, biz.aQute.bndlib.tests/src/test/component/PermissionGeneratorTest.java, biz.aQute.bndlib.tests/src/test/component/ds14/AnComponentDSFourteen.java, biz.aQute.bndlib.tests/src/test/component/ds14/MyInterface.java, biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java, biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
This change checks if the `Component` annotation class in the analyzer
is itself annotated with `RequireServiceComponentRuntime`. If it is, then
that annotation will handle generating the requirement for the DS
extender and the DS annotation processing code will not emit the
extender requirement.
=> Avoid duplicate DS extender for DS version 1.4+

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientTest.java, biz.aQute.bndlib.tests/test/test/PluginTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/junit/JUnitFramework.java, biz.aQute.bndlib/src/aQute/bnd/make/MakeCopy.java, biz.aQute.bndlib/src/aQute/bnd/osgi/ActivelyClosingClassLoader.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Resource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/URLResource.java
This allows -pluginpath URLs and -includeresource URLs to be handled by
HttpClient which utilizes connection settings to handle authentication
and proxies.
=> bndlib: Replace URLConnection usage with Resource.fromURL w/ HttpClient

biz.aQute.remote/src/aQute/remote/agent/RedirectOutput.java
In java 11 OutputStream has its own public nullOutputStream(),
we cannot reduce the visibility of the inherited method
https://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/java.base/share/classes/java/io/OutputStream.java
Signed-off-by: stbischof stbischof@bipolis.org
=> java11 OutputStream has its own public nullOutputStream()

aQute.libg/src/aQute/lib/converter/Converter.java, aQute.libg/src/aQute/lib/getopt/CommandLine.java, aQute.libg/src/aQute/lib/xmldtoparser/DomDTOParser.java, aQute.libg/src/aQute/libg/sed/ReplacerAdapter.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java, biz.aQute.repository/src/aQute/p2/provider/XML.java
Change to call invoke differently for static or non-static members
rather than bind which creates objects we can easily avoid.
=> methodhandles: Avoid object creation for non-static invocation

biz.aQute.bndlib.tests/test/test/ClazzTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
This method uses the InnerClasses attribute of the class file to
determine if the receiver is an inner class.
Fixes https://github.com/bndtools/bnd/issues/2714
=> clazz: Add isInnerClass method

aQute.libg/src/aQute/libg/slf4j/GradleLogging.java
Use local var to hold class name for Class.forName. This avoids
ldc/invokestatic bytecode sequence which Bnd will find and generate an
import for the package.
=> Avoid import of gradle logging package

biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bndlib/bnd.bnd, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java, biz.aQute.bndlib/src/aQute/bnd/home/Home.java, biz.aQute.bndlib/src/aQute/bnd/home/package-info.java, biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java, biz.aQute.bndlib/src/aQute/bnd/maven/MavenCommand.java, biz.aQute.remote/src/aQute/remote/main/Main.java
**Status**
**Description**
in some cases it might be necessary to relocate ~/.bnd by setting a env. property.
e.g. gitlab-ci could not cache directories in~/
https://gitlab.com/gitlab-org/gitlab-runner/issues/327
in most cases like mvn and gradle they relocate the dir.
```
export GRADLE_USER_HOME=`pwd`/.gradle
MAVEN_OPTS: "-Dmaven.repo.local=.m2"
```
bnd should also be able to to relocate the ~/.bnd folder.
**Checklist**
* none
* none
**Questions**
none
=> [libg] relocate Bnd home (~/.bnd)

biz.aQute.bnd.gradle/bnd.bnd, biz.aQute.bnd.gradle/build.gradle, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBaselineTask.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBndPlugin.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBundlePlugin.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestExportTask.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestIndexTask.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestResolveTask.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestTestOSGiTask.groovy, biz.aQute.bnd.gradle/testresources/workspaceplugin1/settings.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin2/settings.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin3/settings.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin4/build.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin5/settings.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin6/settings.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin7/settings.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin8/workspace/build.gradle, biz.aQute.bnd.gradle/testresources/workspaceplugin9/settings.gradle, biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bnd/test/aQute/bnd/main/TestBndMain.java, biz.aQute.bnd/testdata/workspace/p3/bnd.bnd, biz.aQute.bnd/testdata/workspace/p3/src/somepackage/SomeClass.java, biz.aQute.bnd/testdata/workspace/p4/src/req/RequireAnnotationOne.java, cnf/ext/central.mvn, settings.gradle
Using the new maven pom dependencies support, the gradle plugin jar
will no longer embed its dependencies and will rely upon gradle
downloading the dependencies from a repository and making them available
on the plugin's classpath.
=> gradle: Cease embedding dependencies in plugin jar

.travis.yml, biz.aQute.bndlib/src/aQute/bnd/header/Attrs.java, maven/bnd-baseline-maven-plugin/pom.xml, maven/bnd-export-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/pom.xml, maven/bnd-maven-plugin/pom.xml, maven/bnd-resolver-maven-plugin/pom.xml, maven/bnd-testing-maven-plugin/pom.xml
We also remove debug output for the maven-invoker-plugin execution to vastly shorten the build output.
=> Switch to Azul JDK 10 binary to avoid current issues with AdoptOpenJDK JDK 10 releases

biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
If the Jar object has a module-info.class, read the class to obtain the
module name and module version information. If the class does not have
a module-info.class, fall back to the Automatic-Module-Name header, if
present, for the module name.
Closes https://github.com/bndtools/bnd/pull/2747
=> jar: Add methods to access JPMS module name and version

biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
These task allow other tasks to depend upon various tasks (jar, release,
check, clean) of the transitive dependencies.
=> gradle: Add additional workspace model tasks

biz.aQute.bnd.diagnostics.gogo/bnd.bnd, biz.aQute.bnd.remote.junit/bnd.bnd, cnf/bnd.bnd, cnf/ext/repositories.bnd
This replaces our bespoke update site on bintray.
=> build: Update repos to use Eclipse Luna 4.4.2 site

biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
When testing a field type to determine if the field type is a collection
subclass, treat inability to load the field type as the type is not a
collection subclass. Then the field type will be treated as a scalar
instead of a collection.
=> ds: Better handle inability to locate class for field references

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, docs/_heads/import_package.md
Add @bundlesymbolicname and @bundleversion properties. For imported packages, @ properties are defined which reference the bundle symbolic name and bundle version of the exporter from the
classpath.
=> Add support to use bundle-symbolic-name and bundle-version attributes for Import-Package

biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/generator/ReportGeneratorBuilder.java, biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/helpers/HeadersHelper.java, biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/manifest/dto/OSGiHeadersDTO.java, biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/entries/bndproject/BndProjectContentsPlugin.java, biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/entries/bndworkspace/BndWorkspaceContentsPlugin.java, biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/entries/bundle/ManifestPlugin.java, biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/helpers/HeadersHelperTest.java, biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/bundle/ManifestPluginTest.java, biz.aQute.bnd/src/aQute/bnd/main/ExportReportCommand.java
Some enhancements for the reporter project:
* Add methods to setup a generator for a specific use case: The generator is mostly used to extract data from a bundle, a project or a workspace/aggregator project. A method is added to the builder to customize the generator for each of this use case. This prevents to duplicate code when used from maven, bnd CLI, gradle,...
* Replace reflection with a DTO in the manifest extractor
=> Reporter enhancements

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
By default, only jar and war packaging types are being processed. If you
want to run bnd for other packaging types, you can define the list of
packaging types bnd will be run for. All types will be treated like
'jar', only 'war' has a special codepath.
```
<configuration>
<packagingTypes>
<packagingType>jar</packagingType>
<packagingType>war</packagingType>
<packagingType>xxx</packagingType>
</packagingTypes>
</configuration>
```
Alternatively, you can use -Dbnd.packagingTypes=jar,war,xxx to specify
the types to use
=> Configurable packaging types (Fixes #2870)

biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
While the documentation states `-donotcopy` will be taken into account
when unrolling a JAR, this has not yet been implemented.
see https://github.com/bndtools/bnd/blob/master/docs/_instructions/includeresource.md
=> Actually use -donotcopy when unrolling jar

docs/_instructions/diffignore.md, docs/_instructions/pom.md
Fix Bundle-Developer to Bundle-Developers manifest header.
Fix warning on diffignore.md when processed by the jekyll.
Make -pom instruction more readable by introducing given parameters in a table view.
=> Fix docs manual for -pom instruction

bndtools.core/src/bndtools/wizards/bndfile/RunExportSelectionPage.java
This saves a click when using the UI to export a launcher.
=> Export: Select the first option on load

bndtools.core/src/org/bndtools/core/ui/wizards/shared/TemplateSelectionWizardPage.java
Because TemplateLoader.findTemplates() returns a collection of Promises, we don't want to release our service reference until after those Promises have finished, as they may still be using internal service state.
This fixes an issue where the list of available templates is sometimes not populated when trying to create a new project.
=> TemplateLoader: Race condition when loading templates

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientTest.java, biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java, biz.aQute.bndlib/src/aQute/bnd/http/URLCache.java, biz.aQute.bndlib/src/aQute/bnd/http/package-info.java
Clears the cache now when a cached call is made and we get
a 404.
Fixes #2098
=> [httpclient] HttpClient's urlcache not updated on 404 #2098

demo/x.bndrun
The bndrun file did not successfully launch since the gogo bundles
required a later version of felix than specified.
=> demo: Use felix framework version supporting the gogo version

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPluginConvention.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndProperties.groovy, bndtools.builder/src/org/bndtools/builder/DeltaWrapper.java
We only compute the ignore set once per delta visitor run in the
Bndtools builder.
Also, we support -builderignore as a merged property.
=> builderignore: Avoid repetitive ignore values computation

biz.aQute.launchpad/src/aQute/launchpad/BundleBuilder.java, biz.aQute.launchpad/src/aQute/launchpad/LauchpadBuilder.java, biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java, biz.aQute.launchpad/test/aQute/launchpad/BeforeAfterTest.java, biz.aQute.launchpad/test/aQute/launchpad/HelloTest.java, biz.aQute.launchpad/test/aQute/launchpad/RuleTest.java, bndtools.builder/bnd.bnd, bndtools.builder/src/org/bndtools/builder/classpath/BndContainer.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerRuntimeClasspathEntryResolver.java
The computes the runtime classpath from the classpath entries in the
current BndContainer. The goal here is to provide greater fidelity to
the command line gradle build by removing transitive project
dependencies.
This is a complete replacement for #2971. @pkriens Please try this out and see if it works for you. We may find we need some more tweaks.
=> Add a RuntimeClasspathEntryResolver to Bndtools

biz.aQute.bnd.runtime/test/aQute/bnd/runtime/snapshot/SnapshotTest.java, biz.aQute.bnd.runtime/test/biz/aQute/bnd/diagnostics/gogo/DSDiagTest.java, biz.aQute.bnd.runtime/test/biz/aQute/bnd/diagnostics/gogo/DiagnosticsTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/About.java, biz.aQute.launchpad/src/aQute/launchpad/BundleBuilder.java, biz.aQute.launchpad/src/aQute/launchpad/BundleSpecBuilder.java, biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java, biz.aQute.launchpad/src/aQute/launchpad/LaunchpadBuilder.java, biz.aQute.launchpad/test/aQute/launchpad/BeforeAfterTest.java, biz.aQute.launchpad/test/aQute/launchpad/HelloTest.java, biz.aQute.launchpad/test/aQute/launchpad/LaunchpadTest.java, biz.aQute.launchpad/test/aQute/launchpad/RuleTest.java
Started trying to work with Peter Kriens' newly-renamed "Launchpad" (see #2957). Wondered why the compiler couldn't find LaunchpadBuilder even after I added it to the build path and imported it.
Turns out it was misspelled as "Lauchpad". The joys of automated refactoring means that this typo propagated through the whole repository while still compiling. This patch fixes the spelling.
I also had the thought to search the workspace for other similar misspellings of "launch", which is an easy enough mistake to make. Found one in a message in biz.aQute.bndlib/src/aQute/bnd/osgi/About.java which I have also fixed in this patch.
=> Fix misspellings of "Launch"

bndtools.builder/src/org/bndtools/builder/classpath/BndContainer.java
When adding a project's output folder to the runtime class path, use
the project as the source attatchement path for the output folder.
=> bndcontainer: Use project as source path for runtime class path

aQute.libg/src/aQute/lib/aspects/Aspects.java, aQute.libg/src/aQute/lib/consoleapp/AbstractConsoleApp.java, aQute.libg/src/aQute/lib/exceptions/Exceptions.java, aQute.libg/src/aQute/lib/link/Link.java, aQute.libg/src/aQute/libg/reporter/ReporterAdapter.java, aQute.libg/test/aQute/lib/exceptions/ExceptionsTest.java, biz.aQute.bnd.runtime/src/aQute/bnd/runtime/gogo/Activator.java, biz.aQute.bnd/src/aQute/bnd/main/Shell.java, biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.junit/src/aQute/junit/Activator.java, biz.aQute.remote/src/aQute/remote/util/Link.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java, biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2IndexerTest.java, bndtools.core/src/bndtools/editor/contents/GeneralInfoPart.java, bndtools.core/src/bndtools/editor/pkgpatterns/PkgPatternsProposalProvider.java, bndtools.core/src/bndtools/editor/project/RepositorySelectionPart.java, bndtools.core/src/bndtools/model/repo/RepositoryEntry.java, bndtools.core/src/bndtools/views/repository/RepositoriesView.java, bndtools.core/src/bndtools/wizards/bndfile/EmptyBndFileWizard.java, bndtools.core/src/bndtools/wizards/bndfile/ExecutableJarExportWizard.java, bndtools.core/src/bndtools/wizards/workspace/WorkspaceSetupWizard.java, bndtools.core/src/org/bndtools/core/resolve/ui/ResolutionResultsWizardPage.java, bndtools.core/src/org/bndtools/core/ui/wizards/jpm/AddJpmDependenciesWizard.java, bndtools.core/src/org/bndtools/core/ui/wizards/jpm/JpmDependencyWizardPage.java, bndtools.core/src/org/bndtools/core/ui/wizards/shared/TemplateSelectionWizardPage.java
This method will provide consistent unrolling of exception causes such as InvocationTargetException.
There many places where InvocationTargetException was unrolled and many of the places had bugs which could result in a null exception value result leading to NPEs.
=> Exceptions: Add and use unrollCause method

maven/bnd-indexer-maven-plugin/README.md, maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/LocalIndexerMojo.java
The maven local-index goal allows to set a baseFile that is used to
relativize the found file locations URLs.
If the baseFile property is missing the directory of the output XML file
is used.
There is currently no option (using the Maven indexer plugin) to disable
the relativize step -- which is supported by the used SimpleIndexer
implementation.
This change allows to use a special baseFile property to disable the
relativize.
This way it is possible to create indices that are using e.g. abolute
paths to the local JAR files.
To create nicer file URLs the canonical representation is used
(`foo/../bar` can be replaced by `bar` without changing the location
itself).
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>
=> index - maven plugin: allow local indices without relativize

biz.aQute.bndlib/src/aQute/bnd/build/ProjectTracker.java
The project directory may still exist but the bnd.bnd file may have
been removed.
Fixes https://github.com/bndtools/bnd/issues/3004
=> project: Ensure tracked project is still valid

biz.aQute.launchpad/src/aQute/launchpad/BundleSpecBuilder.java, biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java, biz.aQute.launchpad/src/aQute/launchpad/LaunchpadBuilder.java, biz.aQute.launchpad/test/aQute/launchpad/LaunchpadTest.java
Further fix for #2957. Some literals, comments and variables were missed in the original rename.
=> [launchpad] Rename literals and comments.

biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java, biz.aQute.launchpad/src/aQute/launchpad/Parameters.java, biz.aQute.launchpad/test/aQute/launchpad/ParametersTest.java
Included OSGiHeaders but this included too many
dependencies and these were not even properly 
conditionally included.
Created a simple Parameters class that assumes the
header is correct and does not try to analyze 
what might be wrong.
=> [launchpad] Launchpad imported too much

aQute.libg/src/aQute/libg/glob/AntGlob.java, aQute.libg/src/aQute/libg/sed/ReplacerAdapter.java, aQute.libg/src/aQute/libg/uri/URIUtil.java, biz.aQute.bnd/src/aQute/bnd/main/RemoteCommand.java, biz.aQute.bnd/src/aQute/bnd/main/RepoCommand.java, biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib.tests/test/test/NativeHeader.java, biz.aQute.bndlib.tests/test/test/VerifierTest.java, biz.aQute.bndlib/src/aQute/bnd/metatype/ADDef.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java, bndtools.jareditor/src/bndtools/jareditor/internal/Printer.java
The Verifier previously ignored the manifest in the Jar which may hold necessary information, such as Bundle-ClassPath, for proper verification.
=> Fix Verifier to properly verify Jars

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
Since module-info classes are not used at runtime by OSGi, we can safely
exclude them from the EE calculation for a bundle.
Fixes https://github.com/bndtools/bnd/issues/3010
=> analyzer: Exclude module-info.class from EE calculation

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientProxyTest.java, biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java, biz.aQute.repository/src/aQute/bnd/deployer/repository/CachingUriResourceHandle.java
When we get a SocketException, we convert to a 520 http response code.
This allows the retry support for 5xx response codes to retry.
=> httpclient: Support retrying SocketException: Connection reset

aQute.libg/src/aQute/lib/io/IO.java, aQute.libg/src/aQute/lib/io/packageinfo, biz.aQute.launchpad/src/aQute/launchpad/BundleBuilder.java, biz.aQute.launchpad/src/aQute/launchpad/BundleSpecBuilder.java, biz.aQute.launchpad/test/aQute/launchpad/BundleBuilderTest.java
Instead of throwing an IllegalArgumentException if you try to set the BSN twice, this PR changes it so that the second set will simply override the first. This fixes #3019.
Also added some sanity checking using aQute.bnd.osgi.Verifier to make sure that you can't accidentally set an invalid BSN.
=> [launchpad] Fix sanity checking for bundleSymbolicName()

biz.aQute.bndlib/src/aQute/bnd/service/specifications/RunSpecification.java, biz.aQute.launchpad/src/aQute/launchpad/LaunchpadBuilder.java, biz.aQute.launchpad/test/aQute/launchpad/LaunchpadBuilderTest.java
Changes constructor to ensure that it deep clones projectTestSetup, to avoid making accidental changes to the master copy.
Defensive guarding of projectTestSetup to make it harder (though not impossible) for code to manipulate it accidentally.
Also ensures that LaunchpadBuilder.set() updates the instance runspec and not the static one.
Fixes #3026.
=> launchpad: Deep clone runspec in LaunchpadBuilder()

bndtools.builder/src/org/bndtools/builder/classpath/BndContainer.java
Otherwise, when debugging you can end up viewing un-editable source from
a project's jar rather than the editable source of the project.
=> bndcontainer: Always include project source for runtime classpath

azure-pipelines.yml
Add Azure Pipelines task to publish the main job (OpenJDK8) test results. This will allow us more insight when a test case fails for an Azure build.
=> azure: Publish test results for main job

cnf/ext/repositories.bnd
See https://github.com/osgi/osgi.enroute/pull/98
=> build: Avoid Sonatype OSGi group and use the repositories instead

biz.aQute.bnd.gradle/bnd.bnd, biz.aQute.bnd.runtime/bnd.bnd, biz.aQute.bnd/bnd.bnd, biz.aQute.bndlib/bnd.bnd, biz.aQute.junit/bnd.bnd, biz.aQute.launchpad/bnd.bnd, biz.aQute.repository/bnd.bnd, biz.aQute.resolve/bnd.bnd, biz.aQute.tester/bnd.bnd
Some projects have many -buildpath entries with maven-scope=provided
attributes. For those projects, we set the instruction
-maven-scope=provided so the default scope for dependencies in generated
POMs is provided rather than the default of compile. This means that
some -buildpath entries will then need to specify maven-scope=compile
to make sure they are not provided.
=> Use -maven-scope instruction to simplify some -buildpaths

biz.aQute.bnd.gradle/bnd.bnd, biz.aQute.bnd.gradle/build.gradle, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestTestOSGiTask.groovy, biz.aQute.bnd.gradle/testresources/testosgitask1/build.gradle, biz.aQute.bnd.gradle/testresources/testosgitask2/build.gradle, biz.aQute.bnd.gradle/testresources/testosgitask3/build.gradle, biz.aQute.bnd.gradle/testresources/testosgitask4/build.gradle
This is necessary for next to use the associated version of
biz.aQute.junit for the version of bnd being built.
=> gradle: Use bnd version of build for biz.aQute.junit version in test

biz.aQute.bndlib.tests/test/test/AnalyzerTest.java, biz.aQute.bndlib.tests/test/test/ProjectTest.java, biz.aQute.bndlib/src/aQute/bnd/help/Syntax.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, docs/_instructions/require_bnd.md
We now use a Version object in the map to the filter to get proper
version comparison semantics. We also fix the test methods and docs to
properly use filter expressions for `-require-bnd`.
=>  analyzer: Fix -require-bnd instruction

biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java, biz.aQute.repository/src/aQute/p2/provider/ArtifactRepository.java, biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2IndexerTest.java
The check and retry logic is moved into a then so we only retry for the
error identified by the check rather than any other upstream error.
=> p2: Cleanup promise callbacks for retry

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java, biz.aQute.bndlib/src/aQute/bnd/http/HttpRequest.java, biz.aQute.bndlib/src/aQute/bnd/http/RetryException.java, biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java, biz.aQute.repository/src/aQute/maven/provider/MavenRemoteRepository.java, biz.aQute.repository/test/aQute/bnd/deployer/http/HttpRedirectionTest.java
The retry logic is hoisted up around the send method to allow retries
when file caching fails when reading from the connection. This happens
sometimes on Eclipse p2 repos.
We also update the sha/md5 checks in p2 and maven repos.
=> httpclient: Rewrite retry logic using Promises

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
If we use recoverWith on the delayed promise while using the inline
executor we end up moving work onto the scheduled executors thread.
Since we have only a limited number of schedule executor threads, we
want to avoid long term use. So when using the inline executor, we wait
for the delay to expire on the current thread. This should keep all work
on the current thread when using the inline executor.
=> http: Delay on current thread when using inline executor

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientTest.java, biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java, biz.aQute.bndlib/src/aQute/bnd/http/HttpRequest.java, biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java, biz.aQute.repository/test/aQute/bnd/repository/p2/provider/P2IndexerTest.java
We now set the TimeoutException stack trace to that of the "stuck"
request thread for some better diagnostic information. We also attempt
to close the input stream and delete the file of the TaggedData if there
is one for the request thread.
We also set the temporarily set the thread name to the URL of the
request. This can be quite useful in debugging and thread dumps.
=> httpclient: Refactor for better handling of TimeoutException

cnf/ext/repositories.bnd
The Eclipse download site is too unreliable for our use. Even with
significant robustness improvements to HttpClient and P2Repository,
the reliability of download.eclipse.org is bad enough to still fail
our CI builds on a regular basis.
I took the content from the 3 p2 repos we used and merged them into a
single indexed repo on bintray. The index will reduce the number of
files which need to be downloaded which may improve CI build times.
=> build: Switch away from Eclipse p2 repos to our own bintray copy

.gitignore, .travis.yml, azure-pipelines.yml, biz.aQute.bnd.gradle/build.gradle, build.gradle, maven/bnd-baseline-maven-plugin/pom.xml, maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-export-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/helloworld-for-indexer-testing/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/include-jar/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/index-folder-includes-excludes/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/index-folder/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-bnd/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-deploy-no-dist-mgmt/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-deploy/pom.xml, maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/test-snapshot/pom.xml, maven/bnd-maven-plugin/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-api-bundle/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/pom.xml, maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/test-inheriting-api-bundle/pom.xml, maven/bnd-resolver-maven-plugin/pom.xml, maven/bnd-run-maven-plugin/pom.xml, maven/bnd-run-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/bnd-testing-maven-plugin/pom.xml, maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/pom.xml, maven/pom.xml
Add CI build job for JDK 12. We keep the JDK 11 build job since JDK 11 is an LTS release.
=> Build jdk12

aQute.libg/src/aQute/lib/io/IO.java
A Windows file system oddity means that when a symlink is created, the
file system has to know if the target is a directory. So when we make
a directory via a symlink, we must recreate the symlink so that Windows
knows that the symlink points to a directory and not a file.
See dwFlags parameter:
https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-createsymboliclinkw#parameters
=> Handle symlinks to non-existent target folders on Windows

aQute.libg/src/aQute/libg/reporter/slf4j/Slf4jReporter.java, biz.aQute.bnd/src/aQute/bnd/ant/BaseTask.java, biz.aQute.bndlib/src/aQute/bnd/build/LoggingProgressPlugin.java, biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java, biz.aQute.bndlib/src/aQute/bnd/maven/MavenDeploy.java, biz.aQute.bndlib/src/aQute/bnd/maven/MavenDeployCmd.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.bndlib/src/aQute/bnd/url/DefaultURLConnectionHandler.java, biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java, biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java, biz.aQute.repository/src/aQute/maven/provider/MavenRemoteRepository.java
Primarily this is "Downloading" output. Gradle moved its downloading
messages from LIFECYCLE (a special, output-by-default log level of
Gradle) to INFO. So we do the same to limit chattiness of the build
output. Running gradle with --info will display these download messages.
When not using gradle, this change has no effect.
=> gradle: Make Bnd less chatty on build output

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/Tool.java, biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java, biz.aQute.repository/testresources/src/X.java
When the user supplies the sources option to -maven-releasse, use these
sources for the generated javadoc instead of any sources which may be in
the jar.
=> maven repo: Use sources when specified for javadoc generation

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/Tool.java, biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java, cnf/build.bnd
This avoids work when the sources path is specified in -maven-release.
=> maven repo: Avoid extracting source from jar until needed

maven/bnd-baseline-maven-plugin/pom.xml, maven/bnd-export-maven-plugin/pom.xml, maven/bnd-indexer-maven-plugin/pom.xml, maven/bnd-maven-plugin/pom.xml, maven/bnd-resolver-maven-plugin/pom.xml, maven/bnd-run-maven-plugin/pom.xml, maven/bnd-testing-maven-plugin/pom.xml, maven/build.gradle, maven/pom.xml
Found this nugget <https://blogs.itemis.com/en/in-a-nutshell-removing-artifact-messages-from-maven-log-output> which explained how to cleanup the build output! Now the CI build output is significantly shorter.
=> Remove "Downloading" messages from maven build

biz.aQute.bndall.tests/keep_notrace.bndrun, biz.aQute.bndall.tests/test/biz/aQute/launcher/LauncherTest.java, biz.aQute.launcher/src/aQute/launcher/Launcher.java, biz.aQute.launcher/src/aQute/launcher/constants/LauncherConstants.java, biz.aQute.launcher/src/aQute/launcher/pre/EmbeddedLauncher.java
I may have gone a bit far with the verbose stuff, but It really helped during developement. The new run Method in the Embedded Launcher allows the equinox native executables to trigger the bnd launcher.
- the different ways of intializing that have been spread over the
Constructor and the main method have been moved to init(), run() and
runWithoutInit()
- adds a run method to the EmbeddedLauncher
- the argument -v or -verbose triggers debug logging for the
EmbeddedLauncher and sets the Launcher into trace mode
=> 3109 modify launcher

biz.aQute.launchpad/src/aQute/launchpad/junit/LaunchpadRule.java, biz.aQute.launchpad/test/aQute/launchpad/JunitRuleTest.java
If you have a `LaunchpadRule` attached to your JUnit 4 test class, and you happen to not call `getLaunchpad()` in one of the tests in that class, then you'll get a `NullPointerException` when that test ends.
This PR fixes that problem.
=> [launchpad] LaunchpadRule to gracefully handle non-creation of Launchpad

biz.aQute.bndlib/src/aQute/bnd/service/specifications/BuilderSpecification.java, biz.aQute.launchpad/src/aQute/launchpad/BundleSpecBuilder.java, biz.aQute.launchpad/test/aQute/launchpad/BundleBuilderTest.java
Original implementation used the BSN as the bundle key ("location") when installing the bundle. This means you can't install two bundles in the same Launchpad with the same BSN, even if they have different versions, which means you can't use Launchpad to test the full gamut of OSGi situations.
This patch changes `BundleSpecBuilder` so that it uses BSN + bundle version as the bundle key rather than just the BSN, which allows the Launchpad to install multiple versions of the same bundle with the same BSN.
=> [launchpad] BundleSpecBuilder to allow multiple versions of a bundle

biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java, biz.aQute.launchpad/src/aQute/launchpad/BundleSpecBuilder.java
This allows additional maven dependencies to be specified in the bnd
file to supplement any dependencies computed from the -buildpath.
=>  pom: Use merged properties for -maven-dependencies 

biz.aQute.bnd/src/aQute/bnd/main/RemoteCommand.java, biz.aQute.bnd/test/aQute/bnd/main/DistroCommandTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/XMLResourceParser.java
- An OBR XML is now always added to the bistro jar
- The -x command allows the generation of an xml instead of a jar
=> [distro] Adds XML support

biz.aQute.bnd/bnd.bnd
We do not want bnd code to use code from reporter specific dependencies.
So we move those dependencies out of -buildpath. We use -classpath to
build the jar and -testpath to support test case execution.
=> bnd: Remove reporter dependencies from bnd buildpath

biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java, biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
The DSAnnotations analyzer plugin is a singleton in bnd. However, the min (and later max versions) were kept as instance variables. If the build is ran in parallel then I suspect this caused problems. 
Moved the min/max version to a Version Settings object that is a local parameter and therefore not prone to parallel builds.
bnd is not designed to be used in parallel builds but I suspect when it happens we have a lock. Need to look how this works later.
=> [component] Random DS schema version generation

biz.aQute.bnd/src/aQute/bnd/main/CommunicationCommands.java, biz.aQute.bnd/src/aQute/bnd/main/GraphCommand.java, biz.aQute.bnd/src/aQute/bnd/main/bnd.java, biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/SettingsParserTest.java, biz.aQute.bndlib.comm.tests/testresources/ws/cnf/invalid.xml, biz.aQute.bndlib.comm.tests/testresources/ws/cnf/valid.xml, biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java, biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java
Parsing an invalid XML file caused an NPE
This patch ensures there is always an Http Client
even if the parse fails. The error is now better
reported on the workspace.
=> [httpclient] Report failing to parse settings

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java, biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java, biz.aQute.launchpad/src/aQute/launchpad/LaunchpadBuilder.java, biz.aQute.launchpad/test/aQute/launchpad/LaunchpadTest.java
Debug mode in launchpad builder now shows filter and all extra packages
Increase time out for stress test in launchpad
Fixes #3226
=> [launchpad]

bndtools.builder/src/org/bndtools/builder/WorkingSetTracker.java, docs/_instructions/workingset.md
Some people want to maintain private working sets but
bnd would remove a project from a working set if
the -workingset was used in a project.
This change makes bnd ignore working sets that do
not follow the required naming pattern. Using such
a pattern for a workings therefore implies that the
user is on its own.
For example, a .Private working set will never be 
touched by bnd.
Fixes #3207
=> [workingsets] Ignore workings with non-java-id name

biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
ECJ can generate invalid signatures in SignatureAttributes on synthetic methods. See #3239. To avoid failing to process the class, we don't process SignatureAttributes on synthetic elements.
=> Don't process SignatureAttribute on synthetic elements in class files

biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/Scope.java
Maven allows custom scopes. However since bnd's maven support tries to validate a fixed set I'm proposing to add this non-standard one in order to at least have a bucket to put things in. This has no other effect beyond allowing the `bnd-*-maven-plugin`  `<scopes>` configuration to include, and search this custom scope.
=> [maven] custom scope for distros

biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java, biz.aQute.bndlib/src/aQute/bnd/metatype/MetatypeAnnotations.java, biz.aQute.bndlib/src/aQute/bnd/metatype/OCDReader.java
Since the plugin instance is a singleton, we must avoid instance
variables that mutate for each invocation.
See #3209
=> metatype: Avoid instance variable for parallelism

biz.aQute.bndlib/src/aQute/bnd/header/OSGiHeader.java
If a key is used N times in a header, the code to deduplicate the key
name used O(N^2) containsKey calls to find a deduplicated name. When
large headers are parsed, this can consume considerable time. One
scenario called containsKey 265M times! This fix uses a separate map to
hold the last used deduplicated key name so the next deduplicated key
name can be computed and confirmed available in a single containsKey
call.
=> header: Change duplicate key handling code to avoid O(N^2) containsKey calls

biz.aQute.launchpad/bnd.bnd, biz.aQute.launchpad/src/aQute/launchpad/LaunchpadBuilder.java, biz.aQute.launchpad/test/aQute/launchpad/LaunchpadBuilderTest.java
This is a simple patch to allow you to override the object returned by `LaunchpadBuilder.getMyClassLoader()`.
I had a use case where it was not sufficient for me to simply hide a package by excluding it from `-runsystempackages` - this makes the package invisible to all bundles except the system bundle. I needed a way to hide a class/package from the system bundle as well. This feature allows me to achieve this by interposing a custom excluding classloader between the framework and LaunchpadBuilder's own classloader.
=> [launchpad] Add ability to specify a root classloader

biz.aQute.bndlib.tests/test/test/InstructionTest.java, biz.aQute.bndlib/src/aQute/bnd/help/instructions/ResolutionInstructions.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, biz.aQute.resolve/src/biz/aQute/resolve/RunResolution.java, biz.aQute.resolve/test/biz/aQute/resolve/RunResolutionTest.java, docs/_chapters/300-launching.md, docs/_chapters/305-startlevels.md, docs/_instructions/runbundles.md, docs/_instructions/runstartlevel.md
- Changed the instruction from -runorder to -runstartlevel
- Order bundles now also with a start level attribute
- Support a begin and step for the auto numbering in resolve
- Added tests
- Provide documentation
=> [startlevel] Start level for resolve ordering support

biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/helpers/HeadersHelperTest.java, biz.aQute.bndlib.tests/test/test/ParseHeaderTest.java, biz.aQute.bndlib/src/aQute/bnd/header/Attrs.java
The previous code used a regex which would not match a plain List type.
So the key ended in `:List` and the value type was String. This fix
correctly handles plain List as the type `List<String>`.
Furthermore, we avoid regex matching when the key does not contain a `:`
which is the most common scenario. This can provide a small performance
boost.
Thanks to @seanbright for the test fixes in HeadersHelperTest!
=> attr: Fix handling of plain List and avoid regex if no type specified

biz.aQute.bndlib/src/aQute/bnd/header/Attrs.java
Since directives end in `:`, we look for this to avoid regex processing
on directives.
=> attr: Avoid regex processing for directives

biz.aQute.bndlib.tests/test/test/ParseHeaderTest.java, biz.aQute.bndlib/src/aQute/bnd/header/Attrs.java
Optimize for the regular case with no embedded whitespace. We can
now handle without the need for regex matching. Regex matching is only
needed when a typed List is used with spacing around the angle brackets.
Manifests generated by Bnd will not generate with spaces, so parsing Bnd
generated manifests will never require regex matching for attribute
parsing.
The `ResolveTest.testResolveWithLargeDistro` method will now execute
without needing to do any regex matching for header parsing of
attributes.
=> attr: A further improvement to type parsing which mostly avoids regex

biz.aQute.bnd.annotation/src/aQute/bnd/annotation/baseline/BaselineIgnore.java, biz.aQute.bnd.annotation/src/aQute/bnd/annotation/baseline/package-info.java, biz.aQute.bndlib.tests/test/test/api/C.java, biz.aQute.bndlib.tests/test/test/api/Interf.java, biz.aQute.bndlib.tests/test/test/api/package-info.java, biz.aQute.bndlib.tests/test/test/diff/DiffTest.java, biz.aQute.bndlib/src/aQute/bnd/differ/Baseline.java
When this annotation is applied to a baselined element, the baseliner
will ignore the annotated element when baselining against a baseline
package whose version is less than the specified version.
This means the annotated element will not produce a baselining mismatch.
The correct baseline information about the element will be in the
baseline report, but the element will not cause baselining to fail.
When baselining against a baseline package whose version is greater
than or equal to the specified version, this annotation is ignored and the
annotated element will be included in the baselining.
=> baseline: Add BaselineIgnore annotation support

biz.aQute.junit/src/aQute/junit/plugin/ProjectTesterImpl.java, biz.aQute.tester/src/aQute/tester/plugin/ProjectTesterImpl.java
Update from pre JDK 1.5 pattern for constants.
=> [tester] Use static import rather than inheritance for constants

biz.aQute.bnd.runtime/bnd.bnd, biz.aQute.junit/bnd.bnd, biz.aQute.launcher/bnd.bnd, biz.aQute.launchpad.tests/bnd.bnd, biz.aQute.tester/bnd.bnd
We use latest to keep all projects in sync and control the OSGi core
version being used via repo curation in cnf/ext/central.mvn
=> build: Update references to OSGi core artifact in bnd files

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestHelper.groovy
Forgot this change in https://github.com/bndtools/bnd/pull/3216
=> gradle: Use parseMavenString method to parse maven version strings

.editorconfig
This will render the code in GitHub (and other editors/viewers which
support .editorconfig) to match the Eclipse settings we use.
https://editorconfig.org/
=> build: Add .editorconfig file to repo

aQute.libg/src/aQute/lib/date/DateUtil.java, biz.aQute.bndall.tests/test/biz/aQute/launcher/LauncherTest.java, biz.aQute.bndlib.tests/test/test/InstructionTest.java, biz.aQute.bndlib.tests/test/test/MacroTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Instructions.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
In a lot of cases you need to expand a Parameters via a template. I've added  a
macro:
${template;-runbundles;@=@startlevel;,}
This will get the property `-runbundles` (in merged and decorated form) and will iterate over its entries. It will expand the template
for each entry. While expanding, it will set
@ to the key and all attributes with a '@' prefixed.
I've changed the macros slightly. Normally macros set override built in functions. However, this was not the case with macros that too parameters. Now the name of the macro
is used to do the lookup.
Also added some more test to get more coverage
[decorate] Made the default to not expand literals for the decorator
The decorator added literals to the output even if they did not exist in the output. Made this optional and the default to …
=> [templating] Added a template function

aQute.libg/src/aQute/lib/io/IO.java, aQute.libg/src/aQute/libg/remote/source/SourceFS.java, azure-pipelines.yml, biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotationReader.java, biz.aQute.bndlib/src/aQute/bnd/metatype/ADDef.java, biz.aQute.bndlib/src/aQute/bnd/metatype/OCDReader.java, biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java, biz.aQute.bndlib/src/aQute/bnd/service/url/TaggedData.java, biz.aQute.repository/src/aQute/maven/provider/POM.java, bndtools.builder/src/org/bndtools/builder/classpath/BndContainerInitializer.java
Change append loop to avoid StringBuffer. We often don't need to use a replacement string with group numbers, so we can use a different loop to avoid StringBuffer and the expense of Matcher.appendReplacement which spends time looking at the replacement string for group numbers.
=> Matcher append loop

maven/build.gradle
The maven build has been flaky. Removing this to see if it stabilizes.
=> maven: Remove parallel option for maven build

biz.aQute.bnd/src/aQute/bnd/main/RemoteCommand.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java, biz.aQute.remote/bnd.bnd, biz.aQute.remote/src/aQute/remote/agent/AgentServer.java, biz.aQute.remote/src/aQute/remote/api/Agent.java, biz.aQute.remote/test/aQute/remote/util/JMXBundleDeployerTest.java, biz.aQute.remote/test/biz/aQute/remote/AgentTest.java
- API used the install method name twice, the link only supports one, last added changed to installWithData
- Added tests
- Location can now be null, will search for existing location based on BSN
an exception is thrown when there are 2 bundles with the same bsn installed.
- Location specified via option
- Allow multiple files on the command line
=> [remote] Error in API & null location

biz.aQute.bnd.gradle/README.md
Fixes https://github.com/bndtools/bnd/issues/3349
=> gradle: Use -exportcontents in examples for Bnd Builder plugin [skip ci]

.travis.yml, azure-pipelines.yml
Gradle runs each test task in a separate java process. When a test case
uses the Bnd workspace as a workspace in a test, then the new java
process will register a remotews port. So we end up with one port from
the main gradle process for the build and another for each parallel test
process which accesses the Bnd workspace as a workspace in a test. Since
the remote client uses the most recent remotews file, one test process
can use the remote workspace port from another test process. When this
happens and the other test process exits, then the test process using
its remote port will fail as the remote port is unexpectedly closed.
So we disable parallel builds in the CI until we can find a better
solution.
=> Disable parallel gradle build in CI

biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
We try to use FileResource instead of JarResource when including
jars from the project's classpath. A FileResource will keep the jar file
unchanged. A JarResource will write a new jar into the bundle which can
result in SHA changes due to potential zip directory reordering.
=> builder: Avoid rejarring for -includeresource jars from classpath

biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/templates/blocks.twig, biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/transformer/templates/readme.twig, docs/_chapters/395-generating-documentation.md
Closes #3391 
This PR makes manual editing of readme file easier by adding more empty blocks.
The generated readme file is not affected by this modification, so no test to update. 
The documentation has been updated.
=> [reporter] Add more blocks to make manual editing of readme file easier

biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java, biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
The -pom instruction is parsed and added to the scoped processor for the
PomResource class. We must not inherit these properties from the parent
processor. They must come from the -pom instruction or be
passed to the PomResource constructor. Otherwise setting a `version`
property in the cnf/build.bnd or a .bnd file can confuse PomResource.
=> pom: Don't inherit -pom instruction properties from parent processor

biz.aQute.launcher/src/aQute/launcher/Launcher.java, biz.aQute.launcher/src/aQute/launcher/LauncherSystemProperties.java
The watcher, now updated to use a scheduled executor, failed to properly
handle updating the system properties and the launcher parms when the
properties file was updated.
Also remove use of Vector and regex.
=> launcher: Fix handling of system properties and launcher parms on update

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientTest.java, biz.aQute.bndlib/src/aQute/bnd/url/HttpsVerification.java, biz.aQute.http.testservers/src/aQute/http/testservers/HttpTestServer.java, biz.aQute.http.testservers/src/aQute/http/testservers/Httpbin.java, biz.aQute.http.testservers/src/aQute/http/testservers/Server.java
The hostname verification logic in HttpsVerification is incorrect. If "verify" is true then it actually disables hostname verification. If "verify" is false, then it always fails hostname verification.
I added two tests using a cert with an incorrect CN for the hostname. Both tests fail with the old code and pass with the new.
=> Issue 3443 - Incorrect behaviour for HttpsVerification.hostnameVerify

aQute.libg/bnd.bnd, aQute.libg/test/aQute/lib/io/IOTest.java, aQute.libg/test/aQute/libg/uri/URIUtilsTest.java, biz.aQute.bnd.gradle/bnd.bnd, biz.aQute.junit/bnd.bnd, build.gradle, cnf/ext/central.mvn, cnf/ext/junit.bnd
Example of how JUnit 5 support might be added to the Bnd build.
This PR does the following:
* Adds library packages for JUnit Platform, and the Jupiter and Vintage engines to ext/central.mvn
* Adds macros to group them logically to ext/junit.bnd
* Converts `aQute.libg` to use the JUnit Platform.
* `build.gradle` modified to cause Gradle to use the JUnit Platform rather than the JUnit 4 runner.
* Converted `aQute.lib.io.IOTest` and `aQute.libg.uri.URIUtils` to use the Jupiter engine.
* All other test classes remain as they were (JUnit 3 or 4 tests) and are executed by JUnit Platform using the Vintage engine.
* All other projects continue to use the JUnit 4 runner. To migrate them:
1. Replace the ${junit} dependency in `-testpath` with ${junit-platform}
2. Add the engines that you need to …
=> Use JUnit 5 for JUnit test cases

biz.aQute.bnd/test/aQute/bnd/main/TestBndMain.java, biz.aQute.bnd/test/aQute/bnd/main/TestBndMainBase.java, biz.aQute.bnd/testdata/brew/index.xml, biz.aQute.bnd/testdata/brew/launch.bndrun
If the output of the resolve command changes such that this test method
needs to be changed, we must also modify the brew bnd formula
accordingly when we release.
=> bnd: Add test for the brew bnd formula expected output

README.md, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
This will protect against an empty property/provider assigned to the
project.version property.
=> gradle: Use getOrNull to access archiveVersion property of Jar task

biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java
The missing `!` caused Embedded-Activators to be ignored which breaks
biz.aQute.junit. I discovered this when trying to use 4.3.0 with the
OSGi build where some test project still use biz.aQute.junit as the
-tester.
Fixes https://github.com/bndtools/bnd/issues/3481
=> launcher: Don't always set launch.activators to an empty string

biz.aQute.launcher/src/aQute/launcher/Launcher.java
If the launcher ran in this peace of code, it always communicated an error "could not resolve the bundles: []" which is apparently no error.
=> fixed error printout on launch without any error having appeared

biz.aQute.junit/src/aQute/junit/Activator.java, biz.aQute.junit/src/aQute/junit/plugin/ProjectTesterImpl.java, biz.aQute.launcher/src/aQute/launcher/minifw/BundleRevisionImpl.java, biz.aQute.launcher/src/aQute/launcher/minifw/BundleStartLevelImpl.java, biz.aQute.launcher/src/aQute/launcher/minifw/BundleWiringImpl.java, biz.aQute.launcher/src/aQute/launcher/minifw/Context.java, biz.aQute.launcher/src/aQute/launcher/minifw/FrameworkStartLevelImpl.java, biz.aQute.launcher/src/aQute/launcher/minifw/FrameworkWiringImpl.java, biz.aQute.launcher/src/aQute/launcher/minifw/MiniFramework.java
The use of `-runframework: none` was broken by changes to the launcher
which expects the framework to be adaptable to certain start level and
wiring types.
Fixes #3489
=> launcher: Fix MiniFramework operation

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
Fixes https://github.com/bndtools/bnd/issues/3494
=> gradle: Fix deprecation warning for using Jar.baseName property

biz.aQute.bndlib.tests/build.gradle
So we configure gradle to make sure those project's `jar` tasks are
up-to-date before starting the `test` task.
Fixes https://github.com/bndtools/bnd/issues/3500
=> tests: Some tests depend upon jars in `-dependson` projects

biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/build.gradle, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndUtils.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/PropertiesWrapper.groovy, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestHelper.groovy, biz.aQute.bnd.gradle/testresources/baselinetask1/build.gradle, biz.aQute.bnd.gradle/testresources/baselinetask4/build.gradle, biz.aQute.bnd.gradle/testresources/builderplugin1/build.gradle, biz.aQute.bnd.gradle/testresources/indexplugin1/build.gradle, biz.aQute.bnd.gradle/testresources/runtask1/build.gradle, biz.aQute.bnd.gradle/testresources/testosgitask1/build.gradle, biz.aQute.bnd.gradle/testresources/testosgitask2/build.gradle, biz.aQute.bnd.gradle/testresources/testosgitask3/build.gradle, biz.aQute.bnd.gradle/testresources/testosgitask4/build.gradle, maven/pom.xml, org.bndtools.p2/build.gradle
Set Gradle 5.1 as the base version of Gradle supported.
Remove all conditional code for Gradle 4.0 and avoid using deprecated
fields in Gradle 6.0 to avoid runtime warnings.
=> Gradle 6 0 support

biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelector.java, biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java, biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java, biz.aQute.tester.test/test/aQute/tester/testbase/AbstractActivatorTest.java
This race condition caused random failures on JDK 11 on the CI builds.
A test bundle could have been installed between the initial request
creation and the opening of the BundleTracker. So tests would sometimes
see a test bundle fail to be processed.
We change to use the BundleTracker to create BundleSelectors for
all bundles and queue them for the main processing loop. In the main
processing loop, we process all available BundleSelectors together even
waiting briefly to see if the BundleTracker is still adding elements to
the queue.
=> junit-platform: Fix race condition in automatic()

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy, build.gradle
Project plugins include workspace plugins, so we want to make sure
workspace plugins are complete before adding to projects plugins.
Fixes https://github.com/bndtools/bnd/issues/3499
=> workspace: Ensure workspace plugins are fully initialized before use

cnf/ext/repositories.bnd
This will allow easier changes to the Eclipse dependencies.
=> cnf: Split -plugin into multiple -plugin.* properties

docs/_chapters/200-components.md
- Adopt 4 spaces prefix to trigger code block formatting
- `[=\=]` tokens removed as they do not seem part of the code
=> docs: Fix code blocks

biz.aQute.bnd.embedded-repo/bnd/embedded-repo.bnd, biz.aQute.bnd.gradle/biz.aQute.bnd.builder.gradle.plugin.bnd, biz.aQute.bnd.gradle/biz.aQute.bnd.gradle.bnd, biz.aQute.bnd.gradle/biz.aQute.bnd.gradle.plugin.bnd, biz.aQute.bnd.gradle/biz.aQute.bnd.workspace.gradle.plugin.bnd, biz.aQute.bnd.gradle/bnd.bnd, biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientProxyTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
This will allow Gradle to find the Bnd Gradle plugin ids using the
`plugins {}` DSL block when using Maven Central or JCenter.
See https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers
=> gradle: Build plugin markers for the Bnd Gradle plugins

biz.aQute.junit/src/aQute/junit/Activator.java
We want to match the complete method name and not a prefix of the
complete method name.
Fixes https://github.com/bndtools/bnd/issues/3562
=> junit: Fix method name matching for JUnit 4

bndtools.core/src/bndtools/launch/JUnitShortcut.java, bndtools.core/src/bndtools/launch/api/AbstractLaunchShortcut.java
* When finding an existing launch configuration, it will match on the Eclipse project only unless a `bnd.bnd` file or a `bndrun` file has been selected.
* Clears the `tester.names` property on JUnit launches unless a testable Java element has been selected.
=> [bndtools] Use sensible defaults when launching using context menu

biz.aQute.junit/src/aQute/junit/Activator.java, biz.aQute.junit/src/aQute/junit/BundleUtils.java, biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/BundleDescriptor.java, biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/utils/BundleUtils.java
We avoid Bundle.getHeaders since it can merge a fragment's Test-Cases
header into the host's headers.
A nice effect of this change is that we now properly ignore empty Test-Cases headers.
=> junit: Read Test-Cases header directly from bundle

aQute.libg/src/aQute/lib/startlevel/StartLevelRuntimeHandler.java
This PR extends the `-resolve` instruction from `manual` (default) and `auto` with `beforelaunch`. The `beforelaunch` option will  calculate the `-runbundles` on demand. It has a cache based on the project properties.
=> -resolve instruction extended with beforelaunch

biz.aQute.junit/src/aQute/junit/Activator.java, biz.aQute.launcher/src/aQute/launcher/Launcher.java, biz.aQute.launcher/src/aQute/launcher/minifw/BundleClassLoader.java, biz.aQute.launcher/src/aQute/launcher/minifw/Headers.java, biz.aQute.launcher/src/aQute/launcher/minifw/IteratorEnumeration.java, biz.aQute.launcher/src/aQute/launcher/minifw/MiniBundle.java, biz.aQute.launcher/src/aQute/launcher/minifw/MiniFramework.java, biz.aQute.launcher/src/aQute/launcher/minifw/Tracing.java
Testing changed to use Bundle.getEntry to read the bundle manifest. The MiniFramework implementation of Bundle.getEntry did not return the correct manifest.
=> Fix MiniFramework to work with recent changes to testing

aQute.libg/src/aQute/lib/collections/MultiMap.java, aQute.libg/src/aQute/lib/collections/packageinfo, biz.aQute.bnd/src/aQute/bnd/ant/PackageTask.java, biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java, biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java, biz.aQute.bndlib/src/aQute/bnd/build/Run.java, biz.aQute.bndlib/src/aQute/bnd/exporter/executable/ExecutableJarExporter.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Instructions.java, biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java, demo/export-options.bndrun, docs/_instructions/export.md
The -export instruction can export bndrun files. However,
these exports were done in the Project Builder. At that
time any bundles are build but not yet present on the file
system. If the bndrun file included the bundles (Jars) 
then it got an error on a clean build or a previous
version.
This patch moves the -export execution into Project
and executes it after the bundles/jars are stored
on the file system.
=> [export] bndrun configurations cannot be exported #3339

aQute.libg/src/aQute/lib/exceptions/Exceptions.java, aQute.libg/src/aQute/lib/exceptions/packageinfo, aQute.libg/test/aQute/lib/exceptions/ExceptionsTest.java
These methods make it easy to call Callables and RunnableWithExceptions
and duck the thrown exception. It is expected these methods would be
used mostly with lambda expression and the compiler will select the
proper unchecked method depending upon whether the lambda provides a
return value.
=> libg: Add convenience unchecked methods to Exceptions

biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java, biz.aQute.tester.test/test/aQute/tester/bundle/engine/test/BundleEngineTest.java
There were no tests to check that method selectors with unresolved classes would be handled properly. There was a TODO in the code to add these, so it is now TODONE.
This was done partially in preparation for #3589 to make sure that we don't regress during that implementation.
=> [junit-platform tester] Add missing tests for method selectors

biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/Activator.java
Now that we're on a more recent version of junit-platform-launcher, there is a builder API that can be used to construct launcher configs. This is a neater way of constructing a launcher that uses only the `BundleEngine` as a test engine, rather than using the ThreadContextClassLoader hack that we were forced to use in the earlier release.
=> [junit-platform] Use Launcher builder framework

.travis.yml, biz.aQute.bndlib.comm.tests/bnd.bnd, biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientProxyTest.java
We were having intermittent BindException because the chosen port was in
use.
=> comm.tests: Use different port range for windows

biz.aQute.bnd/src/aQute/bnd/main/MbrCommand.java, bndtools.core/src/bndtools/launch/api/AbstractLaunchShortcut.java, bndtools.test/workspace/.gitignore
There were changes made in the launching code. One of those changes called the launch method with a null path, this then created an NPE in:
protected void launch(IPath targetPath, IProject targetProject, String mode) {
Because targetPath was null.
Changed to use the bnd.bnd file in the project directory as target path in:
protected void launchProject(IProject project, String mode) {
=> [launch] Launching on project or bnd.bnd failed

bndtools.core/_plugin.xml, bndtools.core/src/bndtools/explorer/BndtoolsExplorer.java, bndtools.core/src/bndtools/perspective/BndPerspective.java, bndtools.utils/src/org/bndtools/utils/swt/FilterPanelPart.java
A replacement for the package explorer in the
bndtools perspective. The bndtools explorer
has a filter field for projects. Filtering
is only done on project name (glob), all its
resources are then visible.
=> [view] Bndtools Explorer

bndtools.core/src/bndtools/launch/AbstractOSGiLaunchDelegate.java
Changed the `AbstractOSGiLaunchDelegate` so that instead of calling `getProjectLauncher().update()` inline from the resource listener, the listener will instead schedule a job to run that:
1. waits for any in-progress build to complete, then
2 calls `getProjectLauncher().update()` to update the running process.
Fixes #3623.
Comments/feedback welcome.
=> [bndtools] Wait for build to complete before updating launch

cnf/ext/central.mvn
I cleaned up the index on bintray for Eclipse 2018-12 to reduce the
resource count from 5430 to 119. These resources are now also on bintray
to remove our dependency on Eclipse download site. This will speed up
building and refreshing repositories since the index file is much
smaller.
Since the Eclipse index provides the Guava 21 used by Eclipse, we remove
the artifact from maven central that was added some time back for
Eclipse Oxygen.
=> build: Remove duplicate artifact provided by Eclipse index

biz.aQute.bnd.gradle/publish.gradle, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndUtils.groovy, biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
If the `java-library` plugin is applied, Gradle will compile against
the dependency's classes dir instead of building the jar and compiling
against the jar. This is not good for bundles since Bnd can pull in code
from other places and also set the package metadata.
So we configure the sourceSet's compileClasspath configuration to use
jars for compilation.
This support requires Gradle 5.6 or later.
See https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_classes_usage
=> gradle: Use dependency's jars for compilation

bndtools.core/_plugin.xml, bndtools.core/src/bndtools/explorer/BndProjects.java, bndtools.core/src/bndtools/explorer/EmptyPackageFilter.java
Filters from Package Explorer couldn't be used
- Added .* filter, empty packages
- Added filter for Bndtools projects
=> [bndexplorer] Fix filters

docs/_instructions/runvm.md
Doc incorrectly stated that -D would be inferred if no leading - was found on the property. This is not the case - arguments are added as-is.
Fixes #3652.
=> [docs] Fixed misleading doc for -runvm

biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/BndrunContainer.java, biz.aQute.bndlib/src/aQute/bnd/stream/MapStream.java, biz.aQute.bndlib/test/aQute/bnd/stream/MapStreamTest.java
Generalize ofKeys to ofEntries. This provides a more general method to create a MapStream from a Stream.
=> Mapstream update

biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java, biz.aQute.tester.test/src/aQute/tester/test/params/CustomParameter.java, biz.aQute.tester.test/src/aQute/tester/testclasses/bundle/engine/JUnit5ParameterizedTest.java, biz.aQute.tester.test/test/aQute/tester/bundle/engine/test/BundleEngineTest.java
This PR has two commits:
1. The first adds checks for unresolved methods - ie, reporting if you try to specify a method in `tester.names` that doesn't exist. Previously, it would only check for unresolved classes.
2. The second is the fix for #3589 - it sets the TCCL to the resolved test class before calling `ReflectionSupport.findMethod()`, so that the JUnit reflection code will use the correct class loader for attempting to resolve the parameters.
=> [junit-platform tester] Resolve method selector parameters

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
So we can remove the unnecessary toString call.
=> gradle: archiveVersion is already a String

bndtools.test/tester/cnf/ext/central.mvn, bndtools.test/tester/cnf/ext/repositories.bnd, bndtools.test/tester/main-with-runners/runtests-shared.bndrun
Some fixes to bring the tester workspace up-to-date with Eclipse 2018-12 to make testing the tester easier.
=> [junit-platform tester] Update tester workspace for Eclipse 2018-12

biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/BundleDescriptor.java, biz.aQute.tester.test/test/aQute/tester/bundle/engine/test/BundleEngineTest.java
Original implementation mimicked Gogo's "lb" command - it would use `Bundle-Name` if available, then BSN. The core team felt that always using BSN would be better in a dev context.
This is easily revertable, or possibly in the future configurable if there is a demand.
=> [junit-platform tester] Always use BSN for bundle display name

biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java, biz.aQute.tester.test/src/aQute/tester/testclasses/bundle/engine/JUnit3And4Test.java, biz.aQute.tester.test/src/aQute/tester/testclasses/bundle/engine/JUnit3And5Test.java, biz.aQute.tester.test/src/org/junit/venus/Test.java, biz.aQute.tester.test/test/aQute/tester/bundle/engine/test/BundleEngineTest.java, biz.aQute.tester.test/test/aQute/tester/testclasses/bundle/engine/JUnit3AndVenusTest.java
Will check classes for mixed JUnit 3 and 4 tests and generate a test error for each one it finds under the bundle in which the class was found.
Fixes #3671.
=> [junit-platform tester] Check for mixed JUnit 3 and 4 tests

biz.aQute.junit/src/aQute/junit/JUnitEclipseReport.java, biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/JUnitEclipseListener.java
The code now uses nio SocketChannel to communicate with the Eclipse client. The code now also waits for a brief delay after reporting the test run end to try to ensure the Eclipse client receives the message before the connection is closed and the test VM terminates. The 0.25 sec value chosen seems to reliably solve the issue on my system. We may need to tweak the value with some more experience.
=> Eclipse JUnit reporting fixes

aQute.libg/src/aQute/lib/strings/Strings.java
The calculation of the byteUnit was incorrect. Constants are now used
to avoid int multiplication overflow problem. Long constants are also
used to avoid implicit conversion from int constants to long values.
=> strings: Fix Magnitude enum

biz.aQute.bndlib.tests/test/test/VersionPolicyTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
https://bnd.bndtools.org/chapters/170-versioning.html describes several
idioms for describing version ranges: @ prefix, @ suffix, = prefix.
However these were not properly processed when used in Import-Package
statements as shown in the documentation. This fix updates the
cleanupVersion method to detect usage of these idioms and convert them
to the standard OSGi internal syntax.
=> Properly handle version range idioms: @ prefix, @ suffix, = prefix

aQute.libg/src/aQute/lib/hex/Hex.java, aQute.libg/test/aQute/lib/hex/HexTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java, bndtools.jareditor/bnd.bnd, bndtools.jareditor/src/bndtools/jareditor/internal/JAREditor.java, bndtools.jareditor/src/bndtools/jareditor/internal/JARTreeEntryPart.java, bndtools.jareditor/src/bndtools/jareditor/internal/JarFileSystem.java, bndtools.jareditor/src/bndtools/jareditor/internal/TemporaryFile.java, bndtools.jareditor/src/bndtools/jareditor/internal/TemporaryProject.java
We now avoid repetitively reading the entire jar into memory hundreds of times by properly caching the eclipse file system nodes and not reading entries into memory until they are needed for the view component.
Fixes https://github.com/bndtools/bnd/issues/3722
=> Fix performance issues in Jar viewer

bndtools.jareditor/src/bndtools/jareditor/internal/JarFileSystem.java
The ZipEntry may contain -1 for the uncompressed size, so we must
drain the input stream to compute the uncompressed size.
=> jareditor: If the ZipEntry does not contain a size, compute the size

bndtools.core/src/bndtools/launch/OSGiJUnitLaunchDelegate.java
Loop around the call to `accept()` to accept reconnection attempts (such as what happens when the tester bundle is restarted).
Partial fix for #3528.
=> [tester] OSGiJUnitLaunchDelegate to handle restarting tester bundle

bndtools.jareditor/bnd.bnd, bndtools.jareditor/src/bndtools/jareditor/internal/TemporaryFile.java
The code NPE'd trying to get the state location because no one started
the bundle. So we mark it lazy activation to get Eclipse to start it.
=> jareditor: Plugin must be started for the Bundle-Activator to be called

biz.aQute.tester.junit-platform/src/aQute/tester/bundle/engine/discovery/BundleSelectorResolver.java, biz.aQute.tester.test/test/aQute/tester/junit/platform/test/ActivatorJUnitPlatformTest.java
JUnit 5.5 changed to call getSelectorsByType with the base
DiscoverySelector type which caused us to fail to substitute the OSGi
ready selectors.
We change to call the original request and then filter out the selector
we will supply. We then add the selectors we will supply to the stream.
Fixes https://github.com/bndtools/bnd/issues/3745
=> junit-platform: Fix Sub-request to handle plain DiscoverySelector

biz.aQute.tester.test/test/aQute/tester/bundle/engine/test/BundleEngineTest.java
=> [junit-platform] Regression test for #3746

.gradle-wrapper/gradle-wrapper.properties
This fixes the creation of the empty /gradle folder.
=> gradlew: Update to 6.1.1

biz.aQute.bndlib.tests/test/test/ResourceTest.java, biz.aQute.bndlib/src/aQute/bnd/header/Attrs.java, biz.aQute.bndlib/src/aQute/bnd/header/package-info.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapReqBuilder.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java
We now decorate package capabilities with the bundle-symbolic-name
and bundle-version of the exporting bundle (when known).
We also properly generate the filter directive on wiring namespaces for
matching attributes.
Fixes #3748
=> indexing: Properly handle bundle-symbolic-name and bundle-version

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndUtils.groovy
A project can have multiple Bundle tasks all using the same sourceSet.
So we avoid setting the org.gradle.libraryelements attribute to jar if
it is already set to jar. We also defend against attempting to set the
attribute after it have been made immutable.
Fixes https://github.com/bndtools/bnd/issues/3780
=> gradle: Avoid multiple sets of org.gradle.libraryelements to jar

bndtools.core/src/bndtools/editor/BndEditor.java
The change made started to use an absolute path
for the bnd file instead of relative. That threw
off the routine that selected the set of tabs
to use.
In the old situation, using the same algorithm
based on Eclipse code.
=> [bndeditor] Wrong file name

biz.aQute.repository/bnd.bnd
I don't believe there ever was an org.osgi.service.indexer package.
=> repository: Remove export of non-existent package

docs/_instructions/groupid.md
See https://github.com/bndtools/bnd/issues/3807
=> docs: Clarify the default of -groupid is the workspace folder name

biz.aQute.bndlib/src/aQute/bnd/build/model/EE.java, biz.aQute.bndlib/src/aQute/bnd/build/model/package-info.java, bndtools.utils/src/org/bndtools/utils/javaproject/JavaProjectUtils.java
Fixes #3798 by replacing the bndtools specic JavaLevel Enum with the
usage of the EE enum
=> fixed support for current java Versions in templates

biz.aQute.launcher/bnd.bnd, biz.aQute.launcher/src/aQute/launcher/Launcher.java, cnf/ext/osgi-snapshots.mvn
The OSGi Alliance is working on a Connect specification.
This specification will allow an SPI to take over some
of the module handling in an OSGi Framework.
This change will first look if there is a Module
Connector loadable via the Service Loader. If so,
it will try to use OSGi Connect with the found
Module Connector. If anything fails, it will fall
back to the classic mode. I.e, the types of OSGi
Connect are not required to be part of the class path.
Also, a static method is added to call the launcher
externally. This method can take an optional 
Properties and/or an optional Bundle Activator. The
Bundle Activator is called before the bundles are started.
An implicit change is that the code now uses the Service Loader
for the framework as well. This code was originally 
artisan but …
=> [launcher] Added a connect mode to the launcher.

biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java, biz.aQute.bndlib/src/aQute/bnd/help/instructions/LauncherInstructions.java, biz.aQute.bndlib/src/aQute/bnd/help/instructions/package-info.java, biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java, docs/_instructions/executable.md
The current launcher calculates a unique name for
each embedded JAR when creating an executable JAR.
This unique name is based on the name of the file
in the repo. Some of these files are just the bsn
but sometimes the full version is in there. 
Unfortunately, the launcher uses this path in the
executable JAR to create the location of the 
corresponding bundle. 
If the version is in that name, then this creates
a problem if the storage area is kept. If the version
of a bundle gets changed, it will create a new location
creating unwanted duplicates.
To generate a proper location, you need a strategy.
You could use a location that is unique for a
bsn, implying that all bundles are singletons. A sensible
strategy seems to include the major version in the 
location, allowing unique locations …
=> [launcher] Location format

docs/_chapters/310-testing.md, docs/releases/5.0.0/chapters/310-testing.html
* Old docs referred to 4.4 release which became the 5.0 release.
* Old docs referred to Eclipse Oxygen, which is now Eclipse 2018-12.
* Added note about 5.6 release of JUnit being bundled.
* Added note about incompatibility with JUnit 5.5.
Fix includes HEAD and 5.0.0 release notes.
=> [docs] Update/correct tester docs with latest version information

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
If the maven-release instruction sets a source path, it is not obvious
why and if no sources are packaged. Thus a warning will be logged.
=> Adds a log warning if no sources available

biz.aQute.bnd.gradle/publish.gradle
This workaround makes use of the plugin-publish plugin's integration
with the java-gradle-plugin and maven-publish plugins. However, instead
of generating a POM based on the pluginMaven publication added by the
former, the task is disabled and the published POM is copied to its
destination. Thus, the publishPlugins task will pick it up and upload
it to the Gradle Plugin Portal.
---
Please note that I wasn't able to fully test this with the actual Plugin Portal.
=> Publish existing POM to Gradle Plugin Portal

biz.aQute.bndall.tests/test/biz/aQute/launcher/AlsoLauncherTest.java, biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java
Bndtools can attach source code to files for ease of debugging. These
source-enhanced-files have file names which start with '+'. When making
an executable, we should use the original files instead of the
source-enhanced-files.
I discovered this issue because a test case failed on my system because
I had had Bndtools add source to one of the files used by the test and
the extra '+' in the file name caused the test to fail.
=> launcher: Handle source enhanced files

.github/scripts/build.sh, .github/scripts/docs.sh, .github/scripts/rebuild.sh, .github/workflows/cibuild.yml, .github/workflows/docsbuild.yml
v2 only does a shallow fetch so we must unshallow the fetch for building
push events on the main repo since we need to know the prior tag for
git describe.
=> actions: Update checkout to v2

biz.aQute.bndlib/src/aQute/bnd/service/progress/ProgressPlugin.java, biz.aQute.bndlib/src/aQute/bnd/service/progress/TaskManager.java, biz.aQute.bndlib/src/aQute/bnd/service/progress/packageinfo, bndtools.core/src/bndtools/central/Central.java
Added a task manager that tracks a Task per 
thread.
This makes it possible to let any code query if
the 'current' task is canceled.
The Central code binds this to the given
monitor.
=> [tasks] Task Manager

biz.aQute.bnd.reporter/bnd.bnd, biz.aQute.bndlib/bnd.bnd
adds osgi.dto pckg to fix CNF Exception in gradle for p2 repo
* addionally counts the package version up, because baselineing
complained about it
=> Adds org.osgi.dto Package to fixe ClassNotFoundException in gradle build when using P2Repository

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/NexusCommand.java, biz.aQute.repository/src/aQute/maven/nexus/provider/Signer.java, biz.aQute.repository/src/aQute/maven/nexus/provider/package-info.java
We implement the --key option which was present but never implemented.
This allows the user to sign with a key other than the gpg default key.
We also add a --settings option to the nexus command to specify the
-connections-settings property to allow the user to specify connection
settings other than the default.
Documentation annotations are also added so that the bnd help command
can provide helpful output.
=> bnd: Improvements to bnd nexus sign command

.github/workflows/cibuild.yml, .gradle-wrapper/gradle-wrapper.properties, biz.aQute.bnd.gradle/README.md, biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestHelper.groovy
Now that JDK 14 is released and supported by Gradle 6.3, we update the build.
=> Updates for JDK 14

biz.aQute.bnd.reporter/bnd.bnd, biz.aQute.bndlib.tests/test/test/MavenTest.java, biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java, biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java
We now use the Maven G:A:V coordinates as the key for clauses in the
generated -maven-dependencies instruction. This will allow merged
-maven-dependencies instructions to override the computed dependency GAV
information by using the G:A:V key computed for the main
-maven-dependencies instruction.
Fixes https://github.com/bndtools/bnd/issues/3854
=> pom: Make it possible to override computed dependency elements

aQute.libg/src/aQute/lib/collections/ExtList.java, aQute.libg/src/aQute/lib/promise/PromiseCollectors.java, biz.aQute.bnd/src/aQute/bnd/main/XRefCommand.java, biz.aQute.bndlib/src/aQute/bnd/build/Project.java, biz.aQute.bndlib/src/aQute/bnd/cdi/CDIAnnotations.java, biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java, biz.aQute.bndlib/src/aQute/bnd/osgi/PermissionGenerator.java, biz.aQute.bndlib/src/aQute/bnd/osgi/repository/ResourcesRepository.java, biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java, biz.aQute.bndlib/src/aQute/bnd/plugin/jpms/JPMSModuleInfoPlugin.java, biz.aQute.bndlib/test/aQute/bnd/stream/MapStreamTest.java, biz.aQute.launcher/src/aQute/launcher/minifw/MiniBundle.java
For generic types, we specify the generics when using the ::new method
reference. This helps the compiler and removes some cast to Supplier
to establish the generic types.
=> generics: Specify generics for Supplier method reference to new

bndtools.core/src/bndtools/wizards/project/NewBndProjectWizard.java
The original design was to have no Java project setup. However, during one release the wizard crashed with an NPE if we skipped that page. That seems to be fixed.
We decided to remove this page to see how this goes?
Attempt for #3824
=> [newproject] Removed the Java Page

biz.aQute.tester.junit-platform/src/aQute/tester/junit/platform/JUnitEclipseListener.java, biz.aQute.tester/src/aQute/junit/JUnitEclipseReport.java
The Eclipse JUnit view was slow to respond for test execution progress
for Bnd OSGi Test Launcher runs. More frequent flushing of the progress
messages to Eclipse seems to improve the UX.
=> tester: Flush more often to get progress messages to Eclipse

biz.aQute.bnd.maven/src/aQute/bnd/maven/lib/resolve/DependencyResolver.java
At dependency resolution the scope should be used to identify if an artifact should be added or not.
It must not be used to skip the whole part of a tree as the childs of a tree node could use a different scope then one of its predecessor.
Related to: https://github.com/bndtools/bnd/issues/3783
=> fix scope handling at dependency resolution

biz.aQute.bndlib/src/aQute/bnd/osgi/repository/BridgeRepository.java, biz.aQute.bndlib/src/aQute/bnd/service/clipboard/Clipboard.java, biz.aQute.bndlib/src/aQute/bnd/service/clipboard/package-info.java, biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java, bndtools.core/src/bndtools/central/Central.java, bndtools.core/src/bndtools/central/SWTClipboard.java
A menu action on the BndPomRepository to copy
the GAVs from the POM (or search, or etc.) to
the clipboard so they can be used for a MavenBndRepository
=> [gavs pom] A menu action to copy GAVs

biz.aQute.bndlib/src/aQute/bnd/service/clipboard/package-info.java, biz.aQute.resolve/src/biz/aQute/resolve/AbstractResolveContext.java, biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java, biz.aQute.resolve/src/biz/aQute/resolve/GenericResolveContext.java
The debug report resulted in calling the resolver which called back
into the resolve context on another thread. Since the resolve context
was still initializing and held the init lock, the resolver could
deadlock.
So we move the debug report operation to after the
init operation completes and releases the init lock.
Fixes #3900
=> resolve: Move resolve debug output report out of synchronized init

biz.aQute.bndlib.tests/test/test/JarTest.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
We may need to make multiple modifications to the directories map when
adding a resource. computeIfAbsent does not allow the mapping function
to modify the map.
Fixes #3903
=> jar: Replace incorrect use of computeIfAbsent in putResource

biz.aQute.bndlib.tests/test/test/BuilderTest.java, biz.aQute.bndlib.tests/test/test/ClassReferenceTest.java, biz.aQute.bndlib.tests/test/test/model/EETest.java, biz.aQute.bndlib/src/aQute/bnd/build/model/EE.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java, biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java, biz.aQute.bndlib/src/aQute/bnd/plugin/jpms/JPMSModuleInfoPlugin.java, docs/_chapters/330-jpms.md
More of the test parameters are automatically generated based upon code or test resources.
Also, constants are added fro Java 16 and 17 to get a little ahead of the game.
Unfortunately we have 2 enums, EE and JAVA, which are in the public API that must be changed for each new version of Java. Tests were added to ensure they are updated together.
=> Updates for Java version support

bndtools.builder/src/org/bndtools/builder/indexer/BuiltBundleIndexer.java, bndtools.core/src/bndtools/central/EclipseWorkspaceRepository.java
We now fall back to buildfiles if the index file is not present. We
also rename the index file to .index.xml to (1) force reindexing upon
update to this new support and (2) to be able to view the file using
the XML support in Eclipse.
=> workspacerepo: Move all indexing logic into EclipseWorkspaceRepository
