aQute.libg/src/aQute/lib/converter/Converter.java
aQute.libg/test/aQute/lib/converter/ConverterTest.java
biz.aQute.bndlib.tests/src/test/VerifierTest.java
biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
biz.aQute.launcher/test/aQute/launcher/plugin/ProjectLaunchImplTest.java
biz.aQute.launcher/test/ws/p1/.gitignore

These are cherry picked from master.

Additional fixes for 2.4.1

---

biz.aQute.bndlib.tests/testresources/a space/cnf/ext/defaults.bnd
biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/defaults.bnd

Fixes https://github.com/bndtools/bndtools/issues/970

Add javac.profiles to defaults

---

biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java
org.osgi.impl.bundle.repoindex.cli/bnd.bnd

Some fixes to the generated poms. Maven central requires a description.

Maven central pom fix

---

biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java

See http://central.sonatype.org/pages/requirements.html#project-name-description-and-url

pom: Use maven central recommended default name

---

biz.aQute.repository/src/aQute/bnd/deployer/repository/AbstractIndexedRepo.java

it can't contact the repo.
Looks like I caused this issue with the initial implementation of refresh(). This is a better way to handle refreshing of AbstractIndexRepo.
Signed-off-by: Carter Smithhart <carter.smithhart@gmail.com>

AbstractIndexedRepo shouldn't delete an index from a remote repo if

---

cnf/build.bnd

Signed-off-by: Carter Smithhart <carter.smithhart@gmail.com>
See bndtools/bndtools#1003

Test out new eclipse access rules in bnd workspace

---

biz.aQute.resolve/bnd.bnd
org.osgi.impl.bundle.repoindex.ant/bnd.bnd
org.osgi.impl.bundle.repoindex.cli/bnd.bnd
org.osgi.impl.bundle.repoindex.test/bnd.bnd

build: Fix bnd -buildpath to use projects that export the types

---

org.osgi.impl.bundle.repoindex.ant/bnd.bnd
org.osgi.impl.bundle.repoindex.cli/bnd.bnd

build: fix split-packages warning

---

aQute.libg/src/aQute/lib/io/IO.java
aQute.libg/src/aQute/libg/reporter/ReporterMessages.java
biz.aQute.bnd/src/aQute/bnd/main/Profiles.java
biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bndlib/src/aQute/bnd/annotation/ProxyType.java
biz.aQute.bndlib/src/aQute/bnd/annotation/packageinfo
biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
biz.aQute.bndlib/src/aQute/bnd/build/ProjectMessages.java
biz.aQute.bndlib/src/aQute/bnd/build/packageinfo
biz.aQute.bndlib/src/aQute/bnd/exporter/subsystem/SubsystemExporter.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.bndlib/src/aQute/lib/deployer/FileRepo.java
biz.aQute.repository/src/aQute/bnd/deployer/repository/wrapper/InfoRepositoryWrapper.java
biz.aQute.repository/test/aQute/bnd/deployer/repository/wrapper/TestWrapper.java
biz.aQute.resolve/src/biz/aQute/resolve/internal/BndrunResolveContext.java

Adding extra facilities to be able to create subsystems out of a bndrun file.
Also contains some extra utilities in libg that were useful

Work in progress on Subsystem .esa generation

---

biz.aQute.bnd/bnd.bnd

bnd: Fix -split-package warnings

---

org.osgi.impl.bundle.repoindex.lib/src/org/osgi/service/indexer/impl/SCRAnalyzer.java

Fixes an NPE mentioned in bndtools/bndtools#455.

Scranalyzer fixes

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java

error formatting: Fix to actually make array objects printable

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java

error formatting: Handle primitive arrays

---

biz.aQute.bndlib.tests/src/test/LocationTest.java

[test] teardown deleted the wrong directory

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java

Filed #846 because I think this is a compatible change.

[basleine] Change was not compatible enough

---

biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java

Fixes https://github.com/bndtools/bnd/issues/850

baseline: fix warning message

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java

[processor] Make sure files exist before searching

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java

The exception is added as an error already.

analyzer: Remove printStackTrace

---

biz.aQute.bndlib.tests/src/test/MacroTest.java
biz.aQute.bndlib.tests/src/test/VerifierTest.java
biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
org.osgi.impl.bundle.repoindex.lib/src/org/osgi/service/indexer/impl/SCRAnalyzer.java
org.osgi.impl.bundle.repoindex.lib/testdata/fragment-scr_services.txt

#770 #761 and correction for previous PR

Bug fixes #770 #761 and correction for previous PR

---

biz.aQute.bndlib/src/aQute/bnd/build/RunSession.java
biz.aQute.bndlib/src/aQute/bnd/exporter/subsystem/SubsystemExporter.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
biz.aQute.bndlib/src/aQute/bnd/signing/Signer.java
biz.aQute.bndlib/src/aQute/bnd/url/BasicAuthentication.java
biz.aQute.bndlib/src/aQute/bnd/url/BndAuthentication.java
biz.aQute.remote/agent.subsystem.bndrun
biz.aQute.remote/src/aQute/remote/plugin/RunSessionImpl.java
biz.aQute.remote/src/aQute/remote/util/Dispatcher.java
biz.aQute.remote/test/biz/aQute/remote/MainTest.java

Launcher is now working basically, obviously lots of tuning left

Finishing touches for the launcher

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPluginConvention.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndProperties.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bundle.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy

Several improvements to the gradle plugin.

Gradle bundle task update

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy

The bnd gradle plugins are mutually exclusive.

gradle plugin: Check that the other bnd gradle plugin is not applied

---

bnd-maven-plugin/pom.xml
bnd-maven-plugin/src/main/java/org/bndtools/maven/MavenVersion.java

Add sources and javadoc plugin

---

bnd-maven-plugin/pom.xml
bnd-maven-plugin/src/test/resources/unit/settings.xml
bnd-maven-plugin/src/test/resources/unit/test-api-bundle/pom.xml
bnd-maven-plugin/src/test/resources/unit/test-impl-bundle/pom.xml

bnd-maven-plugin: Add settings.xml

---

bnd-maven-plugin/pom.xml

Added project URL to POM

---

biz.aQute.bnd/src/aQute/bnd/ant/RunBundlesTask.java
biz.aQute.bnd/src/aQute/bnd/ant/RunconfigToDistributionTask.java
biz.aQute.bnd/src/aQute/bnd/ant/taskdef.properties

Fixes #866
Signed-off-by: Humeniuk, Dave <david.humeniuk@udri.udayton.edu>

ant: Add Ant task to deploy run bundles like the Gradle version

---

biz.aQute.bnd/src/aQute/bnd/ant/BaseTask.java

Signed-off-by: Ferry Huberts <ferry.huberts@pelagic.nl>

BaseTask: fix unguarded trace

---

bnd-maven-plugin/pom.xml
bnd-maven-plugin/src/test/resources/integration-test/test/pom.xml
bnd-maven-plugin/src/test/resources/integration-test/test/test-api-bundle/pom.xml
bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/pom.xml

build: update build to target java 1.7

---

biz.aQute.bndlib.tests/src/test/MacroTest.java
biz.aQute.bndlib.tests/src/test/packageinfo/annotated/BlahAnnotation.java
biz.aQute.bndlib.tests/src/test/packageinfo/annotated/package-info.java
biz.aQute.bndlib.tests/src/test/packageinfo/nopackageinfo/Dummy.java
biz.aQute.bndlib.tests/src/test/packageinfo/notannotated/package-info.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Packages.java

${packages} macro

---

bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/bnd.bnd

Fixes https://github.com/bndtools/bnd/issues/924

bnd-maven-plugin: Enable use of pom properties in bnd

---

biz.aQute.bndlib.tests/src/test/annotationheaders/AnnotationHeadersTest.java
biz.aQute.bndlib/src/aQute/bnd/annotation/headers/RequireCapability.java
biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java

Fix #936: @RequireCapability: filter should be optional

---

biz.aQute.remote/src/aQute/remote/agent/RedirectOutput.java
biz.aQute.remote/src/aQute/remote/agent/Shell.java

[remote] wait until flush() is called to send output across the wire

---

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib.tests/src/test/metatype/SpecMetatypeTest.java
biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java
biz.aQute.bndlib/src/aQute/bnd/component/ComponentDef.java
biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
biz.aQute.bndlib/src/aQute/bnd/component/HeaderReader.java
biz.aQute.bndlib/src/aQute/bnd/component/ReferenceDef.java
biz.aQute.bndlib/src/aQute/bnd/metatype/ADDef.java
biz.aQute.bndlib/src/aQute/bnd/metatype/DesignateDef.java
biz.aQute.bndlib/src/aQute/bnd/metatype/DesignateReader.java
biz.aQute.bndlib/src/aQute/bnd/metatype/MetatypeAnnotations.java
biz.aQute.bndlib/src/aQute/bnd/metatype/OCDDef.java
biz.aQute.bndlib/src/aQute/bnd/metatype/OCDReader.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/xmlattribute/ExtensionDef.java
biz.aQute.bndlib/src/aQute/bnd/xmlattribute/XMLAttributeFinder.java

This at least seems to work on basic cases.

957 anno defaults

---

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib.tests/src/test/component/PermissionGeneratorTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/PermissionGenerator.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/FilterParser.java

So, I've started on an implementation that only parses the DS service definitions for now. Can you review if this is what you were expecting?
See discussion here: https://groups.google.com/forum/#!topic/bndtools-dev/Ra7GDT7x_4U

Issue 797: generating service permissions

---

biz.aQute.bndlib.tests/src/test/ResourcesTest.java

[windows] Disabled tests on windows that uses shell

---

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib.tests/src/test/component_extra/DSAnnotationExtrasTest.java
biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
biz.aQute.bndlib/src/aQute/bnd/component/MergedRequirement.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java

 	Add resolution;="optional" and cardinality:="multiple" directives based on reference cardinality

---

biz.aQute.bndlib.tests/src/test/FilterParserTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/FilterParser.java

Support bundle-version ranges in FilterParser

---

biz.aQute.jpm/src/aQute/jpm/lib/JustAnotherPackageManager.java
biz.aQute.jpm/src/aQute/jpm/lib/Service.java
biz.aQute.jpm/src/aQute/jpm/main/Main.java
biz.aQute.jpm/src/aQute/jpm/platform/Unix.java

[jpm] Improved service handling

---

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java

Fixes https://github.com/bndtools/bnd/issues/1003

ds annotations: Properly emit types for properties from byte/short types

---

.travis.yml
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/About.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
org.osgi.impl.bundle.repoindex.test/bnd.bnd

– value is now trimmed
– Empty string is now false
– If starting with !, will invert (can be repeated)

ifTrue extension (and About change)

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java

This reverts commit 4516d48ba3c9fa15be8cc6e3b6d662418713505b.

Revert "[plugins] Use biz.aQute.repository from latest build #970"

---

org.osgi.impl.bundle.repoindex.lib/src/org/osgi/service/indexer/impl/RepoIndex.java
org.osgi.impl.bundle.repoindex.lib/src/org/osgi/service/indexer/impl/util/Tag.java
org.osgi.impl.bundle.repoindex.lib/test/org/osgi/service/indexer/impl/BadAnalyzer.java
org.osgi.impl.bundle.repoindex.lib/test/org/osgi/service/indexer/impl/TestIndexer.java

Improve bindex error output when analyzers go wrong

---

org.osgi.impl.bundle.repoindex.lib/src/org/osgi/service/indexer/impl/BundleAnalyzer.java
org.osgi.impl.bundle.repoindex.lib/test/org/osgi/service/indexer/impl/TestIndexer.java
org.osgi.impl.bundle.repoindex.lib/testdata/fragment-01-relative.txt

Fix path relativization errors in the bindex BundleAnalyzer

---

bnd-maven-plugin/install-bndlib.sh
bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
bnd-maven-plugin/src/test/resources/integration-test/test/test-api-bundle/pom.xml
bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/bnd.bnd
bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/pom.xml
bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/src/main/java/org/example/impl/Config.java

Some minor fixes to bnd-maven-plugin.

Bnd maven plugin fixes

---

biz.aQute.bnd.test/src/aQute/bnd/test/BndTestCase.java
biz.aQute.bndlib.tests/src/test/BuilderTest.java
biz.aQute.bndlib.tests/src/test/component/BNDAnnotationTest.java
biz.aQute.bndlib.tests/src/test/component/ComponentTest.java
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib.tests/src/test/metatype/BNDMetatypeTest.java
biz.aQute.bndlib.tests/src/test/metatype/SpecMetatypeTest.java
biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
biz.aQute.bndlib/src/aQute/bnd/metatype/MetatypeAnnotations.java

Signed-off-by David Jencks <david_jencks@yahoo.com>

1041 default for -dsannotation and -metatypteannotation is *

---

biz.aQute.bndlib/src/aQute/bnd/osgi/OSInformation.java

Signed-off-by: Sean Bright <sean@malleable.com>

native_capability support for Windows 10

---

biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java
biz.aQute.bndlib/src/aQute/bnd/osgi/PreprocessResource.java

This is a very small patch but unfortunately the formatting was changed :-(

A command to show the capabilities (also visible in jar editor print tab)

---

.travis.yml
appveyor.yml

travis: Cache ~/.gradle
appveyor: invalidate cache if new gradlew version

ci: update yml

---

biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java

[resolve] Avoid NPE when there are no resolve requirements

---

aQute.libg/src/aQute/lib/persistentmap/PersistentMap.java
aQute.libg/src/aQute/libg/remote/sink/RemoteSink.java
aQute.libg/src/aQute/libg/remote/sink/SinkFS.java
aQute.libg/src/aQute/libg/remote/source/RemoteSource.java
aQute.libg/src/aQute/libg/remote/source/SourceFS.java
biz.aQute.bnd/src/aQute/bnd/ant/TestTask.java
biz.aQute.bnd/src/aQute/bnd/main/RepoCommand.java
biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bndlib/src/aQute/bnd/exporter/subsystem/SubsystemExporter.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapReqBuilder.java
biz.aQute.junit/src/aQute/junit/UnresolvedTester.java
biz.aQute.remote/src/aQute/remote/agent/AgentServer.java
biz.aQute.remote/src/aQute/remote/plugin/LauncherSupervisor.java
biz.aQute.remote/src/aQute/remote/plugin/RunSessionImpl.java
biz.aQute.repository/src/aQute/bnd/deployer/repository/providers/R5RepoContentProvider.java

[repo] Do not update repo when files have not changed

---

biz.aQute.bndlib.tests/src/test/JarTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/EmbeddedResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java

Added a writeFolder to Jar 
Also added start batch files for *nix and pc in the launcher

Write Folder function on JAR

---

biz.aQute.bndlib/src/aQute/bnd/build/Project.java

export: Collect info from launcher into project

---

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib.tests/src/test/component/PermissionGeneratorTest.java
biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java

Signed-off-by David Jencks <david_jencks@yahoo.com>

fixes #1064 validate service in related method signature

---

aQute.libg/src/aQute/lib/utf8properties/UTF8Properties.java
aQute.libg/test/aQute/lib/utf8properties/UTF8PropertiesTest.java

[utf 8 properties] did not store properties

---

biz.aQute.bndlib/src/aQute/bnd/build/Run.java

[workspace] NPE in creating Run

---

build.gradle

build: Log full exception for test failures

---

biz.aQute.bndlib/src/aQute/bnd/build/packageinfo

Bump package version aQute.bnd.build

---

biz.aQute.repository/bnd.bnd

Make biz.aQute.repository a fragment

---

biz.aQute.bndlib/src/aQute/bnd/build/Run.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
biz.aQute.resolve/JUNIT_biz.aQute.resolve.launch
biz.aQute.resolve/test/biz/aQute/resolve/StandaloneTest.java
biz.aQute.resolve/testdata/standalone/attribs.bndrun
biz.aQute.resolve/testdata/standalone/multi.bndrun
biz.aQute.resolve/testdata/standalone/relative_url.bndrun
biz.aQute.resolve/testdata/standalone/simple.bndrun

Fix for standalone workspace repos

---

appveyor.yml

[maven-plugins] Build maven plugins as part of the Appveyor build

---

biz.aQute.bndlib/src/aQute/bnd/build/Run.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java

Don't throw IllArgEx on missing -standalone

---

maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/non-transitive/pom.xml
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/pom.xml
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/transitive/pom.xml
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/verify.groovy

Testing for indexer plugin

---

maven/README.md
maven/bnd-indexer-maven-plugin/README.md

[maven-plugins] Add README information for the maven plugins

---

maven/bnd-indexer-maven-plugin/README.md
maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java
maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/LocalURLs.java
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/pom.xml
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/require-local/pom.xml
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/scoped/pom.xml
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/verify.groovy

[indexer-maven-plugin] Add a test for dependency scoping

---

aQute.libg/src/aQute/libg/uri/URIUtil.java
aQute.libg/test/aQute/libg/uri/URIUtilsTest.java
biz.aQute.bndlib/src/aQute/bnd/build/Run.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
biz.aQute.resolve/test/biz/aQute/resolve/StandaloneTest.java
biz.aQute.resolve/testdata/standalone/macro.bndrun

Fix macro expansion in -standalone

---

maven/.project
maven/README.md
maven/bnd-indexer-maven-plugin/pom.xml
maven/bnd-maven-plugin/pom.xml
maven/pom.xml

So maven generates a less silly prefix for the parent pom.

maven: rename parent pom

---

maven/.gitignore
maven/bnd-maven-plugin/install-bndlib.sh
maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/bnd.bnd
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/pom.xml
maven/bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy

Also add tests to validate properties in generated bundles.
Fixes https://github.com/bndtools/bnd/issues/1111

bnd-maven-plugin: Fix pom properties support and support settings props

---

biz.aQute.bndlib/src/aQute/bnd/build/model/clauses/HeaderClause.java

Quote name in HeaderClause formatter

---

biz.aQute.resolve/testdata/defltversions/run.bndrun

The test was including the patch

[resolve] Test against default versions now

---

biz.aQute.repository/bnd.bnd

Remove import of bindex from repo plugin

---

maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/verify.groovy

[indexer-maven-plugin] Ensure URLs are correctly assembled

---

maven/bnd-maven-plugin/src/test/resources/integration-test/test/pom.xml
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/bnd.bnd
maven/bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy

bnd-maven-plugin: Test we can access parent pom properties

---

aQute.libg/src/aQute/lib/json/JSONCodec.java
aQute.libg/test/aQute/lib/getopt/CommandTest.java
biz.aQute.bnd.test/src/aQute/bnd/test/XmlTester.java
biz.aQute.bndlib/src/aQute/bnd/annotation/headers/About.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java
biz.aQute.bndlib/src/aQute/bnd/url/BasicAuthentication.java
biz.aQute.bndlib/src/aQute/bnd/url/BndAuthentication.java
biz.aQute.repository/src/aQute/bnd/deployer/repository/AbstractIndexedRepo.java
biz.aQute.resolve/src/biz/aQute/resolve/AbstractResolveContext.java
biz.aQute.resolve/test/biz/aQute/resolve/BndrunResolveContextTest.java
biz.aQute.resolve/test/biz/aQute/resolve/ResolveTest.java
biz.aQute.resolve/test/biz/aQute/resolve/repository/JpmRepoTest.java

Fix a number of compiler warnings in the build.

Fix warnings

---

maven/bnd-baseline-maven-plugin/pom.xml
maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/Base.java
maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/settings.xml
maven/bnd-maven-plugin/src/test/resources/integration-test/settings.xml
maven/pom.xml

* Add simple baselining support
* Speed up the integration tests as per https://maven.apache.org/plugins/maven-invoker-plugin/examples/fast-use.html

Updates to maven plugins

---

biz.aQute.bndlib.tests/src/test/ManifestTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java

Fixes https://github.com/bndtools/bnd/issues/1156

manifest: Line length of 72 must include EOL bytes

---

biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bnd/test/aQute/bnd/main/TestBndMain.java
biz.aQute.bnd/testdata/standalone/standalone.bndrun

Fix #1153: bnd package command does not work with -standalone

---

biz.aQute.bndlib.tests/src/test/metatype/SpecMetatypeTest.java
biz.aQute.bndlib/src/aQute/bnd/metatype/OCDReader.java

This resolves issue #1130
Signed-off-by David Jencks <david_jencks@yahoo.com>

Make sure we really have an OCD before trying to output it.

---

biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java

A flatten command and removal of signatures in a JAR when it has changed

Added a flatten command to bnd

---

biz.aQute.bndlib.tests/src/test/MakefileTest.java
biz.aQute.bndlib/src/aQute/bnd/build/Makefile.java
biz.aQute.bndlib/src/aQute/bnd/build/Project.java

A -prepare command can specify shell commands to run before we build the JAR. Contains a little make facility to check if sources are out of date wrt to target.

[prepare] Added a prepare facility

---

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java

dsannotations: Fix to properly default reference cardinality on fields

---

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java

bndlib.tests: Add some more tests for DS Reference annotation

---

biz.aQute.repository/src/aQute/bnd/deployer/repository/LocalIndexedRepo.java

As discussed here https://github.com/bndtools/bnd/pull/1155

Allow the separator in LocalIndexedRepo to be '-' or '_'

---

biz.aQute.remote/test/biz/aQute/remote/LauncherTest.java
biz.aQute.remote/test/biz/aQute/remote/RemoteJMXTest.java

Signed-off-by: Gregory Amerson <gregory.amerson@liferay.com>

Updated launcher/remote test files

---

biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java

They were reported to the ProjectLauncher, and nobody ever checked.
This problem was mentioned in
https://github.com/bndtools/bnd/issues/1192#issuecomment-155892387

check: Report missing -runbundles to Project

---

maven/bnd-maven-plugin/pom.xml
maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
maven/pom.xml

Updated fix for #1180

---

biz.aQute.junit/build.gradle
biz.aQute.launcher/build.gradle
biz.aQute.tester/build.gradle

Fixes https://github.com/bndtools/bnd/issues/1163.

build: Generate maven metadata for launcher, junit, and tester

---

biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java

Signed-off-by David Jencks <david_jencks@yahoo.com>

Break out of loop when extended class is missing.

---

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java

fixes #1203
Fix assignable check by looking at superclass interfaces, and add more tests.
Signed-off-by: David Jencks <david_jencks@yahoo.com>

Fix service implementation checks.

---

biz.aQute.bndlib.tests/src/test/ContractTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Contracts.java

Made ranges into exact version

---

biz.aQute.bnd/src/aQute/bnd/ant/BndTask.java

signed-off-by Glenn Marcy <gmarcy@us.ibm.com>

ant: Add File.exists() checks for classpath elements

---

biz.aQute.bnd/test/aQute/bnd/main/TestBndMain.java
biz.aQute.bndlib.tests/src/test/AnalyzerTest.java
biz.aQute.bndlib.tests/src/test/ProjectTest.java
biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java

-bnd-require did not work for projects #1137

---

biz.aQute.bndlib.tests/src/aQute/bnd/osgi/AnalyzerTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java

Signed-off-by: David Jencks <david_jencks@yahoo.com>

Fix NPE when manifest has a single stray '@'

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy

Processor really wants a properties file. So we now
write the manifest properties and the specified bnd file into a temp
bnd file which we use to set the Builder's properties file.
We also clean up the sub builders check since we don't use the specified
bnd file as the Builder's properties file.

gradle: Use an actual bnd file for the non-workspace plugin

---

biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java

InetAddress.getLocalHost() may return ip's from wrong local interfaces,
use 'localhost' instead.

Fix: java.net.BindException: Can't assign requested address

---

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/bnd.bnd
maven/bnd-maven-plugin/src/test/resources/integration-test/test/other.bnd
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/bnd.bnd
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/other.bnd
maven/bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy

These commits harmonize behavior with the gradle plugin for non-workspace builds.
`-include` support is added as well as some common bnd properties.

Bnd maven plugin enhancements

---

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java

I used the wrong boolean operator.

bnd-maven: Fix subbundles check

---

biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java

Signed-off-by: David Jencks <david_jencks@yahoo.com>

Move 'assignable' methods to Analyzer for general use.

---

biz.aQute.bnd.gradle.tests/test/biz/aQute/bnd/gradle/TestBndPlugin.groovy
biz.aQute.bnd.gradle.tests/test/biz/aQute/bnd/gradle/TestBundlePlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndProperties.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy

Removed unnecessary `def`s and used `withCloseable`.

gradle: Clean up the groovy code

---

aQute.libg/src/aQute/lib/base64/Base64.java
aQute.libg/src/aQute/lib/base64/packageinfo
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java

Updates the base64 macro with length check

This takes over PR #1127

---

biz.aQute.junit/src/aQute/junit/JunitXmlReport.java

[junit] JUnit4 test reports contain the wrong test class name 

---

biz.aQute.bndlib.tests/src/test/ProcessorTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java

Resolves the specified uri against the specified base uri. The base uri
defaults to the Processor base.

Add new uri macro

---

aQute.libg/src/aQute/lib/properties/PropertiesParser.java

Deprecate old properties parser to ensure nobody uses it

---

biz.aQute.remote/src/aQute/remote/agent/AgentServer.java
biz.aQute.remote/src/aQute/remote/api/Agent.java
biz.aQute.remote/src/aQute/remote/api/packageinfo
biz.aQute.remote/test/biz/aQute/remote/AgentTest.java

I'd like to request this additional API in the remote Agent so that we can call the agent from some of our dev tools at Liferay, namely the Liferay IDE eclipse plugin.

[remote] added new agent methods for working with bundles

---

aQute.libg/src/aQute/lib/json/JSONCodec.java
aQute.libg/src/aQute/libg/uri/URIUtil.java
aQute.libg/src/aQute/service/reporter/Report.java
biz.aQute.bnd/src/aQute/bnd/main/BaselineCommands.java
biz.aQute.bndlib/src/aQute/bnd/annotation/headers/About.java
biz.aQute.bndlib/src/aQute/bnd/annotation/headers/BundleDevelopers.java
biz.aQute.bndlib/src/aQute/bnd/annotation/headers/BundleLicense.java
biz.aQute.bndlib/src/aQute/bnd/differ/DiffPluginImpl.java
biz.aQute.bndlib/src/aQute/bnd/maven/MavenDependencyGraph.java
biz.aQute.bndlib/src/aQute/bnd/osgi/About.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
biz.aQute.bndlib/src/aQute/bnd/properties/ITextStore.java
biz.aQute.bndlib/src/aQute/bnd/service/RemoteRepositoryPlugin.java
biz.aQute.bndlib/src/aQute/bnd/service/RepositoryPlugin.java
biz.aQute.bndlib/src/aQute/bnd/service/url/URLConnectionHandler.java
biz.aQute.bndlib/src/aQute/bnd/url/BasicAuthentication.java
biz.aQute.bndlib/src/aQute/bnd/url/BndAuthentication.java
biz.aQute.remote/src/aQute/remote/api/Agent.java
biz.aQute.repository/src/aQute/bnd/deployer/repository/AbstractIndexedRepo.java

Fix Javadoc Warnings

---

maven/README.md
maven/bnd-baseline-maven-plugin/README.md

[baseline-maven-plugin] Add documentation for the baseline maven plugin

---

.travis.yml
appveyor.yml
biz.aQute.bndlib.tests/src/aQute/bnd/build/defaults.bnd
biz.aQute.bndlib.tests/src/test/WorkspaceTest.java
biz.aQute.bndlib/src/aQute/bnd/build/defaults.bnd
maven/pom.xml

Instead of a fixed value (which was 1.5), we base the default off the running Java.

defaults: Change javac defaults to base on java.specification.version

---

biz.aQute.bnd.gradle.tests/testresources/builderplugin1/build.gradle
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy

Some minor improvments to the non-workspace gradle plugin

Gradle fixes

---

biz.aQute.bndlib.tests/src/test/MacroTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java

packages macro: Fix negation processing

---

biz.aQute.bndlib.tests/src/test/MavenTest.java
biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java
cnf/build.bnd

Update -pom processing and use SPDX license identifier in build

SPDX license

---

biz.aQute.resolve/src/biz/aQute/resolve/ProjectResolver.java
biz.aQute.resolve/src/biz/aQute/resolve/ResolverValidator.java
biz.aQute.resolve/test/biz/aQute/resolve/ResolveTest.java
biz.aQute.resolve/test/biz/aQute/resolve/repository/JpmRepoTest.java

resolver: Avoid resolver created and destroyed executor

---

biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java

Improvements to the support for default bundle content for workspace projects.

Default content updates

---

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientTest.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpRequest.java
biz.aQute.bndlib/src/aQute/bnd/service/url/TaggedData.java
biz.aQute.bndlib/src/aQute/bnd/url/HttpsVerification.java
biz.aQute.http.testservers/src/biz/aQute/http/testservers/Httpbin.java

[http] Fixed etag & modified + test cases

---

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java

This allows m2e to show the problems on the bnd file in Eclipse.

bnd-maven-plugin: log errors and warnings through BuildContext

---

biz.aQute.bnd.gradle.tests/test/aQute/bnd/gradle/TestBaselineTask.groovy
biz.aQute.bnd.gradle.tests/test/aQute/bnd/gradle/TestBndPlugin.groovy
biz.aQute.bnd.gradle.tests/test/aQute/bnd/gradle/TestBundlePlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java

A series of fixes for the gradle plugins mostly around logging.

Bnd gradle fixes

---

biz.aQute.bndlib.tests/src/test/MavenVersionTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/version/MavenVersion.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-wrapper-bundle/pom.xml
maven/bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy

Fixes https://github.com/bndtools/bnd/issues/1337

snapshot: Also support qualifier ending in "-SNAPSHOT"

---

biz.aQute.bndlib/src/aQute/bnd/osgi/About.java

Derived from `git shortlog --no-merges 3.1.0.REL.. -- biz.aQute.bndlib`.

bndlib: Add text to CHANGES_3_2

---

biz.aQute.bnd.gradle/README.md

[ci skip]
Closes https://github.com/bndtools/bnd/pull/1371

gradle: Update README to highlight workspace and non-workspace plugins

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
biz.aQute.bnd/bnd.bnd
biz.aQute.bndlib.tests/bnd.bnd
biz.aQute.bndlib/bnd.bnd
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.bndlib/src/aQute/bnd/osgi/repository/packageinfo
biz.aQute.launcher/bnd.bnd
biz.aQute.repository/bnd.bnd
biz.aQute.resolve/bnd.bnd
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/verify.groovy
org.osgi.impl.bundle.repoindex.test/bnd.bnd

Use slf4j for Processor.trace

---

biz.aQute.repository/build.gradle
biz.aQute.resolve/build.gradle

Fixes https://github.com/bndtools/bndtools/issues/1326

build: maven artifacts for biz.aQute.resolve and biz.aQute.repository

---

aQute.libg/src/aQute/lib/collections/SortedList.java
aQute.libg/src/aQute/lib/json/ObjectHandler.java
biz.aQute.bnd/src/aQute/bnd/main/BaselineCommands.java
biz.aQute.bndlib.tests/src/test/ProjectTest.java
biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java
biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceRepository.java
biz.aQute.bndlib/src/aQute/bnd/build/model/EE.java
biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
biz.aQute.bndlib/src/aQute/bnd/component/HeaderReader.java
biz.aQute.bndlib/src/aQute/bnd/differ/Element.java
biz.aQute.bndlib/src/aQute/bnd/make/metatype/MetaTypeReader.java
biz.aQute.bndlib/src/aQute/bnd/maven/MavenCommand.java
biz.aQute.bndlib/src/aQute/bnd/maven/MavenRepository.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Descriptors.java
biz.aQute.bndlib/src/aQute/bnd/osgi/repository/AggregateRepository.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/FilterParser.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/PersistentResource.java
biz.aQute.bndlib/src/aQute/bnd/url/HttpsVerification.java
biz.aQute.configadmin/src/biz/aQute/configadmin/StaticConfigurationAdmin.java
biz.aQute.launcher/src/aQute/launcher/SimplePermissionPolicy.java
biz.aQute.launcher/src/aQute/launcher/minifw/MiniFramework.java
biz.aQute.launcher/src/aQute/launcher/pre/EmbeddedLauncher.java
biz.aQute.remote/src/aQute/remote/main/EnvoyDispatcher.java
biz.aQute.repository/src/aQute/bnd/deployer/repository/AbstractIndexedRepo.java
biz.aQute.repository/test/aQute/bnd/deployer/repository/FindProvidersTest.java
maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java

Minor perf improvement.
See http://shipilev.net/blog/2016/arrays-wisdom-ancients/

coll.toArray(new T[coll.size()]) => coll.toArray(new T[0])

---

biz.aQute.repository.aether/src/aQute/bnd/deployer/repository/aether/AetherRepository.java

fixes the problem described here: https://groups.google.com/d/topic/bndtools-users/H2iRlTUDBPA/discussion

fix null artifact file uploading

---

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
biz.aQute.repository/test/aQute/bnd/repository/maven/provider/AgainstNexusTest.java
biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java

[maven] Make the default release type based on the set urls

---

biz.aQute.bnd.embedded-repo/bnd.bnd
biz.aQute.bndlib.tests/bnd.bnd
biz.aQute.bndlib.tests/src/test/ProcessorTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/Tool.java
biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java

A number of fixes in preparation for moving the build to use the new maven repo support.

Pre maven repos

---

build.gradle
gradle.properties
settings.gradle

Get gradle plugin from maven shaped repo

Maven repos - step 2

---

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/Tool.java
rebuild-with-local-plugin

Avoid long command line on windows

Use Javadoc options file

---

biz.aQute.launcher/src/aQute/launcher/Launcher.java

Replace with use of wiring API from Core 4.3 spec.
Closes https://github.com/bndtools/bnd/pull/1414

launcher: Avoid use of PackageAdmin

---

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/Tool.java
biz.aQute.repository/test/aQute/bnd/deployer/repository/TestFixedIndexedRepo.java
biz.aQute.repository/test/aQute/bnd/deployer/repository/TestLocalIndexGeneration.java
biz.aQute.repository/test/aQute/bnd/deployer/repository/TestLocalIndexedRepo.java
biz.aQute.repository/test/aQute/bnd/deployer/repository/TestLocalObrGeneration.java
biz.aQute.repository/test/aQute/bnd/deployer/repository/TestMultipleLocalIndexGeneration.java
biz.aQute.repository/test/aQute/bnd/deployer/repository/wrapper/TestWrapper.java
biz.aQute.repository/test/aQute/bnd/jpm/JPMTest.java
biz.aQute.repository/test/aQute/bnd/repository/maven/provider/AgainstNexusTest.java
biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
biz.aQute.repository/test/aQute/bnd/repository/maven/provider/WorkspaceTest.java
biz.aQute.repository/test/aQute/maven/provider/CentralTest.java
biz.aQute.repository/test/aQute/maven/provider/MavenRepoTest.java
biz.aQute.repository/test/aQute/maven/provider/NexusTest.java
biz.aQute.repository/test/aQute/maven/provider/RemoteRepoTest.java

There were several bugs in the support for specifying the javadoc and sources path in the `-maven-release` instruction.

Maven Repo release jars

---

biz.aQute.repository/src/aQute/bnd/jpm/StoredRevisionCache.java

Move to the http client created an NPE when file was not found

[resolve] NPE in wrapper

---

.travis.yml
appveyor.yml
maven/bnd.bnd
maven/build.gradle
maven/pom.xml

Change the CI build to encapsulate the maven command in a gradle task: `:maven:deploy`.

Maven build changes

---

org.osgi.impl.bundle.repoindex.lib/src/org/osgi/service/indexer/impl/RepoIndex.java
org.osgi.impl.bundle.repoindex.lib/src/org/osgi/service/indexer/impl/Schema.java

Fixes https://github.com/bndtools/bnd/issues/1444

repoindex: Add missing stylesheet support

---

biz.aQute.launcher/src/aQute/launcher/Launcher.java

Do not delete files that temporarily do not exist. Files that do not exist are treated as existent until they are installed or updated. So we no longer temporarily uninstall non-existent files.
Fixes Bndtools bug nr bndtools/bndtools#1267 

Don't update framework during build

---

biz.aQute.resolve/test/biz/aQute/resolve/ValidatorTest.java

ArrayIndexOutOfBoundException: -1 when Resolving #1439

---

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java

[http] Increased timeout to 1 min instead of 5 secs

---

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java

maven.repo.local system property must be consulted.

maven repo: Fix default local repo location

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java

Fixes https://github.com/bndtools/bnd/issues/1468

packageattribute: Return 0 for version attr if not present

---

biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java

add a method on ResourceUtil to detect fragments

add a method to check if resource is a fragment

---

biz.aQute.repository/bnd.bnd

missed configurable package

---

biz.aQute.jpm/src/aQute/jpm/platform/Windows.java

Signed-off-by: Andy Wu <andy.wu@liferay.com>

correct jvmargs writing into ini file on windows

---

biz.aQute.bndlib/src/aQute/bnd/build/LoggingProgressPlugin.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java

Signed-off-by: Gregory Amerson <gregory.amerson@liferay.com>

[progress] add LoggingProgressPlugin to all Workspace instances

---

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientTest.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
biz.aQute.repository/src/aQute/bnd/deployer/http/DefaultURLConnector.java
biz.aQute.repository/src/aQute/bnd/deployer/repository/ProgressWrappingStream.java

Signed-off-by: Gregory Amerson <gregory.amerson@liferay.com>

[progress] support multiple ProgressPlugins

---

biz.aQute.bndlib/src/aQute/bnd/build/LoggingProgressPlugin.java
biz.aQute.bndlib/src/aQute/bnd/http/ProgressWrappingStream.java

A couple of small fixes for the progress reporting

Progress fixes

---

biz.aQute.repository/bnd.bnd

[repository] Forgot the magic export attire.

---

biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java

This issue arose when using ${repo} macro in the -include instruction.
See https://github.com/bndtools/bnd/issues/1498#issuecomment-229313115 for a mention of using ${repo} in -include.

workspace: Detect project initialization recursion and short-circuit it

---

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java

For incremental builds, we store the manifest lastUpdated time in the
BuildContext and check it on subsequent incremental builds. This should
detect if some other part of maven replaces the manifest with an empty
default manifest.
Fixes https://github.com/bndtools/bnd/issues/1551

bnd-maven-plugin: Enhanced check for manifest file generation

---

biz.aQute.bndlib/src/aQute/bnd/osgi/ClassDataCollectors.java

Fixes https://github.com/bndtools/bnd/issues/1543

analyzer: Improve ClassDataCollectors to better report errors

---

biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java
biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiRepository.java

[osgi-indexed] Stale time not properly handled

---

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java

Fixes #1526
Signed-off-by: David Jencks (david_jencks@yahoo.com)

Deal with additional plausible ServiceReference property map types

---

biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java

Signed-off-by David Jencks (david_jencks@yahoo.com)

provide ds options for no capabilties and no requirements. Fixes #1364

---

biz.aQute.bndlib/src/aQute/bnd/build/Project.java

Fixes https://github.com/bndtools/bndtools/issues/1462

project: Use Strategy.LOWEST for -testpath

---

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/SettingsParserTest.java

Removed reference to httpbin.org

---

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
biz.aQute.bndlib/src/aQute/bnd/http/URLCache.java
biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java

If no ETAG is set, try to use ifModified

[httpclient] If ETAG was not send then we would always download again

---

biz.aQute.bndlib/src/aQute/bnd/http/URLCache.java
biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java
biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiRepository.java
biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java

[osgi repo] Repo could not be refreshed

---

biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiRepository.java

[osgirepo] Use proper cache dir

---

biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java

Use Workspace.getCache to get the cache folder to play nice with others
using cnf/cache. Don't extract META-INF folder.

embedded-repo: Improvements to extraction to file repo in cache

---

maven/bnd-indexer-maven-plugin/README.md
maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java
maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/LocalIndexerMojo.java
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/index-folder/pom.xml
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/pom.xml
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/rename-output/pom.xml
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/verify.groovy

* Allow the output file to be renamed
* Support indexing a local folder gathered by the maven dependency plugin

Some improvements for the bnd Indexer maven plugin

---

maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java

Signed-off-by: Christian Schneider <chris@die-schneider.net>

Fixes #1591 Allow configuration of failOnChanges

---

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomRepository.java

Bnd Pom Repo fix

---

biz.aQute.bndlib.tests/src/test/ResourceTest.java
biz.aQute.bndlib.tests/testresources/manifest/configadmin-1.8.8.mf
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomRepository.java

[pom repo] Check cache

---

biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java
biz.aQute.bndlib/src/aQute/bnd/make/Make.java
biz.aQute.bndlib/src/aQute/bnd/metatype/OCDReader.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.bndlib/src/aQute/bnd/signing/Signer.java
biz.aQute.bndlib/src/aQute/bnd/xmlattribute/XMLAttributeFinder.java

Clean up Processor.exception method and log debug any reported exceptions for visibility with `--debug` under gradle and mvn.

Processor.exception

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java

[macro] Lookup macro method without generating NoSuchMethodException's

---

biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java

We now avoid waiting for each promise to resolve in some order. The
promises can resolve in any order. The method will return upon the first
failed promise or when all promises have resolved.

osgirepo: Improve use of Promises in isStale

---

biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java

[build] Cleaned up use of buildDir

---

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java
biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java

[pomrepo] Read the top level pom in the http client

---

biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java

[workspace] Create and check default workspace

---

biz.aQute.bndlib.tests/src/test/BuilderTest.java
biz.aQute.bndlib/src/aQute/bnd/build/Container.java
biz.aQute.bndlib/src/aQute/bnd/build/DownloadBlocker.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/RepoActions.java
biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java
biz.aQute.repository/src/aQute/maven/provider/POM.java
demo-fragment/.gitignore

A collection of small fixes while reviewing repo code for promise improvements.

Repo fixes

---

biz.aQute.bndlib/src/aQute/bnd/build/Container.java
biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java

Use a more unique file name for deferred downloads in BndPomRepository. This allows Containers to be unique.

False container duplicates

---

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java

Use a ThreadLocal for the not-threadsafe DateFormat

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java

Replace 'Duh?' with slightly more meaningful trace output

---

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java

We record the marked files and clear their markers on the next build.

bnd-maven-plugin: Remove markers from previous build

---

biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java

Also load -runblacklist from repository augments

---

biz.aQute.repository/src/aQute/maven/provider/MavenBackingRepository.java

Allow some messed up shit in the digest string from the remote

---

biz.aQute.bndlib.tests/src/test/resource/CapReqFilterTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java

A Requirement without a filter always matches.

---

biz.aQute.bndlib/src/aQute/bnd/osgi/repository/BridgeRepository.java
biz.aQute.bndlib/src/aQute/bnd/version/MavenVersion.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java
biz.aQute.repository/src/aQute/maven/api/IPom.java
biz.aQute.repository/testdata/pomrepo/entity.xml

[pom] A few fixes when the pom fails to download

---

biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java

maven repo: Handle local only repo for non-snapshot release

---

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java

The file move fails on Windows because multiple threads are contending
for the index file. Use a read/write lock to manage the contention.

maven repo: Use read/write lock to avoid contention on Windows

---

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java

[maven] Don't poll in batch mode

---

biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapReq.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceImpl.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java

Require certain arguments to be non-null; create unmodifiable objects
earlier.

resource: Tighten up impls

---

README.md

Update README.md with YourKit acknowledgement

---

docs/_plugins/maven.md
docs/_plugins/pomrepo.md

[docs] Update maven repo + adding Bnd Pom Repository

---

docs/_plugins/pomrepo.md

[docs] Configurations got formatted badly

---

biz.aQute.bnd.gradle/README.md
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBndPlugin.groovy
biz.aQute.bnd.gradle/testresources/workspaceplugin1/cnf/ext/repositories.bnd
biz.aQute.bnd.gradle/testresources/workspaceplugin1/cnf/repo/index.xml
biz.aQute.bnd.gradle/testresources/workspaceplugin1/test.simple/bnd.bnd
biz.aQute.bnd.gradle/testresources/workspaceplugin1/test.simple/resolve.bndrun
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceUtils.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/packageinfo
biz.aQute.resolve/src/biz/aQute/resolve/WorkspaceResourcesRepository.java

Also add a test case for resolve.* and update the readme for the new tasks.

gradle: Update implementation of new resolve.* and run.* tasks

---

maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java

https://github.com/bndtools/bnd/issues/1726

Fixes issue 1726 which changes the version when installing a SNAPSHOT

---

maven/bnd-testing-maven-plugin/.settings/org.eclipse.core.resources.prefs
maven/bnd-testing-maven-plugin/README.md
maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java
maven/pom.xml

[maven-testing] Added options for one or globbing of testing

---

.travis.yml
appveyor.yml
biz.aQute.resolve/src/biz/aQute/resolve/ResolveProcess.java
maven/build.gradle

Also update travis and appveyor builds. This should help stop the travis timeouts.

augment: Use all found unresolved requirements at timeout

---

maven/bnd-maven-plugin/README.md

Clarify how to configure goal execution

---

biz.aQute.bndlib.tests/src/test/ClazzTest.java
biz.aQute.bndlib.tests/src/test/component/DSAnnotationTest.java
biz.aQute.bndlib.tests/src/test/metatype/SpecMetatypeTest.java
biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java
biz.aQute.bndlib/src/aQute/bnd/component/ComponentDef.java
biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
biz.aQute.bndlib/src/aQute/bnd/component/HeaderReader.java
biz.aQute.bndlib/src/aQute/bnd/metatype/MetatypeAnnotations.java
biz.aQute.bndlib/src/aQute/bnd/metatype/MetatypeVersion.java
biz.aQute.bndlib/src/aQute/bnd/metatype/OCDDef.java
biz.aQute.bndlib/src/aQute/bnd/metatype/OCDReader.java

Signed-off-by: David Jencks (david_jencks@yahoo.com)

Implement version option for ds and metatype. Closes #1728

---

biz.aQute.bndlib.tests/src/aQute/bnd/osgi/repository/data/macbadge.xml
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java

The mime type was partially incorrect.

resource: Correct mime type for bundles

---

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java

Fixes https://github.com/bndtools/bnd/issues/1765

maven index: Fix NPE when promise holds null value

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
cnf/build.bnd

If the workspace properties or the project properties change, the jar should be rebuilt.
Also, add tag to Bundle-SCM header.

gradle: workspace and project bnd files are jar task inputs

---

build.gradle
docs/_plugins/maven.md

Misc fixes

---

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-api-bundle/pom.xml

support execution level configuration

---

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-api-bundle/pom.xml

Revert "support execution level configuration"

---

maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java
maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java
maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java
maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/LocalIndexerMojo.java
maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/pom.xml
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-wrapper-bundle/pom.xml
maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java

Also clean up some @Parameter declarations.

maven: Support configuration from executions

---

biz.aQute.bndlib.tests/src/test/ClassParserTest.java
biz.aQute.bndlib.tests/src/test/stackmaptable/ClassRefInStackMapTable.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java

Also some cleanups to Clazz before the fix.

clazz: Process StackMapTable attributes for class references

---

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java

Fixes https://github.com/bndtools/bnd/issues/1784

maven: Add unused parameters for documentary purposes

---

biz.aQute.repository/src/aQute/maven/api/IPom.java
biz.aQute.repository/src/aQute/maven/provider/POM.java
biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java

Closes https://github.com/bndtools/bnd/pull/1799

pom: Capture parsed classifier and extension information

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java

The plugins Set can now be safely iterated over.
Fixes https://github.com/bndtools/bndtools/issues/1610

processor: Fix concurrency issue with plugins Set

---

.gitignore

Ignore the .recommenders directory

---

biz.aQute.bndlib.tests/src/test/AnalyzerTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java

Extra checks for Bundle-Activator in the Verifier

---

maven/bnd-testing-maven-plugin/.settings/org.eclipse.core.resources.prefs
maven/bnd-testing-maven-plugin/pom.xml
maven/bnd-testing-maven-plugin/src/test/resources/integration-test/settings.xml
maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/pom.xml
maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/test-no-resolve/bnd.bnd
maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/test-no-resolve/pom.xml
maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/test-no-resolve/src/main/java/bnd/test/SimpleBndTest.java
maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/test-no-resolve/test.bndrun
maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/test-with-resolve/bnd.bnd
maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/test-with-resolve/pom.xml
maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/test-with-resolve/src/main/java/bnd/test/ResolvingBndTest.java
maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/test-with-resolve/test.bndrun
maven/bnd-testing-maven-plugin/src/test/resources/integration-test/test/verify.groovy

Add tests for the bnd-testing-maven-plugin

---

maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java

Make baseline detail reporting more fine-grained

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Baseline.groovy

Add similar detail as was done in
https://github.com/bndtools/bnd/pull/1857.

baseline: Add more detail to gradle baseline task report

---

biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Repository.java

Fixes https://github.com/bndtools/bnd/issues/1863

p2repo: Add toString so the repo has a name

---

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java

Fixes https://github.com/bndtools/bnd/issues/1849

traverser: Handle pom not being found

---

biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java

ds annotations: Only emit extender requirement if a component processed

---

README.md

Fixes https://github.com/bndtools/bnd/issues/1871

readme: link mail lists to the google groups

---

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java

Fixes https://github.com/bndtools/bnd/issues/1808

maven: bnd-maven-plugin does not support -wab or -wablib

---

biz.aQute.bnd/src/aQute/bnd/main/Plugins.java
biz.aQute.bnd/src/aQute/bnd/main/Profiles.java
biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bndlib.tests/src/test/ProjectTest.java
biz.aQute.bndlib/src/aQute/bnd/build/Container.java
biz.aQute.bndlib/src/aQute/bnd/build/Makefile.java
biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java
biz.aQute.bndlib/src/aQute/bnd/header/OSGiHeader.java
biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java
biz.aQute.remote/src/aQute/remote/plugin/RemoteProjectLauncherPlugin.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
biz.aQute.resolve/src/biz/aQute/resolve/BndrunResolveContext.java
biz.aQute.resolve/src/biz/aQute/resolve/ProjectResolver.java

See https://github.com/bndtools/bnd/issues/1864

parameters: Pass a reporter to the parsing logic to report parse issues

---

aQute.libg/src/aQute/lib/io/IO.java
aQute.libg/src/aQute/lib/io/packageinfo
aQute.libg/test/aQute/lib/io/IOTest.java
biz.aQute.bndlib/src/aQute/bnd/util/repository/DownloadListenerPromise.java
biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java

Closes https://github.com/bndtools/bnd/pull/1835
Fixes https://github.com/bndtools/bnd/issues/1834

Don't create symlinks on Windows

---

biz.aQute.bndlib/src/aQute/bnd/osgi/resource/FilterParser.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/RequirementImpl.java

Fixes https://github.com/bndtools/bnd/issues/1892

resource: Better message when parsing invalid filter expression

---

biz.aQute.bndlib/src/aQute/bnd/build/Project.java
docs/_instructions/releaserepo.md

-releaserepo is now a merged property and you can specify multiple
repository names to release into.
Completes the work started in https://github.com/bndtools/bnd/issues/1110

release: Support releasing to multiple repos on -releaserepo

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
biz.aQute.resolve/bnd.bnd
cnf/ext/central.mvn

Also update felix resolver to 1.12.0.

Prepare for Gradle 3.4

---

biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java

Fixes https://github.com/bndtools/bnd/issues/326

launcher: Call cleanup() for export task

---

biz.aQute.launcher/README
biz.aQute.launcher/src/aQute/launcher/Launcher.java

Fixes https://github.com/bndtools/bnd/issues/1919

launcher: Run on compact1 without java.lang.instrument

---

biz.aQute.bnd/src/aQute/bnd/ant/WrapTask.java
biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bndlib.tests/src/test/AnalyzerTest.java
biz.aQute.bndlib.tests/src/test/JarSignerTest.java
biz.aQute.bndlib.tests/src/test/MacroTest.java
biz.aQute.bndlib/src/aQute/bnd/differ/DiffPluginImpl.java
biz.aQute.bndlib/src/aQute/bnd/make/MakeBnd.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java

A series of fixes related to the Analyzer including processing conditional packages before calling plugins and processing header annotations.

Analyzer fixes

---

biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
biz.aQute.bndlib/src/aQute/bnd/build/model/OSGI_CORE.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
biz.aQute.bndlib/src/aQute/lib/spring/SpringComponent.java
biz.aQute.repository/src/aQute/bnd/deployer/repository/CachingUriResourceHandle.java
biz.aQute.repository/src/aQute/bnd/jpm/Repository.java

Refactoring classes to handle autoclosable inside try with resources block.
Fixes https://github.com/bndtools/bnd/issues/1929
Signed-off-by: Bartlomiej Sulich <bartlomiej.sulich@intel.com>

Streams are not properly closed

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
demo/bnd.bnd

Also some fixes to the gradle plugin to avoid Gradle 3.2 API dependency.

Fix jenkins

---

biz.aQute.bndlib/src/aQute/bnd/differ/Baseline.java
biz.aQute.bndlib/src/aQute/bnd/differ/DiffPluginImpl.java

Fixes https://github.com/bndtools/bnd/issues/1488

baseline: Properly handle empty directories in newly built jars

---

biz.aQute.jpm/bnd.bnd
biz.aQute.jpm/run.bnd
docs/_chapters/300-launching.md

[jpm] Slf4j was not included so at startup it failed

---

maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java
maven/bnd-resolver-maven-plugin/src/main/java/aQute/bnd/maven/resolver/plugin/ResolverMojo.java
maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java

A series of fixes to the maven plugins based upon lessons learned in writing the new gradle task types to mirror the function in these maven plugins.

Maven plugin fixes

---

biz.aQute.bndlib.tests/src/test/metatype/SpecMetatypeTest.java
biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java
biz.aQute.bndlib/src/aQute/bnd/metatype/OCDReader.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Descriptors.java

Also some fixes for PREFIX_ support.

Support $ for pid/factoryPid in Metatype ObjectClassDefinition annotation

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy
biz.aQute.bndlib/src/aQute/bnd/build/Project.java
gradle.properties

A series of fixed to the workspace build gradle plugin.

Gradle workspace build plugin fixes

---

biz.aQute.remote/src/aQute/remote/util/AgentSupervisor.java
biz.aQute.remote/test/biz/aQute/remote/AgentTest.java

Signed-off-by: Andy Wu <andy.wu@liferay.com>

throw exception when timeout

---

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
biz.aQute.bndlib/src/aQute/bnd/http/URLCache.java

Some minor fixes to HttpClient code.

HttpClient fixes

---

aQute.libg/src/aQute/lib/io/IO.java
aQute.libg/src/aQute/lib/utf8properties/UTF8Properties.java
aQute.libg/test/aQute/lib/io/IOTest.java
biz.aQute.bndlib/src/aQute/bnd/maven/support/MavenEntry.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.bndlib/src/aQute/bnd/plugin/eclipse/EclipsePlugin.java
biz.aQute.bndlib/src/aQute/bnd/plugin/maven/MavenPlugin.java
biz.aQute.bndlib/src/aQute/lib/spring/SpringComponent.java
biz.aQute.bndlib/src/aQute/lib/spring/XMLType.java
biz.aQute.http.testservers/src/aQute/http/testservers/HttpTestServer.java
biz.aQute.repository/src/aQute/bnd/deployer/repository/CachingUriResourceHandle.java
biz.aQute.repository/src/aQute/bnd/deployer/repository/providers/KnownBundleAnalyzerPlugin.java

And some other changes to make sure the better IO methods are used.

io: Update IO to exploit FileChannel for file operations

---

aQute.libg/src/aQute/lib/io/IO.java
aQute.libg/test/aQute/lib/io/IOTest.java

Forgot to handle offset when ByteBuffer has an array. Also capped the
size of the copy-through array when the ByteBuffer does not have an
array.

io: copy to ByteBuffer fixes

---

aQute.libg/src/aQute/lib/io/ByteBufferDataInput.java
aQute.libg/src/aQute/lib/io/ByteBufferInputStream.java
aQute.libg/src/aQute/lib/io/CharBufferReader.java
aQute.libg/src/aQute/lib/io/IO.java
aQute.libg/src/aQute/lib/io/NonClosingInputStream.java
biz.aQute.bndlib.tests/src/test/CalltreeTest.java
biz.aQute.bndlib/bnd.bnd
biz.aQute.bndlib/src/aQute/bnd/make/metatype/MetaTypeReader.java
biz.aQute.bndlib/src/aQute/bnd/maven/MavenCommand.java
biz.aQute.bndlib/src/aQute/bnd/osgi/AbstractResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
biz.aQute.bndlib/src/aQute/bnd/osgi/EmbeddedResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/FileResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
biz.aQute.bndlib/src/aQute/bnd/osgi/PreprocessResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Resource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/URLResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/WriteResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/ZipResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/packageinfo
biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java

We add ByteBuffers to Resources.

clazz: Use ByteBuffer to parse class files

---

biz.aQute.remote/src/aQute/remote/main/Envoy.java
biz.aQute.remote/src/aQute/remote/main/EnvoyDispatcher.java

[remote] Implement ping on envoy level

---

biz.aQute.launcher/src/aQute/launcher/pre/EmbeddedLauncher.java
biz.aQute.launcher/src/aQute/launcher/pre/JpmLauncher.java

Fixes https://github.com/osgi/osgi.enroute.examples.eval/issues/3

launcher: Avoid reference to IO class in embedded launchers

---

biz.aQute.bndlib/src/aQute/bnd/version/Version.java
biz.aQute.repository/src/aQute/bnd/repository/p2/provider/ArtifactID.java
biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java
biz.aQute.repository/src/aQute/p2/api/Artifact.java
biz.aQute.repository/src/aQute/p2/api/package-info.java
biz.aQute.repository/src/aQute/p2/provider/ArtifactRepository.java
biz.aQute.repository/src/aQute/p2/provider/XML.java

Fix for #2027, this knocks huge amounts of time off certain builds. Tens of minutes easily on an old HDD.

#2027 p2 indexing fix

---

biz.aQute.junit/src/aQute/junit/Activator.java

If the test bundle is a fragment then its host is
used for class loading.

[testing] Fragment testing #1970

---

aQute.libg/src/aQute/lib/utf8properties/PropertiesParser.java
aQute.libg/test/aQute/lib/utf8properties/UTF8PropertiesTest.java

Handles escaped quotes and only checks headers starting with '-'

Handle escaped quotes (or anything)

---

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
biz.aQute.repository/src/aQute/maven/api/Release.java
biz.aQute.repository/src/aQute/maven/provider/MetadataParser.java
biz.aQute.repository/src/aQute/maven/provider/Releaser.java
biz.aQute.repository/src/aQute/maven/provider/SnapshotReleaser.java
biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
biz.aQute.repository/test/aQute/maven/provider/MavenRepoTest.java

[maven] Build number in snapshot release is now increasing

---

biz.aQute.bndlib.tests/src/test/MavenVersionTest.java
biz.aQute.bndlib/src/aQute/bnd/version/MavenVersion.java
biz.aQute.bndlib/src/aQute/bnd/version/MavenVersionRange.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java
biz.aQute.repository/src/aQute/maven/api/IPom.java
biz.aQute.repository/src/aQute/maven/api/Revision.java
biz.aQute.repository/src/aQute/maven/provider/POM.java
biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java

[maven] Added support for version ranges in dependency parsing

---

biz.aQute.bnd/src/aQute/bnd/main/ResolveCommand.java
biz.aQute.bndlib/src/aQute/bnd/build/model/clauses/HeaderClause.java
biz.aQute.resolve/src/biz/aQute/resolve/Bndrun.java
maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java
maven/bnd-testing-maven-plugin/src/main/java/aQute/bnd/maven/testing/plugin/TestingMojo.java

This option writes runbundles back to the specified file, e.g.:
$ bnd resolve resolve --write foo.bndrun

Add --write option to 'bnd resolve' command

---

biz.aQute.bnd.gradle/build.gradle
biz.aQute.bnd/src/aQute/bnd/main/ResolveCommand.java

Remove unnecessary Run object and properly close the Bndrun object. Also
correctly capture any resolve exception so it does not fail the bnd
command.

bnd: Improve resolve command

---

biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/Run.java

Fixes https://github.com/bndtools/bndtools/issues/1707

run: Use bndrun file name as project name

---

aQute.libg/src/aQute/libg/classdump/ClassDumper.java
aQute.libg/test/aQute/lib/converter/ConverterTest.java
biz.aQute.launcher/src/aQute/launcher/Launcher.java
biz.aQute.launcher/src/aQute/launcher/minifw/MiniFramework.java
build.gradle

Some changes found when testing with java 9.

Build fixes

---

biz.aQute.bndlib/src/aQute/bnd/signing/JartoolSigner.java

[JartoolSigner] Add support for Time Stamping Authority (TSA)

---

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomConfiguration.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/SearchRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/package-info.java
biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java

Allows a transitive false|true option for a BndPomRepository

---

biz.aQute.bndlib.tests/src/test/NativeCodeHeaderTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java

Fix #2080: incorrect osgi.native req. from Bundle-NativeCode

---

.travis.yml
biz.aQute.bnd/src/aQute/bnd/main/BaselineCommands.java
biz.aQute.bnd/src/aQute/bnd/main/DiffCommand.java
biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bndlib.tests/src/test/LocationTest.java
biz.aQute.bndlib.tests/src/test/ProjectTest.java
biz.aQute.bndlib.tests/src/test/TestSelfBuild.java
biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
biz.aQute.bndlib/src/aQute/bnd/build/WorkspaceRepository.java
biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java
biz.aQute.bndlib/src/aQute/bnd/compatibility/ParseSignatureBuilder.java
biz.aQute.bndlib/src/aQute/bnd/differ/DiffPluginImpl.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpRequestException.java
biz.aQute.bndlib/src/aQute/bnd/make/component/ComponentAnnotationReader.java
biz.aQute.bndlib/src/aQute/bnd/maven/MavenCommand.java
biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/CommandResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
biz.aQute.bndlib/src/aQute/bnd/plugin/eclipse/EclipsePlugin.java
biz.aQute.bndlib/src/aQute/bnd/plugin/maven/MavenPlugin.java
biz.aQute.bndlib/src/aQute/bnd/signing/Signer.java
biz.aQute.bndlib/src/aQute/bnd/testing/DSTestWiring.java
biz.aQute.bndlib/src/aQute/bnd/url/BndAuthentication.java

Replaces and closes https://github.com/bndtools/bnd/pull/2090.
This includes the commit from 2090.

Close builders that were created but not closed

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java

Analyzer: Sort private references for consistent error messages

---

biz.aQute.bndlib/src/aQute/bnd/maven/MavenRepository.java
biz.aQute.bndlib/src/aQute/bnd/maven/support/Maven.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java

Couple of minor fixes to the maven support in bnd.

Maven repo fixes

---

docs/_instructions/javaagent.md

See https://github.com/bndtools/bndtools/issues/1434 where a user was confused by the documentation.

docs: Fix documentation for -javaagent instruction

---

biz.aQute.bnd.diagnostics.gogo/.classpath
biz.aQute.bnd.diagnostics.gogo/.gitignore
biz.aQute.bnd.diagnostics.gogo/.project
biz.aQute.bnd.diagnostics.gogo/.settings/org.eclipse.core.resources.prefs
biz.aQute.bnd.diagnostics.gogo/.settings/org.eclipse.jdt.core.prefs
biz.aQute.bnd.diagnostics.gogo/bnd.bnd
biz.aQute.bnd.diagnostics.gogo/run.bndrun
biz.aQute.bnd.diagnostics.gogo/src/biz/aQute/bnd/diagnostics/gogo/impl/Diagnostics.java
biz.aQute.bnd.diagnostics.gogo/src/biz/aQute/bnd/diagnostics/gogo/impl/Export.java
biz.aQute.bnd.diagnostics.gogo/src/biz/aQute/bnd/diagnostics/gogo/impl/FilterListener.java
biz.aQute.bnd.diagnostics.gogo/src/biz/aQute/bnd/diagnostics/gogo/impl/Search.java
biz.aQute.bnd.diagnostics.gogo/src/biz/aQute/bnd/diagnostics/gogo/osgi/Activator.java
biz.aQute.bnd.diagnostics.gogo/test/biz/aQute/bnd/diagnostics/gogo/DiagnosticsTest.java
biz.aQute.bnd.diagnostics.gogo/test/biz/aQute/bnd/diagnostics/gogo/foo/Foo.java

[gogo] A diagnostics bundle

---

biz.aQute.remote/src/aQute/remote/plugin/RunRemoteDTO.java
biz.aQute.remote/src/aQute/remote/plugin/RunSessionImpl.java

isReachable does not always work

[remote] Ignore reachable check settable

---

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java

Eclipse download site is returning 307 redirection code and we don't
seem to handle it properly.

http: Handle HTTP/1.1 redirection codes 307 and 308

---

biz.aQute.bndlib/src/aQute/bnd/build/LoggingProgressPlugin.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java

This will be useful debugging download issues.

http: Enable additional debug messages

---

biz.aQute.bndlib/src/aQute/bnd/junit/package-info.java

Just switched to 3.5 as baseline

[junit] Baseline error

---

demo/bnd.bnd

[demo] Use more modern framework

---

biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
cnf/build.bnd

And some fixes to make this work in the build.

java9: Add Automatic-Module-Name manifest header to bnd jars

---

biz.aQute.bnd/test/aQute/bnd/main/DistroCommandTest.java
biz.aQute.resolve/bnd.bnd
biz.aQute.resolve/src/biz/aQute/resolve/DebugReporter.java
biz.aQute.resolve/src/biz/aQute/resolve/ResolverLogger.java
biz.aQute.resolve/src/biz/aQute/resolve/packageinfo
biz.aQute.resolve/test/biz/aQute/resolve/BndrunResolveContextTest.java
biz.aQute.resolve/test/biz/aQute/resolve/GenericResolveContextResolveTest.java
biz.aQute.resolve/test/biz/aQute/resolve/ResolveProcessTest.java
biz.aQute.resolve/test/biz/aQute/resolve/ResolveTest.java
biz.aQute.resolve/test/biz/aQute/resolve/ResolverLoggerTest.java

To properly close tmp file. Also reduce object creation.

resolve: Change ResolveLogger to AutoClosable and remove finalize

---

biz.aQute.remote/src/aQute/remote/agent/Activator.java

[remote] Message at end killed test

---

aQute.libg/src/aQute/lib/promise/PromiseExecutor.java
aQute.libg/src/aQute/lib/promise/packageinfo
biz.aQute.bnd/bnd.bnd
biz.aQute.bndall.tests/bnd.bnd
biz.aQute.bndlib.tests/bnd.bnd
biz.aQute.bndlib/bnd.bnd
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpRequest.java
biz.aQute.bndlib/src/aQute/bnd/http/package-info.java
biz.aQute.bndlib/src/aQute/bnd/osgi/repository/BaseRepository.java
biz.aQute.repository/src/aQute/bnd/repository/fileset/FileSetRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/SearchRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java
biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java
biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java
biz.aQute.repository/src/aQute/p2/provider/P2Impl.java
biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java
biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiIndexTest.java
biz.aQute.repository/test/aQute/maven/provider/CentralTest.java
biz.aQute.repository/test/aQute/maven/provider/MavenRepoTest.java

Refactor code using Promises in preparation for using Promises 1.1 with the existing Bnd executor.

Promise refactor

---

biz.aQute.bndlib.tests/src/test/annotationheaders/StdAnnotationHeadersTest.java
biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/AnnotatedAnnotation.java
biz.aQute.bndlib.tests/src/test/annotationheaders/multiple/std/PetstoreAppComponent.java
biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java

Capability annotation versions should be of type Version not String

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndWorkspacePlugin.groovy
biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/packageinfo
dist/build.gradle
maven/build.gradle

Calculate project dependents and then use that for the gradle buildDependents target.

Project dependents

---

aQute.libg/src/aQute/lib/promise/PromiseExecutor.java
biz.aQute.bndlib/src/aQute/bnd/make/component/ServiceComponent.java

Minor fixes

---

aQute.libg/src/aQute/lib/promise/PromiseExecutor.java
biz.aQute.bndlib/src/aQute/bnd/osgi/repository/ResourcesRepository.java
biz.aQute.repository/src/aQute/bnd/repository/fileset/FileSetRepository.java
biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java
biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java
biz.aQute.resolve/src/biz/aQute/resolve/WorkspaceResourcesRepository.java
cnf/ext/osgi-snapshots.mvn

Being using the new Promise 1.1 APIs. They provide many useful features. Perhaps the most useful is allowing functions to throw Exception which enables use of more simple lambda expressions.
Also using Streams with Promises to greatly simplify some method implementations. There is a Collector to collect a stream of Promise<T> into a Promise<List<T>> using Promises.all.

Turn it up to 11

---

aQute.libg/src/aQute/lib/promise/PromiseExecutor.java
biz.aQute.repository/src/aQute/bnd/repository/fileset/FileSetRepository.java
biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java

Fixes https://github.com/bndtools/bnd/issues/2200

promise: Minor adjustments to promises from OSGi

---

biz.aQute.bndlib.tests/src/test/resource/CapReqBuilderTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/CapReqBuilder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/packageinfo

Signed-off-by: Neil Bartlett <neil.bartlett@ocado.com>

Expose CapReqBuilder.unalias() for Bndtools

---

aQute.libg/src/aQute/lib/promise/PromiseCollectors.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpRequest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/repository/BaseRepository.java
biz.aQute.launcher/bnd.bnd
biz.aQute.repository/src/aQute/bnd/repository/fileset/FileSetRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/SearchRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/Traverser.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java
biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java
biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java
biz.aQute.repository/src/aQute/p2/provider/P2Impl.java
biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java
biz.aQute.repository/test/aQute/maven/provider/CentralTest.java
biz.aQute.repository/test/aQute/maven/provider/MavenRepoTest.java

PromiseExecutor to be removed in a future commit.

promise: Refactor to use PromiseFactory

---

biz.aQute.bndlib.tests/src/test/annotationheaders/StdAnnotationHeadersTest.java
biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/IndirectlyAnnotatedAnnotation.java
biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/UsingIndirectlyAnnotatedAnnotation.java
biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java

Correctly handle meta-annotated requirements - Fixes #2212

---

maven/bnd-indexer-maven-plugin/README.md
maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java

Sometimes we don't want to publish a Maven generated index

[indexer] Add a flag to disable publishing the index

---

biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java

Avoid issuing loadability warnings for *safe* annotations

---

maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/LocalIndexerMojo.java

Fixes https://github.com/bndtools/bnd/issues/2209

indexer-maven: Check that inputDir is a directory

---

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/InnerRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomConfiguration.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/PomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/package-info.java
biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java
biz.aQute.repository/testdata/pomrepo/simple.xml

Adding polling support to BndPomRepository when is it used in Eclipse under Bndtools.
This is a refactor and improvement of the work in #2114.
Fixes https://github.com/bndtools/bnd/issues/2113
Closes https://github.com/bndtools/bnd/pull/2114

BndPomRepository polling for changes

---

biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java

Only warn about missing annotations when pedantic

---

maven/bnd-export-maven-plugin/README.md
maven/bnd-export-maven-plugin/src/main/java/aQute/bnd/maven/export/plugin/ExportMojo.java

[export] Attach the generated runnable jar

---

biz.aQute.repository/src/aQute/bnd/repository/maven/pom/provider/BndPomRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/Configuration.java
biz.aQute.repository/test/aQute/bnd/repository/maven/pom/provider/PomRepositoryTest.java
docs/_plugins/maven.md

And a few small, other changes.

Fix doc for MavenBndRepository snapshotUrl parameter

---

maven/bnd-indexer-maven-plugin/README.md
maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/IndexerMojo.java
maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/LocalIndexerMojo.java
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/verify.groovy

[indexer] Support setting the repository index name

---

biz.aQute.bndlib.tests/src/test/ExportAnnotationTest.java
biz.aQute.bndlib.tests/src/test/ParseHeaderTest.java
biz.aQute.bndlib.tests/src/test/export/annotation/testCalculated/package-info.java
biz.aQute.bndlib/src/aQute/bnd/header/Attrs.java
biz.aQute.bndlib/src/aQute/bnd/header/packageinfo
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java

Also make sure types are included when printing clauses from Attrs. The
Attrs implementation is also cleaned up.

attrs: Properly copy entry types when combining Attrs

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndBuilderPlugin.groovy

Fixes https://github.com/bndtools/bnd/issues/2253

gradle: Only set bndfile property for jar task is bnd.bnd file exists

---

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientTest.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
biz.aQute.http.testservers/src/aQute/http/testservers/Httpbin.java

Handle relative redirects. Closes #2259.
Signed-off-by: Michael Lipp <mnl@mnl.de>

Handle relative redirects.

---

biz.aQute.bndlib.tests/src/test/annotationheaders/StdAnnotationHeadersTest.java
biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/AnnotatedAnnotation.java
biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/IndirectlyAnnotatedAnnotation.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java

Fix support for the standard Header annotation

---

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/pom.xml
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/pom.xml
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/test-inheriting-api-bundle/README.txt
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/test-inheriting-api-bundle/bnd.bnd
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/test-inheriting-api-bundle/pom.xml
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/test-inheriting-api-bundle/src/main/java/org/example/api/ExampleConsumerInterface.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/test-inheriting-api-bundle/src/main/java/org/example/api/ExampleProviderInterface.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/test-inheriting-api-bundle/src/main/java/org/example/api/package-info.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/test-inheriting-api-bundle/src/main/java/org/example/types/ThingyDTO.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/test-inheriting-api-bundle/src/main/java/org/example/types/package-info.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-in-build-pluginManagement-inheritance/test-inheriting-api-bundle/src/main/resources/org/example/api/aresource.txt
maven/bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy

Fixes https://github.com/bndtools/bnd/issues/2265

bnd-maven-plugin: Support configuration in pluginManagement section

---

biz.aQute.bndlib/src/aQute/bnd/http/URLCache.java

URLCache: Reduce synchronization, improve concurrency.

---

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java

HttpClient: Add ProxyHandlers to correct Collection

---

biz.aQute.bndlib.tests/src/test/component_extra/DSPropertyAnnotationsTest.java
biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java

Add support for Component Property Marker annotations

---

biz.aQute.bndlib.tests/src/test/MavenVersionTest.java
biz.aQute.bndlib/src/aQute/bnd/version/MavenVersion.java

Fixes https://github.com/bndtools/bnd/issues/2286

mavenversion: cleanupVersion must handle Integer.MAX_VALUE

---

biz.aQute.bndlib.tests/src/test/MavenVersionTest.java
biz.aQute.bndlib/src/aQute/bnd/version/MavenVersion.java
biz.aQute.bndlib/src/aQute/bnd/version/MavenVersionRange.java
biz.aQute.bndlib/src/aQute/bnd/version/packageinfo

See http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html
Fixes https://github.com/bndtools/bnd/issues/2285

mavenversion: Support all maven version range formats

---

maven/pom.xml

This is the version of maven plugins against which the bnd maven plugins
will compile.

maven: Set maven target version to 3.1.1

---

biz.aQute.bndlib.tests/src/test/diff/DiffTest.java

This jar is only used by the tests.

bndlib.tests: Move jar from cnf/repo to test jar folder

---

maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/Base.java
maven/bnd-baseline-maven-plugin/src/main/java/aQute/bnd/maven/baseline/plugin/BaselineMojo.java
maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-previous-same/pom.xml
maven/bnd-baseline-maven-plugin/src/test/resources/integration-test/test/valid-with-provider/pom.xml

The README clearly stated ranges could be used but the code never
attempted to resolve the range to a specific version.
Fixes https://github.com/bndtools/bnd/issues/2315

bnd-baseline-maven-plugin: Handle version range in configuration

---

biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java
biz.aQute.repository/src/aQute/maven/provider/POM.java

Fixes https://github.com/bndtools/bnd/issues/2078

pom: use directory of pom file as base for relative reference

---

aQute.libg/src/aQute/libg/glob/AntGlob.java
aQute.libg/src/aQute/libg/glob/Glob.java
aQute.libg/src/aQute/libg/glob/packageinfo
aQute.libg/test/aQute/libg/glob/AntGlobTest.java
aQute.libg/test/aQute/libg/glob/GlobTest.java
biz.aQute.bndlib.tests/src/test/JarSignerTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java

Antglob: add new Glob subclass that understands ant-style path globbing

---

aQute.libg/src/aQute/libg/glob/AntGlob.java

The old code did not properly handle escaping since it use endsWith.
Also `**` must now be the complete path segment: `**`, `**/`, `/**`, or `/**/`.

antglob: Fix handling of trailing / or /**

---

aQute.libg/src/aQute/libg/glob/AntGlob.java
aQute.libg/test/aQute/libg/glob/AntGlobTest.java

Ant-style glob patterns will not know to escape {}.

antglob: Remove {} support taken from Glob

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Export.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Resolve.groovy

Use Resolve task type in workspace model build.

Gradle resolve task

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java

Fixes to Clazz.is and Analyzer classes macro implementation.

Classes fixes

---

biz.aQute.bnd/src/aQute/bnd/ant/ExpandPropertiesTask.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java

Also remove visited items during queue init.

clazz: Change queue implementation to avoid duplicates

---

biz.aQute.bndlib.tests/src/test/annotationheaders/StdAnnotationHeadersTest.java
biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/AnnotatedAnnotation.java
biz.aQute.bndlib.tests/src/test/annotationheaders/multiple/std/PetstoreAppComponent.java
biz.aQute.bndlib/src/aQute/bnd/component/AnnotationReader.java
biz.aQute.bndlib/src/aQute/bnd/metatype/DesignateReader.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Annotation.java
biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java
biz.aQute.bndlib/src/aQute/bnd/osgi/ClassDataCollector.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java

Also some other fixes and some cleanup.

Fix uses handling on annotations

---

.travis.yml
biz.aQute.bnd.gradle/build.gradle
biz.aQute.bndlib.tests/src/test/JarTest.java
build.gradle

With this fix, the Java 9 build passes on Travis.

File system time fix

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Index.groovy
biz.aQute.bnd/src/aQute/bnd/main/IndexCommand.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java
biz.aQute.bndlib/src/aQute/bnd/osgi/repository/SimpleIndexer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/repository/XMLResourceGenerator.java
biz.aQute.bndlib/src/aQute/bnd/osgi/resource/ResourceBuilder.java
biz.aQute.repository/src/aQute/bnd/deployer/repository/providers/R5RepoContentProvider.java
maven/bnd-indexer-maven-plugin/src/main/java/aQute/bnd/maven/indexer/plugin/LocalIndexerMojo.java

Includes localizing copyright and description.

Index fixes

---

biz.aQute.bndlib.tests/src/test/MavenVersionTest.java
biz.aQute.bndlib/src/aQute/bnd/version/MavenVersion.java
biz.aQute.bndlib/src/aQute/bnd/version/Version.java

A version with a 10 digit micro version failed to parse.

maven: Update for version found in Maven Central

---

aQute.libg/src/aQute/lib/utf8properties/UTF8Properties.java
aQute.libg/src/aQute/lib/utf8properties/packageinfo
aQute.libg/src/aQute/libg/uri/URIUtil.java
aQute.libg/test/aQute/libg/uri/URIUtilsTest.java
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
biz.aQute.bnd.gradle/test/aQute/bnd/gradle/TestBundlePlugin.groovy
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
maven/bnd-maven-plugin/README.md
maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java
maven/bnd-maven-plugin/src/test/resources/integration-test/test/verify.groovy

also document all mojo configuration parameters
Closes https://github.com/bndtools/bnd/pull/2272

clarify bnd instruction inheritance/merging

---

biz.aQute.repository/src/aQute/maven/provider/POM.java

See https://github.com/bndtools/bnd/issues/2410

pom: Fix error message for missing parent to display parent revision

---

biz.aQute.resolve/src/biz/aQute/resolve/ProjectResolver.java

See https://github.com/bndtools/bndtools/issues/1877

resolving: Use ResolverLogger with Felix Resolver to avoid OOM

---

biz.aQute.bnd.embedded-repo/bnd.bnd
biz.aQute.bnd.exporters/src/aQute/bnd/exporter/subsystem/SubsystemExporter.java
biz.aQute.bnd/src/aQute/bnd/main/SubsystemExporter.java
biz.aQute.bndall.tests/test/aQute/bnd/junit/JUnitFrameworkTest.java
biz.aQute.bndlib.tests/bnd.bnd
biz.aQute.bndlib.tests/src/test/BuilderTest.java
biz.aQute.bndlib.tests/src/test/JarTest.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
biz.aQute.bndlib/src/aQute/bnd/make/MakeCopy.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/EmbeddedResource.java
biz.aQute.bndlib/src/aQute/bnd/signing/Signer.java
biz.aQute.junit/bnd.bnd
biz.aQute.launcher/src/aQute/launcher/Launcher.java
biz.aQute.launcher/src/aQute/launcher/plugin/ProjectLauncherImpl.java
biz.aQute.resolve/test/biz/aQute/resolve/ProjectResolverTest.java

This led to the discovery of some other bugs which are fixed.

Update biz.aQute.junit to add AssertJ support

---

biz.aQute.bndlib.tests/bnd.bnd
biz.aQute.bndlib/bnd.bnd
biz.aQute.http.testservers/bnd.bnd
biz.aQute.repository/bnd.bnd
biz.aQute.resolve.test/bnd.bnd
cnf/ext/central.mvn
cnf/ext/osgi-snapshots.mvn
cnf/ext/repositories.bnd
demo/bnd.bnd

OSGi has release Core R7 and Compendium R7 companion code.

osgi: Update from snapshot jars

---

.mailmap
biz.aQute.bndlib/src/aQute/bnd/header/Attrs.java

Directives are always type String.

attrs: Only attributes can be typed

---

biz.aQute.bndlib.tests/src/test/annotationheaders/StdAnnotationHeadersTest.java
biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/AnnotatedAnnotation.java
biz.aQute.bndlib.tests/src/test/annotationheaders/attrs/std/UsingAnnotatedAnnotation.java

Fix the identified problem in Attrs

Add tests for using the Directive meta-annotation

---

aQute.libg/src/aQute/lib/utf8properties/UTF8Properties.java
aQute.libg/src/aQute/libg/qtokens/QuotedTokenizer.java
biz.aQute.bndlib.tests/src/test/TestQuotedTokenizer.java
biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java

Some minor fixes I made while debugging a test issue in the osgi build.

Testing fixes

---

biz.aQute.junit/bnd.bnd
biz.aQute.launcher/src/aQute/launcher/SimplePermissionPolicy.java
biz.aQute.tester/bnd.bnd

When used in OSGi tests, the bundles will request AllPermission.

junit: Add permissions.perm files to tester bundles

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BundleTaskConvention.groovy
biz.aQute.bnd.gradle/testresources/builderplugin1/build.gradle

Fixes https://github.com/bndtools/bnd/issues/2439

gradle: Clean up Gradle 5.0 deprecation warnings

---

biz.aQute.bnd/src/aQute/bnd/main/ResolveCommand.java
biz.aQute.bndlib/src/aQute/bnd/build/model/OSGI_CORE.java
biz.aQute.bndlib/src/aQute/bnd/build/model/osgi-core/R7_0_0.mf
biz.aQute.bndlib/src/aQute/bnd/build/model/packageinfo
biz.aQute.resolve.test/test/biz/aQute/resolve/test/HugeRepositoryTest.java
biz.aQute.resolve/test/biz/aQute/resolve/ValidatorTest.java

Fixes https://github.com/bndtools/bnd/issues/2449

model: Add R7_0_0 enum value to OSGI_CORE

---

biz.aQute.bnd.gradle/README.md
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Bndrun.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/TestOSGi.groovy
biz.aQute.bnd.gradle/testresources/testosgitask1/build.gradle
biz.aQute.bnd.gradle/testresources/testosgitask2/build.gradle
biz.aQute.bnd.gradle/testresources/testosgitask3/build.gradle
biz.aQute.bnd.gradle/testresources/testosgitask4/build.gradle
biz.aQute.bndlib.tests/src/aQute/bnd/osgi/repository/XMLResourceGeneratorTest.java
biz.aQute.bndlib.tests/src/aQute/bnd/osgi/repository/data/macbadge.xml

Add Bndrun task type to gradle plugin.

Gradle Bndrun task type

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy

In Gradle 4.8, the groovy plugin ignored the groovy.outputDir setting
which caused the Bnd build to fail building the Bnd Gradle plugin. I
opened https://github.com/gradle/gradle/issues/5722. The Gradle developer
indicated that the SourceDirectorySet.outputDir property was perhaps a
mistake and that the compile tasks destinationDir property should be set.
This change sets both the outputDir and destinationDir properties which
appears to work fine. Failing to set the outputDir folder caused test
failures for the Bnd Gradle plugin test cases. When/If Gradle removes
the outputDir property, this code should be updated.

gradle: Update SourceDirectorySet.outputDir handling

---

aQute.libg/src/aQute/lib/annotations/setter/AnnotationSetter.java
aQute.libg/src/aQute/lib/config/proxy/ConfigurationProxy.java
aQute.libg/src/aQute/lib/converter/Converter.java
aQute.libg/src/aQute/lib/fileset/FileSet.java
aQute.libg/src/aQute/lib/fileset/packageinfo
aQute.libg/src/aQute/lib/strings/Strings.java
aQute.libg/src/aQute/lib/utf8properties/UTF8Properties.java
aQute.libg/src/aQute/lib/utf8properties/packageinfo
aQute.libg/src/aQute/lib/xmldtoparser/DomDTOParser.java
aQute.libg/src/aQute/libg/cryptography/SHA512.java
aQute.libg/src/aQute/libg/cryptography/packageinfo
aQute.libg/src/aQute/libg/glob/Glob.java
aQute.libg/src/aQute/libg/glob/packageinfo
aQute.libg/test/aQute/lib/annotations/setter/AnnotationSetterTest.java
aQute.libg/test/aQute/lib/config/proxy/ConfigurationProxyTest.java
aQute.libg/test/aQute/lib/converter/ConverterTest.java
aQute.libg/test/aQute/lib/fileset/FileSetTest.java
aQute.libg/test/aQute/libg/glob/GlobTest.java

- Helper to set annotation values
- Mangle method name -> property key updated to OSGi
- Files check for directory before descent
- UTF8Properties from file constructor
- A DTO parser on a XML DOM
- SHA512 class for crypto
- Multiple glob checking
- Configuration interface proxy

[libg] Addition of a number of utilities in lib

---

aQute.libg/src/aQute/lib/tag/Tag.java
aQute.libg/src/aQute/lib/tag/packageinfo
aQute.libg/test/aQute/lib/tag/OtherDTO.java
aQute.libg/test/aQute/lib/tag/TagTest.java

Modify the Tag class to accept DTO object

---

biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java

Fixes https://github.com/bndtools/bnd/issues/2474

maven settings: Better handle issues decrypting maven settings

---

biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_10_0.properties
biz.aQute.bndlib/src/aQute/bnd/build/model/JavaSE_9_0.properties

See https://docs.oracle.com/javase/9/docs/api/java.se.ee-summary.html
Fixes #2496 
Also add JavaFX packages which are part of se as of Java 9.

 ee: Adjust packages list for Java 9/10 to exclude ee modules content

---

biz.aQute.bndlib.tests/src/test/ClazzTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java
docs/_macros/classes.md

HIERARCHY_ANNOTATED means the class or any super class is directly
annotated.
HIERARCHY_INDIRECTLY_ANNOTATED means the class or any super class is
indirectly annotated.

classes: Add new types to macro

---

biz.aQute.bndlib.tests/src/test/ExportAnnotationTest.java
biz.aQute.bndlib.tests/src/test/export/annotation/testConsumer/package-info.java
biz.aQute.bndlib.tests/src/test/export/annotation/testNoimport/package-info.java
biz.aQute.bndlib.tests/src/test/export/annotation/testNouses/package-info.java
biz.aQute.bndlib.tests/src/test/export/annotation/testProviderType/ConsumerInterface.java
biz.aQute.bndlib.tests/src/test/export/annotation/testProviderType/impl/ConsumerInterfaceImpl.java
biz.aQute.bndlib.tests/src/test/export/annotation/testProviderType/impl/package-info.java
biz.aQute.bndlib.tests/src/test/export/annotation/testProviderType/package-info.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java

Fixes https://github.com/bndtools/bnd/issues/769

annotations: Support ProviderType annotation in package-info.class

---

biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bndlib/src/aQute/bnd/help/Syntax.java
biz.aQute.bndlib/src/aQute/bnd/maven/PomFromManifest.java

See https://github.com/bndtools/bnd/issues/233

headers: Add Bundle-SCM to Syntax

---

aQute.libg/src/aQute/libg/command/Command.java
biz.aQute.bndlib.tests/src/test/LauncherTest.java
biz.aQute.bndlib.tests/src/test/lib/NanoHTTPD.java
biz.aQute.bndlib/src/aQute/bnd/build/ProjectLauncher.java
biz.aQute.bndlib/src/aQute/bnd/build/packageinfo
biz.aQute.junit/src/aQute/junit/Activator.java
biz.aQute.junit/src/aQute/junit/JUnitEclipseReport.java
biz.aQute.launcher/src/aQute/launcher/constants/LauncherConstants.java
biz.aQute.repository/test/test/lib/NanoHTTPD.java
demo/src/test/TestActivator.java
docs/_heads/test_cases.md
docs/_instructions/testcontinuous.md
docs/_instructions/testunresolved.md

Fixes https://github.com/bndtools/bnd/issues/2473

launcher: Use unsigned byte for process exit codes

---

biz.aQute.bnd/bnd.bnd
biz.aQute.bndall.tests/bnd.bnd
biz.aQute.resolve/bnd.bnd
biz.aQute.resolve/src/biz/aQute/resolve/BndResolver.java
biz.aQute.resolve/src/biz/aQute/resolve/packageinfo
cnf/ext/central.mvn

This requires using the OSGi resolver 1.1 package.

resolve: Update to Felix Resolver 2.0

---

biz.aQute.bnd/src/aQute/bnd/main/bnd.java

- remove wrong return; from perProject mehod,
- clean perProject,
- prevent nullpointer in release method

Fix some problems while iterating over all WorkspaceProjects

---

docs/_heads/include_resource.md
docs/_instructions/includeresource.md

[doc] Move text of include resource to proper place

---

biz.aQute.bndlib.tests/src/test/ExportAnnotationTest.java
biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
biz.aQute.bndlib/src/aQute/bnd/help/instructions/BuilderInstructions.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Domain.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Instructions.java
biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java
docs/_instructions/includepackage.md

Fix double export of package

---

aQute.libg/src/aQute/libg/glob/Glob.java
aQute.libg/test/aQute/libg/glob/GlobTest.java
biz.aQute.bndlib.tests/src/test/InstructionTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Instruction.java

Add constructor to Instruction which takes a custom Pattern.

Instruction pattern

---

aQute.libg/src/aQute/libg/glob/Glob.java
aQute.libg/test/aQute/libg/glob/GlobTest.java
biz.aQute.bndlib/src/aQute/bnd/make/Make.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Instruction.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.junit/bnd.bnd
cnf/ext/central.mvn
maven/bnd-maven-plugin/src/test/resources/integration-test/test/test-impl-bundle/bnd.bnd
maven/bnd-shared-maven-lib/.settings/org.eclipse.core.resources.prefs
maven/bnd-shared-maven-lib/pom.xml
maven/bnd-shared-maven-lib/src/test/java/aQute/bnd/maven/lib/configuration/BeanPropertiesTest.java
maven/pom.xml

Replacing the default pattern with the Glob.
We also add a legacy method for places which are too dependent on the
legacy pattern of Instruction.

Instruction improvements

---

biz.aQute.bnd/src/aQute/bnd/main/RepoCommand.java
biz.aQute.bndlib.tests/src/simplelogger.properties
biz.aQute.bndlib.tests/src/test/component/PermissionGeneratorTest.java
biz.aQute.bndlib/src/aQute/bnd/component/DSAnnotations.java
biz.aQute.bndlib/src/aQute/bnd/header/Parameters.java
biz.aQute.bndlib/src/aQute/bnd/osgi/AnnotationHeaders.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.bndlib/src/aQute/bnd/version/VersionRange.java

Some small tweaks I came across and made while debugging.

Bnd tweaks

---

docs/_instructions/connection-settings.md

Signed-off-by: Amit Kumar Mondal <admin@amitinside.com>

Updated connection-settings instruction

---

aQute.libg/src/aQute/libg/command/Command.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java

Use daemon threads for Processor's executors and avoid long running Timer thread for Command.

Threading improvements

---

aQute.libg/src/aQute/lib/xmldtoparser/DomDTOParser.java
aQute.libg/src/aQute/lib/xmldtoparser/XmlAttribute.java
aQute.libg/test/aQute/lib/xmldtoparser/ComponentsDTO.java
aQute.libg/test/aQute/lib/xmldtoparser/DomDTOParserTest.java
aQute.libg/testresources/dsxmls/t1.xml

- handles null for collections (creates a collection)
- allows XmlAttributes for enum names
- test case

[xmldtoparser] Improvements

---

maven/pom.xml

Set lifecycle mapping for maven plugins.

maven: Fix m2e warnings

---

biz.aQute.bndlib/src/aQute/bnd/connection/settings/ConnectionSettings.java

Related to [issue 2550](https://github.com/bndtools/bnd/issues/2550).

Fix race condition on ProxySetup creation

---

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/RepoActions.java

The <versions> element in Maven metadata is not necessarily sorted high
to low, making the "Update to" action in the Repositories view offer to
upgrade you to a lower version. In the case of mysql-connector-java:
https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/maven-metadata.xml
The "Update to" action suggested updating to 2.0.14, simply because it
is the last version listed.
Instead we find all later revisions and group them by major & minor so
that the user can select an appropriate later version to upgrade to.
I don't know how to exercise this with command line Bnd, so here are before and after images from within Bndtools:
**Before:**
**After:**

Fix 'Update to' repository actions

---

biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy

Fixes https://github.com/bndtools/bnd/issues/2591

gradle: Handle source set convention which are not SourceDirectorySet

---

biz.aQute.bndlib/src/aQute/bnd/osgi/ClassDataCollector.java
biz.aQute.bndlib/src/aQute/bnd/osgi/ClassDataCollectorRecorder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/ClassDataCollectors.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java

This ensures all interesting fields like constants, signatures are set
when the class is visited.

clazz: Process complete class before calling ClassDataCollector

---

aQute.libg/src/aQute/lib/io/IO.java
aQute.libg/test/aQute/lib/io/IOTest.java

The calculation of the home directory first looks at %HOME%/$HOME and then it uses the system property user.home. 
On Windows %HOME% contains other environment variables, i.e. it is not expanded. Users had to remove this variable to make it work.
This fix expands macros on windows in %HOME%

[io] Home directory and getenv

---

biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bndlib.tests/src/aQute/bnd/osgi/ActivelyClosingClassloaderTest.java
biz.aQute.bndlib.tests/src/test/WorkspaceTest.java
biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
biz.aQute.bndlib/src/aQute/bnd/osgi/ActivelyClosingClassloader.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java

The current class loader for the plugins kept files
open. This patch changes it to have a class loader that
closes the open files after 5-10 secs after the last class load.

[plugins] Actively Closing Loader

---

biz.aQute.launcher/bnd.bnd
biz.aQute.repository/bnd.bnd
cnf/ext/central.mvn

Remove use of javax.xml.stream bundle since this is part of Java 8+

build: More build cleanup

---

aQute.libg/src/aQute/libg/reporter/ReporterMessages.java
biz.aQute.bndlib/src/aQute/bnd/signatures/ClassTypeSignature.java
biz.aQute.bndlib/src/aQute/bnd/signatures/Signatures.java
biz.aQute.bndlib/src/aQute/bnd/signatures/SimpleClassTypeSignature.java
biz.aQute.bndlib/src/aQute/bnd/signatures/TypeParameter.java
biz.aQute.bndlib/src/aQute/bnd/signatures/TypeVariableSignature.java

Better exception reporting for ERROR class proxies.
Also, intern strings created in signature package to reduce in memory copies.

Exception reporting

---

aQute.libg/src/aQute/libg/glob/Glob.java
aQute.libg/src/aQute/libg/qtokens/QuotedTokenizer.java
aQute.libg/src/aQute/libg/reporter/ReporterAdapter.java
aQute.libg/src/aQute/libg/reporter/slf4j/Slf4jReporter.java
aQute.libg/src/aQute/service/reporter/Reporter.java
biz.aQute.bnd/bnd.bnd
biz.aQute.bnd/src/aQute/bnd/main/CommunicationCommands.java
biz.aQute.bnd/src/aQute/bnd/main/GraphCommand.java
biz.aQute.bnd/src/aQute/bnd/main/Shell.java
biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
biz.aQute.bndlib/src/aQute/bnd/osgi/repository/BridgeRepository.java
biz.aQute.bndlib/src/aQute/bnd/osgi/repository/SimpleIndexer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/repository/XMLResourceParser.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/NexusCommand.java
biz.aQute.repository/src/aQute/maven/nexus/provider/Nexus.java
biz.aQute.repository/src/aQute/maven/nexus/provider/package-info.java
cnf/ext/central.mvn

Shell and graph command in bnd, fixes, and convenience methods

---

biz.aQute.bndlib/src/aQute/bnd/util/dto/DTO.java

OSGi R7 updated to support these types in DTOs.

bndlib: Update DTO class to handle enum and Version

---

.travis.yml
biz.aQute.bndlib.tests/test/aQute/bnd/osgi/ActivelyClosingClassLoaderTest.java
biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java

Maven release fix from next branch

---

aQute.libg/src/aQute/configurable/Configurable.java
aQute.libg/src/aQute/lib/converter/Converter.java
aQute.libg/src/aQute/lib/getopt/CommandLine.java
aQute.libg/src/aQute/lib/json/CollectionHandler.java
aQute.libg/src/aQute/lib/json/Handler.java
aQute.libg/src/aQute/lib/json/MapHandler.java
aQute.libg/src/aQute/lib/json/ObjectHandler.java
aQute.libg/src/aQute/lib/json/SpecialHandler.java
aQute.libg/src/aQute/lib/xmldtoparser/DomDTOParser.java
aQute.libg/src/aQute/lib/xpath/XPathParser.java
aQute.libg/src/aQute/libg/classloaders/URLClassLoaderWrapper.java
aQute.libg/src/aQute/libg/sed/ReplacerAdapter.java
aQute.libg/test/aQute/lib/json/JSONTest.java
biz.aQute.bnd.annotation/src/aQute/bnd/annotation/metatype/Configurable.java
biz.aQute.bndlib/src/aQute/bnd/build/Project.java
biz.aQute.bndlib/src/aQute/bnd/build/ReflectAction.java
biz.aQute.bndlib/src/aQute/bnd/build/Workspace.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
biz.aQute.bndlib/src/aQute/bnd/resource/repository/ResourceDescriptorImpl.java
biz.aQute.junit/src/aQute/junit/BasicTestReport.java
biz.aQute.junit/src/aQute/junit/JUnitEclipseReport.java
biz.aQute.launcher/src/aQute/launcher/Launcher.java
biz.aQute.launcher/src/aQute/launcher/pre/EmbeddedLauncher.java
biz.aQute.remote/src/aQute/remote/agent/AgentDispatcher.java
biz.aQute.repository/src/aQute/p2/provider/XML.java
demo/src/test/TestCase1.java

We don't want an invocation exception on the first method to report a locating exception of the fallback method.
Also updates to replace reflection with method handles.

Distinguish between locating and invocation of method

---

maven/bnd-maven-plugin/README.md
maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java

This closes #2447
Signed-off-by: Konrad Windszus <kwin@apache.org>

derive more bundle-headers from pom information by default

---

docker/Dockerfile
docker/README.md
docker/build.sh

**Status**
**Description**
- update bnd in docker image  to 4.1.0, 
- use jdk to enable compile
- short description in README.md
**Checklist**
* (no versions between (3.3.0; 4.1.0])
* docker push to https://hub.docker.com/r/bndtoolsorg/bnd/
**Question**
@bjhargrave 
- is there a way/need to test it?

[docker] update bnd in docker

---

docs/_chapters/125-tour-features.md
docs/_chapters/150-build.md
docs/_chapters/400-commandline.md
docs/_chapters/600-developer.md
docs/_commands/convert.md
docs/_commands/digest.md
docs/_commands/eclipse-pde.md
docs/_commands/ees.md
docs/_commands/grep.md
docs/_commands/index.md
docs/_commands/macro.md
docs/_commands/print.md
docs/_commands/repo.md
docs/_commands/select.md
docs/_commands/settings.md
docs/_commands/source.md
docs/_commands/verify.md
docs/_commands/view.md
docs/_commands/wrap.md
docs/_commands/xref.md
docs/_heads/bundle_license.md
docs/_includes/nav.htm
docs/_instructions/profile.md

**Status**
**Description**
fix docs,
- processing of <key>,
- broken nav link
- headlines
**Checklist**
* none
* none
Signed-off-by: stbischof <stbischof@bipolis.org>

[docs] fix docs

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java

Avoid duplicate checks and loops.

clazz: Clean up processing of superclass and interfaces

---

biz.aQute.bndlib/src/aQute/bnd/classfile/AnnotationInfo.java
biz.aQute.bndlib/src/aQute/bnd/classfile/AnnotationsAttribute.java
biz.aQute.bndlib/src/aQute/bnd/classfile/BootstrapMethodsAttribute.java
biz.aQute.bndlib/src/aQute/bnd/classfile/ClassFile.java
biz.aQute.bndlib/src/aQute/bnd/classfile/CodeAttribute.java
biz.aQute.bndlib/src/aQute/bnd/classfile/ConstantPool.java
biz.aQute.bndlib/src/aQute/bnd/classfile/ElementValueInfo.java
biz.aQute.bndlib/src/aQute/bnd/classfile/FieldInfo.java
biz.aQute.bndlib/src/aQute/bnd/classfile/LineNumberTableAttribute.java
biz.aQute.bndlib/src/aQute/bnd/classfile/LocalVariableTableAttribute.java
biz.aQute.bndlib/src/aQute/bnd/classfile/LocalVariableTypeTableAttribute.java
biz.aQute.bndlib/src/aQute/bnd/classfile/MemberInfo.java
biz.aQute.bndlib/src/aQute/bnd/classfile/MethodInfo.java
biz.aQute.bndlib/src/aQute/bnd/classfile/ParameterAnnotationInfo.java
biz.aQute.bndlib/src/aQute/bnd/classfile/ParameterAnnotationsAttribute.java
biz.aQute.bndlib/src/aQute/bnd/classfile/SourceDebugExtensionAttribute.java
biz.aQute.bndlib/src/aQute/bnd/classfile/StackMapTableAttribute.java
biz.aQute.bndlib/src/aQute/bnd/classfile/TypeAnnotationInfo.java
biz.aQute.bndlib/src/aQute/bnd/classfile/TypeAnnotationsAttribute.java

Complete support for all attribute types specified in JVMS 11.

Classfile completion

---

biz.aQute.bnd/bnd.bnd
biz.aQute.bnd/src/aQute/bnd/main/ExportReportCommand.java
biz.aQute.bnd/src/aQute/bnd/main/bnd.java
biz.aQute.bnd/test/aQute/bnd/main/TestBndExportReport.java
dist/bnd.bnd

[bnd] Add exportreport command

---

docs/_commands/exportreport.md
docs/_instructions/exportreport.md
docs/_instructions/reportconfig.md

[docs] Add exportreport documentation

---

aQute.libg/src/aQute/lib/tag/Tag.java
aQute.libg/test/aQute/lib/tag/TagTest.java
biz.aQute.junit/src/aQute/junit/Tag.java

 junit: Handle embedded double quote character in attribute value 

---

aQute.libg/src/aQute/libg/glob/PathSet.java
biz.aQute.bndlib/src/aQute/bnd/build/packageinfo
biz.aQute.bndlib/src/aQute/bnd/junit/package-info.java
biz.aQute.bndlib/src/aQute/bnd/maven/PomResource.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java

This is a replacement for and closes https://github.com/bndtools/bnd/pull/2645.

Use pom.properties found on -buildpath to generate dependencies section in pom

---

biz.aQute.repository/bnd.bnd
cnf/ext/central.mvn

build: Complete removal of jetty from the build

---

azure-pipelines.yml
maven/bnd-indexer-maven-plugin/src/test/resources/integration-test/test/setup.groovy

Initial commit for Azure Pipelines build

Set up CI with Azure Pipelines

---

README.md
biz.aQute.bnd.gradle/README.md
biz.aQute.repository/test/aQute/bnd/repository/osgi/OSGiRepositoryTest.java
docs/_chapters/120-install.md
docs/md/120-install.md
gradle.properties

Remove cloudbees references from the build.

Goodbye cloudbees

---

biz.aQute.bndlib/src/aQute/bnd/build/Project.java

We know rely on drivers of bndlib such as Gradle, Maven and Bndtools
to determine when a project should be built. The Project class should
not attempt to second guess the drivers decision but declining to write
out the built files.
Fixes https://github.com/bndtools/bnd/issues/2664

project: Always save built jar

---

cnf/ext/repositories.bnd

See https://issues.sonatype.org/browse/OSSRH-44832

build: Release groupId org.bndtools to OSSRH

---

biz.aQute.bnd.gradle/README.md
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/BndPlugin.groovy
biz.aQute.bnd.gradle/src/aQute/bnd/gradle/Index.groovy
dist/build.gradle
maven/build.gradle
org.bndtools.p2/build.gradle

Also some build tweaks to take advantage of new workspace tasks and some code cleanup in BndPlugin.

gradle: Add base property to Index task

---

cnf/includes/bndtools.bnd
dist/bnd.bnd
dist/build.gradle
maven/build.gradle

Build index so it can reside in a maven repository.

Dist index

---

biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java

This will enable one to point OSGiRepository to a jar in a maven repo
which holds an index to other bundles in the repo.

repo: Add support for index.xml entry in a zip file for OSGiRepository

---

maven/bnd-maven-plugin/src/main/java/aQute/bnd/maven/plugin/BndMavenPlugin.java

Fixes https://github.com/bndtools/bnd/issues/2800

[maven] prevent m2e infinitely building project that doesn't include the classesDir

---

biz.aQute.bnd.diagnostics.gogo/bnd.bnd
biz.aQute.bnd.embedded-repo/bnd.bnd
biz.aQute.bnd.exporters/bnd.bnd
biz.aQute.bnd.remote.junit/bnd.bnd
biz.aQute.bnd.reporter/bnd.bnd
biz.aQute.remote/bnd.bnd
bndtools.bndplugins/bnd.bnd
dist/bnd.bnd
dist/build.gradle

Modify the dist bundle to be usable with BndPomRepository to create a baseline repo.

Dist baseline

---

aQute.libg/src/aQute/lib/strings/Strings.java
aQute.libg/src/aQute/lib/strings/packageinfo
biz.aQute.bndlib.tests/test/test/MacroTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Processor.java
docs/_macros/list.md

Add new list macro that eturns a list of the values of the named properties with escaped semicolons.

List macro

---

aQute.libg/src/aQute/lib/collections/ExtList.java
aQute.libg/src/aQute/lib/strings/Strings.java
aQute.libg/src/aQute/libg/qtokens/QuotedTokenizer.java
aQute.libg/src/aQute/libg/qtokens/packageinfo
aQute.libg/src/aQute/libg/sed/ReplacerAdapter.java
aQute.libg/test/aQute/libg/qtokens/TestQuotedTokenizer.java
aQute.libg/test/aQute/libg/sed/ReplacerTest.java
biz.aQute.bnd.remote.junit/src/aQute/bnd/remote/junit/JUnitFramework.java
biz.aQute.bnd.runtime/bnd.bnd
biz.aQute.bnd.runtime/gogo.bnd
biz.aQute.bnd.runtime/snapshot.bnd
biz.aQute.bnd/test/aQute/bnd/main/TestBndExportReport.java
biz.aQute.bndlib.tests/test/test/BuilderTest.java
biz.aQute.bndlib.tests/test/test/MacroTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
cnf/ext/central.mvn

Some more fixes/enhancement to macro processing. It now handles embedded quotes better when splitting on comma.

Macro enhancements

---

bndtools.builder/src/org/bndtools/builder/handlers/component/DSAnnotationErrorHandler.java

Fails building project #2872

---

biz.aQute.bndlib.tests/test/test/MacroTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
docs/_macros/list.md
docs/_macros/replace.md
docs/_macros/replacelist.md
docs/_macros/replacestring.md

Part one of reverting the replace macro to use simple list splitting.

Replace legacy

---

biz.aQute.bndlib.tests/test/test/MacroTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Macro.java
docs/_macros/lsa.md
docs/_macros/lsr.md

Fixes https://github.com/bndtools/bnd/issues/2915

macro: Fix lsa/lsr macro operation when no instruction specified

---

biz.aQute.bndlib.tests/test/test/component/DSAnnotationTest.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Clazz.java

Final final final.
Fixes #2928

Clazz: A non-final field in a final class is not final.

---

biz.aQute.bndlib/src/aQute/bnd/make/component/ServiceComponent.java

The other plugins do something similar, so for consistency do it here too.

ServiceComponent: Override toString() for cleaner debug output

---

org.bndtools.embeddedrepo/bnd.bnd

Add -dependson bndtools.embeddedrepo.

---

org.bndtools.headless.build.plugin.ant/bnd.bnd

Another -dependson needed for the merge of bndtools into bnd repo.

build: Add -dependson needed since we merged bndtool into bnd

---

biz.aQute.remote/src/aQute/remote/plugin/RunRemoteDTO.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/ReleaseDTO.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/packageinfo
biz.aQute.repository/src/aQute/maven/api/Release.java
biz.aQute.repository/src/aQute/maven/api/packageinfo
biz.aQute.repository/src/aQute/maven/nexus/provider/Signer.java
biz.aQute.repository/src/aQute/maven/nexus/provider/package-info.java
biz.aQute.repository/src/aQute/maven/provider/MavenRepository.java
biz.aQute.repository/src/aQute/maven/provider/Releaser.java
biz.aQute.repository/src/aQute/maven/provider/SnapshotReleaser.java
biz.aQute.repository/src/aQute/maven/provider/packageinfo

- Maven signing
- Default remote reachable set to false

Maven signing and tiny change for remote

---

biz.aQute.bndlib/src/aQute/bnd/help/Syntax.java

Content Assist couldn't list all existent instructions and headers. This fix solves this problem.
Fixes #2974 
Signed-off-by: Amit Kumar Mondal <admin@amitinside.com>

[Bndtools Core] Fixed Content Assist

---

biz.aQute.bndlib.tests/test/test/properties/PropertiesTest.java
biz.aQute.bndlib/src/aQute/bnd/build/model/BndEditModel.java

Packages specified with -privatepackages weren't listed in the view. This fix solves the problem.
Fixes #2937
Signed-off-by: Amit Kumar Mondal <admin@amitinside.com>

[Bndtools Core] Fixed issue with Private Packages View

---

biz.aQute.bndlib/src/aQute/bnd/help/Syntax.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Constants.java
bndtools.core/src/bndtools/editor/completion/BndScanner.java

Added missing syntaxes to Syntax class
Fixes #2990

[Bndtools Core] Fixed Problem with Instruction Highlighting

---

biz.aQute.bndlib/src/aQute/bnd/cdi/CDIAnnotations.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Analyzer.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Jar.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Verifier.java
biz.aQute.bndlib/src/aQute/bnd/signing/JartoolSigner.java
biz.aQute.bndlib/src/aQute/lib/spring/SpringComponent.java
biz.aQute.bndlib/src/aQute/lib/spring/XMLType.java

Use consistent paths for Jar and Bundle-ClassPath entries.

Bundle-ClassPath related fixes

---

biz.aQute.launchpad/src/aQute/launchpad/Parameters.java

[launchpad] Remove empty enum

---

biz.aQute.bndlib.comm.tests/test/aQute/bnd/comm/tests/HttpClientTest.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpRequest.java

Under threat of BJ going insane added a retry to
the http client.

[httpclient] Added retries

---

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java
biz.aQute.bndlib/src/aQute/bnd/http/HttpRequest.java

Improve log messages for retry and remove class-wide suppress warnings.

httpclient: Some minor code tweaks

---

docs/_instructions/stalecheck.md

[docs] stalecheck

---

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/MavenBndRepository.java
biz.aQute.repository/src/aQute/bnd/repository/maven/provider/ReleasePluginImpl.java
biz.aQute.repository/test/aQute/bnd/repository/maven/provider/MavenBndRepoTest.java
biz.aQute.repository/testdata/releasews/cnf/.gitignore
biz.aQute.repository/testresources/mavenrepo2/index.maven

Add support for using Workspace properties and macros in MavenBndRepository index files.

Maven index macros

---

biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java
biz.aQute.repository/src/aQute/maven/provider/MavenBackingRepository.java
biz.aQute.repository/src/aQute/maven/provider/MavenRemoteRepository.java
biz.aQute.repository/src/aQute/p2/api/Artifact.java
biz.aQute.repository/src/aQute/p2/api/package-info.java
biz.aQute.repository/src/aQute/p2/provider/ArtifactRepository.java

If the MD5 or download size is incorrect, retry download. We have 2
retry attempts (for 3 total attempts) with a delay between attempts.

p2: Verify MD5 or download size on downloaded files

---

biz.aQute.bndlib/src/aQute/bnd/http/HttpClient.java

Improvements from analyzing logs from the azure build for Eclipse download retries.

Http client tweaks

---

biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java

If the checksum of the downloaded file fails, we retry up to 2 times.

osgirepo: Add SHA256 checksum checks for downloaded files

---

biz.aQute.bnd.runtime/test/aQute/bnd/runtime/snapshot/SnapshotTest.java

[fix] tests are flaky probably due to gogo

---

biz.aQute.bnd.runtime/test/aQute/bnd/runtime/snapshot/SnapshotTest.java

[fix] Another gogo thing

---

biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java

Signed-off-by: Bram Pouwelse <bram@pouwelse.com>

Remove exceptions never thrown from method signatures

---

biz.aQute.launchpad/src/aQute/launchpad/Launchpad.java

Signed-off-by: Bram Pouwelse <bram@pouwelse.com>

[fix] pass targetFilter param to getServices call

---

aQute.libg/src/aQute/libg/parameters/Attributes.java
aQute.libg/src/aQute/libg/parameters/ParameterMap.java
aQute.libg/src/aQute/libg/qtokens/QuotedTokenizer.java
aQute.libg/src/aQute/libg/qtokens/packageinfo
aQute.libg/test/aQute/libg/parameters/ParameterMapTest.java

To prevent coupling to the core bnd code

[parameters] An uncoupled version of the Parameters

---

biz.aQute.launchpad/src/aQute/launchpad/LaunchpadBuilder.java
docs/_chapters/315-launchpad-testing.md

[launchpad] Documentation

---

biz.aQute.repository/src/aQute/bnd/repository/maven/provider/IndexFile.java

This reverts a change that should not have been committed yet and
may likely cause a refresh loop in Eclipse.

[mavenbndrepo] Revert

---

biz.aQute.launchpad/test/aQute/launchpad/WorkspaceTest.java

[launchpad] Potential race condition in test

---

docs/_commands/exportreport.md
docs/_instructions/exportreport.md
docs/_instructions/reportconfig.md

reporter: Documentation Fixes

---

biz.aQute.bnd.reporter/bnd.bnd
biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/generator/EntryNamesReference.java
biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/generator/ReportGeneratorBuilder.java
biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/generator/package-info.java
biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/helpers/HeadersHelper.java
biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/helpers/VersionHelper.java
biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/manifest/dto/CommonInfoDTO.java
biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/manifest/dto/OSGiHeadersDTO.java
biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/manifest/dto/package-info.java
biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/entries/bndworkspace/CommonInfoPlugin.java
biz.aQute.bnd.reporter/src/biz/aQute/bnd/reporter/plugins/entries/bundle/ManifestPlugin.java
biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/helpers/HeadersHelperTest.java
biz.aQute.bnd.reporter/test/biz/aQute/bnd/reporter/plugins/entries/workspace/CommonInfoPluginTest.java
docs/_instructions/reportconfig.md

reporter: Add the CommonInfo EntryPlugin

---

biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Descriptors.java

Fixes https://github.com/bndtools/bnd/issues/3141

wab: Better support excluding meta packages from WEB-INF/classes

---

biz.aQute.bnd/src/aQute/bnd/main/RemoteCommand.java
biz.aQute.remote/src/aQute/remote/agent/AgentServer.java
biz.aQute.remote/src/aQute/remote/api/Agent.java
biz.aQute.remote/src/aQute/remote/api/packageinfo
biz.aQute.remote/test/biz/aQute/remote/AgentTest.java

Bnd agent has been enhanced to perform remote bundle operations (install, update and list)

Added functionality to perform remote bundle operations

---

biz.aQute.bnd/src/aQute/bnd/main/RemoteCommand.java
biz.aQute.remote/test/biz/aQute/remote/AgentTest.java

Also, avoid use of Google classes.

remote: Use IO class for I/O

---

biz.aQute.remote/src/aQute/remote/main/Main.java

[remote] Documentation on remote main command

---

biz.aQute.repository/src/aQute/bnd/repository/osgi/OSGiIndex.java
biz.aQute.repository/src/aQute/bnd/repository/p2/provider/P2Indexer.java
biz.aQute.repository/src/aQute/maven/provider/MavenRemoteRepository.java

Add missed change to OSGiIndex recovery logic.

httpclient: Clean up promise recovery to be more consistent

---

biz.aQute.bndlib/src/aQute/bnd/build/ProjectBuilder.java
biz.aQute.bndlib/src/aQute/bnd/osgi/Builder.java

Fixes https://github.com/bndtools/bnd/issues/3198

builder: Add -privatepackage to ProjectBuilder startBuild check
